cmd/importer/importer.go

Added a func to get the env vars and do some semantic checking.

some env var semantic checking

---

manifests/importer-namespace.yaml
manifests/importer-pod-config.yaml
manifests/importer-pod-secret.yaml
manifests/importer-pod.yaml

This is just an initial stab at some of the manifest yaml files. The pod's hostpath needs to be defined. The pvc and pv need to be created.

1st manifests -- needs work

---

Makefile
build/controller/Dockerfile
build/importer/Dockerfile
cmd/importer/importer.go
cmd/importer/util.go

Changed makefile behavior to compile and build image with 1 target; Added env var IMPORTER_DESTINATION to pass local write location to importer binary; changed Dockerfile to use busybox

Parameterize write location

---

Makefile
manifests/importer-pod-config.yaml
manifests/importer-pod.yaml

currently gcloud specific.  Will have to change once we move to a public repo

Added push targest to Makefile

---

Makefile
cmd/importer/importer.go
manifests/importer-pod-config.yaml
manifests/importer-pod.yaml

Write var is now hardcoded in the bin

Removed write path from env vars

---

cmd/importer/importer.go

First pass. Compiles but omitting access and secret has not been tested with the minio client.

optional secret and access keys

---

cmd/importer/importer.go

minor refactor and consistent use of func name in error msgs.

refactor to add newDataReader()

---

cmd/controller/controller.go
manifests/controller/import-controller-pod.yaml

Was not able to test due to inability to push my controller image to rhjcope registry, which we can deal with tomorrow. Meanwhile, there's a decent chance this works.

controller uses own namespace

---

pkg/controller/controller.go
pkg/controller/util.go

returns *Secret. Maybe should just return Secret.Name? But ok for now...

secret and endpoint progress

---

pkg/controller/controller.go
pkg/controller/util.go

If kubevirt.io/storage.import.status pvc annotation is present the pvc will be skipped.
Also this same annotation is set to "In-process" when the claim is being processed.

look for pvc status annotation

---

pkg/validation/validate.go

while I'm working on unit test, I found there is a mistake, tell me if I'm wrong.
@copejon @jeffvance

Fix HasSuffix() parameter in a wrong order

---

pkg/validation/validation_test.go

I rebased my previous pr, but I think due to merge order, the path changed again.
@jeffvance @copejon

minor fix import path

---

build/importer/Dockerfile
cmd/importer/importer.go
pkg/image/qemu.go
pkg/image/validate.go
pkg/importer/util.go

Peppered in comments in main
Added qemu-img dependencies to importer dockerfile
StreamDataToFile only needs io.Reader

Convert qcow2 to raw based on magic numbers read from data stream.

---

Makefile
pkg/image/validation_test.go

Fixes: https://github.com/kubevirt/containerized-data-importer/issues/53
@jeffvance

add a simple make test step into Makefile

---

README.md

update security recommendations

---

cmd/importer/importer.go
pkg/image/decompress.go
pkg/image/validate.go
pkg/importer/dataStream.go
pkg/importer/importer_test.go
pkg/importer/util.go

some test changes to reflect the reader refactoring but more to do here: 1) add _local_ tests, 2) make importer test more closely follow importer main code, 3) make the `dataStream` struct support the io.ReadCloser interface.
@copejon This can be prefixed "WIP" if you want.

Local import and some Reader related refactoring.

---

pkg/controller/controller_test.go

Controller unit test still fails but this is a start at addressing issue #84:

1st pass at ns unit test

---

.travis.yml

Signed-off-by: Fabian Deutsch <fabiand@fedoraproject.org>

travis: Run unit and functional tests

---

pkg/controller/controller_test.go

fixes #84 
After some investigation with Jeff we discovered that `namespace` is needed when the queue is created to properly find the importer pod.

fix controller unit test to be namespace aware

---

pkg/controller/controller_test.go

1.  each controller unit tests gets its own pvc name.
1.  the pvcObj is local per `It` block so that these tests can be run in parallel if needed.
1.  some minor additional refactoring.

pvc name per test, pvcObj per It

---

pkg/importer/importer_test.go

fixes #78 
Initial WIP to adda unit test for file/local dataStream

add unit test for file dataStream

---

.travis.yml

Travis minikube fix

---

Makefile
cmd/controller/controller.go
pkg/controller/controller.go
pkg/controller/util.go

Update makefile to push releases to kubevirt repo
Modify controller bin to accept non-default importer images
cc @jeffvance @screeley44

Use docker.io/kubevirt for release images.

---

cmd/controller/controller.go
pkg/controller/controller.go
pkg/controller/controller_test.go

add UpdateFunc to pvcInformer

---

.travis.yml
Makefile
version

trying to add an automated release from travis

WIP: add git tag and release

---

README.md

The readme file should mention that the pvc can be watched to detect the importer pod's status. And, that kubevirt creates the VM once the import process completes.

update readme for pod monitoring

---

pkg/controller/controller_test.go
pkg/controller/util.go

1 char long PR to add a hyphen
Fixes #145

Add hyphen after pod name

---

README.md
manifests/controller/cdi-controller-deployment.yaml

add tighter rbac to controller

---

pkg/controller/controller.go
pkg/controller/util.go

fixes #160 
Improves (hopefully) some log messages with better consistency.
Some err messages also updated.

change Patch to Update

---

pkg/controller/controller.go
pkg/controller/util.go

refactor of util funcs

---

manifests/controller/cdi-controller-deployment.yaml

add rbac access to secrets

---

Makefile

Standardize build environments by switching to a Docker container to compile project binaries.

Containerized Build Env

---

Makefile

fixes #195 
adding :Z flag to -v run volumes

fix SELinux perms

---

.travis.yml

Shut off travis deployments until versioning and api fixes have been made and tested.

temporarily disable travis deployments

---

Makefile

fix issue 199 - add containerized and non-containerized ability to Makefile

---

README.md
doc/releases.md

Publish CDI versioning and release procedures for developer reference
Addresses #205

Add release procedure documentation

---

hack/version/lib.sh

Add 'g' to sed command for global substitutions

make set-version: do global sed replacements of versions

---

pkg/controller/import-controller_test.go
pkg/controller/util_test.go

[WIP] add unit test for pkg/controller util_test.go and import_controller_test.go

---

Makefile

trying to containerize unit tests

WIP: containerizing unit-tests

---

README.md

Add Size() info and restrictions to readme.
Fixes #232

add Size to readme

---

manifests/controller/cdi-controller-deployment.yaml

These are just some simple changes to the manifest that help the quality of life for other projects consuming the controller manifest.
functionally, nothing is changing here

Controller Manifest Updates

---

cmd/controller/controller.go
manifests/cloner/Dockerfile
manifests/cloner/script.sh
manifests/example/target-pvc.yaml
pkg/common/common.go
pkg/controller/clone-controller.go
pkg/controller/util.go

Still need to add 'CloneOf' on cloning completion.
I might also find a way to label the node automatically, for the the NodeAffinity.

[WIP] Host-assisted cloning integrated to CDI

---

Makefile

@copejon has a Makefile / test refactoring on the way, but meanwhile I need this minor change so that CI passes for pr #227

minor unit-test fix

---

pkg/common/common.go
pkg/controller/clone-controller.go
pkg/controller/util.go

Pod-affinity fails when cloning is done within same namespace #261

Pod-affinity fails when cloning is done within same namespace #261

---

.gitignore
.travis.yml
Makefile
hack/build/build-go.sh
hack/build/build-manifests.sh
hack/build/docker/builder/Dockerfile
hack/build/goveralls.sh

Adds makefile target for goverall coverage reporting for coveralls.io.
Adds travis step to generate goverall report per commit merge/push to upstream/master

Add goveralls support to makefile

---

.gitignore
.travis.yml
Makefile
doc/releases.md
hack/README.md
hack/build/config.sh
hack/build/release-description.sh

Mimics kubevirt's realease-announcement generator script and make target
Refactors makefile to remove ugly duplication

Release announcement generator

---

.travis.yml
hack/build/build-manifests.sh
tools/manifest-generator/manifest-generator.go

Fixes https://github.com/kubevirt/containerized-data-importer/issues/223

[WIP] Provide a jinja2 template for the cdi manifest 

---

hack/README.md

fixes #327 
Add simple instructions on how to execute the `make functest` properly

add e2e functional test steps to hack/README.md

---

tests/utils.go

- Added code to get an instance of a CDI client, copied from PR #328

Add CDI client getter

---

tests/tests_suite_test.go
tests/utils.go

- Added randomized_namespace generation code, copied from PR #328 and
changed to use Namespace instead of strings.

Add create/delete randomized_namespace

---

tests/pvc_utils.go

Added some PVC utility functions

---

Makefile
hack/build/build-functest.sh
hack/build/docker/builder/Dockerfile
pkg/controller/import_controller_ginkgo_suite_test.go
pkg/importer/importer_suite_test.go
tests/reporters/reporters.go
tests/tests_suite_test.go

It is necessary to close a loop for QE life-cycle .
Signed-off-by: Lukas Bednar <lbednar@redhat.com>

Add option to generate junit and polarion report

---

doc/releases.md
hack/README.md

Fixes the make targets in hack/README.md
Adjusts the release directions in doc/releases.md

Update hack readme

---

tests/basic_sanity_test.go
tests/framework/framework.go
tests/import_test.go

Change embedded Config from ptr to regular embed

---

tests/cloner_test.go
tests/framework/exec_util.go
tests/framework/framework.go
tests/framework/pod.go
tests/framework/pvc.go
tests/utils/pod.go
tests/utils/pvc.go

- Positive test clone from namespace into same namespace.
- Positive test clone from namespace into other namespace.
- Re-arranged pod helpers in framework.

Add cloner e2e tests

---

cmd/cdi-controller/controller.go
pkg/controller/clone-controller.go
pkg/controller/clone-controller_test.go
pkg/controller/import-controller_test.go
pkg/controller/util.go
pkg/controller/util_test.go

CDI: expectations and single queue - cloning refactoring

---

Makefile
automation/check-patch.k8s-1.10.4-release.mounts
automation/check-patch.k8s-1.10.4-release.packages
automation/check-patch.k8s-1.10.4-release.sh
automation/check-patch.mounts
automation/check-patch.openshift-3.10-release.mounts
automation/check-patch.openshift-3.10-release.packages
automation/check-patch.openshift-3.10-release.sh
automation/check-patch.packages.el7
automation/check-patch.sh
automation/test.sh
cluster/cli.sh
cluster/sync.sh
cluster/up.sh
hack/build/config.sh
hack/build/run-functional-tests.sh
hack/build/run-tests.sh
stdci.yaml
tests/cloner_test.go
tests/framework/framework.go
tests/utils.go
tests/utils/pod.go

- Added oVirt STDCI configuration files.

Configure STDCI

---

Makefile

Fix `docker-functest-image-http` target bug that caused the build to fail in clean repo.

tweak makefile filehost build target

---

hack/README.md

add hack/README documentation for non-standard execution path of functional tests

---

tests/framework/framework.go
tests/utils/pod.go

- Implemented missing LabelSelector code.
- Fixed bug where err was not nil in inner function.

Fix find pod by prefix

---

pkg/importer/dataStream.go
pkg/importer/dataStream_test.go
pkg/importer/importer_test.go
pkg/importer/util.go

Fix golint on importer pkg

---

tests/framework/framework.go

Return error if creating of clients fails in framework

---

hack/build/run-functional-tests.sh

- If a CDI pod fails it should abort the CI run.

Add retry counter for waiting on CDI pods

---

pkg/common/common.go
pkg/controller/util.go
pkg/controller/util_test.go
tests/transport_test.go

Fixed capitalization to correalte with other constants in the file.

common: fixed key constants capitalization

---

pkg/expectations/expectations.go

Avoiding any real changes other than just the required items to make
golint pass.  Realizing that this is a copy/past of k8s pkg.

Fix golint errors on expectations pkg

---

pkg/image/filefmt.go
pkg/image/qemu.go
pkg/image/validate.go

Fix golint errors in image pkg

Fix lint erros in image pkg

---

pkg/controller/clone-controller.go
pkg/controller/clone-controller_test.go
pkg/controller/datavolume-controller.go
pkg/controller/import-controller.go
pkg/controller/util.go
pkg/controller/util_test.go

Fix golint errors in controller pkg (replaces previous work in smaller chunks)

Fix golint errors on controller pkg directory

---

pkg/controller/util.go

Fix the standard PVC e2e test failing.

---

manifests/example/golden-pvc.yaml

doc: Add storage class to example PVC

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Issue and PR templates for PROW

---

cluster/down.sh

fixes #434 
not sure this is necessary in ci environment but I noticed locally these volumes add up on my system and eat up all my space, so adding a little clean up routine.

cleaning up dangling volumes from cluster-up

---

manifests/example/cloner-datavolume.yaml
manifests/example/datavolume.yaml

These examples will only work with ReadWriteOnce access mode
Fixes #
```release-note
NONE
```

Update datavolume examples to use ReadWriteOnce for hostpath

---

manifests/templates/file-host.yaml.in
tests/transport_test.go
tests/utils/common.go
tests/utils/services.go

Improves transport tests to check that the downloaded file size matches it's remote source's size.
Adds file host utilities for 
- getting all remote files
- getting a remote file's size

Transport tests validate image size

---

pkg/controller/clone-controller.go
pkg/controller/clone-controller_test.go
pkg/controller/controller.go
pkg/controller/controller_test.go
pkg/controller/datavolume-controller.go
pkg/controller/datavolume-controller_test.go
pkg/controller/import-controller.go
pkg/controller/import-controller_test.go
pkg/controller/util.go
pkg/controller/util_test.go
tests/cloner_test.go
tests/utils.go

This PR reduces the duplicated code in the clone, datavolume, and import controllers making maintenance easier.
Fixes #
```release-note
NONE
```
**

CDI controller code dedupe

---

pkg/apis/datavolumecontroller/v1alpha1/types.go
pkg/client/clientset/versioned/clientset.go
pkg/client/clientset/versioned/fake/clientset_generated.go
pkg/client/clientset/versioned/fake/register.go
pkg/client/clientset/versioned/scheme/register.go
pkg/client/clientset/versioned/typed/datavolumecontroller/v1alpha1/datavolume.go
pkg/client/clientset/versioned/typed/datavolumecontroller/v1alpha1/datavolumecontroller_client.go
pkg/client/clientset/versioned/typed/datavolumecontroller/v1alpha1/fake/fake_datavolume.go
pkg/client/clientset/versioned/typed/datavolumecontroller/v1alpha1/fake/fake_datavolumecontroller_client.go
pkg/client/informers/externalversions/datavolumecontroller/v1alpha1/datavolume.go
pkg/client/informers/externalversions/factory.go
pkg/client/informers/externalversions/generic.go
pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
pkg/client/listers/datavolumecontroller/v1alpha1/datavolume.go
pkg/controller/datavolume-controller.go

This PR add a missing secret ref needed for accessing protected http data sources using data volumes.
Fixes #441 
```release-note
NONE
```

Add SecretRef for HTTP data source.

---

hack/build/build-manifests.sh
manifests/templates/cdi-controller.yaml.in

Fixes #
```release-note
NONE
```

Fix templatized manifest for upload containers

---

README.md

Adds badged for goreport and goveralls to easily see status of code.
Fixes #
```release-note
NONE
```

Add goverals/go report in README

---

pkg/apiserver/apiserver.go
pkg/expectations/expectations.go
tests/cloner_test.go
tests/framework/framework.go
tests/utils/fileConversion.go

It fixes some spelling errors
It fixed some assignments that did nothing anyway.
Fixes #
```release-note
NONE
```

Clean up some code and spelling issues.

---

doc/datavolumes.md
manifests/example/example-clone-dv.yaml
manifests/example/example-import-dv.yaml
manifests/example/example-vm-dv.yaml

This PR adds documentation explaining the benefits of Data Volumes and gives some examples.
None
```release-note
NONE
```

Add Data Volume documentation

---

pkg/importer/dataStream.go

By default, the go http client has no timeout.  Meaning it could block forever!  This PR adds a very generous timeout of 1 hour.  
Fixes #
```release-note
Add 1hr timeout to http(s) import download
```

add timeout to http client

---

cluster/up.sh

- For a development environment set a fixed OCP console port (8443)
When creation an instance of a CDI development environment (make cluster-up) with an open shift provider, set the console port to a fixed value instead of picking a random port.
Fixes #
```release-note
NONE
```

Set fixed OCP console port in dev environment

---

pkg/controller/datavolume-controller.go
tests/datavolume_test.go

Fixes #437
```release-note
NONE
```

add events to DataVolume controller

---

tests/cloner_test.go
tests/import_test.go
tests/transport_test.go
tests/utils/pod.go
tests/utils/pvc.go
tests/utils/secrets.go

CDI e2e negative tests

---

pkg/controller/upload-controller.go
pkg/controller/upload-controller_test.go

Let's say a user deletes a PVC before uploading to it.  Currently the pvc does not get deleted because the upload pod is running.  And the pod does not get deleted because it is "owned by" the PVC.  Basically a catch 22 situation here.
Fixes #
```release-note
NONE
```

force delete upload pod if not completed and pvc deleted

---

hack/README.md

Add test-lint target in hack/README make targets description
Fixes #
```release-note
NONE
```
Signed-off-by: Fred Rolland <frolland@redhat.com>

Add test-lint target to README

---

pkg/controller/import-controller.go
pkg/controller/util.go
pkg/controller/util_test.go

Add structure to hold all CDI importer environment variables
Fixes #501 
```release-note
NONE
```

Add structure to hold all CDI importer environment variables #501

---

manifests/templates/cdi-controller.yaml.in
pkg/controller/util.go
pkg/controller/util_test.go

This PR makes sure all CDI components are properly labeled with cdi.kubevirt.io
Fixes #
```release-note
All CDI components are now labeled with cdi.kubevirt.io
```

Properly label all CDI components.

---

tests/cloner_test.go
tests/datavolume_test.go
tests/framework/framework.go
tests/import_test.go
tests/utils.go
tests/utils/datavolume.go
tests/utils/pod.go

Increase all the timeouts to account for the over commit on the STD CI system to hopefully increase the success rate of the e2e tests.
Fixes #
```release-note
NONE
```

Increase e2e test timeouts.

---

manifests/templates/cdi-controller.yaml.in
pkg/apiserver/apiserver.go
pkg/apiserver/webhooks/validating-webhook/validating-webhook.go
pkg/apiserver/webhooks/validating-webhook/validating-webhook_test.go

make sure we create valid API objects.
This PR consists of 2 parts:
1. CRDs are auto generated according to API schema.
2. Non-conforming DataVolumes objects are rejected by validating webhook.
Fixes #439 
``` 
API objects are now validated and non-conforming objects should be rejected.
```

add API validations

---

tests/utils/deployments.go

Fixes #
```release-note
NONE
```

fix minor typo in comments

---

pkg/controller/datavolume-controller.go
tests/datavolume_test.go
tests/upload_test.go
tests/utils/pod.go
tests/utils/pvc.go
tools/cdi-func-test-file-host-init/main.go

Attempts to fix some of the flaky CI tests to make it more useful.
```release-note
NONE
```

Fix some flaky tests.

---

pkg/importer/dataStream.go

Call the right function to resize.
Fixes #
```release-note
NONE
```

Use ResizeImage instead of Resize

---

hack/README.md

Added a note about running specific functional tests using ginkgo command line options.
```release-note
None
```

dev readme: run specific functional tests

---

tests/utils/datavolume.go

Remove a duplicate comment from 'NewDataVolumeWithPVCImport' func.
Fixes #
```release-note
NONE
```

datavolume: remove a duplicate comment

---

pkg/importer/dataStream.go

dataStream -> DataStreamOptions -> SecKey: comment that the string is encoded in base64.
Fixes #
```release-note
NONE
```

dataStream: DataStreamOptions - comment on base64

---

pkg/util/util_test.go
tests/cloner_test.go
tests/datavolume_test.go
tests/utils/pvc.go

Add extra logging to the clone e2e tests. It sometimes fails and this will hopefully help debug why.
Fixes #
```release-note
NONE
```

Added logging to cloning e2e tests to figure out why it sometimes fails.

---

cmd/cdi-importer/importer.go
pkg/common/common.go
pkg/importer/dataStream.go
pkg/importer/dataStream_test.go
pkg/importer/util.go
tests/utils/fileConversion.go

This pull request adds CDI the support for unpacking archives.
Fixes #
```release-note
NONE
```

Unpacking archives

---

doc/archived/manual-deploy.md

Fixes #
```release-note
NONE
```

Minor typo fix to check CI in master

---

glide.lock
vendor/github.com/ulikunitz/xz/TODO.md
vendor/github.com/ulikunitz/xz/cmd/gxz/licenses.go
vendor/github.com/ulikunitz/xz/cmd/gxz/version.go
vendor/github.com/ulikunitz/xz/cmd/xb/copyright.go
vendor/github.com/ulikunitz/xz/cmd/xb/version.go
vendor/github.com/ulikunitz/xz/lzma/encoder.go
vendor/k8s.io/gengo/.import-restrictions
vendor/k8s.io/gengo/examples/deepcopy-gen/generators/deepcopy.go
vendor/k8s.io/gengo/examples/deepcopy-gen/generators/deepcopy_test.go
vendor/k8s.io/gengo/examples/deepcopy-gen/main.go
vendor/k8s.io/gengo/examples/defaulter-gen/.import-restrictions
vendor/k8s.io/gengo/examples/defaulter-gen/generators/defaulter.go
vendor/k8s.io/gengo/examples/defaulter-gen/main.go
vendor/k8s.io/gengo/examples/import-boss/generators/import_restrict.go
vendor/k8s.io/gengo/examples/import-boss/main.go
vendor/k8s.io/gengo/examples/set-gen/generators/sets.go
vendor/k8s.io/gengo/examples/set-gen/generators/tags.go
vendor/k8s.io/gengo/examples/set-gen/main.go
vendor/k8s.io/gengo/generator/execute.go
vendor/k8s.io/gengo/generator/import_tracker.go
vendor/k8s.io/gengo/parser/parse.go
vendor/k8s.io/gengo/types/types.go

Updates some vendored dependencies.
Fixes #
```release-note
NONE
```

Update vendor dependencies.

---

doc/annotations.md
doc/local-pv-allocation.md
manifests/example/local-pv-allocation-claim.yaml

Fixes #
```release-note
NONE
```

Fix wrong annotation in documentation

---

hack/build/release-description.sh

Update the template for the release description to include all the links and text.
Fixes #
```release-note
NONE
```

Updated release-description.sh to include relevant info.

---

doc/blank-raw-image.md

A user guide for creation of a blank raw image
```release-note
A user guide for creation of a blank raw image
```

How to create Blank Raw Image User Guide

---

cmd/cdi-cloner/clonertarget.go
cmd/cdi-cloner/clonertarget_test.go
pkg/image/skopeo.go
pkg/importer/dataStream.go
pkg/importer/registry_test.go
pkg/importer/util.go
pkg/util/util.go
tests/transport_test.go

Added UnArchiveLocalTar func to util for using in skoepo (instead of ExtractTar func).
Fixes #
```release-note
None
```

skopeo: use util UnArchiveTar

---

cmd/cdi-importer/importer.go
pkg/system/prlimit.go
tests/framework/pvc.go
tests/import_test.go
tests/upload_test.go
tests/utils/pvc.go

(cherry picked from commit 2b6b39361adec3237a5e98462466c7f2cc850a00)
Fixes #561 
```release-note
Fixes issue #561 
```

was incorrectly getting available free space on volume

---

doc/image-from-registry.md

Fixes #
```release-note
NONE
```

Add doc how to build a registry image with VM disk

---

tests/api_validation_test.go
tests/manifests/datavolume.yaml

e2e testing of api object validation
```release-note
NONE
```

API validation test

---

pkg/controller/clone-controller.go

Fixing issue #560 Clone sometimes doesn't add k8s.io/CloneOf annotation to target PVC
Fixes #560 
```release-note
NONE
```

Clone sometimes doesn't add k8s.io/CloneOf annotation to target PVC #560

---

manifests/templates/cdi-controller.yaml.in
pkg/apiserver/webhooks/validating-webhook/validating-webhook.go
pkg/apiserver/webhooks/validating-webhook/validating-webhook_test.go

Fixes #
```release-note
NONE
```

Add Registry source validation to Datavolume

---

tests/datavolume_test.go
tests/framework/exec_util.go
tests/framework/pv.go
tests/framework/pvc.go
tests/import_test.go
tests/local_volume_test.go
tests/transport_test.go
tests/upload_test.go
tests/utils/cli.go
tests/utils/datavolume.go
tests/utils/pod.go
tests/utils/pv.go
tests/utils/pvc.go
tests/utils/upload.go

we need more functional tests to increase our testing coverage.
Fixes #
```release-note
None
```

Adding more functional tests for blank-raw-image, PV allocation on specific node and upload disk image features

---

doc/exposing-upload-proxy.md

small fix in exposing CDI upload proxy document.
Fixes #
```release-note
NONE
```

fix open quotes

---

doc/annotations.md

Fixes #
```release-note
NONE
```

Fix annotation in documentation

---

pkg/importer/dataStream.go
pkg/importer/dataStream_test.go

We have a lot of code duplicity in data stream and the code is messy.
Organized copy function so that we can add more import types to this function (registry for example).
Fixes #
```release-note
NONE
```

refactor data stream copy 

---

manifests/templates/file-host.yaml.in
manifests/templates/registry-host.yaml.in

Alternative to:  https://github.com/kubevirt/containerized-data-importer/pull/612
Fixes #
```release-note
NONE
```

Alternative fix for broken Openshift functional test

---

pkg/apiserver/apiserver_test.go
pkg/operator/api.go

adding the owner reference to the api service broke unit tests.  this should fix.
Fixes #
```release-note
NONE
```

fix apiserver unittests

---

pkg/apiserver/webhooks/validating-webhook/validating-webhook.go
pkg/apiserver/webhooks/validating-webhook/validating-webhook_test.go
tests/api_validation_test.go
tests/manifests/dv0SizePVC.yaml
tests/manifests/dvBlankArchive.yaml
tests/manifests/dvInvalidContentType.yaml
tests/manifests/dvInvalidSourcePVC.yaml
tests/manifests/dvInvalidURL.yaml
tests/manifests/dvMissingPVCSpec.yaml
tests/manifests/dvMissingResourceSpec.yaml
tests/manifests/dvMissingSource.yaml
tests/manifests/dvMultiSource.yaml

Adds validation of content type in data volumes.
Adds unit tests to verify the validation.
Fixes #
```release-note
Added validation of content type in data volumes.
```

Add validation of content type and unit tests.

---

.travis.yml
hack/build/build-manifests.sh

Update the files that are on the release page to include latest binaries and examples.
```release-note
NONE
```

Updated the released files to include operator and current binaries.

---

pkg/image/qemu.go
pkg/image/qemu_test.go
pkg/importer/dataStream.go
pkg/importer/dataStream_test.go

Backport of #632 
Fixes #
```release-note
NONE
```

Check if target size < virtual size, if so reject import.

---

pkg/controller/import-controller.go
pkg/controller/import-controller_test.go

backport of #644 to release-v1.5
Fixes #
```release-note
NONE
```

backport of #644 to release-v1.5

---

cmd/cdi-importer/importer.go
pkg/importer/dataStream.go
pkg/importer/dataStream_test.go
pkg/importer/registry_test.go

Backport of #648 with some adjustments for divergence.
Fixes #
```release-note
NONE
```

Check space before importing to report correct image resize size.

---

cmd/cdi-importer/importer.go
doc/image-from-registry.md
hack/build/docker/cdi-func-test-registry-populate/populate-registry.sh
manifests/example/registry-image-pvc.yaml
pkg/importer/dataStream.go
pkg/importer/dataStream_test.go
pkg/importer/registry_test.go
pkg/importer/util.go
pkg/util/util.go
tests/transport_test.go
tests/utils/datavolume.go
tests/utils/pod.go
tools/cdi-func-test-registry-init/main.go

Fixes #
```release-note
CDI import from registry supports the same container image format as  kubevirt containerdisks
```

Import container disk image from registry

---

pkg/importer/dataStream.go

This PR fixes two bugs, one where the space validation is incorrect and another where the error is not being propagated properly back to the called.
Fixes #
```release-note
NONE
```

Fix validate space constraints to properly validate the space needed.

---

api/openapi-spec/swagger.json
cmd/cdi-importer/importer.go
hack/build/docker/cdi-func-test-registry-init/Dockerfile
manifests/example/registry-image-pvc.yaml
manifests/templates/registry-host.yaml.in
pkg/apis/core/v1alpha1/openapi_generated.go
pkg/apis/core/v1alpha1/types.go
pkg/apis/core/v1alpha1/types_swagger_generated.go
pkg/common/common.go
pkg/controller/datavolume-controller.go
pkg/controller/import-controller.go
pkg/controller/util.go
pkg/controller/util_test.go
pkg/image/skopeo.go
pkg/image/skopeo_test.go
pkg/importer/dataStream.go
pkg/importer/dataStream_test.go
pkg/importer/registry_test.go
tests/datavolume_test.go
tests/transport_test.go
tests/utils/common.go
tests/utils/configmaps.go
tools/cdi-func-test-registry-init/main.go

Registry imports secure by default.  Ability to specify certs when importing.
Fixes #
```release-note
NONE
```

secure registry import

---

api/openapi-spec/swagger.json
cmd/cdi-importer/importer.go
hack/build/docker/cdi-func-test-registry-init/Dockerfile
manifests/example/registry-image-pvc.yaml
manifests/templates/registry-host.yaml.in
pkg/apis/core/v1alpha1/openapi_generated.go
pkg/apis/core/v1alpha1/types.go
pkg/apis/core/v1alpha1/types_swagger_generated.go
pkg/common/common.go
pkg/controller/datavolume-controller.go
pkg/controller/import-controller.go
pkg/controller/util.go
pkg/controller/util_test.go
pkg/image/skopeo.go
pkg/image/skopeo_test.go
pkg/importer/dataStream.go
pkg/importer/dataStream_test.go
pkg/importer/registry_test.go
tests/datavolume_test.go
tests/transport_test.go
tests/utils/common.go
tests/utils/configmaps.go
tools/cdi-func-test-registry-init/main.go

Backport secure registry support
Fixes #
```release-note
NONE
```

secure registry 1.5

---

pkg/util/util.go

Fixes #
Remove unused code
```release-note
None
```

Remove unused code

---

pkg/image/qemu.go
pkg/image/qemu_test.go
pkg/image/skopeo.go

Turns out our process limits were a little too um limiting.  Only limit "qemu-img info"
Fixes #
```release-note
NONE
```

only limit "qemu-img info"

---

tests/upload_test.go
tests/utils.go
tests/utils/upload.go

Been meaning to switch this over ever since I learned about port-forward
Fixes #637
```release-note
NONE
```

use port forwarding for upload tests instead of ssh to node01

---

doc/upload.md

**What this PR does / why we need it**: more docs on the upload proxy to make it easier to set up for people

Add info on kubectl port-fwd to upload doc

---

pkg/controller/config-controller.go
pkg/controller/util.go
pkg/controller/util_test.go

Fixes #674
```release-note
NONE
```

Make the CDI Config more resilient to runtime errors

---

.travis.yml
hack/build/docker/builder/Dockerfile
pkg/image/qemu.go
pkg/importer/dataStream.go
pkg/operator/api.go
pkg/uploadserver/uploadserver.go
tools/openapi-spec-generator/openapi.go

Let's use the same version of Go as KubeVirt
Fixes #
```release-note
NONE
```

update go to 1.11.5

---

pkg/uploadproxy/uploadproxy.go

This should help with flaky functional tests that I see locally.  Also good for real world?  I think so.  
Fixes #
```release-note
NONE
```

make uploadproxy slightly more resilient to network errors

---

cluster/clean.sh
hack/build/docker/cdi-func-test-file-host-http/nginx.conf
manifests/templates/file-host.yaml.in
pkg/importer/dataStream.go
pkg/importer/dataStream_test.go
tests/datavolume_test.go
tests/transport_test.go
tests/utils/certs.go
tests/utils/common.go
tests/utils/configmaps.go
tests/utils/datavolume.go
tools/cdi-func-test-file-host-init/main.go
tools/cdi-func-test-registry-init/main.go

We added `storage.import.certConfigMap` for registry import, so why not use it for https import as well
Fixes #
```release-note
NONE
```

https cert configuration

---

doc/datavolumes.md
manifests/example/cert-configmap.yaml

Document https cert configuration
Fixes #
```release-note
NONE
```

update docs for https cert configuration

---

doc/image-from-registry.md

Security tunables for registry import.
Fixes #
```release-note
NONE
```

add documentation on registry security

---

hack/build/docker/cdi-func-test-registry-populate/populate-registry.sh
manifests/templates/registry-host.yaml.in

1. remove unecessary pvc and volume mount
2. bug fix in populate-registry error handling
Fixes #
FIxes:
1. Remove unnecessary pvc in registry pod configuration
2. fix error handling in populate_registry.sh script 
```release-note
None
```

registry func test host fixes

---

cmd/cdi-operator/operator.go
pkg/operator/controller/controller.go
pkg/operator/controller/controller_test.go
pkg/operator/controller/route.go
pkg/operator/controller/scc.go
pkg/operator/controller/util.go

Operator creates route for upload proxy (must remove from kubevirt-ansible).
While I was in there, I also did some cleanup:  
Make sure we were watching securitycontextconstraints
Don't watch configmaps/secrets since they may be mutated
Fixes #
```release-note
Operator creates UploadProxy Route for Openshift deployments
```

operator creates upload proxy route

---

doc/upload.md

Issue brought to our attention via community member.
Fixes #
```release-note
NONE
```

add missing apiVersion to upload doc

---

doc/import-block-pv.md

Fixes #737 
```release-note
None
```

Fixing issue 737 - update import-block-pv.md

---

doc/scratch-space.md
doc/supported_operations.md

Documents the supported combination of content-type/source/formats
Fixes #
```release-note
NONE
```

Support matrix

---

pkg/apiserver/webhooks/validating-webhook/validating-webhook.go
tests/api_validation_test.go
tests/manifests/dvMissingPVCSize.yaml

Fixes #
```release-note
BugFix: better error message if pvc requests size is missing
```

add a better error message if pvc size is missing

---

cmd/cdi-cloner/cloner_startup.sh
cmd/cdi-cloner/clonertarget.go
doc/clone-block-datavolume.md
hack/build/docker/cdi-cloner/Dockerfile
hack/build/docker/cdi-func-test-block-device/entrypoint.sh
manifests/example/clone-block-datavolume.yaml
manifests/templates/block-device.yaml.in
pkg/common/common.go
pkg/controller/clone-controller_test.go
pkg/controller/util.go
pkg/controller/util_test.go
pkg/importer/http-datasource.go
pkg/importer/s3-datasource.go
pkg/importer/upload-datasource.go
pkg/importer/util.go
pkg/importer/util_test.go
pkg/util/util.go
tests/cloner_test.go
tests/datavolume_test.go
tests/framework/pvc.go
tests/import_test.go
tests/upload_test.go
tests/utils/pod.go
tests/utils/pv.go

This is WIP pr for adding support to clone disk image from one Block PV to another.
```release-note
Adding support to clone disk image from one raw block PV to another
```

Adding support to clone disk image from one Raw Block PV to another 

---

manifests/example/upload-block-datavolume-token.yaml
manifests/example/upload-block-datavolume.yaml
pkg/controller/util.go
tests/upload_test.go
tests/utils/pvc.go
tests/utils/upload.go

Adding support to upload disk image to a Raw Block PV
```release-note
Adding support to upload disk image to a Raw Block PV
```

Adding support to upload disk image to a Raw Block PV

---

doc/supported_operations.md

Clarify that we require scratch space regardless of if we use it in upload.
Fixes #
```release-note
NONE
```

Clarify upload scratch space usage.

---

api/openapi-spec/swagger.json
pkg/apis/core/v1alpha1/openapi_generated.go
pkg/apis/core/v1alpha1/types.go
pkg/operator/controller/controller.go
pkg/operator/controller/controller_test.go

See referenced issue.  Basically, add the ability to specify docker repo/tag in CDI object.
Fixes #741 
```release-note
NONE
```

allow for override of registry and tag in CDI object

---

README.md

**What this PR does / why we need it**: drop the curl progress bar where it's very much not needed.
```
NONE
```

Make curl silent on install instructions

---

doc/datavolumes.md
manifests/example/vm-dv.yaml

Fix some documentation example links.
Fixes #719
```release-note
NONE
```

Fix example links in datavolume documentation.

---

pkg/apiserver/webhooks/validating-webhook/validating-webhook.go
pkg/controller/clone-controller.go
pkg/controller/clone-controller_test.go
pkg/controller/util.go
pkg/controller/util_test.go

Before attempting to clone verify the following:
The target request size >= source request size.
The target and source volume modes are the same.
Fixes #
```release-note
NONE
```

Verify source and target PVC are correct before proceeding with clone.

---

README.md

Fixes link to example in main readme.
Fixes #765
```release-note
NONE
```

Fix link to example in REAdME

---

doc/exposing-upload-proxy.md

Fixes #
```release-note
NONE
```

fix link in exposing upload proxy document

---

cmd/cdi-cloner/clonertarget.go

Adds some extra logging to the cloner target pod to see where it gets stuck in CI sometimes.
Fixes #
```release-note
NONE
```

Extra logging for cloner target

---

pkg/importer/data-processor.go
pkg/importer/util.go

Cleans up target directory before writing when importing.
Fixes #
This is a fix for random CI failures where a restart of a failed pod leaves garbage behind.
```release-note
NONE
```

Before writing import, clean target filesystem.

---

pkg/operator/resources/operator/operator.go
tests/operator_test.go

Operator RBAC was updated recently and did not have proper permission to create a route. 
Fixes #
```release-note
NONE
```

fix operator route creation

---

api/openapi-spec/swagger.json

We merged a PR that forgot to run make generate, this fixes that.
Fixes #
```release-note
NONE
```

Ran make generate.

---

tests/api_validation_test.go
tests/basic_sanity_test.go
tests/manifests/dvBlankInvalidContentType.yaml
tests/manifests/dvInvalidAccessModes.yaml
tests/manifests/dvInvalidStorageSizeQuantity.yaml
tests/manifests/dvLeadingZero.yaml
tests/manifests/dvMissingCompleteSpec.yaml
tests/manifests/dvMissingRequestSpec.yaml
tests/manifests/dvMissingSource2.yaml
tests/manifests/dvMissingSourceHttp.yaml
tests/manifests/dvMultipleAccessModes.yaml
tests/manifests/dvNoMetaData.yaml
tests/manifests/dvNoName.yaml
tests/utils.go

Adds more functional tests to validate that our admission web hook is properly working.
Fixes #
```release-note
NONE
```

DataVolume api validation

---

README.md
doc/basic_pv_pvc_dv.md

Adds some documentation on how to provision storage for kubernetes.
Fixes #776 
```release-note
NONE
```

Added some basic storage information

---

pkg/operator/resources/operator/operator.go
tests/operator_test.go

Backport for 1.9
Fixes #
```release-note
NONE
```

backport route creation fix to 1.9

---

tests/import_test.go

Fixes the use of a const that was removed in another PR. This broke master.
Fixes #
```release-note
NONE
```

Fix archive test to properly use cdi namespace variable.

---

doc/cdi-operator-olm.md
pkg/operator/resources/operator/components.go
pkg/operator/resources/operator/operator.go

- BugFix of issue https://github.com/kubevirt/containerized-data-importer/issues/802
- tuned cdi-operator rbac
1. tuned securityconstraints permission for priviledged and not
2. added permission for get and list of storagclass resource
- md file fixes
Fixes #
https://github.com/kubevirt/containerized-data-importer/issues/802
1. Fixed API cdi provide for OLM manifests generation
2. Fixed typos in md file
3. Edited CDI operator cluster-role and CDI CR with additional attributes
```release-note
Must be backported to release 1.9.0, since it is …
```

BugFix: OLM manifests 

---

tests/import_test.go

Add Polarion ID to import archive test
```release-note
NONE
```

Add Polarion ID to import archive test

---

pkg/controller/import-controller.go

This PR adds the ability to record the error messages from the importer pod to the PVC event log.
Fixes #
```release-note
NONE
```

Record import failure messages

---

pkg/apiserver/webhooks/validating-webhook/validating-webhook.go

minor fix to add spaces in one of the webhook validation error msg

---

hack/build/docker/cdi-apiserver/Dockerfile
hack/build/docker/cdi-controller/Dockerfile
hack/build/docker/cdi-importer/Dockerfile
hack/build/docker/cdi-operator/Dockerfile
hack/build/docker/cdi-uploadproxy/Dockerfile
hack/build/docker/cdi-uploadserver/Dockerfile
pkg/common/common.go
pkg/controller/util.go
pkg/controller/util_test.go
pkg/operator/resources/utils/common.go
tests/upload_test.go

**What this PR does / why we need it**: For increased security, don't run our applications as root when possible.  As far as I can tell, we only need root for host assisted cloning and import/upload to a block pvc.  
Fixes #
```release-note
NONE
```

don't run as root

---

doc/datavolumes.md

Fix typo in DataVolume spec in Block Volume Mode.
Fixes #
```release-note
```

Fix typo in DataVolume example spec

---

tests/datavolume_test.go
tests/import_test.go
tests/utils/datavolume.go

Added positive and negative functional tests for importing tar archive files.
```release-note
NONE
```

datavolume_test: tar archive import

---

tests/import_test.go

Remove flaky part of import progress test that didn't really add value, but caused failures.
Fixes #
```release-note
NONE
```

Remove a flaky part of the test that didn't add value.

---

pkg/apiserver/webhooks/validating-webhook/validating-webhook.go

Fix admission webhook that checks if a PVC with the entered DV name already exists. It was looking up all pvcs instead of just the one name we were looking for.
Fixes #
```release-note
NONE
```

Use get instead of list to find the existing PVC for dv admission web hook.

---

pkg/controller/util.go

update IsOpenShift function with OCP4 changes
(cherry picked from commit cc49ec208a94e25a1035731cea0f35e8eb5051e3)
Fixes #
```release-note
BugFix: fix OpenShift checks for OCP4
```

update IsOpenShift function with OCP4 changes

---

cluster-sync/okd-4.1.0/create-local-storage-cr.yaml
cluster-sync/okd-4.1.0/provider.sh
cluster-up/ssh.sh

Creating LocalVolume failing because api version updated
Fixes #
```release-note
NONE
```

fix cluster-sync for okd

---

hack/build/run-functional-tests.sh
pkg/controller/util.go
pkg/controller/util_test.go
pkg/importer/data-processor.go
pkg/importer/data-processor_test.go
tests/cloner_test.go
tests/framework/pvc.go
tests/import_test.go
tests/upload_test.go
tests/utils/upload.go

**What this PR does / why we need it**: File based PVC cloning was broken in OS.
Fixes #870
```release-note
NONE
```

make clone pods use selinux type spc_t instead of privileged

---

tests/webhook_test.go

**What this PR does / why we need it**:  there may be a delay between when permissions are applied and enforced, so let's retry operations that expect the new permissions.
Fixes #
```release-note
NONE
```

fix flaky webhook test

---

pkg/apiserver/webhooks/datavolume-mutate.go
pkg/controller/util.go
pkg/controller/util_test.go
tests/upload_test.go

Copy/paste error broke token validation.  Will have to backport this too.
Fixes #
```release-note
NONE
```

token validation broken

---

pkg/apiserver/webhooks/datavolume-mutate.go
pkg/controller/util.go
pkg/controller/util_test.go
tests/upload_test.go

**What this PR does / why we need it**: backport of #884 to 1.9 branch
Fixes #
```release-note
NONE
```

Backport 884

---

.travis.yml
Makefile
hack/build/build-manifests.sh

Call make manifests on publish target as well.
Fixes environment variable name being incorrect.
Fixes #
```release-note
NONE
```

Call make manifests during publish as well.

---

automation/test.sh

Fixed the path where we create and write the junit xml file.
Fixes #
```release-note
NONE
```

Fix path to exported artifacts.

---

pkg/controller/datavolume-controller.go
pkg/controller/datavolume-controller_test.go

Backport of #899 
Fixes #
```release-note
NONE
```

Pass annotations to PVC from data volume.

---

tests/cloner_test.go
tests/datavolume_test.go
tests/framework/pvc.go
tests/utils/datavolume.go

Add functional tests for host assisted cloning.
Fixes #
```release-note
NONE
```

Add cloning functional tests.

---

pkg/operator/controller/callbacks.go
pkg/operator/controller/controller.go
pkg/operator/controller/controller_test.go
pkg/operator/controller/route.go
pkg/operator/controller/scc.go
pkg/operator/controller/util.go
pkg/operator/resources/namespaced/controller.go
pkg/operator/resources/namespaced/factory.go
pkg/operator/resources/operator/operator.go
pkg/operator/resources/utils/common.go

Make the operator reconcile loop more generic with callbacks.  Add SCC update/route creation to callbacks.  Also refactor code that cleans up after CDI is deleted to callbacks.
Fixes #
Somewhat related and could be considered a prereq for #910 and #902
```release-note
NONE
```

Operator refactoring to support callback model

---

Makefile

This pr fixes make targets that provide the following for cdi-olm-catalog:
* build required biaries
* create cdi-olm-catalog docker container
* push cdi-olm-catalog to docker
Fixes #
This pr fixes make targets that provide the following for cdi-olm-catalog:
* build required biaries
* create cdi-olm-catalog docker container
* push cdi-olm-catalog to docker
```release-note
None
```

* olm-catalog make target fix

---

hack/build/run-tests.sh
tests/cloner_test.go
tests/utils/datavolume.go

Introduce block versions of cloning functional tests.
Fixes #
```release-note
NONE
```

Add block versions of cloning functional tests.

---

.travis.yml

Backport #932 
Fixes #
```release-note
NONE
```

Strip 'v' from CSV_VERSION. (#932)

---

.travis.yml

Push to quay during release builds.
Fixes #
```release-note
NONE
```

Push to quay during release.

---

pkg/operator/controller/controller.go
pkg/operator/controller/controller_test.go

The conditions were not properly being set during deployment (Available too soon). This fixes the conditions to match the following:
Start deploy:
Available: false
Progression: true
Degraded: false
During deploy stay on that.
Once deploy is finished and all pods are available:
Available: true
Progression: false
Degraded: false
Fixes #
```release-note
NONE
```

Set conditions properly while deploying.

---

pkg/operator/controller/controller.go
pkg/operator/controller/controller_test.go

Backport of #948 
Fixes #
```release-note
NONE
```

Set conditions properly while deploying. (#948)

---

tests/leaderelection_test.go

Updated import while leader changes test to not use scale up as it is not reliable in all situations.
Fixes #
```release-note
NONE
```

Fix leader election test with import by not scaling.

---

automation/test.sh
cluster-sync/install.sh
cluster-sync/k8s-1.13.3/provider.sh
cluster-sync/k8s-1.15.1/provider.sh
cluster-sync/okd-4.1/install.sh
cluster-sync/sync.sh
hack/build/docker/cdi-olm-catalog/Dockerfile
pkg/operator/controller/controller.go
tests/cloner_test.go
tests/datavolume_test.go
tests/framework/pvc.go
tests/import_test.go
tests/leaderelection_test.go
tests/local_volume_test.go
tests/operator_test.go
tests/smartclone_test.go
tests/transport_test.go
tests/upload_test.go
tests/utils/upload.go

Backport the functional test fixes and updates.
Fixes #
```release-note
NONE
```

Backport functional test

---

pkg/controller/datavolume-controller.go
pkg/controller/import-controller.go
pkg/controller/import-controller_test.go
tests/import_test.go
tests/utils/datavolume.go

Creating a blank disk on a block device
```release-note
Creating a blank disk on a block device
```

Creating a blank disk on a block device

---

pkg/controller/datavolume-controller.go
pkg/controller/import-controller.go
pkg/controller/import-controller_test.go
tests/import_test.go
tests/utils/datavolume.go

Backport rbac fixes and blank disk on block.
Fixes #
```release-note
NONE
```

Creating blank disk on a block device (#962)

---

manifests/templates/release/cdi-operator.yaml.in
pkg/operator/resources/cluster/factory.go
pkg/operator/resources/cluster/rbac.go
pkg/operator/resources/operator/operator.go
tests/rbac_test.go
tests/webhook_test.go
tools/manifest-generator/manifest-generator.go

Backport of #961
Fixes #
```release-note
NONE
```

Backport 961

---

pkg/importer/data-processor.go
pkg/importer/data-processor_test.go
tests/utils/pod.go

Adds unit test to verify calculateTargetSize returns right value.
Fixes #
```release-note
NONE
```

Added unit test to verify quantity returns right value.

---

tests/rbac_test.go

backport #969
Fixes #
```release-note
NONE
```

backport #969

---

tests/local_volume_test.go
tests/utils/pod.go

Fixes #
```release-note
NONE
```
Co-authored-by: Daniel Erez derez@redhat.com
Signed-off-by: Fred Rolland frolland@redhat.com

Select a schedulable node in local PV test

---

tests/framework/pvc.go
tests/import_test.go
tests/local_volume_test.go
tests/transport_test.go
tests/upload_test.go
tests/utils/pod.go

Backport of #974 and #977 
Fixes #
```release-note
NONE
```

Functional test bp

---

pkg/apiserver/authorizer.go
pkg/apiserver/authorizer_test.go
pkg/operator/resources/cluster/rbac.go
tests/rbac_test.go

backport #979
Fixes #
```release-note
NONE
```

backport #979

---

tests/rbac_test.go

Test that upload tokens can be created
Fixes #
```release-note
NONE
```

additional RBAC test

---

cluster-up/check.sh
cluster-up/cluster/ephemeral-provider-common.sh
cluster-up/cluster/kind-k8s-sriov-1.14.2/config_sriov.sh
cluster-up/cluster/kind-k8s-sriov-1.14.2/manifests/network_config_policy.yaml
cluster-up/cluster/kind/common.sh
cluster-up/cluster/okd-4.1/provider.sh
hack/update-codegen.sh

Update the kubevirtci OKD image to have a valid certificate again.
Fixes #
```release-note
None
```

Update kubevirt ci image to have valid certificates.

---

README.md

Fixes #
```release-note
NONE
```

Provide general overview of source and contentType in README

---

tests/cloner_test.go
tests/datavolume_test.go

some test cases had bad id (starting with 'CNV-'),
some test cases had a bad attribute (case_id instead of test_id)
Fixes #
```release-note
NONE
```

Fix rfe id & test id issues

---

tests/cloner_test.go
tests/framework/BUILD.bazel
tests/framework/framework.go
tests/smartclone_test.go

Signed-off-by: Fred Rolland <frolland@redhat.com>
Co-authored-by: Daniel Erez <derez@redhat.com>
```release-note
NONE
```

Replace isSnapshotClass available logic

---

CONTRIBUTING.md

Correct URL

---

doc/clone-datavolume.md

Correct path in documentation

---

manifests/example/vm-dv.yaml

Signed-off-by: Pedro Ibáñez <pedro@redhat.com>
Fixes #
```release-note
```

fixing names issue as the image is the cirros and the names where fedora

---

automation/test.sh
cluster-sync/ephemeral_provider.sh
cluster-sync/external/provider.sh
cluster-sync/k8s-1.15.1/ceph_sc.yaml
cluster-sync/k8s-1.15.1/provider.sh
cluster-sync/k8s-1.15.1/rook_ceph.yaml
cluster-sync/okd-4.1/provider.sh
cluster-sync/sync.sh
go.mod
hack/build/run-functional-tests.sh
pkg/controller/datavolume-controller.go
pkg/controller/smart-clone-controller.go
tests/cloner_test.go
tests/framework/framework.go

Add reporting of DVs on test failures.
Update ceph to the latest version available.
Implement DV dumping on test failures.
Fixes #
```release-note
NONE
```

Replace current ceph install with operator based rook-ceph.

---

doc/smart-clone.md

Documentation wordsmithing

---

README.md

Expand the acronym "CRD", it only appears once in the README

---

automation/test.sh
pkg/operator/resources/cluster/uploadproxy.go
pkg/uploadproxy/uploadproxy.go
pkg/uploadproxy/uploadproxy_test.go
tests/upload_test.go
tests/utils/pvc.go
tests/utils/upload.go

Backport #996 
Fixes #
```release-note
NONE
```

[release-v1.10] Uploadproxy should use use pod ready annotation (#996)

---

hack/README.md

doc: don't link to the current point in the document

---

automation/test.sh
cmd/cdi-uploadserver/uploadserver.go
pkg/controller/clone-controller.go
pkg/controller/clone-controller_test.go
pkg/controller/controller.go
pkg/controller/controller_test.go
pkg/controller/import-controller.go
pkg/controller/upload-controller.go
pkg/controller/upload-controller_test.go
pkg/controller/util.go
pkg/controller/util_test.go
pkg/operator/resources/cluster/uploadproxy.go
pkg/uploadproxy/uploadproxy.go
pkg/uploadproxy/uploadproxy_test.go
pkg/uploadserver/uploadserver.go
pkg/uploadserver/uploadserver_test.go
tests/cloner_test.go
tests/upload_test.go
tests/utils/datavolume.go
tests/utils/pvc.go
tests/utils/upload.go

Revert commits to wrong branch.
Fixes #
```release-note
NONE
```

Reverts commits to v1.10 branch that are in wrong branch.

---

automation/test.sh
pkg/operator/resources/cluster/uploadproxy.go
pkg/uploadproxy/uploadproxy.go
pkg/uploadproxy/uploadproxy_test.go
tests/upload_test.go
tests/utils/pvc.go
tests/utils/upload.go

Backport of #996 
Fixes #
```release-note
NONE
```

[release v1.11] uploadproxy should use use pod ready annotation (#996) (#1020)

---

.travis.yml

Don't release as many artifacts as before, only the needed ones.
Fixes #
```release-note
NONE
```

[release v1.11] Don't release too many artifacts.

---

tests/framework/pvc.go
tests/smartclone_test.go

Inspired by issue #939
```release-note
NONE
```

Test that smart clone is used also in volumeMode: block

---

tests/cloner_test.go

Adds a functional test to verify we can clone from one node to another node when using local volume provisioner storage.
Fixes #
```release-note
NONE
```

Add node to node clone functional test

---

pkg/operator/controller/controller.go

Operator should not "fail" a CDI CR when it cannot create the ownership ConfigMap.  Addresses: https://bugzilla.redhat.com/show_bug.cgi?id=1751193
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=1751193
```release-note
NONE
```

make operator more resilient when creating ownership ConfigMap fails

---

hack/build/bazel-build-builder.sh

Had a typo in the script, this PR fixes it. It didn't show until attempting to push the image.
Fixes #
```release-note
NONE
```

Add missing parenthesis

---

cluster-sync/k8s-1.16.2/provider.sh
go.mod

Add a new ci option to use hostpath provisioner in the k8s-1.16.2 lane.
Fixes #
```release-note
NONE
```

Setup hostpath provisioner as an option in ci.

---

pkg/controller/config-controller.go
pkg/controller/config-controller_test.go
pkg/controller/util.go

Increase code coverage for these functions
Move CDI config related functions to config-controller
Add unit tests for these functions.
Fixes #
```release-note
NONE
```

Move CDI config related functions to config controller from utils.

---

cluster-sync/ephemeral_provider.sh
cluster-sync/k8s-1.16.2/provider.sh
cluster-sync/okd-4.3/hpp-master-mc.yaml
cluster-sync/okd-4.3/hpp-worker-mc.yaml
cluster-sync/okd-4.3/provider.sh
cluster-up/cluster/okd-4.3/provider.sh
hack/README.md
tests/BUILD.bazel

Enable hostpath provisioner for OKD 4.3 provider, using KUBEVIRT_STORAGE environment variable.
Fixes #
```release-note
NONE
```

Enable hostpath provisioner for OKD 4.3 kubevirtci provider.

---

tests/smartclone_test.go

Smartclone tests: refer to Polarion IDs

---

doc/upload.md

Signed-off-by: Pedro Ibáñez <pedro@redhat.com>
Minor documentation fixes. The upload.md in the documentation had a wrong filename for the token example, now it's fixed. And also the content of the file shown was incorrect and not working, fixed now too.
Fixes #
```release-note
NONE
```

upload.md minor fixes

---

cmd/cdi-operator/BUILD.bazel
go.mod

Include csv-generator in operator container release artifcat.
Fixes #1032 
```release-note
csv-generator now included in upstream release.
```

Include csv-generator in upstream operator container.

---

tests/cloner_test.go

Add test id to node to node test.
Fixes #
```release-note
NONE
```

Add id to node to node test.

---

README.md

Might be more convenient to use.
```release-note
NONE
```

README: Provide a deep link to slack

---

api/openapi-spec/swagger.json
tools/openapi-spec-generator/definitions.go
tools/openapi-spec-generator/openapi-spec-generator.go

This has been missing for a long time
Fixes #
```release-note
NONE
```

add CDIConfig to swagger

---

doc/quota.md
tests/cloner_test.go
tests/framework/framework.go
tests/import_test.go
tests/upload_test.go
tests/utils/pod.go

Added documentation for ResourceQuota.
Add functional tests for the Resource Request/Limits feature.
Add documentation.
Fixes #
```release-note
NONE
```

Added functional tests for ResourceRequirements feature.

---

manifests/templates/imageio.yaml.in

This PR add link to source of imageio docker images used for functional tests.
This PR add link to source of imageio docker images used for functional tests.
Fixes #
```release-note
NONE
```

Add source of imageio docker images

---

go.mod
go.sum
pkg/operator/controller/controller.go
pkg/operator/controller/controller_test.go
tests/BUILD.bazel
tests/operator_test.go
vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/README.md
vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/polarion_reporter.go
vendor/modules.txt

CDI uninstall/reinstall in quick succession was occasionally causing CDI CR to get into error state.  For more info, see link.
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=1809872
Fixed by waiting for all old resources to be deleted before attempting new install.
```release-note
NONE
```

CDI install synchronization

---

tests/api_validation_test.go
tests/certrotation_test.go
tests/datavolume_test.go
tests/webhook_test.go

Fixes #
```release-note
NONE
```

Add missing test ids

---

go.sum
pkg/operator/controller/controller.go
pkg/operator/controller/controller_test.go
tests/BUILD.bazel
tests/operator_test.go
vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/README.md
vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/polarion_reporter.go
vendor/modules.txt

cherrypick #1156 
Fixes #
```release-note
NONE
```

cherry-pick #1156 to release-1.13

---

pkg/system/prlimit.go

Removes unnecessary log message. The system.ExecWithLimits did log error message and return error, and even when the caller ignored errors, the message was logged - this was confusing for users. Since it returns err, there is no need to log it.
Example: When resizing an image to available space (util.RetryBackoffSize) - after a failure it retries with new parameters until it succeeds (max 10 times), and it ignores errors until max retries is reached. When it fails on first try and then succeeds it does not return error. With the old behavior an error was logged, a user could see a misleading message like this:
```
I0114 13:38:50.390318 1 data-processor.go:246] Expanding image size to: 1003917312 …
```

Remove error log from ExecWithLimits, let the caller handle this

---

go.mod
go.sum
pkg/common/common.go
pkg/operator/controller/BUILD.bazel
pkg/operator/controller/callbacks.go
pkg/operator/controller/controller.go
pkg/operator/controller/controller_test.go
pkg/operator/controller/cruft.go
pkg/operator/controller/scc.go
pkg/operator/controller/util.go
pkg/operator/resources/namespaced/controller.go
pkg/operator/resources/operator/operator.go
pkg/operator/resources/utils/common.go
tests/operator_test.go
vendor/modules.txt

See: https://bugzilla.redhat.com/show_bug.cgi?id=1821905
Fixes #
```release-note
Create dedicated SecurityContextConstraint on OpenShift
```

use dedicated SCC

---

pkg/common/common.go
pkg/operator/controller/BUILD.bazel
pkg/operator/controller/callbacks.go
pkg/operator/controller/controller.go
pkg/operator/controller/controller_test.go
pkg/operator/controller/cruft.go
pkg/operator/controller/scc.go
pkg/operator/controller/util.go
pkg/operator/resources/namespaced/controller.go
pkg/operator/resources/operator/operator.go
pkg/operator/resources/utils/common.go
tests/operator_test.go

Cherrypick #1174 to release 1.13 branch
Fixes #
```release-note
Create dedicated SecurityContextConstraint on OpenShift
```

Cherrypick #1174

---

hack/README.md

Updates provider versions in hack/README
Fixes #
```release-note
NONE
```

update hack/readme with new provider versions

---

pkg/controller/clone-controller.go

have to handle PVC delete during clone
Fixes #
```release-note
NONE
```

fix clone delete.  could not delete target while clone in progress

---

tests/leaderelection_test.go

During Leader election tests during import functional test it is possible for the pod from the original deployment to grab the leader before the pod of the new deployment (race condition). However for that test, either pod becoming leader is success if the import doesn't die during leader changes. So check both pod logs to see if one becomes leader
Fix leader election test failing sometimes when the pod from the original deployment becomes leader instead of the pod from the new deployment.
Fixes #
**Release …

Fix Leader election tests during import functional test

---

cluster-sync/ember/ember-csi-lvm.yaml
cluster-sync/ember/snapshot-class.yaml
cluster-sync/ephemeral_provider.sh
cluster-sync/k8s-1.16/provider.sh
cluster-sync/rook-ceph/operator.yaml
tests/upload_test.go

Update ember csi to latest which includes the beta snapshot API
Fixes #
```release-note
NONE
```

ember csi with beta snapshot api

---

go.mod
tests/framework/pvc.go
tests/utils/pod.go

Our cloning source pvc file didn't have a gid, so it wouldn't get copied. This PR gives the source file a GID if it applies, so it gets copied and the check properly identifies the gid.
Fixes #
```release-note
NONE
```

Give source clone pvc a gid so it gets copied properly.

---

pkg/importer/imageio-datasource.go
pkg/importer/imageio-datasource_test.go

By calling Finalize method in Close method of the imageio source
we will make sure we finalise the import immediately, rather then
rely on implicit finalise of imageio, which is based on timeout.
Fixes #
```release-note
Explicitly finalise image transfer connection instead of let it timeout for imageio datasource.
```

Call finalize in close for imageio source

---

pkg/image/qemu.go
pkg/importer/data-processor.go
tests/cloner_test.go
tests/datavolume_test.go
tests/framework/pvc.go
tests/import_test.go
tests/upload_test.go
tests/utils/pod.go

Updated functional tests to check for permissions
Make sure the disk.img file is not world readable. Updated functional tests to check for the permissions.
Fixes #
```release-note
NONE
```

Change permissions to always be 660 for the disk image.

---

tests/cdiconfig_test.go
tests/datavolume_test.go
tests/operator_test.go
tests/rbac_test.go

Fixes #
```release-note
NONE
```

Add test-ids for new tests

---

tests/framework/framework.go

Display more setup information so we can see what is going in the test setup. In particular the number of failure dumps.
Fixes #
```release-note
NONE
```

Report the failure count and environmental setup of failure counts

---

go.mod
go.sum
pkg/uploadproxy/BUILD.bazel
pkg/uploadproxy/uploadproxy.go
pkg/uploadproxy/uploadproxy_test.go
tests/upload_test.go
vendor/github.com/rs/cors/.travis.yml
vendor/github.com/rs/cors/BUILD.bazel
vendor/github.com/rs/cors/LICENSE
vendor/github.com/rs/cors/README.md
vendor/github.com/rs/cors/cors.go
vendor/github.com/rs/cors/go.mod
vendor/github.com/rs/cors/utils.go
vendor/modules.txt

CORS was more complicated than initially suspected.  Let's bring in a package to do it corectly. 
Fixes #1251 
```release-note
Add handler to uploadproxy for CORS
```

use go package to properly handle CORS requests

---

doc/quota.md

From CRD it should be "podResourceRequirements" not "PodResourceRequirements".
Fixes #
```release-note
NONE
```

Fix PodResourceRequirements

---

tests/badserver_test.go
tools/cdi-func-test-bad-webserver/main.go

Adds a missing check at the end of the tests.
Fixes #
```release-note
NONE
```

Correct check in badserver_tests

---

tests/datavolume_test.go
tools/cdi-func-test-file-host-init/nginx.conf

Adds a new test that checks if the import can continue after failure is resolved. 
Fixes #
```release-note
NONE
```

New test case "delete file during import"

---

go.mod
tests/BUILD.bazel
tests/datavolume_test.go
tests/utils/configmaps.go

Verify that the pod remains pending for a while until we create the config map and then the import succeeds.
Fixes #
```release-note
NONE
```

[test] Attempt to import from registry without the CA config map existing

---

manifests/templates/registry-host.yaml.in
tests/transport_test.go
tools/cdi-func-test-registry-init/BUILD.bazel
tools/cdi-func-test-registry-init/htpasswd
tools/cdi-func-test-registry-init/populate-registry.sh
tools/cdi-func-test-registry-init/registry-auth-config.yml
tools/cdi-func-test-registry-init/start-registry.sh

This PR adds a tier1 test for importing an image from a repository that requires user credentials.
Fixes #
```release-note
NONE
```

[test] Import from registry using credentials - tier 1 test

---

tests/cloner_test.go
tests/upload_test.go

Fix flaky test
Fixes #
#1285 
#1301
```release-note
NONE
```

Fix test kill container

---

hack/build/bazel-build-builder.sh
hack/build/bazel-docker.sh
hack/build/build-cdi-func-test-file-host.sh
hack/build/build-cdi-func-test-registry-host.sh
hack/build/build-copy-artifacts.sh
hack/build/build-functest.sh
hack/build/build-go.sh
hack/build/build-manifests.sh
hack/build/common.sh
hack/build/format.sh
hack/build/in-docker.sh
hack/build/resource-generator.sh
hack/build/run-functional-tests.sh
hack/update-codegen.sh
hack/version/set-version.sh

Fixes #1317 (possibly, I don't have a macOS machine to confirm)
```release-note
NONE
```

Avoid using unportable readlink -f, use pwd -P instead

---

hack/build/config.sh
hack/build/docker/builder/entrypoint-bazel.sh

Should have been part of #1324
Fixes #
```release-note
NONE
```

update PATH for bazel builder image

---

hack/build/config.sh

Update the image to the official image again.
Fixes #
```release-note
NONE
```

Update builder image to official latest

---

tests/BUILD.bazel
tests/explain_test.go

Add some functional tests to verify that explain works on the CDI CRDs
Fixes #
```release-note
NONE
```

Add functional tests to explain CDI CRDs.

---

tests/cloner_test.go
tests/import_test.go
tests/upload_test.go

Fix quota restore logic to use deep copy/equal instead of trying to manually restore
Fixes #
```release-note
NONE
```

Update quota restore logic

---

.travis.yml

Build the tests with the release so we stay in sync when running tests.
Fixes #
```release-note
NONE
```

Publish test binary on release

---

api/openapi-spec/swagger.json
pkg/apis/core/v1alpha1/openapi_generated.go
pkg/apis/core/v1alpha1/types.go
pkg/apis/core/v1alpha1/types_swagger_generated.go
pkg/apis/core/v1beta1/openapi_generated.go
pkg/apis/core/v1beta1/types.go
pkg/apis/core/v1beta1/types_swagger_generated.go

Text comes from pkg/operator/resources/cluster/cdiconfig.go.
```release-note
NONE
```

Copy missing description for pod resource requirement.

---

tests/import_test.go
tests/operator_test.go

Add ref_id and test_id for CDI placement API tests
Fixes #
```release-note
None
```

Add ref_id and test_id for CDI placement API tests

---

.travis.yml
Makefile
hack/build/osci-image-builder.sh
hack/ci/Dockerfile.ci
hack/ci/build-functest.sh
hack/ci/build.sh
hack/ci/test.sh

This PR prepares a docker image with functional tests binary for use in OpenShift CI
Fixes #
This is build to mimic Kubevirt's OS CI image. I'm not 100% sure what I'm doing.
```release-note
NONE
```

Prepare test image for OpenShift test lane.

---

tests/alpha_test.go
tests/cdiconfig_test.go
tests/cloner_test.go
tests/datavolume_test.go
tests/explain_test.go
tests/import_test.go
tests/operator_test.go
tests/smartclone_test.go
tests/upload_test.go

Add test_ids for the test cases
Fixes #
```release-note
None
```

Add test_ids for the test cases

---

tests/upload_test.go

Add the automated test causing a client side upload failure during upload. After verifying failure, the test continues with correct upload to check if the DV upload is eventually consistent and can finish successfully.
Fixes #
```release-note
NONE
```

Test behavior after client-side upload failure.

---

pkg/clone/auth.go
tests/webhook_test.go

Fixes #
Should really be there, but kind of NBD since we are checking a serviceaccount.
```release-note
NONE
```

add system:authenticated to groups checked for clone auth

---

cluster-sync/sync.sh

Upgrade testing should verify all cdi pod names, uids and image versions changed (CNV-5252).
```NONE
```

Check for expected changes after CDI upgrade

---

Makefile
cluster-sync/sync-os-ci.sh
hack/ci/Dockerfile.ci

Added file `cluster-sync/sync-os-ci.sh`, which pushes images to a registry and deploys CDI. Added missing commands in `hack/ci/Dockerfile.ci`
Fixes #
```release-note
NONE
```

Add files used in OpenShift CI.

---

tests/upload_test.go

Backport of #1437 
Fixes #
```release-note
NONE
```

[release-v1.23] Retry upload in case upload pod wasn't 100% ready when attempting upload (#1437)

---

hack/build/config.sh
hack/build/docker/builder/Dockerfile

Updates the builder, so PRs that need libnbd to build can work.
Fixes #
```release-note
NONE
```

Update builder image to add libnbd

---

tests/framework/framework.go

Extend the test framework so it dumps service resources as a test artifact
Fixes #
```release-note
NONE
```

Test framework dump service

---

tests/operator_test.go

The operator CR destruction suite creates stray pods by
deleting/re-creating the CDI CR, causing several pods to
terminate & be re-created.
This disrupts the critical addons test, which counts the number of
pods before and after.
To avoid doing this, mimic the critical addons test and wait until
the number of pods is the same as before the test run.
While here, also destroy/re-create the CDI CR unconditionally in
AfterEach. We want all the CDI pods to be running at the end of
a test, and being sure that they were first terminated lets us
be certain that we are checking that the pods are the new ones,
not old pods that haven't started terminating yet.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when …

Fix flaky operator test

---

tests/cloner_test.go
tests/framework/pvc.go
tests/smartclone_test.go
tests/utils/pod.go

It now rate-limits unauthenticated users, so we can only run so
many tests before we hit the rate limit.
Fixes #1469
```release-note
Adjust testsuite to not hit dockerhub unauthenticated user pull limits
```

Pull less from dockerhub when running testsuite

---

pkg/apis/core/v1alpha1/BUILD.bazel
pkg/apis/core/v1alpha1/utils/BUILD.bazel
pkg/apis/core/v1alpha1/utils/utils.go
pkg/apis/core/v1alpha1/utils/utils_test.go
pkg/apis/core/v1alpha1/utils/v1alpha1_suite_test.go
pkg/apis/core/v1beta1/BUILD.bazel
pkg/apis/core/v1beta1/utils/BUILD.bazel
pkg/apis/core/v1beta1/utils/utils.go
pkg/apis/core/v1beta1/utils/utils_test.go
pkg/apis/core/v1beta1/utils/v1beta1_suite_test.go
pkg/controller/BUILD.bazel
pkg/controller/util.go

coverage is very low
Fixes #
```release-note
NONE
```

Fix coverage

---

tests/operator_test.go

In the operator test there is a critical addons test that removes and
restarts the pod used in tests. It verified the pods where 'ready' but
not that the service using those pods had working endpoints. Due to the
changes where we start the next test without waiting for the namespace
to finish deleting, those services didn't have enough time to have their
endpoints be available. This ensures the endpoints are available before
moving onto the next tests.
Fixes #
```release-note
NONE
```

Fix critical addons operator test to fully restore services before moving to next test

---

tests/operator_test.go

Ensure CDI operator continuously reconciles all the resources it created
Fixes #
```release-note
NONE
```

Add strict reconciliation tests

---

tests/operator_test.go

Sometimes other things will influence the nodes so the update will
fail on an outdated generation number.
Seen [here](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1503/pull-containerized-data-importer-e2e-k8s-1.18-nfs/1333427034675744768)
```release-note
Stabilize functional test
```

Try updating the node taint in a loop

---

pkg/controller/clone-controller.go
pkg/controller/clone-controller_test.go
pkg/controller/util.go
pkg/operator/controller/callbacks.go
pkg/operator/controller/cruft.go
pkg/operator/controller/scc.go

cherry-pick of https://github.com/kubevirt/containerized-data-importer/pull/1524
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=1907623
```release-note
Clone source pods mount PVCs read-only
```

[release-v1.23] Read-only clone source pods

---

WORKSPACE
cmd/cdi-cloner/clone-source.go
cmd/cdi-cloner/cloner_startup.sh
pkg/apis/core/v1alpha1/BUILD.bazel
pkg/apis/core/v1alpha1/utils.go
pkg/controller/clone-controller.go
pkg/controller/clone-controller_test.go
pkg/controller/datavolume-controller.go
pkg/controller/datavolume-controller_test.go
pkg/controller/util.go
pkg/operator/controller/callbacks.go
pkg/operator/controller/cruft.go
pkg/operator/controller/scc.go

cherry-pick #1521 and #1524
added commits mentioned here:  https://github.com/kubevirt/containerized-data-importer/pull/1531#issuecomment-745078925
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=1907624
```release-note
Bugfix: Clone source pod will detect tar errors and abort rather than silently ignore
Clone source pods mount PVCs read-only
```

[release-v1.18] cherry-pick #1521 and #1524

---

pkg/importer/vddk-datasource.go

Fixes a VDDK importer crash, and reports progress correctly.
Fixes #1544 
Tested a wider range of source disk images this time - originally I tested with disks that had lots of zero blocks, so I did not see this bug.
```release-note
Fixed an importer crash when copying from a VDDK data source.
```

VDDK: more reliable transfers of full disks.

---

tests/operator_test.go

Adding ids for recent tests + an id that was missed in bulk
Fixes #
```release-note
NONE
```

Add test ids to strict reconciliation tests

---

pkg/importer/http-datasource.go
pkg/importer/http-datasource_test.go
pkg/importer/s3-datasource.go
pkg/importer/s3-datasource_test.go
pkg/importer/upload-datasource_test.go

I left out one comment in the unit test:
"should call Convert after Process phase"
Wasn't sure what other name to use for this unit test.
Going ahead with the rest of the changes since they're a net improvement.
```release-note
NONE
```

Text-only changes missed in removing the Process phase (#1446)

---

doc/smart-clone.md

```release-note
Document smartclone disable feature
```

Document smartclone disable feature in markdown

---

tests/utils/pod.go

Previously, if Delete was successful, err was nil,
so we didn't wait for the pod to not be found.
This is an alternative way of fixing the problem pointed out in #1573.
```release-note
Make functional tests more resilient.
```

Make DeletePodByName always wait for the pod to stop existing.

---

tests/BUILD.bazel
tests/datavolume_test.go

We sometimes have failures if we look for the pods before they are created (or maybe after they have disappeared). Retry in the case the pods don't exist yet.
Fixes #
```release-note
NONE
```

Retry finding the pods for looking up the annotations.

---

pkg/importer/transport.go
tests/BUILD.bazel

Technical debt. 
Fixes #
```release-note
NONE
```

Replaced file copying code with an existing utility function.

---

pkg/feature-gates/feature-gates_suite_test.go

Adds missing feature-gates_suite_test. Now tests for featuregates can actually be run. 
Fixes #
```release-note
NONE
```

Enable tests for featuregates

---

doc/datavolumes.md

Signed-off-by: LIYUNFAN <leeyunfans@gmail.com>
The url of `datavolume-annotations.md` is incorrect.
Fixes #
```release-note
NONE
```

doc: update url in doc/datavolumes.md.

---

doc/datavolumes.md

text corrections and readability improvements

---

pkg/controller/upload-controller.go

rename importController to uploadController in the upload-controller.go file
Fixes #
```release-note
NONE
```

rename importController to uploadController in the upload-controller.go file

---

tests/upload_test.go

A silly mistake made the test to verify all upload paths not work as
designed.
Fixes #
```release-note
NONE
```

Preallocation test did not run all scenarios

---

doc/scratch-space.md

Update scratch-space doc to reflect the new behavior introduced by nbdkit curl
Fixes #
```release-note
None
```

doc: update scratch-space

---

tests/operator_test.go

More robust retry handling because we may have read date between updates (one annotation updated and not the other)
Fixes #1596 
```release-note
NONE
```

Flaky cert test fix

---

tests/datavolume_test.go

We now expect it to pass (after #1466 was merged).
```release-note
NONE
```

Revert skipping test 2555 on OpenShift.

---

pkg/controller/util.go

Fixes #
```release-note
NONE
```

Fixed typo in annotation name

---

tests/smartclone_test.go

Fixes rare flakiness in the smart clone tests.
fyi @brybacki 
```release-note
NONE
```

Check for DV success before we verify the contents is right.

---

hack/build/config.sh
hack/build/docker/builder/Dockerfile

Adds gosec to builder image.
Fixes #
```release-note
NONE
```

Adding Gosec builder docker image

---

doc/releases.md

Fixes #
```release-note
NONE
```

Improved instructions about creating a new release.

---

pkg/operator/resources/cluster/cdiconfig.go
pkg/operator/resources/cluster/datavolume.go
pkg/operator/resources/operator/operator.go

Dedup top code duplications noted by sonarcloud.
[Overall Duplications](https://sonarcloud.io/component_measures?id=kubevirt_containerized-data-importer&metric=duplicated_lines_density&view=list) before this PR :
Density 18.9%
Duplicated Lines 6,529
Duplicated Blocks 113
Duplicated Files 27
```release-note
NONE
```

Deduplicate resource definition code

---

manifests/templates/imageio.yaml.in

The container was being pulled from docker hub and running into rate limit issues. Also was using latest instead of a tagged version so it would pull constantly. This PR fixes both issues.
Fixes #
```release-note
NONE
```

Use quay.io for imageio test image

---

tests/cdiconfig_test.go

At least test_id:3962 seems to assume that the scratch space storage
class isn't set, so make sure this is true using BeforeEach.
Restore the previous scratch space storage class in AfterEach
rather than trampling it in each run.
The trampling of scratch space storage class in AfterEach is why the test seems to pass
most of the time. If test_id:3962 is the first one to run in this DescribeTable, and scratch
space storage class is set, it'll fail.
```release-note
NONE
```

Correct the behaviour of scratch space SC tests if env uses this tunable

---

hack/build/bazel-push-images.sh

Tag was set to blank, and that was causing a problem during releases.
Fixes #
```release-note
NONE
```

Set tag properly when doing releases in PROW

---

pkg/image/qemu.go
pkg/image/qemu_test.go

Code refactored to be more idiomatic to Golang. Added unit tests for addPreallocation.
Fixes #
```release-note
NONE
```

Refactored addPreallocation.

---

tests/transfer_test.go

Signed-off-by: Kevin Alon Goldblatt <kgoldbla@redhat.com>
**What this PR does / why we need it**: Added Polarion IDs to tier1 test cases
Fixes #
**Release note**: 
```release-note
NONE
```

Added Polarion IDs to tier1 test cases

---

pkg/importer/s3-datasource.go
tests/alpha_test.go
tests/cdiconfig_test.go
tests/cloner_test.go

Fix ineffassign issues.
```release-note
NONE
```

Fix ineffassign issues

---

pkg/operator/resources/cluster/cdiconfig.go
pkg/operator/resources/operator/operator.go

Dedup top code duplications noted by sonarcloud.
```release-note
NONE
```

Deduplicate resource definition in CDIConfig and Operator

---

doc/waitforfirstconsumer-storage-handling.md

Update wffc documentation to refer to CDI spec.config

---

doc/releases.md

We recently changed from using Travis CI to PROW for our releases. This PR updates the documentation on how to make a release.
Fixes #
```release-note
NONE
```

Update the release documentation to the new PROW CI.

---

pkg/operator/resources/operator/operator.go

Dedup top code duplications noted by sonarcloud.
```release-note
NONE
```

Deduplicate resource definition in Operator

---

cluster-sync/k8s-1.19/provider.sh
cluster-sync/k8s-1.20/provider.sh

We should make sure we are testing the latest kubevirtci lanes available for us.
After this PR is merged, https://github.com/kubevirt/project-infra/pull/867 can be merged.
```release-note
NONE
```

Copy k8s-1.18 logic to k8s-1.20

---

cmd/cdi-importer/importer.go
pkg/importer/imageio-datasource.go
pkg/importer/imageio-datasource_test.go

This pull request unlocks ImageIO source disks when the importer returns an error. The importer was not finalizing the transfer through the ImageIO API because the finalize code lives in the Close method, which previously relied on a "defer" that was skipped by os.Exit. In the linked bug, the transfer was successful, but the resize failed, triggering an os.Exit that skipped the deferred Close and therefore the finalize.
This pull request adds an explicit call to Close just before the relevant calls to os.Exit (there are only a few). In the interest of further safety, this pull request also cancels a transfer if the finalize fails.
Fixes [BZ#1945522](https://bugzilla.redhat.com/show_bug.cgi?id=1945522)
**Release …

Unlock ImageIO disks after importer failure.

---

cmd/cdi-cloner/clone-source.go
cmd/cdi-importer/importer.go
cmd/cdi-uploadserver/BUILD.bazel
cmd/cdi-uploadserver/uploadserver.go
pkg/common/common.go
pkg/controller/clone-controller.go
pkg/controller/import-controller.go
pkg/controller/upload-controller.go
pkg/controller/util.go
pkg/controller/util_test.go
tests/cloner_test.go
tests/utils/pvc.go

Fixes #
```release-note
Added support for Cloning DataVolumes.
```

Preallocate cloning DV

---

WORKSPACE

sha changed for the base image we use.
Fixes #
```release-note
NONE
```

Fedora 33 hash changed in quay.

---

tests/datavolume_test.go

Fixes #
```release-note
NONE
```

Fix test being focused.

---

tests/datavolume_test.go

Update testid
Fixes #
```release-note
NONE
```

Update id for pvc size calculation tests

---

doc/waitforfirstconsumer-storage-handling.md

Fix typos, rephrase a little bit.
Hopefully an improvement.
```release-note
NONE
```

Touch-ups to WFFC documentation

---

pkg/controller/datavolume-controller.go

I had a few nitpicks on namespace transfer code, this fixes them.
Fixes #
```release-note
NONE
```

Namespace transfer fixing nitpicks

---

tests/import_proxy_test.go

Add a functional test demonstrating we are indeed using the proxy for registry imports as well.
Fixes #
```release-note
NONE
```

Add functional test showing we proxy registry imports.

---

tests/datavolume_test.go

Updated test id.
Fixes #
```release-note
NONE
```

Test: updated test id for fsOverhead resize tests

---

doc/datavolumes.md

Signed-off-by: Jeesmon Jacob <jjacob@us.ibm.com>
Fixes #
Fix URL in the doc
```release-note
NONE
```

Fix Secret URL

---

hack/build/config.sh

builder generated from this:  https://github.com/kubevirt/containerized-data-importer/pull/1815
Fixes #
```release-note
NONE
```

update builder image

---

pkg/controller/util.go

```release-note
Remove noisy log message from cdi deployment.
```

Reduce the amount of noise from the filesystem overhead feature

---

WORKSPACE

Fixes #
```release-note
NONE
```

update fedora sha

---

tests/datavolume_test.go

In the current environment this test is unstable. This is a chaos
test where evil user or script tries to delete scratch space in
the moment where it is created but the import pod has not started yet.
The test brings more problems than real value so it is being removed.
Fix the flaky test by removing it. 
Fixes #
Test originally created to find and fix a bug: https://github.com/kubevirt/containerized-data-importer/pull/1424
```release-note
NONE
```

Remove the test - delete scratch space

---

pkg/clone/BUILD.bazel
pkg/clone/auth.go
tests/BUILD.bazel

This change really has no practical effect but was kept at alpha because that's where kubevirt's at
Fixes #
```release-note
NONE
```

update clone auth api version

---

tests/BUILD.bazel
tests/datavolume_test.go

We had to do a bunch of retries and other things to try and catch completed
pods which was especially hard with a clone of a small disk. Since we can
now retrain completed pods, the tests were updated to do that.
Fixes #
```release-note
NONE
```

Fix annotation tests to keep pods.

---

doc/storageprofile.md
pkg/apis/core/v1alpha1/types.go
pkg/apis/core/v1beta1/openapi_generated.go
pkg/apis/core/v1beta1/types.go
pkg/apis/core/v1beta1/types_swagger_generated.go
pkg/apis/core/v1beta1/zz_generated.deepcopy.go
pkg/controller/datavolume-controller.go
pkg/controller/datavolume-controller_test.go
pkg/controller/util_test.go
pkg/operator/resources/cluster/storageprofile.go

Adds a new way to select preferred CloneStrategy by extending the StorageProfile with `CloneStrategy` field. 
Fixes #
First commit is the cleanup. Some methods where extracted to make main Reconcile loop easier to read. 
```release-note
Add CloneStrategy selection to StorageProfile. 
```

Preferred Clone strategy selection

---

doc/clone-datavolume.md
doc/namespace-transfer.md
doc/smart-clone.md

Let's at least mention namespace transfer
Fixes #
```release-note
NONE
```

namespace transfer doc

---

pkg/controller/datavolume-controller_test.go

Fixes the failing unit test on the release-v1.34 branch.
Fixes: none, just a failing unit test
```release-note
NONE
```

[release-v1.34] Fix failing unit test.

---

doc/preallocation.md

This PR documents some details about preallocation.
```release-note
NONE
```

Added some details about preallocation

---

doc/preallocation.md

Tiny wording change to remove reference to QCOW format.

---

pkg/controller/datavolume-controller.go
pkg/operator/resources/cluster/controller.go
tests/csiclone_test.go

Fixes #
```release-note
NONE
```

Clone strategy csi verify

---

tests/cloner_test.go

Adds a new test case to verify correct behavior when the target pvc name is taken.
PVC name conflict is already verified once by validation hook on dv creation. This tests only covers a situation when the target pvc name is taken between the dv creation and the actual clone process starting.  
Fixes #
```release-note
NONE
```

Test clone with target pvc name conflict

---

tests/csiclone_test.go

Update the RFE ID used for CSI tests
Fixes #
```release-note
NONE
```

Update the RFE ID used for CSI tests

---

tests/utils/pod.go

We're seeing this flake:
```bash
19:10:42  [WARN] error executing command ["/bin/sh" "-c" "head -c 18874368 /pvc 1> null && head -c 18874368 /pvc | md5sum"], error: unable to upgrade connection: container not found ("runner")
```
Which make sense because we only wait for the verifier to reach phase=Ready,
not for the stronger condition Ready=True which indicates something is 100% operational.
Fixes #
```release-note
NONE
```

Wait for pod's Ready=True condition rather than phase=Ready

---

CONTRIBUTING.md
README.md
doc/basic_pv_pvc_dv.md
doc/image-from-registry.md
hack/README.md
pkg/importer/registry-datasource.go
pkg/operator/resources/operator/operator.go
pkg/util/openapi/openapi.go
pkg/version/base.go
pkg/version/types.go
pkg/version/verflag/verflag.go
tests/operator_test.go
tools/openapi-spec-generator/definitions.go
tools/util/marshaller.go

I mostly followed links that are already redirected, but the purpose was to use more inclusive language.
```release-note
NONE
```

Update external links.

---

Makefile
README.md
cmd/cdi-apiserver/apiserver.go
cmd/cdi-controller/controller.go
cmd/cdi-uploadproxy/uploadproxy.go
hack/README.md
hack/build/release-description.sh
hack/build/run-functional-tests.sh
hack/ci/language.sh
hack/gen-swagger-doc/deploy.sh
pkg/version/base.go
pkg/version/version.go
tests/cdiconfig_test.go
tests/framework/framework.go
tests/tests_suite_test.go

 Use inclusive language, add check for inclusive language

---

hack/build/config.sh

Use image changes here:  https://github.com/kubevirt/containerized-data-importer/pull/1944
Fixes #
```release-note
NONE
```

update builder image to 0.13

---

WORKSPACE
hack/build/bazel-build-builder.sh
hack/build/config.sh
hack/build/docker/builder/Dockerfile

Needed to be able to backport test fixes to 1.38
Fixes #
```release-note
NONE
```

[release-v1.38] Manual cherrypick 1944 1965 1967

---

pkg/image/qemu.go
pkg/image/qemu_test.go
tests/import_test.go

Fixes #
```release-note
NONE
```

Revert #2000 because it was merged too quickly

---

tests/datavolume_test.go

As we are aware of the issue and are working on it,
we can disable the test case.
Fixes #
```release-note
NONE
```

Disable [test_id:3937]succeed creating warm import dv

---

pkg/controller/datavolume-conditions.go
pkg/controller/datavolume-conditions_test.go
pkg/controller/datavolume-controller.go
pkg/controller/import-controller.go
pkg/controller/smart-clone-controller.go
pkg/controller/upload-controller.go
pkg/controller/util.go
tests/cloner_test.go
tests/csiclone_test.go
tests/datavolume_test.go
tests/framework/framework.go
tests/import_test.go
tests/smartclone_test.go
tests/utils.go

Fixes #
```release-note
NONE
```

Emit event and update dv conditions when pvc fails to create due to quota

---

tests/dataimportcron_test.go

Fix test nil checks
Fixes #
```release-note
NONE
```

Fix DataImportCron test checks

---

cluster-sync/ephemeral_provider.sh

With hpp operator at v0.11.0 it now requires cert-manager, and webhook. This PR modifies the hpp setup to include setting up those items.
Fixes #
```release-note
NONE
```

Fix hpp setup for tests.

---

pkg/controller/config-controller.go

Surprised the current code works given lack of RBAC support.
Fixes #
```release-note
NONE
```

used uncached client to get cluster proxy configmap

---

tests/csiclone_test.go
tests/datavolume_test.go

Add tests numbers to dv quota tests

---

.vscode/settings.json
go.mod
go.sum
vendor/github.com/opencontainers/runc/libcontainer/user/user.go
vendor/modules.txt

Fixes alert for `github.com/opencontainers/runc` but cannot update `github.com/opencontainers/image-spec` yet because it will break `github.com/containers/image`
Fixes #
```release-note
NONE
```

make dependaabot happier (but not completely happy)

---

pkg/controller/config-controller.go

Backport of #2055 
Fixes #
```release-note
NONE
```

[release-v1.38] used uncached client to get cluster proxy configmap (#2055)

---

pkg/controller/clone-controller.go
pkg/controller/clone-controller_test.go

Put certs in secrets instead of directly into pod specs
Fixes #
```release-note
NONE
```

clone source pod certs in secrets

---

tests/operator_test.go

Add test ids for Alert tests
Fixes #
```release-note
None
```

Add test ids for Alert tests

---

pkg/importer/data-processor.go
pkg/importer/data-processor_test.go

**What this PR does / why we need it**: 
Allows user to extend data processor to handle some specific image format or data source.
Fixes #2094
```release-note
NONE
```

Refactor the data-processor.go to allow customization

---

pkg/controller/dataimportcron-controller.go
pkg/controller/dataimportcron-controller_test.go
pkg/controller/datasource-controller.go
pkg/controller/util.go

Fixes #
```release-note
Add DataImportCron ImageStream tag support
```

Add DataImportCron ImageStream tag support

---

cmd/cdi-importer/importer.go
pkg/apiserver/webhooks/datavolume-validate.go
pkg/controller/datavolume-controller.go
pkg/controller/upload-controller.go
pkg/controller/util.go
pkg/importer/data-processor.go
pkg/importer/data-processor_test.go
pkg/util/util.go
pkg/util/util_test.go
tests/cloner_test.go
tests/framework/pvc.go
tests/utils/datavolume.go

Manual cherry-pick of https://github.com/kubevirt/containerized-data-importer/pull/2096
Needed to update one line. (last commit)
Fixes #
```release-note
NONE
```

[release-v1.43] BugId: 2038679 - Clone with volume mode file system using Storage API fails

---

cmd/cdi-importer/importer.go
pkg/apiserver/webhooks/datavolume-validate.go
pkg/controller/datavolume-controller.go
pkg/controller/upload-controller.go
pkg/controller/util.go
pkg/importer/data-processor.go
pkg/importer/data-processor_test.go
pkg/util/util.go
pkg/util/util_test.go
tests/cloner_test.go
tests/framework/pvc.go
tests/utils/datavolume.go

Manual cherry-pick of https://github.com/kubevirt/containerized-data-importer/pull/2096
Fixes #
```release-note
NONE
```

[release-v1.38] BugId: 2038679 - Clone with volume mode file system using Storage API fails

---

pkg/controller/import-controller.go

* Fix failing imageio test
Always enable scratch space for imageio imports.
* Only always enable scratch space with warm migration imports.
Backport of #2148
Fixes #
```release-note
NONE
```

[release-v1.34] Fix failing imageio test (#2148)

---

cmd/cdi-importer/importer.go

During the first attempt to simplify importer (PR #1987) I had to drop one commit
because of some hard to find errors. This is a second attempt, and I have found
that there is an implicit communication through termination message file.
Importer writes the file and data processor appends some data there
after it is closed. This might need some future improvements.
Fixes #
WDYT? Is it better?
```release-note
NONE
```

Simplify importer code, cleanup and extract function

---

pkg/controller/datavolume-controller.go

Sometimes we skip SnapshotForSmartCloneInProgress and directly go to
Succeeded.
This happens when the `r.updateDataVolume(dataVolumeCopy)` call fails
(for example, with `the object has been modified; please apply your changes to the latest version and try again`).
Fixes #2121 
```release-note
NONE
```

Fix SnapshotForSmartCloneInProgress sometimes not occuring

---

tests/operator_test.go

This PR adds new tests cases for alert definitions. We expect to see "runbook_url" annotations in alerts and those urls must be accessible.
Signed-off-by: assafad <aadmi@redhat.com>
```release-note
None
```

Add test cases for runbook URLs

---

tests/datavolume_test.go

Signed-off-by: Kevin Alon Goldblatt <kgoldbla@redhat.com>
Fixes #
```release-note
```

Added Polarion ID's to 2 test cases

---

tests/upload_test.go

Functional test to confirm that certs are referenced in secrets
Fixes #
```release-note
NONE
```

check uploadserver using certs in secrets

---

pkg/controller/dataimportcron-controller.go
pkg/controller/datasource-controller.go

Fixes #
```release-note
NONE
```

Log UID of DataImportCron, DataSource & DataVolume

---

pkg/controller/datavolume-controller.go
tests/datavolume_test.go

Manual backport of #2196
Fixes #
```release-note
NONE
```

[release-v1.43] Reconcile DVs waiting for default SC

---

pkg/operator/controller/prometheus.go

Manual backport of #2149 
Fixes #
```release-note
NONE
```

[release-v1.43] Manual backport of 2149 - alert summary

---

cmd/cdi-importer/importer.go

In case of timeout the importer container cmd exits with error and
termination message to be used by DV Running condition.
This is specifically for RegistryPullNode imports, used mostly in the
DataImportCron context.
PR #2044 was mistakenly reverted by PR #2141, so it's also fixed here.
Fixes #
```release-note
NONE
```

Add timeout to importer cmd wait for server ready

---

automation/ceph.sh
automation/destructive.sh
automation/istio.sh
automation/latest-hpp.sh
automation/nfs.sh
automation/previous-hpp.sh
automation/upgrade.sh

Instead of setting various variables in project-infra set them in scripts inside this repo instead. This allows us to upgrade
k8s versions without having to modify the project infra lanes.
Fixes #
Needs https://github.com/kubevirt/project-infra/pull/2002 merged before we can test if this work.
```release-note
NONE
```

Add lane scripts in repo

---

tests/dataimportcron_test.go

When updating one can get "Operation cannot be fulfilled on NAME the object has been modified;
please apply your changes to the latest version and try again". Doing a get and update
in loop makes it robust.
Fixes #
Tesk sometimes fails on update -> https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/2200/pull-containerized-data-importer-e2e-k8s-1.22-hpp/1506737762038976512
```release-note
NONE
```

Test flakiness - DataImportCron - retry update at least once

---

tests/datavolume_test.go

Two imageio tests fail pretty frequently blocking other development.
Mark as Pending while the problem is under investigation.
Fixes #
```release-note
NONE
```

Quarantine flaky tests

---

doc/efficient-cloning.md
doc/storageprofile.md

Describes the possibility to configure preferred clone method on storageClass by using annotation.
The original change that introduced it https://github.com/kubevirt/containerized-data-importer/pull/2004
As shown here: https://github.com/kubevirt/containerized-data-importer/issues/2219 the annotation is not known and is helpful.
Fixes #
```release-note
NONE
```

Describe clone-strategy annotation

---

hack/build/docker/builder/Dockerfile

Fixes #
```release-note
BugFix: Updated builder to use golang 1.17.10
```

Update go version to 1.17.10 in builder

---

repo.yaml

Forgotten in #1983, needed to run `make rpm-deps`
```release-note
NONE
```

Add missing file repo.yaml

---

pkg/controller/dataimportcron-controller.go
pkg/controller/dataimportcron-controller_test.go
tools/cdi-source-update-poller/main.go

Manual backport of #2294
Fixes #
```release-note
NONE
```

[release-v1.43] Get rid of unnecessary DIC reconcile updates

---

pkg/controller/dataimportcron-controller.go
pkg/controller/dataimportcron-controller_test.go
tools/cdi-source-update-poller/main.go

Manual backport of #2294
Fixes #
```release-note
NONE
```

[release-v1.49] Get rid of unnecessary DIC reconcile updates

---

pkg/controller/dataimportcron-controller.go
pkg/controller/dataimportcron-controller_test.go

Fixes #
```release-note
NONE
```

Reconcile DIC only if DataSource is not managed by another DIC

---

tests/cloner_test.go

**What this PR does / why we need it**: This PR updates the functional tests included in https://github.com/kubevirt/containerized-data-importer/pull/2222 with proper IDs, following the test plan in Polarion.
Fixes #
```release-note
NONE
```

Update size-detection functional tests with IDs

---

manifests/templates/imageio.yaml.in

Sometimes we see that ticket is not there (thx awels), we might want to
try a few times before giving up.
Fixes #
```release-note
NONE
```

[release-v1.43] Manual backport of 'Retry adding ticket on imageio container startup (#2223)'

---

pkg/apiserver/webhooks/datavolume-validate.go
pkg/controller/clone-controller.go
pkg/controller/clone-controller_test.go
pkg/controller/datavolume-controller.go
pkg/controller/import-controller.go
pkg/controller/upload-controller.go
pkg/controller/util.go
tests/cloner_test.go
tests/utils/datavolume.go

Fixes #
```release-note
BUGFIX: Correct validation of size when cloning from fs to block
```

Manual cherry pick 2299 to release v1.49

---

pkg/apiserver/webhooks/datavolume-mutate.go
pkg/apiserver/webhooks/datavolume-mutate_test.go
pkg/controller/datavolume-controller.go
pkg/controller/smart-clone-controller.go
pkg/controller/util.go
tests/cloner_test.go
tests/datavolume_test.go
tests/import_test.go
tests/upload_test.go
tests/utils/datavolume.go

Fixes #
```release-note
NONE
```

Add GC func tests; mutate DV GC annotation only on create

---

hack/build/bazel-docker.sh

Running our builder on fedora 34 will fail due to a new syscall in centos
that is not support by the security profile in fedora 34. Adding the unconfined
security profile to the builder fixes this. But we don't want to enable this by
default. So check for environment variable before setting it.
`export DISABLE_SECCOMP="--security-opt seccomp=unconfined"`
Fixes #
```release-note
NONE
```

Allow builder with unconfined security profile if env variable is set

---

pkg/apiserver/webhooks/datavolume-validate.go
pkg/controller/clone-controller.go
pkg/controller/clone-controller_test.go
pkg/controller/datavolume-controller.go
pkg/controller/upload-controller.go
pkg/controller/util.go
tests/cloner_test.go
tests/utils/datavolume.go

Fixes #
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2079781
```release-note
BUGFIX: Correct validation of size when cloning from fs to block
```

Manual cherry pick 2299 to release Release v1.43

---

automation/ceph-gc.sh

Fixes #
```release-note
NONE
```

Add Ceph DV GC lane automation script

---

WORKSPACE
go.mod
hack/build/config.sh
hack/update-codegen.sh
pkg/operator/resources/crds_generated.go
staging/src/kubevirt.io/containerized-data-importer-api/go.mod

Fixes #
```release-note
Update golang version to 1.18.3
```

Update golang version to 1.18.3

---

pkg/storagecapabilities/storagecapabilities.go

Based on https://dell.github.io/csm-docs/docs/csidriver/#csi-driver-capabilities.
Fixes #
```release-note
NONE
```

Add dell unity CSI to known provisioners

---

go.mod
pkg/controller/BUILD.bazel
pkg/controller/clone-controller.go
pkg/controller/dataimportcron-controller.go
pkg/controller/datavolume-controller.go
pkg/controller/import-controller.go
pkg/controller/upload-controller.go
pkg/importer/registry-datasource.go
pkg/util/util.go

Ensure the CDI pods comply with the restricted security context.
Fixes #
RHBZ [2088464](https://bugzilla.redhat.com/show_bug.cgi?id=2088464)
```release-note
BugFix: drop all capabilities and set priviledgeEscalation: false on pods
```

Comply with restricted security context

---

tests/framework/framework.go

We were returning a boolean with no indication on what was wrong instead return the error and it should now indicate the problem in a failure.
Fixes #
```release-note
NONE
```

Cleanup error detection and message on cdiconfig update.

---

go.sum
pkg/operator/resources/crds_generated.go
vendor/modules.txt

Fixes #
```release-note
NONE
```

Run make deps and generate

---

Makefile
hack/build/bazel-build-metricsdocs.sh
hack/diff-csv.sh

Add PR sanity GitHub Action check to ensure developers run the metrics doc generation after every metric change.
Fixes #
```release-note
NONE
```

Verify metrics docs are updated

---

Makefile
pkg/storagecapabilities/storagecapabilities.go

```yaml
parameters:
backendType: ontap-nas-economy
```
Was spotted in the wild.
Fixes #
```release-note
NONE
```

Loosen Trident backendType check

---

tests/apiserver_test.go
tests/upload_test.go

Added a step to the crypto policy tests that ensures we can talk to the server
when TLS crypto config allows it, instead of just failing when it doesn't.
Fixes #
```release-note
NONE
```

Add test IDs/minor steps to crypto policy tests

---

pkg/storagecapabilities/storagecapabilities.go

What this PR does / why we need it:
This PR adds the provisioner pxd.portworx.com and adds the volumeMode block to provisioners that use the CSI defined by
https://github.com/libopenstorage/openstorage.
Special notes for your reviewer:
```release-note
Added pxd.portworx.com provisioner and volume mode block to openstorage and portworx provisionners
```

update portworx storage capabilities

---

tests/cloner_test.go

The test is a negative test that creates the sourcepvc, create a pod to keep it busy, then creates the clone dv which can't do the clone yet since the source is busy. then it creates the targetpvc and expects eventually that the clone will fail since there already exists a pvc with the target name.
now the test after creating the target pvc checks for the clone type annotation on the dv. if the target pvc was created fast enough the dv will get to the check of the target pvc name (and return error since it exists) before getting to the reconcileClone function which there you update the clone type annotation. Thats why if the tests wants to check for the event of "source busy" which requires the clone type annotation on the dv it should be done before creating the target pvc.
**What this …

test fix: Move check of clone type before create target pvc

---

doc/exposing-upload-proxy.md

PR updates documentation to provide correct annotations to make cdi-uploadproxy working with NGINX Ingress Controller >=v1.0
Fixes #
```release-note
NONE
```

Fix ingress annotations

---

tests/api_validation_test.go
tests/cloner_test.go
tests/datavolume_test.go
tests/framework/pvc.go
tests/import_test.go
tests/leaderelection_test.go
tests/transport_test.go
tests/upload_test.go

Simplify test PVC creation & force-binding code

---

doc/scratch-space.md
pkg/image/filefmt.go
pkg/image/nbdkit.go
pkg/importer/format-readers.go
pkg/importer/http-datasource.go
pkg/importer/http-datasource_test.go
pkg/importer/registry-datasource.go
tests/import_proxy_test.go

Manual cherry-pick of #2351
Fixes #
```release-note
NONE
```

[release-v1.49] Cherry pick 2351 take2

---

tests/cloner_test.go
tests/datavolume_test.go

This PR cleanups tests for handling populated PVCs. The clone and import tests are already there, just needed some improvements. The upload is being added.
Fixes #
```release-note
NONE
```

Test handling of populatedFor annotation on PVC

---

pkg/importer/vddk-datasource_amd64.go
pkg/importer/vddk-datasource_test.go

For VDDK data sources, there are situations where the target disk name in the data volume spec cannot be found on the current VM hardware configuration or in its snapshot tree. In these cases there's a good chance the disk name is hiding in the backing file information of the parent disk of the root snapshot, so this pull request adds one additional check to handle this case instead of failing immediately.
Partially fixes RHBZ#2086097
```release-note
VDDK: Add a check for the target disk in the parent backing file of the root snapshot
```

VDDK: Add a check for the target disk in the parent backing file of the root snapshot

---

pkg/controller/datavolume-controller.go
pkg/controller/smart-clone-controller.go
pkg/controller/smart-clone-controller_test.go
tests/cloner_test.go

Auto cherry pick got a conflict so now there's this
Fixes #
```release-note
NONE
```

[release-v1.43] fix issue #2323: Cross namespace smart clone not cleaning up

---

pkg/common/common.go
pkg/controller/dataimportcron-controller.go
pkg/operator/controller/callbacks.go
pkg/operator/controller/scc.go

Add cronjob-sa to SCC so we can run inside Open Shift without issues.
Fixes #
```release-note
NONE
```

Add cron-job sa to scc

---

pkg/storagecapabilities/storagecapabilities.go

Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=2143268
```release-note
BugFix: TopoLVM profile missing defaults
```

Add topolvm to known provisioners

---

cluster-sync/sync.sh
manifests/templates/upgrade-testing-artifacts-no-gc.yaml.in
manifests/templates/upgrade-testing-artifacts.yaml.in

Basically #2434 but don't change UPGRADE_FROM versions
Fixes #
```release-note
NONE
```

[release-v1.43] manual cherry pick #2434

---

.gitignore
.vscode/settings.json

Signedoff-by: Michael Henriksen <mhenriks@redhat.com>
These should have never been added.  My bad.
Fixes #
```release-note
NONE
```

remove vscode settings

---

manifests/templates/cdi-testing-scc.yaml.in

The SCC was not applying properly due to some missing required fields. This PR adds those fields.
Fixes #
```release-note
NONE
```

Update cdi-testing-sa SCC to work in newer Open Shift

---

tests/cloner_test.go

Fixes #
```release-note
NONE
```

Correct skip message on CSI Clone tests

---

pkg/controller/common/BUILD.bazel
pkg/controller/common/controller_suite_test.go
pkg/controller/datavolume/BUILD.bazel
pkg/controller/datavolume/controller_suite_test.go

Otherwise we skip the tests in these
Fixes #
```release-note
NONE
```

Create unit test suite for new folders following refactor

---

pkg/storagecapabilities/storagecapabilities.go

Signed-off-by: Jenia Peimer <jpeimer@redhat.com>
Fixes # https://bugzilla.redhat.com/show_bug.cgi?id=2158521
```release-note
BugFix: storage profile missing defaults for LVMS "topolvm.io" provisioner
```

Add topolvm.io to known provisioners

---

cluster-sync/external/README.md

Fixes #
```release-note
NONE
```

Add note about public repos when developing on external provider

---

.fossa.yml
Makefile
hack/fossa.sh

This PR adds the branch name to fossa analysis. Also it reduces and corrects the .fossa.yml configuration file according to latest version described here: https://github.com/fossas/fossa-cli/blob/v3.6.11/docs/references/files/fossa-yml.md
Note: I guess there's been some kind of backwards compatibility.
Fixes #
See https://github.com/kubevirt/kubevirt/pull/9066 as a base for these changes
```release-note
NONE
```

Add branch name to fossa analysis

---

doc/external-dv-population.md

This commit adds documentation for the external-population support in DataVolumes.
**Release note:**
```release-note
NONE
```

Add external-population docs

---

cmd/cdi-controller/controller.go
tests/operator_test.go

Flakiness seems to be introduced by #2546 
Fixes #
```release-note
NONE
```

Fix StorageProfile incomplete metric test flakiness

---

pkg/controller/datavolume-controller.go
tests/cloner_test.go

Manual cherry-pick of https://github.com/kubevirt/containerized-data-importer/pull/2520
Fixes # https://bugzilla.redhat.com/show_bug.cgi?id=2165594
```release-note
[bug-fix] Fix bug in size-detection mechanism when cloning across namespaces
```

[release-v1.55] Fix bug in size-detection mechanism when cloning between namespaces

---

tests/BUILD.bazel
tests/operator_test.go

Fixes #
```release-note
NONE
```

Add functional test for unsupported provisioners

---

tests/dataimportcron_test.go

The short timeout (10sec) may cause flakiness.
Fixes #
```release-note
NONE
```

Fix DataImportCron PVC GC test timeout

---

doc/exposing-upload-proxy.md

Fix the following errors:
```shell
error: error validating "STDIN": error validating data: ValidationError(Ingress.spec.rules[0].http.paths[0]): missing required field "pathType" in io.k8s.api.networking.v1.HTTPIngressPath; if you choose to ignore these errors, turn validation off with --validate=false
```
Fixes #
```release-note
None
```

docs: fix exposing upload proxy ingress

---

tests/operator_test.go

Do not assume CDI CR name is cdi.
Fixes bz #2145146 (fixes the func test)
```release-note
NONE
```

[release-v1.55] Fix cdi_cr_ready test CDI CR name

---

tests/operator_test.go

Tests that revolve around the storage profile metric tend to flake,
try to mitigate by ensuring we are always reverted back to the original metric value using Before/AfterEach.
Fixes #
```release-note
NONE
```

Fix flaky destructive metric tests

---

pkg/image/qemu_test.go

Fixes #
```release-note
NONE
```

Use real tmpdir path in qemu blank image unit tests

---

tests/datasource_test.go
tests/utils/datavolume.go

`verifyConditions()` also checks now that all the test conditions exist
Fixes #
```release-note
NONE
```

Fix DV verifyConditions test

---

tests/datasource_test.go
tests/utils/datavolume.go

Manual backport of #2601
verifyConditions checks if all the conditions exist and match testConditions
Fixes #
```release-note
NONE
```

[release-v1.55] Fix DV verifyConditions test

---

Makefile
hack/build/bootstrap-ginkgo.sh
pkg/token/BUILD.bazel
pkg/token/token_suite_test.go
pkg/token/token_test.go

This will help us avoid something like https://github.com/kubevirt/containerized-data-importer/pull/2518
Fixes #
```release-note
NONE
```

Verify that ginkgo suite is bootstrapped

---

tests/framework/pvc.go
tests/operator_test.go

Be a bit more eager in testing that a DV from very old version survives unmodified - get a completed DV and make additional modifications, and check that the additional modifications survive.
Fix a small issue that became apparent in scaleDeployment function.
```release-note
NONE
```

Adjust alpha deprecation tests

---

automation/test.sh
hack/common-funcs.sh

Fixes #
```release-note
NONE
```

Avoid CI downgrading from latest release to cherrypick PR

---

tests/cloner_test.go
tests/datasource_test.go

Add ref ids and test ids for clone and datasource tests
Fixes #
```release-note
None
```

Add ref ids and test ids for clone and datasource tests

---

doc/maintainer.md

Trying to clarify the requirements and expectations of maintainers and approvers.
Fixes #
```release-note
NONE
```

Add document explaining requirements for mainters/approvers

---

tests/cloner_test.go
tests/csiclone_test.go
tests/datavolume_test.go
tests/framework/pvc.go
tests/import_test.go
tests/smartclone_test.go

Manual backport of #2633 
Fixes #
```release-note
NONE
```

[release-v1.55] Manual backport of follow up for WFFC test suite adjustments

---

pkg/storagecapabilities/storagecapabilities.go

Capabilities taken from https://docs.openshift.com/container-platform/4.12/storage/container_storage_interface/persistent-storage-csi-ovirt.html
Fixes #
```release-note
Add ovirt csi to known provisioners
```

Add ovirt csi to known provisioners

---

tests/utils/datavolume.go

Useful when debugging DataVolumes that are cleaned up in an AfterEach
Fixes #
```release-note
NONE
```

Report last DV phase in tests when garbage collection fails

---

automation/test.sh
hack/build/bazel-docker.sh
hack/common-funcs.sh

Manual combined backport of #2624 and #2448 and #2430 this should fix the build and allows us to backport issues to 1.54
Fixes #
```release-note
NONE
```

[release-v1.54] Combine several fixes so we can run test builds again

---

pkg/token/token.go

typo
Fixes #
```release-note
NONE
```

fix typo in token payload

---

pkg/controller/clone-controller.go
pkg/controller/clone-controller_test.go

manual cherrypick of #2536
Fixes #
```release-note
Clone source pods should mount block PVCs readonly
```

[release-v1.55] manual cherrypick of #2536

---

cmd/cdi-cloner/clone-source.go
pkg/util/util.go

May be helpful to backport new tar behavior to avaoid EPERM
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=2184386
```release-note
NONE
```

[release-v1.49] backport tar handling from #2410

---

pkg/operator/controller/controller_test.go
pkg/operator/controller/prometheus.go

When `RUNBOOK_URL_TEMPLATE` env variable is set, its value will be used as the runbooks URL template. Otherwise, keep using the default runbook URL template `https://kubevirt.io/monitoring/runbooks/%s`. 
This allows using different runbooks versions, in accordance with the installation.
Jira ticket- https://issues.redhat.com/browse/CNV-14384
```release-note
None
```

Use `RUNBOOK_URL_TEMPLATE` env for the runbooks URL template

---

pkg/controller/datavolume/controller-base.go
pkg/controller/datavolume/external-population-controller.go
pkg/controller/datavolume/external-population-controller_test.go
pkg/controller/datavolume/import-controller.go
pkg/controller/datavolume/import-controller_test.go
pkg/controller/datavolume/pvc-clone-controller.go
pkg/controller/datavolume/pvc-clone-controller_test.go
pkg/controller/datavolume/snapshot-clone-controller.go
pkg/controller/datavolume/snapshot-clone-controller_test.go
pkg/controller/datavolume/upload-controller.go
pkg/controller/datavolume/upload-controller_test.go

The embedded reconcile.Reconciler is not needed anymore
Fixes #
```release-note
NONE
```

Remove embedded reconcile.Reconciler

---

hack/update-codegen.sh

Discoverd this when I was going back/forth testing populator PRs
Fixes #
```release-note
NONE
```

remove old generated crds before creating new ones

---

cmd/cdi-cloner/clone-source.go
pkg/util/util.go

Fixes #
```release-note
NONE
```

[release-v1.54] backport tar handling from #2410

---

tests/external_population_test.go
tests/upload_test.go

Manual backport of https://github.com/kubevirt/containerized-data-importer/pull/2677
Fixes #
```release-note
NONE
```

[release-v1.56] Skip TLS crypto test/ensure anyvolumedatasource test pvc is gone

---

pkg/controller/smart-clone-controller.go
pkg/controller/smart-clone-controller_test.go

Manual backport of #2680
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2203278
```release-note
NONE
```

[release-v1.55] Handle 0 restore size better v155

---

tests/dataimportcron_test.go

Add test ids for dataimportcron tests
Fixes #
```release-note
None
```

Add test ids for dataimportcron tests

---

pkg/controller/BUILD.bazel
pkg/controller/dataimportcron-controller.go
pkg/controller/dataimportcron-controller_test.go
pkg/controller/import-controller_test.go

Manual backport of #2712
Fixes bz #2211186
```release-note
Propagate CDI workload NodePlacement to DataImportCron CronJob and initial Job
```

[release-v1.56] Propagate CDI workload NodePlacement to DIC CronJob and initial Job

---

pkg/controller/BUILD.bazel
pkg/controller/dataimportcron-controller.go
pkg/controller/dataimportcron-controller_test.go
pkg/controller/import-controller_test.go

Manual backport of #2712
Fixes bz #2211189
```release-note
Propagate CDI workload NodePlacement to DataImportCron CronJob and initial Job
```

[release-v1.55] Propagate CDI workload NodePlacement to DIC CronJob and initial Job

---

pkg/controller/clone/common.go
pkg/controller/clone/planner.go
pkg/controller/clone/planner_test.go
pkg/controller/common/BUILD.bazel
pkg/controller/common/util.go
pkg/controller/datavolume/snapshot-clone-controller.go
pkg/controller/datavolume/snapshot-clone-controller_test.go
pkg/controller/populators/clone-populator.go
tests/clone-populator_test.go

This Pull Request updates the clone populator to include cloning from snapshot capabilities.
For more information, check the clone populator PR (https://github.com/kubevirt/containerized-data-importer/pull/2709) and the clone from snapshot PR (https://github.com/kubevirt/containerized-data-importer/pull/2522).
**Special notes for your reviewer**: Work in progress.
```release-note
NONE
```

Add clone from snapshot functionalities to clone-populator

---

pkg/operator/resources/cluster/rbac.go
tests/rbac_test.go

This Pull Request updates the populator CRDs roles to include `cluster-readers`.
Fixes # https://bugzilla.redhat.com/show_bug.cgi?id=2217956
```release-note
NONE
```

Update populator CRDs roles to include cluster-readers

---

pkg/storagecapabilities/storagecapabilities.go
tests/cloner_test.go
tests/smartclone_test.go

Per recommendation from ceph CSI team,
switching over to doing CSI clones by default for ceph provisioners. Implementation is very similar to today's smart cloning via temporary snapshot:
https://issues.redhat.com/browse/CNV-28254?focusedId=22318987&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-22318987
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=2223577
```release-note
Switch ceph provisioners clone strategy to CSI cloning
```

Set clone strategy for ceph to CSI clone

---

pkg/controller/clone/common.go
pkg/controller/clone/planner.go
pkg/controller/clone/planner_test.go

Clone populator was not doing sufficient checks before attempting csi-clone.  Was not checking that source and target provisioner/driver were the same.
Fixes # https://bugzilla.redhat.com/show_bug.cgi?id=2231479
```release-note
NONE
```

Fix broken local -> rook-ceph-block clone

---

tests/monitoring_test.go

This PR improves the alerts rules test readability and maintainability. In addition, it adds a check to the alerts rules test, which verifies that the alerts `runbook_url` annotations have a suffix with the alerts names.
**Which issue(s) this PR fixes**: https://issues.redhat.com/browse/CNV-30798
```release-note
None
```

Improve alert rules sanity test

---

tests/dataimportcron_test.go

Adding the polarion id to the tier 1 test (10360)
Fixes #
```release-note
NONE
```

DataImportCron external trigger polarion id

---

hack/build/docker/builder/Dockerfile

Update controller-gen to latest (0.13.0)
Update gingko to latest (2.12.0)
Fixes #
```release-note
NONE
```

Update builder to use golang 1.20.7

---

hack/build/docker/builder/Dockerfile

Created a broken builder by using the wrong path for ginkgo since we are using the v2 version now.
Fixes #
```release-note
NONE
```

Fix gingko install in builder

---

.golangci.yml
hack/build/run-linters.sh
pkg/operator/controller/certrotation.go
pkg/operator/controller/certrotation_test.go

Fixes #
```release-note
None
```

Upgrade golangci-lint to v1.54.2 and fix findings

---

pkg/operator/controller/controller_test.go

Fixes #
```release-note
NONE
```

Add unit test for bad RBAC practices

---

doc/cdi-populators.md
pkg/controller/datavolume/controller-base.go

I find myself going back a lot to this great function and I noticed
some of the fallback reasons are outdated following:
https://github.com/kubevirt/containerized-data-importer/pull/2765
https://github.com/kubevirt/containerized-data-importer/pull/2873
Fixes #
```release-note
NONE
```

Update doc of shouldUseCDIPopulator to reflect changes

---

pkg/util/cert/cert.go

Fixes #
```release-note
NONE
```

chore: import packages only once

---

pkg/storagecapabilities/storagecapabilities.go

Fixes #
```release-note
Advise Trident provisioner to use csi-clone
```

Advise Trident provisioner to use csi-clone

---

pkg/controller/clone-controller.go
pkg/controller/clone-controller_test.go
pkg/controller/common/util.go

Fixes #
```release-note
BugFix: Some provisioners don't allow mounting block PVC ro
```

[release-v1.56] Mount block PVC rw in clone source pods

---

pkg/controller/clone-controller.go
pkg/controller/clone-controller_test.go
pkg/controller/util.go

Fixes #
```release-note
BugFix: Some provisioners don't allow mounting block PVC ro
```

[release-v1.55] Mount block PVC rw in clone source pods

---

doc/efficient-cloning.md

Fixes #
```release-note
NONE
```

Add doc for fallback to host-assisted cloning

---

go.mod
go.sum
vendor/google.golang.org/grpc/internal/transport/http2_server.go
vendor/google.golang.org/grpc/server.go
vendor/google.golang.org/grpc/version.go
vendor/modules.txt

Address CVE-2023-44487
Fixes #
```release-note
NONE
```

Update google.golang.org/grpc to 1.56.3

---

go.mod
go.sum
vendor/google.golang.org/grpc/internal/transport/http2_server.go
vendor/google.golang.org/grpc/server.go
vendor/google.golang.org/grpc/version.go
vendor/modules.txt

Address CVE-2023-44487
Fixes #
```release-note
NONE
```

[release-v1.58] Update google.golang.org/grpc to 1.56.3

---

tests/datavolume_test.go
tests/monitoring_test.go

Fixes #
```release-note
NONE
```

Add tests ids

---

doc/onboarding-storage-provisioners.md
doc/storageprofile.md

This is a way for us to advertise what is needed to ensure smooth integration
with storage providers
Fixes #
```release-note
NONE
```

Add storage provider onboarding doc

---

tests/monitoring_test.go

This should not be used. Instead,
we should get a monitoring-perspective review on the alert design, which will in turn help merge the runbook.
Fixes #
```release-note
NONE
```

Remove runbook URL validation bypass W/A

---

pkg/storagecapabilities/storagecapabilities.go

Fixes #
```release-note
Fix Trident provisioner key for using csi-clone
```

Fix Trident provisioner key for using csi-clone

---

.snyk

feat: add .snyk file
This file is used for excluding vendor folders from snyk code scans
```release-note
NONE
```

[release-v1.55]feat: add .snyk file

---

.snyk

feat: add .snyk file
This file is used for excluding vendor folders from snyk code scans
```release-note
NONE
```

[release-v1.56]feat: add .snyk file

---

tests/datavolume_test.go

Fixes #
```release-note
NONE
```

Parallelize datavolume_test suite

---

tests/BUILD.bazel
tests/framework/framework.go
tests/reporter/BUILD.bazel
tests/reporter/kubernetes.go
tests/tests_suite_test.go

- Move to separate package
- Extract common code
- Ensure the reporting fires right after an It() block instead of (current behavior) after other AfterEach blocks.
This also fixes broken reporting when failures occurred on both the node 1 parallel/serial run
Fixes #
```release-note
NONE
```

Refactor e2e kubernetes reporter

---

pkg/storagecapabilities/storagecapabilities.go

Fixes CNV-36768
```release-note
Add Trident RWO Filesystem capability
```

Add Trident RWO Filesystem capability

---

doc/datavolumes.md

Fixes #
```release-note
NONE
```

Docs for default virt storage class

---

pkg/controller/datavolume/controller-base.go
pkg/controller/datavolume/import-controller.go
pkg/controller/datavolume/import-controller_test.go
pkg/controller/datavolume/upload-controller.go
pkg/controller/datavolume/upload-controller_test.go
tests/cloner_test.go
tests/import_test.go
tests/utils/datavolume.go
tests/utils/pvc.go

Manual backport of #3056 
Fixes #
Jira-ticket: https://issues.redhat.com/browse/CNV-36326
```release-note
Fix pvc not recreating and repopulating after deletion
```

[release-v1.57] Fix populators not repopulating pvc

---

hack/build/docker/builder/Dockerfile

Fixes #
```release-note
NONE
```

Update builder to use golang 1.21.5

---

WORKSPACE
go.mod
go.sum
hack/build/config.sh
staging/src/kubevirt.io/containerized-data-importer-api/go.mod
staging/src/kubevirt.io/containerized-data-importer-api/go.sum
vendor/modules.txt

Fixes #
```release-note
NONE
```

Bump builder, switch to go 1.21

---

pkg/storagecapabilities/storagecapabilities.go

Fixes #
```release-note
None
```

Update portworx csi to have CSI-clone clone strategy

---

pkg/operator/resources/cluster/controller.go

This was mistakenly not added with https://github.com/kubevirt/containerized-data-importer/pull/3078/commits/d1d6eae2afa3483e855536802035cbc70b81eeb8
Fixes #
```release-note
NONE
```

Add missing RBAC for identifying if were running on OpenShift

---

pkg/apiserver/webhooks/datavolume-validate.go
tests/cloner_test.go
tests/datavolume_test.go
tests/external_population_test.go

Fixes #2365 
```release-note
ReadWriteOncePod is now allowed to use with CDI DataVolumes
```

Allow ReadWriteOncePod DVs

---

WORKSPACE

Luckily kubevirt/kubevirt has those exact ones, but going forward we need a more robust
solution like https://github.com/kubevirt/project-infra/issues/3097
Fixes #
```release-note
NONE
```

[release-v1.56] Add mirror for systemd related RPMs

---

pkg/common/common.go
pkg/controller/BUILD.bazel
pkg/controller/dataimportcron-controller.go
pkg/controller/dataimportcron-controller_test.go
pkg/operator/resources/namespaced/controller.go
tests/dataimportcron_test.go

Jira-ticket: https://issues.redhat.com/browse/CNV-35787
```release-note
BugFix: Watch DataImportCron-orphan cronjobs and cleanup them
```

Watch DIC-orphan cronjobs and cleanup them

---

pkg/common/common.go
pkg/controller/BUILD.bazel
pkg/controller/dataimportcron-controller.go
pkg/controller/dataimportcron-controller_test.go
pkg/operator/resources/namespaced/controller.go

Manual backport of #3106
Jira-ticket: https://issues.redhat.com/browse/CNV-35787
```release-note
BugFix: Watch DataImportCron-orphan cronjobs and cleanup them
```

[release-v1.58] Watch DIC-orphan cronjobs and cleanup them

---

pkg/common/common.go
pkg/controller/BUILD.bazel
pkg/controller/dataimportcron-controller.go
pkg/controller/dataimportcron-controller_test.go
pkg/operator/resources/namespaced/controller.go

Manual backport of #3106
Jira-ticket: https://issues.redhat.com/browse/CNV-38889
```release-note
BugFix: Watch DataImportCron-orphan cronjobs and cleanup them
```

[release-v1.57] Watch DIC-orphan cronjobs and cleanup them

---

doc/pvc-mutating-webhook-rendering.md
pkg/apiserver/webhooks/pvc-mutate.go
pkg/common/common.go
pkg/controller/datavolume/controller-base.go
pkg/controller/datavolume/util.go
pkg/operator/controller/callbacks.go
tests/clone-populator_test.go
tests/datavolume_test.go
tests/import_test.go

Thanks for being pedantic @fabiand  :)
Fixes #
```release-note
NONE
```

Rename PVC webhook rendering label to "applyStorageProfile"

---

pkg/importer/vddk-datasource_arm64.go

Fixes #
```release-note
NONE
```

Add missing import in pkg/importer/vddk-datasource_arm64.go

---

tests/clone-populator_test.go
tests/datavolume_test.go
tests/import_test.go

Fixes #
```release-note
NONE
```

Add polarion rfes and ids to webhook rendering

---

pkg/storagecapabilities/storagecapabilities.go

Manual backport of #3140
Fixes # https://issues.redhat.com/browse/CNV-39960
```release-note
Add HPE RWX/Block capability
```

[release-v1.49] Add HPE RWX/Block capability

---

.golangci.yml
pkg/importer/imageio-datasource_test.go
pkg/operator/controller/patches_test.go
tests/operator_test.go

Recently we hit some unexpected changes in commits which could have been caught by goimports:
https://github.com/kubevirt/containerized-data-importer/pull/3057#discussion_r1448696072.
Fixes #
```release-note
NONE
```

Add goimports to golangci linters

---

doc/image-from-registry.md

Add docs which explain how PVCs of imported containerdisks can be decorated with additional labels.
Fixes #3132
```release-note
None
```

docs: Add docs for containerdisk labels

---

pkg/controller/import-controller.go

Fix that the Resources configuration is missing the configuration of the initcontainer container
Fixes #
https://github.com/kubevirt/containerized-data-importer/issues/1043
```release-note
Fix that the Resources configuration is missing the configuration of the cdi-containerimage-server initcontainer container
```

Fix that the Resources configuration

---

.golangci.yml
cmd/cdi-cloner/clone-source.go
cmd/cdi-cloner/clone-source_test.go
pkg/apiserver/webhooks/datavolume-mutate.go
pkg/controller/common/util.go
pkg/image/qemu.go
pkg/importer/data-processor.go
pkg/importer/format-readers.go
pkg/importer/imageio-datasource.go
pkg/importer/imageio-datasource_test.go
pkg/importer/transport.go
pkg/importer/vddk-datasource_amd64.go
pkg/uploadserver/uploadserver.go
pkg/util/util.go
tests/certrotation_test.go
tests/upload_test.go

Enables two linters:
- `errorlint`:  it checks that you properly use errors.Is and errors.As
- `errname`: makes error names consistent
https://github.com/polyfloyd/go-errorlint
https://github.com/Antonboom/errname
I recommend reviewing commit per commit as mistakes on my part could introduce subtle behavior changes, particularly in commit [8783ea3](https://github.com/kubevirt/containerized-data-importer/pull/3177/commits/8783ea38939b19939ccaebe6eb240798f2fd059f).
```release-note
Add linters for error handling and fix detected issues.
```

Enable linters checking error handling

---

.golangci.yml
pkg/controller/dataimportcron-controller.go

Enables the durationcheck linter.
> Check for two durations multiplied together.
https://github.com/charithe/durationcheck
```release-note
Enable durationcheck linter and fix detected issues
```

Enable durationcheck linter

---

doc/datavolume-claim-adoption.md

Let's document how to do claim adoption
Fixes #
https://issues.redhat.com/browse/CNV-40262
```release-note
NONE
```

Claim Adoption Doc

---

pkg/operator/resources/crds_generated.go

Somehow the builder bump generate lane was green even though applying the changes on top of the forklift populator should have resulted in red.
Fixes #
```release-note
NONE
```

Make generate following new builder bump

---

pkg/storagecapabilities/storagecapabilities.go

Reference - https://github.com/Infinidat/infinibox-csi-driver/tree/develop/deploy/examples
alongside some offline chats with recommendations.
Fixes #
```release-note
Onboard Infinibox CSI driver
```

Onboard Infinibox CSI driver

---

pkg/storagecapabilities/storagecapabilities.go

Reference - https://github.com/Infinidat/infinibox-csi-driver/tree/develop/deploy/examples alongside some offline chats with recommendations.
Backport https://github.com/kubevirt/containerized-data-importer/pull/3271 manually
Fixes #
```release-note
Onboard Infinibox CSI driver
```

[release-v1.55] Onboard Infinibox CSI driver

---

pkg/storagecapabilities/storagecapabilities.go

Reference - https://github.com/Infinidat/infinibox-csi-driver/tree/develop/deploy/examples alongside some offline chats with recommendations.
Backport https://github.com/kubevirt/containerized-data-importer/pull/3271 manually
Fixes #
```release-note
Onboard Infinibox CSI driver
```

[release-v1.56] Onboard Infinibox CSI driver

---

tests/import_test.go

I believe this was the original intention, currently, we don't refresh the PVC from the API server.
Fixes #
```release-note
NONE
```

tests: correct check for containerdisk env vars eventually appearing

---

pkg/controller/populators/forklift-populator.go
pkg/controller/populators/forklift-populator_test.go

Because there is time until deletionTimestamp is set on the PVC prime, and since the populator pod is deleted first we might reconcile again when the PVC is not yet marked for deletion, causing the populator pod to be recreated.
This change reorders the operation, to first wait until the PVC is marked for deletion, and then delete the populator pod.
Fixes #
```release-note
Fix race in the forklift populator that might prevent cleanup
```

forklift: fix race between prime pvc and pod removal

---

pkg/storagecapabilities/storagecapabilities.go

On multi node LMVO this setting can cause issues so reverting to host assisted clone which works everywhere
Fixes #
```release-note
NONE
```

Revert LVMO storage CSI snapshot clone.

---

doc/onboarding-storage-provisioners.md

Fixes #
```release-note
NONE
```

Add virt default storage class mention in onboarding doc

---

Makefile
hack/README.md

**What this PR does / why we need it**: Documents environment variables.
I documented the environment variables set in `config.sh` plus a couple extra I could find.
Don't hesitate to tell me if I missed any.
[CNV-35422](https://issues.redhat.com/browse/CNV-35422)
```release-note
NONE
```

Document environment variables in Makefile

---

go.mod
staging/src/kubevirt.io/containerized-data-importer-api/go.mod
vendor/modules.txt

This is needed when building CDI on different platforms, and it looks like this is the common practice nowadays as well.
Fixes #
```release-note
NONE
```

State explicit go version in go.mod files

---

pkg/controller/populators/import-populator.go
pkg/importer/http-datasource.go
tests/datavolume_test.go

Manual backport of #3293 
Fixes #
```release-note
Fix progress reporting for http imports
```

[release-v1.58] Backport 'Fix progress reporting for http imports (#3293)'

---

pkg/controller/populators/import-populator.go
pkg/importer/http-datasource.go
tests/datavolume_test.go

Manual backport of #3293 
Fixes #
```release-note
Fix progress reporting for http imports
```

[release-v1.57] Backport 'Fix progress reporting for http imports (#3293)'

---

pkg/operator/controller/certrotation.go
pkg/operator/controller/certrotation_test.go

Synchronization between fake client and lister could cause flakes
Test assuming creates would be seen immedietly but updates would not
Solution is to forget about validating anything library-go package may do
It's not our code anyway!
Fixes #
```release-note
NONE
```

Flaky certrotation tests

---

pkg/storagecapabilities/storagecapabilities.go

Avoid multiple cherry picks
Fixes #
```release-note
Add vSphere capabilities, fix DELL ones
```

[release-v1.59] Sync multiple storage capability additions

---

pkg/controller/common/checkpoint-util.go

This Pull Request attempts to fix a race condition in the multi-stage import logic when updating checkpoint annotations for a PVC.
**Explanation:**
Once a multi-stage import pod succeeds and the current checkpoint is copied, we update the checkpoint and pod annotations to manually trigger a new importer pod with the updated data.
Cases where the pod has succeeded but still hasn't been deleted are possible. These situations can lead to irrecoverable states where the checkpoint annotations are updated, but the pod annotations remain outdated (still in the succeeded phase). This discrepancy halts progress in both the import-controller and the multi-stage import logic.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes …

Fix race condition in multi-stage import logic

---

pkg/system/prlimit_test.go

Enable running unit tests on IBM Z Platform, by introducing a higher memory limit, when running on s390x.
Fixes #3341 
This fix is a temporary workaround, until the underlying issue is solved.
```release-note
NONE
```

s390x Unit Test Enablement

---

hack/build/docker/builder/Dockerfile

Follow up and more info in https://github.com/kubevirt/containerized-data-importer/pull/3378
Fixes #
```release-note
NONE
```

Remove ginkgo CLI dep from builder

---

hack/build/bazel-docker.sh

We flake very frequently on pulling the builder images, let's see if retrying a few times helps:
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/3371/pull-containerized-data-importer-e2e-hpp-previous/1823003234072006656
Some container runtimes have a `--retry`, other's don't, so opted for writing the retry logic ourselves:
https://docs.podman.io/en/latest/markdown/podman-pull.1.html https://docs.docker.com/reference/cli/docker/image/pull/
Fixes #
```release-note
NONE
```

Retry pulling builder image

---

hack/build/docker/builder/Dockerfile
hack/build/docker/builder/output-bazel-arch.sh

Incorporates cross-compile build tools for s390x in x86 CDI builder container 
Fixes #3289
```release-note
enables cross compile tools for s390x for CDI builder
```

cross-compile docker builder for s390x

---

tests/utils/datavolume.go

Same import under two different names, align them
Fixes #
```release-note
NONE
```

Replace corev1 with k8sv1 in utils/datavolume.go

---

hack/build/config.sh

We've had a few PRs merge to the builder Dockerfile, let's start using the new one.
Fixes #
```release-note
NONE
```

Bump builder to latest

---

hack/build/config.sh

Fixes #
```release-note
NONE
```

[release-v1.60] Bump builder

---

pkg/storagecapabilities/storagecapabilities.go

Add vSphere, Huawei, Longhorn storage capabilities, fix DELL ones.
jira-ticket: https://issues.redhat.com/browse/CNV-50491
```release-note
Add vSphere, Huawei, Longhorn storage capabilities, fix DELL ones
```

[release-v1.55] Sync multiple storage capability additions

---

pkg/storagecapabilities/storagecapabilities.go

Add vSphere, Huawei, Longhorn storage capabilities, fix DELL ones.
jira-ticket: https://issues.redhat.com/browse/CNV-50490
```release-note
Add vSphere, Huawei, Longhorn storage capabilities, fix DELL ones
```

[release-v1.56] Sync multiple storage capability additions

---

pkg/storagecapabilities/storagecapabilities.go

Add vSphere, Huawei, Longhorn storage capabilities, fix DELL ones.
jira-ticket: https://issues.redhat.com/browse/CNV-50488
```release-note
Add vSphere, Huawei, Longhorn storage capabilities, fix DELL ones
```

[release-v1.58] Sync multiple storage capability additions

---

pkg/storagecapabilities/storagecapabilities.go

Add vSphere, Huawei, Longhorn storage capabilities, fix DELL ones.
jira-ticket: https://issues.redhat.com/browse/CNV-50489
```release-note
Add vSphere, Huawei, Longhorn storage capabilities, fix DELL ones
```

[release-v1.57] Sync multiple storage capability additions

---

manifests/templates/file-host.yaml.in

Raising the used Minio version, this also enables it to other architectures, than just amd64
Fixes #3460 
Thanks @brianmcarey for getting the image
```release-note
NONE
```

Bump Minio Version

---

hack/build/docker/builder/Dockerfile

Some maintenance is needed on this branch, similarly to https://github.com/kubevirt/containerized-data-importer/pull/3438 and https://github.com/kubevirt/containerized-data-importer/pull/3389
Fixes #
```release-note
NONE
```

[release-v1.57] Prepare branch for releasing; apidocs/go binary freezes

---

pkg/importer/vddk-datasource_amd64.go
pkg/importer/vddk-datasource_test.go

Manual cherry pick of https://github.com/kubevirt/containerized-data-importer/pull/3534 to speed things up
Fixes #
```release-note
VDDK Fix Incomplete transfer of change blocks leads to data corruption
```

[release-v1.59] Manual cherry pick of CNV-51521 fix

---

pkg/importer/vddk-datasource_amd64.go
pkg/importer/vddk-datasource_test.go

Manual cherry pick of https://github.com/kubevirt/containerized-data-importer/pull/3534 to speed things up
Fixes #
```release-note
VDDK Fix Incomplete transfer of change blocks leads to data corruption
```

[release-v1.58] Manual cherry pick of CNV-51521 fix

---

pkg/controller/datavolume/controller-base.go

Currently, completing an incomplete `StorageProfile` does not reconcile the relevant incomplete `DataVolumes` waiting for it, unlike the case of missing `StorageClass`.
Even after updating the `StorageProfile` `claimPropertySets` to have `AccessMode` and `VolumeMode`, the `DataVolume` is stuck with incomplete `AccessMode` and `VolumeMode` until its exponential back-off reconcile, or until it's manually updated (e.g. annotated) and reconciled.
jira-ticket: https://issues.redhat.com/browse/CNV-46452
```release-note
Watch for StorageProfile updates to reconcile DataVolumes
```

Watch for StorageProfile updates to reconcile DataVolumes

---

pkg/operator/resources/cluster/object-transfer.go

Fixes #
```release-note
NONE
```

Correct typo in deprecation note for ObjectTransfer

---

pkg/apiserver/webhooks/BUILD.bazel

Not sure why the CI lane deps-verify didn't catch this.
Fixes #
```release-note
NONE
```

Make deps update over apiserver change

---

pkg/uploadproxy/uploadproxy.go

The uploadReady func **could** be returning an error that's somehow dependent on user input.
It's somehow unlikely and an edge case but better safe than sorry
Fixes #
```release-note
NONE
```

CWE-79 small tightening up

---

tests/import_test.go

For the functional tests under s390x we filter out tests using unsupported tools. 
For this to work correctly, that tool needs to be mentioned in the description of the test or have a corresponding label assigned.
```release-note
NONE
```

Add vddk label to a func test 

---

doc/releases.md

Fix the dead link leading to the prow post periodic dashboard
Fixes #
```release-note
NONE
```

Update dead link in releases.md

---

pkg/storagecapabilities/storagecapabilities.go

This PR adds support for the nvme protocol to the existing set of protocols supported within CDI.
Fixes #
```release-note
Added support for Infinibox nvme protocol.
```

add support for infinibox nvme protocol

---

pkg/storagecapabilities/storagecapabilities.go

Reference:
https://docs.portworx.com/portworx-csi/release-notes.html#px-csi-2520
Fixes #
```release-note
Add RWX block to Portworx capabilities
```

Add RWX block to Portworx capabilities

---

.golangci.yml
go.mod
hack/build/config.sh
hack/build/run-linters.sh
pkg/apiserver/webhooks/cdi-validate.go
pkg/apiserver/webhooks/cdi-validate_test.go
pkg/controller/datavolume/controller-base.go
pkg/controller/populators/forklift-populator.go
pkg/image/qemu.go
pkg/importer/gcs-datasource.go
pkg/importer/http-datasource.go
pkg/importer/s3-datasource.go
staging/src/kubevirt.io/containerized-data-importer-api/go.mod
tests/basic_sanity_test.go
tests/operator_test.go
vendor/modules.txt

Fixes #
```release-note
Cleanup: build with go 1.23.6
```

Use new 1.23.6 builder

---

go.mod
go.sum
vendor/golang.org/x/oauth2/LICENSE
vendor/golang.org/x/oauth2/README.md
vendor/golang.org/x/oauth2/google/default.go
vendor/golang.org/x/oauth2/google/externalaccount/aws.go
vendor/golang.org/x/oauth2/google/externalaccount/basecredentials.go
vendor/golang.org/x/oauth2/jws/jws.go
vendor/golang.org/x/oauth2/oauth2.go
vendor/golang.org/x/oauth2/pkce.go
vendor/golang.org/x/oauth2/token.go
vendor/modules.txt

Fixes #
```release-note
NONE
```

Update x/oauth2 to v0.27.0

---

pkg/operator/controller/certrotation_test.go

one is not supposed to run informers on a fake client
https://github.com/kubernetes/kubernetes/pull/95897
https://github.com/kubernetes-csi/external-attacher/blob/e32b64308dcb147c6f5a714d1f7e71e0b91a2319/pkg/controller/framework_test.go#L160-L162
Hopefully this is finally fixing the cert rotation unit tests
Fixes #
```release-note
NONE
```

don't start informer in cert rotation unit tests

---

pkg/uploadserver/uploadserver.go
tests/upload_test.go

The uploadserver features two handler functions for sync and async uploads.
The async upload handler correctly reports an error message if QEMU image size validation errors due to lack of space in the target by appending the error message to the HTTP response. The sync upload handler, however, does not.
This commit makes error handling for failed upload identical between both handlers. Furthermore, it also checks for ENOSPC errors during write as can happen when the image is streamed directly into target instead of going through scratch space first (e.g., raw images). It also consolidates the sync and async upload failure e2e tests into a single DescribeTable and improves upon its clarity.
**Which issue(s) this PR fixes** *(optional, in `fixes …

uploadserver, tests: include error message for upload failure due to lack of space

---

pkg/storagecapabilities/storagecapabilities.go

Manual backport of #3687
Fixes #3680
```release-note
Fix Longhorn Filesystem capabilities
```

[release-v1.59] Fix Longhorn Filesystem capabilities

---

tools/cdi-func-test-registry-init/populate-registry.sh

`populate-registry.sh` currently creates variations of [Tiny Core Linux.](http://www.tinycorelinux.net/) In order to support functional testing of multiarch import capabilities in the future, it's required to allow `populate-registry.sh` to build the container image for multiple architectures as well as construct an image index.
This PR introduces the ability to do that and by default builds only tinycore.qcow2 for the amd64, arm64 and s390x architectures.
Partially addresses https://github.com/kubevirt/enhancements/issues/48
The choice to limit the multiarch …

Add multiarch test images to local registry for functional tests

---

pkg/operator/controller/BUILD.bazel
pkg/operator/controller/controller_test.go
pkg/operator/controller/scc.go

Fixes #
```release-note
BugFix: Event hotloop over SCC volume order changes
```

Address SCC hotloop over volumes order

---

pkg/storagecapabilities/storagecapabilities.go

Added for supporting Google Cloud NetApp Volumes with Flex service level.
https://cloud.google.com/netapp/volumes/docs/discover/service-levels
```release-note
Add Google Cloud NetApp Volumes Flex storage capabilities
```

Add GCNV storage capabilities

---

pkg/storagecapabilities/storagecapabilities.go

Manual backport of #3821, for Google Cloud NetApp Volumes with Flex service level.
https://cloud.google.com/netapp/volumes/docs/discover/service-levels
```release-note
Add Google Cloud NetApp Volumes Flex storage capabilities
```

[release-v1.62] Add GCNV storage capabilities

---

tests/BUILD.bazel
tests/import_test.go
tests/upload_test.go

Manual cherry-pick of https://github.com/kubevirt/containerized-data-importer/pull/3802.
```release-note
NONE
```

[release-v1.60] Tests: Fix flaky variable assignments during Update

---

hack/build/resource-generator.sh

These syncs exist as a bandaid on a CI issue;
They recently started causing the entire job to fail over the sync itself.
Fixes #
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/3806/pull-containerized-data-importer-e2e-hpp-latest/1940758388946243584
```release-note
NONE
```

Targeted fsync in resource generating
