cluster-sync/ephemeral_provider.sh

Use the new file name when deploying the legacy HPP CR and storage class.
Fixes #
```release-note
NONE
```

HPP storage class file name changed.

---

pkg/apiserver/webhooks/cdi-validate.go
pkg/common/common.go
pkg/controller/dataimportcron-controller.go
tests/operator_test.go

`DataImportCron` `RetentionPolicy` specifies whether the created `DataVolumes` and `DataSources` are retained when their `DataImportCron` is deleted. Default is `RetainAll`. However, when CDI delete validation finds existing DVs, it fails (if `UninstallStrategy` is `cdiv1.CDIUninstallStrategyBlockUninstallIfWorkloadsExist`). Therefore, on CDI delete validation we are now ignoring DVs labeled with `DataImportCron` so it won't fail if they are the only existing DVs.
```release-note
NONE
```

On CDI delete validation ignore DVs labeled with DataImportCron

---

pkg/importer/BUILD.bazel
pkg/importer/imageio-datasource.go
pkg/importer/imageio-datasource_test.go
pkg/util/BUILD.bazel
pkg/util/prometheus/BUILD.bazel
pkg/util/prometheus/prometheus.go
pkg/util/prometheus/prometheus_test.go
pkg/util/util.go
pkg/util/util_test.go
tests/datavolume_test.go
tests/imageio-inventory.go

This pull request checks for the "extents" feature when connecting to an ImageIO data source. If the feature is available, the importer uses the ImageIO extents API to avoid copying large blocks of all-zero bytes. This should reduce raw format transfer times closer to QCOW format times, and it avoids the need to convert from a QCOW in scratch space to a raw final destination. It also attempts to punch holes in the destination to avoid writing blocks of all-zero bytes. 
Fixes [RHBZ#1993454](https://bugzilla.redhat.com/show_bug.cgi?id=1993454)
Looping through extents does not really mesh well with the existing stack of readers approach, so this works by creating a new reader for …

Use ImageIO extents API to copy raw images more efficiently.

---

pkg/importer/s3-datasource.go
pkg/importer/s3-datasource_test.go

We are using the AWS s3 client, and if the URL we pass in starts with http, the AddScheme function in the AWS S3 client replaces the scheme with https. This checks the URL scheme and if it is http, it disables TLS, which causes the AWS S3 client to set the scheme internally as http.
Fixes #2067 
```release-note
BugFix: Allow http endpoints with s3 import.
```

Allow http in s3 datasource

---

cmd/cdi-controller/controller.go
pkg/controller/dataimportcron-conditions.go
pkg/controller/dataimportcron-controller.go
pkg/operator/controller/prometheus.go
tests/dataimportcron_test.go
tests/operator_test.go

DataImportCrons now have conditions (particularly UpToDate) that tell us if
things are going as planned. We can utilize those to alert whenever were not UpToDate for a while.
Fixes #
```release-note
Alert about a DataImportCron not being up to date; possibly not using a PVC that holds latest OS
```

Add alert for DataImportCron not being up to date

---

pkg/controller/dataimportcron-controller.go
pkg/controller/dataimportcron-controller_test.go
pkg/operator/resources/crds_generated.go
staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go

When `DataImportCron` updated source digest matches an existing `DataVolume`, we should use this DV instead of failing the import. In this case, we also touch the DV Ready condition heartbeat time, and make sure DV wan't be garbage collected although its `CreationTimestamp` might be older than other DVs.
Fixes #
```release-note
Use existing DataVolume on DataImportCron source digest match
```

Use existing DataVolume on DataImportCron source digest match

---

hack/build/bazel-build-builder.sh
hack/build/docker/builder/Dockerfile
hack/build/docker/builder/fedora.repo

1.17 needed for k8s 1.23 libs.  kubebuilder binaries removed because they were changed and IMO not needed for unit tests
Fixes #
```release-note
Update golang in builder image
```

update builder golang to 1.17 remove kubebuilder

---

cmd/cdi-controller/controller.go
pkg/controller/BUILD.bazel
pkg/controller/dataimportcron-conditions.go
pkg/controller/dataimportcron-controller.go
pkg/controller/dataimportcron-controller_test.go
pkg/controller/datasource-controller.go
pkg/controller/datasource-controller_test.go

DataSource is no more dependent on a DataImportCron to update the Ready status condition
Fixes #
```release-note
NONE
```

Add DataSource controller to update the Ready condition

---

cmd/cdi-controller/leaderelection.go
pkg/common/common.go
pkg/operator/controller/cruft.go

This one was missed in #2018, we want to maintain its label values on update as well.
Fixes #
```release-note
NONE
```

Update relationship labels on missed ConfigMap

---

pkg/controller/dataimportcron-controller.go
pkg/controller/dataimportcron-controller_test.go

There are cases when DataImportCron registry source URL contains tag referring a specific version. We use this tagged URL when polling for source updates, but on import we would like to remove the tag as we use a specific sha256.
E.g. for `docker://quay.io/containerdisks/centos:8.4` the `:8.4` tag will be removed.
Fixes #
```release-note
NONE
```

Remove tag from DataImportCron registry source URL

---

WORKSPACE
cluster-sync/ephemeral_provider.sh
tests/datavolume_test.go
tests/import_proxy_test.go
tests/import_test.go
tests/utils.go

Backport of #1778 and #1938 to stop MCP before updating cluster wide proxy and causing issues in the test run.
Fixes #
```release-note
NONE
```

[release-v1.34] Backport cluster proxy test fix

---

pkg/controller/dataimportcron-controller.go

The following labels should be set by the operator that creates the resource, and not by the DataImportCron controller, otherwise it may result an unnecessary reconciliation and a race-condition.
```
app.kubernetes.io/component
app.kubernetes.io/managed-by
```
Fixes #
```release-note
NONE
```

Remove DataImportCron CDI labeling

---

pkg/controller/datasource-controller.go
tests/BUILD.bazel
tests/datasource_test.go

Added the DataSource controller a DV watch, so whenever a DataSource
referred DV/PVC is created/updated/deleted, the DataSource Ready status
condition is updated accordingly.
Fixes #
```release-note
NONE
```

Update DataSource Ready condition on DV update

---

pkg/operator/controller/callbacks.go
tests/BUILD.bazel
tests/operator_test.go

`reconcileDeleteControllerDeployment` deletes the CRDs of `DataImportCron` and `DataVolume`, and returns error if any DIC/DV has a finalizer. It will get retried and controller will eventually remove the finalizers.
Fixes #
```release-note
NONE
```

Delete CRDs & check finalizers in operator delete

---

api/openapi-spec/swagger.json
doc/datavolumes.md
pkg/apis/core/v1alpha1/openapi_generated.go
pkg/apis/core/v1beta1/openapi_generated.go
pkg/controller/datavolume-controller.go
pkg/controller/datavolume-controller_test.go
pkg/controller/import-controller.go
pkg/controller/import-controller_test.go
pkg/controller/util.go
pkg/operator/resources/crds_generated.go
staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1alpha1/types.go
staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1alpha1/types_swagger_generated.go
staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
tests/datavolume_test.go
tests/utils/configmaps.go

This pull request adds an optional initImageURL field to the VDDK data source spec, so that a VDDK archive image can be specified per-DataVolume. This allows MTV to migrate VMware VMs without interfering with the HCO-managed v2v-vmware ConfigMap.
Fixes [BZ#2031033](https://bugzilla.redhat.com/show_bug.cgi?id=2031033) partially, enables complete fix in MTV
```release-note
Allow optional specification of per-DataVolume VDDK archive image.
```

Allow optional per-DataVolume VDDK image.

---

tests/utils.go

For some reason curling localhost stopped working for us after https://github.com/kubevirt/project-infra/pull/1616,
So let's change to 127.0.0.1. Does not reproduce using on my machine when using a prow mimic:
https://github.com/kubernetes/test-infra under `prow/cmd/phaino`.
Only reproduces on the real prow env. thanks @dhiller.
Fixes #
```release-note
NONE
```

Fix prometheus tests failing after bootstrap img bump on CI

---

tests/cloner_test.go
tests/csiclone_test.go
tests/datavolume_test.go
tests/smartclone_test.go

Previous method failed with not a message "expected <bool> ...", now it is changed
to a string comparison, so the expected and received events are shown.
Additionally, the signature was changed, so now it returns AsyncAssert. That way it
correctly reports the line number when it fails.
Improves reading test reports.
Fixes #
It is just a first small improvement. I think I can find some more places when looking at current reports with failed tests.
```release-note
NONE
```

Improve failure reporting in tests

---

cmd/cdi-importer/importer.go
tests/datavolume_test.go

Pass the function only the err without the wraping
back trace which is too long and causes the message
to overflow and not show the specific error.
Fixes: BZ#2000661
```release-note
NONE
```

Fix error message to be without trace

---

cmd/cdi-controller/leaderelection.go
pkg/common/common.go
pkg/operator/controller/cruft.go

This is a manual backport of #2082, we want this single (missed in #2018) resource to also get labeled on update in the previous release.
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=2017478
```release-note
BugFix: Some of the cdi resources are missing labels after upgrade
```

[release-v1.38] Manual cherrypick 2082

---

hack/build/build-go.sh

The PR removes hardcoded GOARCH=amd64 to enable builds for other architectures.
Fixes #2048
The fix is needed for building downstream CDI images. We do not use Bazel and therefore we rely on the native go build. This will simplify the aarch64 support.
```release-note
NONE
```

Allow non amd64 native Go builds

---

pkg/controller/config-controller.go

Backport of #2055 
Fixes #
```release-note
BugFix: Fix unable to list ConfigMap in cluster scope error messages in cdi controller log.
```

[release-v1.34] used uncached client to get cluster proxy configmap (#2055)

---

pkg/controller/BUILD.bazel
pkg/controller/dataimportcron-controller.go
pkg/controller/dataimportcron-controller_test.go
pkg/operator/controller/callbacks.go
pkg/operator/controller/controller_test.go
tests/operator_test.go

Also check DataImportCron CRD has no DeletionTimestamp before adding a
finalizer
Fixes #
```release-note
NONE
```

Fix CRDs deletion in operator deletion

---

cmd/cdi-importer/importer.go
pkg/apiserver/webhooks/datavolume-validate.go
pkg/controller/datavolume-controller.go
pkg/controller/upload-controller.go
pkg/controller/util.go
pkg/importer/data-processor.go
pkg/importer/data-processor_test.go
pkg/util/util.go
pkg/util/util_test.go
tests/cloner_test.go
tests/framework/pvc.go
tests/utils/datavolume.go

Fixes a problem with validation webhook failing for a clone that should succeed.
Validation webhook compares real PVC size of source volume with the requested size on spec.storage. 
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=2038679
Still experimenting 
```release-note
NONE
```

BugId: 2038679 -  Clone with volume mode file system using Storage API fails

---

cmd/cdi-controller/controller.go
cmd/cdi-operator/operator.go
pkg/operator/resources/namespaced/controller.go
pkg/operator/resources/operator/operator.go

Configmap leader election is deprecated.  But we have to continue using them for awhile before fully transitioning to just leases.
Fixes #
```release-note
NONE
```

use leases AND configmaps for leader election

---

pkg/controller/dataimportcron-controller.go
tests/dataimportcron_test.go

Update DataSource only if it has a DataImportCron label
Fixes #
```release-note
Reconcile DataSource PVC on update if managed by DataImportCron
```

Reconcile DataSource PVC on update if managed by DataImportCron

---

pkg/controller/import-controller.go

Always enable scratch space for imageio imports. Before imageio was doing the create pod without scratch space, then detect we need it, delete pod, and start new pod with scratch space cycle for every delta in a warm migration. This PR just takes out the cycle and immediately requires scratch space.
Fixes #
```release-note
NONE
```

Fix failing imageio test

---

tests/upload_test.go

Ignore the error, it might be because the other end closed the connection because it was done. We verify the image uploaded
by md5 anyway.
Fixes #
```release-note
NONE
```

Ignore error in upload copy test

---

tests/datavolume_test.go

Storage class name is always set on the PVC when that PVC is created
by the CDI. Updated a few tests to check for this behavior. Added two new scenarios.
Fixes #
```release-note
NONE
```

Extend tests to check explicit storage class name

---

pkg/common/common.go
pkg/controller/dataimportcron-conditions.go
pkg/controller/dataimportcron-controller.go
pkg/controller/dataimportcron-controller_test.go
pkg/operator/controller/callbacks.go
pkg/operator/resources/cluster/controller.go
tests/dataimportcron_test.go
tests/operator_test.go

Simplify the deletion of CDI and detaching it from cdi-deployment, so we won't need the DataImportCron controller to stay there to remove DataImportCrons finalizer so they can be deleted.   
Fixes #
```release-note
NONE
```

Get rid of DataImportCron finalizer

---

pkg/common/common.go
pkg/controller/dataimportcron-conditions.go
pkg/controller/dataimportcron-controller.go
pkg/controller/dataimportcron-controller_test.go
pkg/operator/controller/callbacks.go
pkg/operator/resources/cluster/controller.go
tests/dataimportcron_test.go
tests/operator_test.go

Cherry-pick of #2144
Simplify the deletion of CDI and detaching it from cdi-deployment, so we won't need the DataImportCron controller to stay there to remove DataImportCrons finalizer so they can be deleted.
Fixes #
```release-note
NONE
```

[release-v1.43] Get rid of DataImportCron finalizer

---

pkg/controller/import-controller.go

* Fix failing imageio test
Always enable scratch space for imageio imports.
* Only always enable scratch space with warm migration imports.
Backport to 1.38
Fixes #
```release-note
NONE
```

[release-v1.38] Fix failing imageio test (#2148)

---

tests/utils/common.go

With increased proxy tests, there are more restarts of the config controller, and sometimes it takes longer than 20 seconds to come back. This increases the timeout so we are more robust when testing. I have seen some tests fail on waiting for the
cdiconfig to be updated completely during proxy tests.
Fixes #
```release-note
NONE
```

Increase time we wait for cdiconfig update

---

BUILD.bazel
WORKSPACE
manifests/templates/imageio.yaml.in
pkg/controller/BUILD.bazel
pkg/controller/import-controller.go
pkg/controller/import-controller_test.go
tests/datavolume_test.go
tests/imageio-inventory.go
tools/image-io/99-cdi.conf
tools/image-io/BUILD.bazel
tools/image-io/myticket.json

Instead of using a really old imageio, use bazel to build a new imageio based on 2.5.0. Update the tests to use the new image
and paths in that new image. This requires a new repo in quay for us to push the image to.
Also changed the approach of resolving the warm import potential dead lock (scratch PVC from previous import pod terminating, while the new pod is trying to create itself). Instead of trying to avoid in all scenarios, detect the state, and delete the pod so the dead lock can be resolved.
Fixes #2145 
**Special notes for your …

Create imageio container during CDI build.

---

tests/framework/BUILD.bazel
tests/framework/pvc.go
tests/upload_test.go

We consistently fail on the check that `info.VirtualSize >= info.ActualSize`
on a real external nfs sever with different block size to what we're using upstream.
This happens because qemu-img info gives us the size on disk in ActualSize.
For the purpose of sparseness, I believe we are interested in the content size and not the padded size on disk.
Fixes #
I have kept a check that fails if the diff between size on disk and content is significant,
so we can still keep looking into the following flake: …

Fix VerifySparse to look at content size and not size on disk

---

pkg/common/common.go
pkg/controller/BUILD.bazel
pkg/controller/dataimportcron-controller.go
pkg/controller/dataimportcron-controller_test.go
pkg/importer/data-processor.go
tests/dataimportcron_test.go
tests/operator_test.go

When a DataImportCron import DV has condition Running=False with Reason=Error, it indicates this DIC might get stuck with this DV forever, so no new import DVs will be created even if the source sha256 is updated. So with this change, when digest is updated, before creating the new DV, we simply delete the erroneous DV if necessary.
Fixes #
Also includes some DataImportCron tests improvements and cleanup
```release-note
Delete erroneous DataVolumes on DataImportCron source digest update
```

Delete erroneous DataVolume on DataImportCron desired digest update

---

tests/import_proxy_test.go

We pause/resume the MCP on OpenShift clusters to not have to go through node reboots.
This is quite expensive AfterEach test, especially because of https://bugzilla.redhat.com/show_bug.cgi?id=2005694.
Let's have whatever runs the tests be responsible for this and preconfigure in setup/teardown scripts instead.
Fixes #
```release-note
NONE
```

Remove MCP pause/resume W/A from test code

---

hack/gen-swagger-doc/deploy.sh

Release script for 1.38 still used old name. Updated.
Fixes #
```release-note
NONE
```

Correct branch name in release script

---

pkg/controller/datavolume-controller_test.go
pkg/storagecapabilities/storagecapabilities.go

When using contentType: archive during unpacking archives onto storage we always require a Filesystem mode PV since a tar file can only be extracted onto a filesystem. 
For ceph-rbd, RWX/Filesystem is not supported so if we choose to select a Filesystem mode with this storage class it must use RWO. This change adds missing configuration for StorageClass capabilities so the correct option can be selected. 
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=2054778
```release-note
BugFix: bz 2054778 -  PVC created with filesystem volume mode …
```

Bugfix for ceph rbd archive upload

---

pkg/importer/http-datasource.go
pkg/importer/s3-datasource.go
pkg/importer/s3-datasource_test.go

Signed-off-by: licheng <chengli@alauda.io>
fix ip:port endpoint is not valid in s3 importer
Fixes #2173
```release-note
fix ip:port endpoint not valid in s3 importer
```

fix<importer>: ip:port endpoint is not valid in s3 importer

---

api/openapi-spec/swagger.json
tools/openapi-spec-generator/definitions.go

Mostly for generating swagger.json consumed by kubevirt-ui
Fixes #
```release-note
Add DataImportCron and DataSource to openapi-spec
```

Add DataImportCron and DataSource to openapi-spec

---

pkg/controller/datavolume-controller.go
tests/datavolume_test.go

DataVolume controller will not create PVCs without a default storage class, and we'll get error and event:
`DataVolume.storage spec is missing accessMode and no storageClass to choose profile`
However, even after defining default SC, so far DV was not reconciled so it was stuck in this state.
Fixes #
```release-note
Automatically recover DV from unconfigured default storage class, once default is set
```

Reconcile DVs waiting for default SC

---

cluster-sync/sync.sh
manifests/templates/upgrade-testing-artifacts.yaml.in
tests/framework/framework.go

* Don't back out until we verify quota status is set following us POSTing it
Otherwise its possible that we attempt to create PVC when quota not yet applied:
```bash
persistentvolumeclaims \"test-pvc\" is forbidden: status unknown for quota: test-storage-quota, resources: persistentvolumeclaims,requests.storage
```
* Include namespace of upgrade testing manifests in yaml
More friendly towards testing us on a different environment than our CI
(won't use cluster-sync on OpenShift testing for example)
Fixes #
```release-note
NONE
```

Include namespace on upgrade test manifest/attempt to fix quota test

---

go.mod
go.sum
vendor/github.com/prometheus/client_golang/prometheus/promhttp/BUILD.bazel
vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
vendor/modules.txt

Meant to address a denial of service vulnerability CVE-2022-21698
https://github.com/prometheus/client_golang/security/advisories/GHSA-cg3q-j54f-5p7p
```release-note
Update github.com/prometheus/client_golang to v1.11.1 as it contains a security fix
```

Update github.com/prometheus/client_golang to v1.11.1

---

pkg/controller/smart-clone-controller.go
pkg/controller/smart-clone-controller_test.go
pkg/controller/transfer/pvc.go
pkg/controller/transfer/pvc_test.go

[BZ: 2057148](https://bugzilla.redhat.com/show_bug.cgi?id=2057148)
There were some pretty nasty synchronization issues between smart clone controller and object transfer controller.  I think this is how we got there:
1.  Smart Clone Controller (SCC) adds "clone of" annotation to tmp pvc
2. SCC errors deleting Volume Snapshot
3. Object Transfer Controller (OTC) deletes tmp PVC
4. SCC creates another tmp PVC
Steps 3 and 4 repeat forever or until we run out of storage/quota in the source namespace
To stop from happening:
1.  SCC deletes VolumeSnapshot before adding "clone of" annotation
2. OTC checks source PVC refers to appropriate PV
I think there is still a possibility that DataVolume controller …

tighten sync between smart clone and transfer controllers

---

go.mod
go.sum
vendor/github.com/prometheus/client_golang/prometheus/promhttp/BUILD.bazel
vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
vendor/modules.txt

Meant to address a denial of service vulnerability CVE-2022-21698
https://github.com/prometheus/client_golang/security/advisories/GHSA-cg3q-j54f-5p7p
Signed-off-by: Maya Rashish <mrashish@redhat.com>
Manual cherry-pick of #2213.
```release-note
Update github.com/prometheus/client_golang to v1.11.1 as it contains a security fix
```

Update github.com/prometheus/client_golang to v1.11.1 (#2213)

---

pkg/controller/datavolume-conditions.go
pkg/controller/datavolume-controller.go
tests/datavolume_test.go

Previously, when a DataVolume was Reconciled then CDI created PVC
regardless of prePopulated annotation.
There is a possibility that DataVolume and PVC pair is being
restored or moved from other cluster. When DataVolume is marked
as prePopulated, the CDI should not try to populate it.
Fixes #
```release-note
Handle prepopulated DV
```

Improve handling of prePopulated DV

---

manifests/templates/imageio.yaml.in

Sometimes we see that ticket is not there (thx awels), we might want to
try a few times before giving up.
With `&&` if the add-ticket command fails, the container will keep restarting.
Fixes #
```release-note
NONE
```

Retry adding ticket on imageio container startup

---

pkg/controller/storageprofile-controller.go
pkg/controller/storageprofile-controller_test.go

Manual backport of one of the commits in https://github.com/kubevirt/containerized-data-importer/pull/2027.
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=2057301
```release-note
BugFix: When a storage class is deleted, it will automatically delete the storage profile
```

[release-v1.38] Delete profile as a follow up to storage class getting deleted

---

pkg/controller/BUILD.bazel
pkg/controller/dataimportcron-controller_test.go

Saw a flaking test where events were saying that importer can't schedule
because cron PVCs are being deleted:
```bash
"involvedObject": {
"kind": "Pod",
"namespace": "cdi-e2e-tests-importer-x9wfd",
"name": "importer-datasource-test-90e064fca2f4",
"uid": "be238296-7adc-41dd-b465-fac45a6a13ab",
"apiVersion": "v1",
"resourceVersion": "1609529"
},
"reason": "FailedScheduling",
"message": "0/6 nodes are available: 6 persistentvolumeclaim \"datasource-test-90e064fca2f4\" is being deleted.",
```
But it looks like we are never going to clean up accidentally,
let's test it and keep looking for the actual reason for the failure.
Pretty cool that we'll have a way to intercept the calls in unit test with …

Add unit test to make sure we don't clean up dataimportcrons accidentally

---

pkg/controller/dataimportcron-controller.go

Watch UpdateFunc predicate is checking if ObjectNew has DataImportCron
label with value, while the request enqueue mapping function may refer
the old object before the label value was set, resulting it to pass a
reconcile.Request where Name is an empty string.
Fixes #
```release-note
NONE
```

Fix DataImportCron watch race

---

cmd/cdi-cloner/cloner_startup.sh

This file uses /bin/sh as its interpreter, but uses a Bash-specific
option (pipefail).  This works in Fedora because /bin/sh is a sym link
to /bin/bash, but it fails on distros where /bin/sh is not a sym link
to /bin/bash (e.g., Ubuntu 20, where /bin/sh is a sym link to
/bin/dash).
Signed-off-by: Jeff Squyres <jsquyres@cisco.com>
The commit message above says it all.
Per https://github.com/kubevirt/containerized-data-importer/blob/main/CONTRIBUTING.md, this seemed like a trivial bug fix, and therefore did not warrant filing a Github issue.
N/A
**Release …

cloner_startup.sh: "pipefail" requires bash

---

pkg/controller/datavolume-conditions.go
pkg/controller/datavolume-controller.go

This change only extracts the code branch that handles the clone. The main idea is to divide the reconcile loop into parts doing import, upload and clone. This makes code easier to read and understand. Additionally a small change to the check if pvc exists was done. There is no more a reduntant bool pvcExists, as it can be checkec with `pvc != nil`.
What is more important it makes it much easier to work on fixes like the one here: https://github.com/kubevirt/containerized-data-importer/pull/2227. 
Fixes #
There is no change in logic. Just the extraction of …

Extract the clone logic from main reconcile loop

---

cmd/cdi-cloner/BUILD.bazel
pkg/controller/BUILD.bazel
pkg/image/BUILD.bazel
pkg/importer/BUILD.bazel
pkg/operator/controller/BUILD.bazel
pkg/operator/resources/cluster/rbac.go
tests/rbac_test.go
tools/metricsdocs/BUILD.bazel

Add get/list/watch cluster RBAC to:
- cdiconfigs.cdi.kubevirt.io
- dataimportcrons.cdi.kubevirt.io
- datasources.cdi.kubevirt.io
- objecttransfers.cdi.kubevirt.io
- storageprofiles.cdi.kubevirt.io
Fixes #
```release-note
Expose all CDI CRDs to cluster-readers
```

Expose all CDI CRDs to cluster-readers

---

pkg/operator/resources/cluster/rbac.go
tests/rbac_test.go

Manual backport of #2245
Add get/list/watch cluster RBAC to:
- cdiconfigs.cdi.kubevirt.io
- dataimportcrons.cdi.kubevirt.io
- datasources.cdi.kubevirt.io
- objecttransfers.cdi.kubevirt.io
- storageprofiles.cdi.kubevirt.io
Fixes #
```release-note
Expose all CDI CRDs to cluster-readers
```

[release-v1.43] Expose all CDI CRDs to cluster-readers

---

pkg/apiserver/webhooks/dataimportcron-validate.go
pkg/apiserver/webhooks/datavolume-validate.go

Manual backport of #2240
Tighten DataImportCron & DataSource max name length as it's used for labeling and indexing which are limited to length 63, unlike DataVolume and other CR names which are limited to length 253.
Fixes #
```release-note
NONE
```

[release-v1.43] Tighten DataImportCron & DataSource max name length

---

pkg/controller/datavolume-controller.go
pkg/controller/datavolume-controller_test.go
tests/cloner_test.go
tests/datavolume_test.go

Correctly handling of the prepopulated volumes created with clone.
Problem: the controller sees "populated for", takes ownership of the PVC, but still gets to the ensureExtendedToken 
This bug has more details: https://bugzilla.redhat.com/show_bug.cgi?id=2070366
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=2070366
First version of the PR was meant to cover all edge cases. Now it only covers part of the clone and the rest can be done in following PR's, and is tracked with https://github.com/kubevirt/containerized-data-importer/issues/2250
**Release …

Bugfix - Correctly handle populated PVC 

---

README.md
automation/test.sh
cluster-sync/ephemeral_provider.sh
cluster-sync/external/provider.sh
hack/common-funcs.sh

CI is failing, it looks like gh releases/latest now redirects (302 HTTP).
Also seems like the go to is to use the gh API for this
Fixes #
```release-note
NONE
```

Change the way we fetch latest release from GitHub

---

BUILD.bazel
cmd/cdi-importer/BUILD.bazel

Doing this at build time means we don't need to run update-ca-trust
on every invocation of the importer pod, which also eliminates a bug
where the relevant certs were not produced if invoked as a data
import cron.
This only does it for cdi-importer.
The other use cases for update-ca-trust are test containers, which are of a lower importance.
They also require update-crypto-policies to be run - I can take a look at that.
Fixes [BZ #2079465](https://bugzilla.redhat.com/show_bug.cgi?id=2079465)
```release-note
Fix regression since switching to …
```

Run part of update-ca-trust at build time for importer_base

---

README.md
automation/test.sh
cluster-sync/ephemeral_provider.sh
cluster-sync/external/provider.sh
hack/common-funcs.sh

CI is failing, it looks like gh releases/latest now redirects (302 HTTP).
Also seems like the go to is to use the gh API for this
Fixes #
```release-note
NONE
```

[release-v1.34] Change the way we fetch latest release from GitHub (manual backport #2256)

---

README.md
automation/test.sh
cluster-sync/ephemeral_provider.sh
cluster-sync/external/provider.sh
hack/common-funcs.sh

CI is failing, it looks like gh releases/latest now redirects (302 HTTP).
Also seems like the go to is to use the gh API for this
Fixes #
```release-note
NONE
```

[release-v1.38] Change the way we fetch latest release from GitHub (manual backport #2256)

---

pkg/controller/clone-controller.go
pkg/controller/datavolume-controller.go
pkg/controller/datavolume-controller_test.go
pkg/controller/smart-clone-controller.go
pkg/controller/storageprofile-controller.go
pkg/controller/storageprofile-controller_test.go
pkg/controller/util.go
pkg/controller/util_test.go
pkg/monitoring/BUILD.bazel
pkg/storagecapabilities/BUILD.bazel
pkg/storagecapabilities/storagecapabilities.go
pkg/util/util.go

Assume there's a persistent volume that we can look up to infer the
correct values for volume mode and access modes.
Move storagecapabilities code into controller as a path of lower
resistance to using "resolveVolumeMode"
As a side-note, this was aiming to detect the storage configuration of [local storage operator](https://github.com/openshift/local-storage-operator).
Looking up the configmap of this operator felt like it might be a layering violation, so I looked for another way.
Looking up persistent volumes actually works for any no-provisioner storage class, which is even better!
```release-note
Detect storage capabilities for no-provisioner storage classes by looking up persistent volumes
```

Detect storage capabilities for no-provisioner storage classes

---

WORKSPACE
hack/build/config.sh

Update to new builder.
Fixes #2267
```release-note
Use builder with 1.17.10 golang
```

Use new builder with go 1.17.10

---

pkg/controller/datavolume-controller.go
pkg/controller/datavolume-controller_test.go
pkg/controller/storageprofile-controller.go
pkg/controller/storageprofile-controller_test.go
staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
tests/cloner_test.go
tests/rbac_test.go
tests/smartclone_test.go

Noticed the consts were strings instead of the right types this changes the type to the right type and modifies the usage to not have to cast to the right type all over the place.
Fixes #
```release-note
BugFix: Modified CDICloneStrategy strings to be correct type
```

Make CDI clone strategy strings correct types

---

pkg/controller/datavolume-controller.go
pkg/controller/datavolume-controller_test.go

In case the pvc got an actual size as the expected
size there wasn't an update of the pvc spec with the
actual user request size, which left the pvc spec with
a smaller size then the user requested(the data size).
This caused a discrepancy when trying to restore such pvc,
which restored a pvc with the small size instead of the user request
size.
Signed-off-by: Shelly Kagan <skagan@redhat.com>
Fixes #BZ2021354
```release-note
Fix smart clone not updating request size if already got the requested size so expansion is not required
```

Fix smart clone request size update

---

pkg/apis/core/v1beta1/types.go
pkg/controller/datavolume-controller.go
pkg/controller/datavolume-controller_test.go
tests/cloner_test.go
tests/rbac_test.go
tests/smartclone_test.go

Noticed the consts were strings instead of the right types
this changes the type to the right type and modifies the usage
to not have to cast to the right type all over the place.
Fixes #
```release-note
NONE
```

[release-v1.38] Make CDI clone strategy strings correct types (#2277)

---

pkg/controller/datavolume-controller.go
pkg/controller/datavolume-controller_test.go

fix for the fix in cherry-pick https://github.com/kubevirt/containerized-data-importer/pull/2283
```release-note
None
```

[release-v1.49] Fix smart clone request size update - fix update condition

---

pkg/controller/datavolume-controller.go
pkg/controller/datavolume-controller_test.go

This is a manual cherry-pick of https://github.com/kubevirt/containerized-data-importer/pull/2276
closing the automatic cherry pick: https://github.com/kubevirt/containerized-data-importer/pull/2281
```release-note
Fix smart clone not updating request size if already got the requested size so expansion is not required
```

[release-v1.43] Fix smart clone request size update

---

pkg/controller/datavolume-controller.go
pkg/controller/datavolume-controller_test.go

This is a fix in the condition for PR: https://github.com/kubevirt/containerized-data-importer/pull/2276
Fixes #
```release-note
NONE
```

Fix smart clone update request size condition

---

pkg/controller/dataimportcron-controller.go
pkg/controller/dataimportcron-controller_test.go
tools/cdi-source-update-poller/main.go

Also fixed `status.lastExecutionTimestamp` to be the last polling time as intended in the design, and not the last reconcile update time.
Fixes #
```release-note
NONE
```

Get rid of unnecessary DIC reconcile updates

---

tools/vddk-test/vddk-test-plugin.c

vddk-test is special, it creates a dynamic library that is
loaded by the importer for test suite runs.
When running tests on a cluster built with an importer built from a
different base image, e.g. when RedHat builds with a CentOS8
equivalent, we might be attempting to load libvddk-test-plugin.so on
the CentOS8 importer. This breaks, as it doesn't have newer symbols.
There's only one new glibc symbol used, for fstat. Let's use
the older glibc definition of fstat, __fxstat explicitly.
```release-note
Fix regression where the testsuite cannot be run if the importer image is built with an older base image (like centos 8)
```

Small shim so libvddk-test-plugin.so can run on older glibc

---

pkg/operator/controller/controller_test.go
pkg/operator/controller/prometheus.go

This PR adds a boolean label to each of CDI alerts, so that we can differentiate between alerts that are related to infrastructure, and alerts that are related to vmi. 
For more info, please see [#7796](https://github.com/kubevirt/kubevirt/pull/7796).
Signed-off-by: assafad [aadmi@redhat.com](mailto:aadmi@redhat.com)
```release-note
None
```

Add an infra label to each of CDI alerts

---

pkg/controller/BUILD.bazel
pkg/controller/dataimportcron-controller.go
pkg/controller/dataimportcron-controller_test.go

When CDI is being upgraded, the DataImportCron CronJobs are kept as is, and refer cdi-importer image of the previous version, rather than the current (upgraded) one.
Fixes #
```release-note
Update DataImportCron CronJob container image if needed due to upgrade
```

Update DataImportCron CronJob when needed

---

pkg/controller/BUILD.bazel
pkg/controller/dataimportcron-controller.go
pkg/controller/dataimportcron-controller_test.go

Manual backport of #2316
When CDI is being upgraded, the DataImportCron CronJobs are kept as is, and refer cdi-importer image of the previous version, rather than the current (upgraded) one.
Fixes #
```release-note
Update DataImportCron CronJob if needed due to upgrade
```

[release-v1.49] Update DataImportCron CronJob if needed

---

pkg/operator/controller/reconciler-hooks.go

Sometimes tls certs get recreated while CDI is deleting
Fixes #
```release-note
NONE
```

Don't manage certs if CDI being deleted

---

tests/upload_test.go

Fix functional tests using sync upload form path instead of the async one
Fixes #
```release-note
NONE
```

Fix functests using sync upload form path instead of async

---

pkg/controller/datavolume-controller.go
pkg/controller/smart-clone-controller.go
pkg/controller/smart-clone-controller_test.go
tests/cloner_test.go

1.  Make sure smart clone controller does not create PVCs if VolumeSnapshot deleted
2.  Make sure that ObjectTransfer cleanup occurs.
Fixes #2323
```release-note
NONE
```

fix issue #2323: Cross namespace smart clone not cleaning up

---

automation/test.sh
tests/framework/framework.go

Since GC if currently disabled by default in OpenShift, we keep it disabled in func tests by default, as we need test coverage when TTL is nil. We already override it for specific GC tests, and we will add a specific lane that enables it. 
Fixes #
```release-note
NONE
```

Disable DV garbage collection by default in func tests

---

pkg/image/nbdkit.go
pkg/importer/http-datasource.go
pkg/importer/http-datasource_test.go

Use http basic auth with nbdkit.  Currently encoding the user/password in the url and that is strongly discouraged and not universally compatible
Fixes #2338
```release-note
NONE
```

use basic auth in nbdkit

---

doc/datavolumes.md
hack/build/rpm-deps.sh
pkg/image/nbdkit.go
rpm/BUILD.bazel

Fixes nbdkit usage of VDDK library for import from VMware.
No bug, I just tried to do some VDDK imports using CDI main and noticed nbdkit failing, likely from the big CentOS update.
`/opt/vmware-vix-disklib-distrib/lib64/lib64/libvixDiskLib.so.7: cannot open shared object file: No such file or directory`
`libsqlite3.so.0: cannot open shared object file: No such file or directory`
I also added the cacheextents filter to nbdkit only for VDDK transfers, so far I have seen it knock several seconds off the transfer startup time when the importer is querying for disk extents. 
```release-note
NONE
```

Fix a few VDDK-related nbdkit issues.

---

pkg/operator/controller/controller_test.go
pkg/operator/controller/prometheus.go

Reverts [#2314](https://github.com/kubevirt/containerized-data-importer/pull/2314). The design is not yet agreed as a standard for all operators alerts, so this label won't be used for now.
Signed-off-by: assafad <aadmi@redhat.com>
```release-note
None
```

Revert infra_label for CDI alerts

---

doc/scratch-space.md
pkg/image/filefmt.go
pkg/image/nbdkit.go
pkg/importer/format-readers.go
pkg/importer/http-datasource.go
pkg/importer/http-datasource_test.go
pkg/importer/registry-datasource.go
tests/import_proxy_test.go

Nbdkit is not a good fit for gz because it downloads/unzips the file to tempdir.
It is also not a good fit for xz, as discussed in #2288.
Fixes #2288
https://bugzilla.redhat.com/show_bug.cgi?id=2089391
```release-note
NBDKit no longer used for .gz or .xz files
```

Don't use nbdkit for xz or gz

---

pkg/controller/clone-controller.go
pkg/controller/datavolume-controller.go
pkg/controller/datavolume-controller_test.go
pkg/controller/import-controller.go
pkg/controller/upload-controller.go
pkg/controller/util.go
pkg/controller/util_test.go
tests/cloner_test.go
tests/csiclone_test.go
tests/datavolume_test.go
tests/framework/framework.go
tests/import_test.go
tests/smartclone_test.go
tests/upload_test.go

**What this PR does / why we need it**: When pod creation fails, the error is usually logged without providing additional information to the user. This behavior is especially risky when the user lacks the permits to check the logs, making it unintuitive and almost impossible to find the source of the problem.
This PR aims to improve the error handling of the pod-creation process, so pertinent info about the failure is included in the pod's PVC/DV.
Fixes #
```release-note
Improve error handling when pod creation fails
```

Improve error handling when pod creation fails

---

go.mod
go.sum
vendor/github.com/emicklei/go-restful/BUILD.bazel
vendor/github.com/emicklei/go-restful/CHANGES.md
vendor/github.com/emicklei/go-restful/cors_filter.go
vendor/github.com/emicklei/go-restful/parameter.go
vendor/github.com/emicklei/go-restful/request.go
vendor/github.com/emicklei/go-restful/response.go
vendor/github.com/emicklei/go-restful/route.go
vendor/github.com/emicklei/go-restful/route_reader.go
vendor/github.com/emicklei/go-restful/web_service.go
vendor/modules.txt

The updated version fixes 'Authorization Bypass Through User-Controlled Key' vulnerability (CVE-2022-1996).
References:
https://github.com/emicklei/go-restful/issues/489
https://github.com/emicklei/go-restful/pull/503
Fixes #
```release-note
NONE
```

Update go-restful to 2.16.0

---

pkg/operator/controller/route.go

Signed-off-by: Oren Cohen <ocohen@redhat.com>
According to:
https://github.com/ComplianceAsCode/content/blob/master/applications/openshift/networking/routes_protected_by_tls/rule.yml
The `ocp4-moderate` profile of the compliance operator expects that all Routes on the cluster should have either `None` or `Redirect` setting under their `.spec.tls.insecureEdgeTerminationPolicy`.
We chose `Redirect`, to be aligned with all other default routes on an OCP cluster, and not to fail HTTP requests but redirect them to HTTPS requests.
This PR adds the expected field to the `cdi-uploadproxy` route deployed by CDI.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets …

Fix 'ocp4-moderate-routes-protected-by-tls' Compliance failure

---

pkg/controller/datavolume-controller.go
pkg/controller/upload-controller.go
pkg/controller/upload-controller_test.go
pkg/controller/util.go
tests/cloner_test.go

When a pod fails after the error handling added in https://github.com/kubevirt/containerized-data-importer/pull/2335, some annotations (running condition, pod phase...) are updated in the affected PVC to let other controllers know.
However, due to a lack of synchronization between some controllers, a race condition could happen where, if a pod is successfully created just after a pod fails in a different controller, the annotations set in the error handling would just be updated inappropriately.
This PR updates the upload controller so it checks for clone errors before updating the annotations.
The described race condition has been only replicable under particular conditions, namely, a cross-namespace clone where the source namespace doesn't have enough quota to create the source-clone …

Fix race condition in upload-controller to keep PVC annotations after a clone error

---

pkg/controller/datavolume-controller.go
tests/datavolume_test.go

This issue came up in testing backup/restore with Kasten k10.  Should queue DataVolumes referred to in "populatedFor" annotations.  Without this change, a "prePopulated" DV created before a "populatedFor" DV will be pending forever if the PVC is not owned by the DV.
Fixes #
```release-note
NONE
```

Queue DataVolumes referred to in "populatedFor" annotations

---

cmd/cdi-importer/importer.go
tests/BUILD.bazel
tools/cdi-containerimage-server/main.go

Don't rename it to `disk.img`, in order to support restricted security context where image uid:gid don't allow renaming it. E.g. DV/DIC with the following results image named `downloaded` with 107:107:
```
source:
registry:
pullMethod: node
url: docker://quay.io/kubevirt/cirros-container-disk-demo
```
Fixes #
```release-note
Use container image name in server as-is to support restricted security context
```

Use container image name in server as-is

---

pkg/importer/data-processor.go
tests/cloner_test.go

I noticed this when cloning block->file system to a slightly larger (1Gi -> 1.1Gi) DV.
Unclear whether this happens in some more scenarios, I'm surprised this problem wasn't reported by others.
Fixes #
```release-note
Fix failure to resize when the request image size is specified in milli- scale.
```

Fix failure to resize when the request image size is specified in milli- scale.

---

cmd/cdi-controller/BUILD.bazel
cmd/cdi-controller/controller.go
cmd/cdi-operator/BUILD.bazel
cmd/cdi-operator/operator.go
go.mod
pkg/controller/datavolume-controller.go
tests/cloner_test.go
tests/framework/framework.go

Currently, fancy clones (CSI/Smart clone) with WFFC storage classes will just hang in "progress" phases such as `SnapshotForSmartCloneInProgress` instead of WaitForFirstConsumer.
This change reports the correct status for those target DataVolumes.
Fixes https://github.com/kubevirt/kubevirt/issues/7927
The first commit is about all logging that's not V(1) being broken, unless I'm missing something
```release-note
Status reporting for CSI & Smart clones with WFFC storage
```

Status reporting for CSI & Smart clones with WFFC storage

---

api/openapi-spec/swagger.json
pkg/apis/core/v1beta1/openapi_generated.go
pkg/operator/resources/crds_generated.go
staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go

Making this new status field required in the JSON, breaks API backward compatibility, so omitempty is added.
Fixes #
```release-note
NONE
```

Add omitempty to DataSourceStatus.source

---

pkg/controller/datavolume-controller.go
pkg/controller/datavolume-controller_test.go
tests/BUILD.bazel
tests/cloner_test.go

In case our pvc is already populated no need to check for source PVC
unknown size etc.
**Missing tests**
Fixes #
This should fix bug: https://bugzilla.redhat.com/show_bug.cgi?id=2104479
```release-note
Fix clone datavolume with populated target PVC without source 
```

Check for pvc populated before doing any clone validations and actions

---

cmd/cdi-controller/BUILD.bazel
cmd/cdi-controller/controller.go
cmd/cdi-operator/BUILD.bazel
cmd/cdi-operator/operator.go
go.mod
pkg/controller/datavolume-controller.go
pkg/controller/datavolume-controller_test.go
tests/BUILD.bazel
tests/cloner_test.go
tests/framework/framework.go

Fixes #
```release-note
Status reporting for CSI & Smart clones with WFFC storage
Fix clone datavolume with populated target PVC without source
```

[release-v1.53] Manual backport of 2364, 2375

---

pkg/apiserver/webhooks/datavolume-mutate.go
pkg/apiserver/webhooks/datavolume-mutate_test.go

We fail to remove the finalizer because the mutating webhook validates source ns exists,
but source ns might not be around anymore, and that is absolutely fine if DV is marked for deletion.
The "offending" test case is `[test_id:4960]`.
Fixes #
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/2363/pull-containerized-data-importer-e2e-ceph-gc/1552213098473984000
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/ …

Fix flake where cross ns finalizer can't be removed

---

api/openapi-spec/swagger.json
doc/cdi-config.md
doc/datavolumes.md
pkg/apis/core/v1beta1/openapi_generated.go
pkg/operator/resources/crds_generated.go
staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go

Fixes #2311
```release-note
NONE
```

Add DV garbage collection doc

---

pkg/apiserver/webhooks/dataimportcron-validate.go
pkg/apiserver/webhooks/datavolume-validate.go
pkg/apiserver/webhooks/datavolume-validate_test.go
pkg/controller/datavolume-controller.go
pkg/controller/datavolume-controller_test.go
tests/BUILD.bazel
tests/cloner_test.go

This PR takes part of PR: https://github.com/kubevirt/containerized-data-importer/pull/2306
and PR: https://github.com/kubevirt/containerized-data-importer/pull/2375
to fix this issue with minimal changes.
In case the target pvc exists and populated we should allow the clone to complete successfully without doing anything
Fixes #
BZ #2109406
https://bugzilla.redhat.com/show_bug.cgi?id=2109406
```release-note
Fix for clone without source pvc but target pvc already populated
```

[release-v1.43] Manual fix for clone without source pvc but target pvc already populated

---

pkg/controller/datavolume-controller.go

When DV is garbage collected and PVC ContentType is not correctly set, there is no way to guess the PVC ContetType. In CDI we assume that if there is no content type it's a kubevirt disk, but is other cases (e.g. export) we cannot make that assumption.
Fixes #
```release-note
NONE
```

Always set a valid ContentType for created PVC

---

pkg/apiserver/webhooks/dataimportcron-validate.go
pkg/apiserver/webhooks/datavolume-validate.go
pkg/apiserver/webhooks/datavolume-validate_test.go
pkg/controller/datavolume-controller.go
pkg/controller/datavolume-controller_test.go
tests/BUILD.bazel
tests/cloner_test.go

This PR takes part of PR: https://github.com/kubevirt/containerized-data-importer/pull/2306
and PR: https://github.com/kubevirt/containerized-data-importer/pull/2375
to fix this issue with minimal changes.
In case the target pvc exists and populated we should allow the clone to complete successfully without doing anything
Fixes # BZ #2109407
https://bugzilla.redhat.com/show_bug.cgi?id=2109407
```release-note
Fix for clone without source pvc but target pvc already populated
```

[release-v1.49] Manual fix for clone without source pvc but target pvc already populated

---

pkg/apiserver/webhooks/dataimportcron-validate.go
pkg/apiserver/webhooks/datavolume-validate.go
pkg/apiserver/webhooks/datavolume-validate_test.go
pkg/controller/datavolume-controller.go
pkg/controller/datavolume-controller_test.go
tests/BUILD.bazel
tests/cloner_test.go

…vc but target pvc already populated (#2405)""
This reverts commit 4e203976683183d4fda4d7ad62fa2fc387c30772.
This PR is a redo -f #2405 because I mistakenly merged it before I should have
Fixes #
BZ #2109406
https://bugzilla.redhat.com/show_bug.cgi?id=2109406
```release-note
Fix for clone without source pvc but target pvc already populated
```

[release-v1.43] Redo 2405

---

hack/build/common.sh
hack/build/docker/builder/Dockerfile

To be merged after https://github.com/kubevirt/project-infra/pull/2301
This PR is intended so our CI can override the build command chosen and use buildah despite otherwise being docker-based at the moment.
This allows us to build arm64 builder images.
Once we change the default builder, we can call #2211 fixed.
```release-note
NONE
```

Make buildcmd choice a tunable

---

tests/framework/framework.go

Currently we'll back out on various errors instead of waiting for proper cleanup,
which results in flakiness. Let's try to give any error a decent chance to go away.
Was partly implemented already in https://github.com/kubevirt/containerized-data-importer/pull/2197.
Fixes #
Returning err (`return false, err`) in polling funcs results in backing out of them instead of retrying
```release-note
NONE
```

Don't back out until we verify quota applied/removed in tests

---

api/openapi-spec/swagger.json
doc/cdi-config.md
doc/datavolumes.md
pkg/apis/core/v1beta1/openapi_generated.go
pkg/apiserver/webhooks/BUILD.bazel
pkg/apiserver/webhooks/datavolume-mutate.go
pkg/apiserver/webhooks/datavolume-mutate_test.go
pkg/controller/datavolume-controller.go
pkg/operator/resources/crds_generated.go
staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
tests/BUILD.bazel
tests/cloner_test.go
tests/datavolume_test.go
tests/import_test.go
tests/operator_test.go
tests/upgrade_test.go
tests/upload_test.go
tests/utils/datavolume.go

It's time to enable DataVolume garbage collection by default.
Fixes #
On the next kubevirt-bot Bump kubevirtci PR (with bump-cdi), it will fail on all kubevirtci lanes with tests referring DVs, as the tests IsDataVolumeGC() looks at CDIConfig Spec.DataVolumeTTLSeconds and assumes default is disabled. This should be fixed there.
```release-note
Enable DataVolume garbage collection by default
```

Enable DataVolume garbage collection by default

---

automation/test.sh
cluster-sync/sync.sh
manifests/templates/upgrade-testing-artifacts-no-gc.yaml.in
manifests/templates/upgrade-testing-artifacts.yaml.in

Only deploy the upgrade test datavolumes on multi upgrade before upgrading to latest. Deploy a different set on upgrade from latest released to contents of PR. This set will have an annotation to not garbage collect the DVs. Also dump some extra information if the DVs do not become ready in time.
Fixes #
```release-note
NONE
```

Change how we deploy the upgrade testing DVs

---

README.md

The blank source is named blank, not none
```release-note
NONE
```

Fix the readme typo

---

hack/build/bazel-docker.sh

An issue appears when running the e2e CDI tests with podman[1].
The rsync container hits an error as the rsync daemon
fails to attach to the specified port. Adding a restart policy to
restart the container any time it stops allows the e2e lanes to run
successfully using podman. A similiar change was made in kubevirt/kubevirt[2].
This change is required to move the CDI repo to podman based CI[3].
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/2339/rehearsal-pull-containerized-data-importer-e2e-ceph/1572199015787794432#1:build-log.txt%3A918
[2] https://github.com/kubevirt/kubevirt/pull/8388
[3] https://github.com/kubevirt/project-infra/pull/2339
Fixes # …

Add restart policy for rsync container

---

pkg/operator/controller/controller_test.go
pkg/operator/resources/namespaced/cronjob.go

It seems we only need the cluster access which happens at `pkg/operator/resources/cluster/cronjob.go`
Fixes #
```release-note
NONE
```

Remove namespaced rbac for dataimportcron

---

doc/waitforfirstconsumer-storage-handling.md
manifests/templates/release/cdi-cr.yaml.in

Modified template that generates CDI cr to honor
wait for first consumer for the release manifest
Fixes #
```release-note
Enable HonorWaitForFirstConsumer by default on release manifest
```

Enable HonorWaitForFirstConsumer by default

---

pkg/controller/datavolume-controller.go
pkg/controller/datavolume-controller_test.go
tests/framework/framework.go

- Handle some storageClassName nils
- We'd expect the CSIDriver object to be there, otherwise ceph install might be struggling
Fixes #
```release-note
NONE
```

Address possible nils in dv controller, log CSIDrivers in tests

---

hack/build/bazel-docker.sh

Signed-off-by: Brian Carey <bcarey@redhat.com>
`bazel-docker.sh` is run numerous times during the large e2e jobs. Each
time the script is run a temporary rsync container is started. If one of
these rsync containers is not cleaned up correctly it can lead to rsync
daemon failuresi[1] when e2e jobs are run with podman.
`podman stop`[2] attempts to stop a container using `SIGTERM` if this fails
within the default 10 seconds a `SIGKILL` is used to forceably stop the
container. Previously the script was not waiting for the container to be
successfully stopped.
Also updating the wait before the `SIGKILL` to 1 second.
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/2446/pull-containerized-data-importer …

Wait for podman stop to successfully stop rsync container

---

pkg/controller/BUILD.bazel
pkg/controller/dataimportcron-controller.go
pkg/controller/dataimportcron-controller_test.go
pkg/controller/import-controller.go
pkg/importer/registry-datasource.go
tests/dataimportcron_test.go
tests/import_proxy_test.go
tests/operator_test.go
tests/utils/BUILD.bazel
tests/utils/dataimportcron.go
tools/cdi-source-update-poller/BUILD.bazel
tools/cdi-source-update-poller/main.go

Use proxy certificates when creating DataImportCron CronJobs, so the pods won't fail on certificate issues when proxy is configured. `cdi-source-update-poller` was also fixed to use the proxy certificates.
Fixes #
```release-note
Add DataImportCron CronJobs Proxy support
```

Add DataImportCron CronJobs Proxy support

---

doc/block_cri_ownership_config.md
doc/datavolumes.md

Document CRI config that allows non-root containers usage of block devices
Fixes #
```release-note
NONE
```

Document CRI config that allows non-root containers usage of block devices

---

pkg/operator/controller/controller_test.go
pkg/operator/controller/scc.go
tests/operator_test.go

We create our SCC with `priority: 10` (not sure why), which means that it might compete (or directly get picked up) by random pods whose service account is privileged enough to access all SCCs:
```bash
$ oc get pods -n openshift-cluster-storage-operator cluster-storage-operator-5648cb555d-zh76b  -o yaml| grep scc
openshift.io/scc: containerized-data-importer
```
Happens because it can physically do that
```bash
$ oc get clusterrolebinding cluster-storage-operator-role -o yaml | grep cluster-admin
name: cluster-admin
```
A nice readout about this in context of the openshift oauth pods:
https://access.redhat.com/solutions/4727461
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, …

Fix SCC priority so it doesn't get picked for random pods

---

pkg/controller/BUILD.bazel
pkg/controller/storageprofile-controller.go
pkg/controller/storageprofile-controller_test.go
pkg/storagecapabilities/storagecapabilities.go
vendor/github.com/prometheus/client_golang/prometheus/testutil/BUILD.bazel
vendor/github.com/prometheus/client_golang/prometheus/testutil/lint.go
vendor/github.com/prometheus/client_golang/prometheus/testutil/promlint/BUILD.bazel
vendor/github.com/prometheus/client_golang/prometheus/testutil/promlint/promlint.go
vendor/github.com/prometheus/client_golang/prometheus/testutil/testutil.go
vendor/modules.txt

Certain storage provisioners are known not to work with CDI.  The main example is provisioners that implement object storage (ie. buckets).  We don't want to populate the StorageProfile with ClaimPropertySets but there is also no need to raise an "incomplete" alert about such a StorageProfile.  The simplest approach is to simply not count these unsupported provisioners when setting the IncompleteProfileGauge.
Fixes #
```release-note
NONE
```

Suppress alerting for unsupported provisioners

---

hack/build/bazel-docker.sh

The quay registry credentials are no longer available when trying to push images using the podman based bootstrap[1]. This is due to the bootstrap image now symlinking .docker/config.json to containers/auth.json [2]. bazel-push expects the registry credentials to exist under .docker/config.json but the symlink is broken as the containers directory is not also mounted into the builder container.
This update mounts the container directory into the builder container so that the symlink can work again. This is required to run any prowjobs that publish images with the new bootstrap image. 
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-containerized-data-importer-push-nightly-ARM64/1594685597958541312 
[2] …

Update to include mount for containers dir in bazel-docker.sh

---

WORKSPACE
hack/build/docker/builder/Dockerfile

fixes https://github.com/kubevirt/containerized-data-importer/issues/2477
Update golang used to build release artifcats to latest 1.18.x
Fixes #2477 
```release-note
BugFix: update golang to 1.18.8
```

Update golang to 1.18.8

---

pkg/util/util.go

On external testing lanes using NFS static PVs, lots of failures show that we lose `chmod 660` when untarring.
Let's attempt to keep the permissions.
On CSI storage we probably get reasonable chmod&chown on spin up stage, but not on regular NFS:
https://kubernetes.io/blog/2020/12/14/kubernetes-release-1.20-fsgroupchangepolicy-fsgrouppolicy/#allow-csi-drivers-to-declare-support-for-fsgroup-based-permissions
Fixes #
```release-note
NONE
```

Preserve permissions on extract

---

pkg/controller/datavolume-controller.go
tests/datavolume_test.go

Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=2149669
Manual backport of #2373
```release-note
Fix DataVolume/PVC restore - don't require PVC initially owned by DataVolume
```

[release-1.49] Queue DataVolumes referred to in "populatedFor" PVC annotations

---

hack/build/config.sh

Fixes #
```release-note
BugFix: Use golang 1.18.8 for building binaries
```

Use new builder with GO 1.18.8

---

hack/build/bazel-docker.sh

Bazel build was generating error due to the way the comparison was. This fixes the problem.
Without this if you run make bazel-build it will generate an error on the comparison.
Fixes #
```release-note
NONE
```

Fix bazel build command

---

pkg/controller/datavolume-controller.go
tests/datavolume_test.go

Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=2149671
Manual backport of https://github.com/kubevirt/containerized-data-importer/pull/2373
```release-note
Fix DataVolume/PVC restore - don't require PVC initially owned by DataVolume
```

[release-1.43] Queue DataVolumes referred to in "populatedFor" PVC annotations

---

README.md
cluster-sync/clean.sh
cluster-sync/external/README.md
cluster-sync/sync.sh

The aim of this change is to make setting up a dev environment on external cluster easier, By doing mainly 2 things:
- Bazel push (CDI containers/e2e testing containers) expects external registry creds to be in the docker CRI default path.
This seems to be half-configurable on the bazel side, except for the [actual file name](https://github.com/bazelbuild/rules_docker/blob/64827560cbbe9359294b9a14e8ac417224f6fdd2/container/go/cmd/pusher/pusher.go#L192) (which differs for podman).
Now we prompt for the credentials and save them on the expected path.
- Deploy the e2e testing manifests on external provider as well
Not sure why not do that today? probably reason dates way back
**Which issue(s) this PR …

Make cluster-sync more friendly for external provider

---

tests/framework/framework.go

Just a little easier to find out which log files correspond to a specific test failure this way
Fixes #
```release-note
NONE
```

Log specific test failure artifact path for easier debugging

---

pkg/storagecapabilities/storagecapabilities.go

Storage classes using the provisioner 'cinder.csi.openstack.org' appear in kubernetes clusters that have been created on OpenStack infrastructure.  Although some cinder volume types can support multi-attach (ReadWriteMany), we cannot be certain of this.  Therefore, we suggest a claimPropertSet of RWO,Block.
See https://github.com/kubernetes/website/pull/34219 for more context.
Fixes #
```release-note
NONE
```

Add cinder to known provisioners

---

pkg/controller/datavolume/clone-controller.go
tests/cloner_test.go

**What this PR does / why we need it**: 
This PR changes the owner of the size-detection pod (from the target DataVolume to the source PVC) to avoid errors when cloning across namespaces.
Fixes # https://bugzilla.redhat.com/show_bug.cgi?id=2152537
**Special notes for your reviewer**: 
```release-note
[bug-fix] Fix bug in size-detection mechanism when cloning across namespaces
```

Fix bug in size-detection mechanism when cloning across namespaces

---

pkg/operator/controller/controller_test.go
pkg/operator/controller/prometheus.go
tests/operator_test.go

Signed-off-by: assafad <aadmi@redhat.com>
This PR adds to each of CDI alerts a label named `operator_health_impact`, which indicates how the alerts impact the operator health. This will enable us filtering alerts based on their impact on the operator health, and to later have an operator health metric, which will tell the user what is the aggregated operator health.
This label gets one of the following values:
- `critical` indicates that the alert fires due to an issue that impacts the operator's functionality badly, and an action must be taken immediately in order to solve it.
-  `warning` indicates that the alert fires due to an issue that soon might impact the operator's functionality badly, and the user should be warned in order to solve the …

Add `operator_health_impact` label to CDI alerts

---

pkg/controller/common/util.go
pkg/controller/dataimportcron-controller.go
pkg/controller/dataimportcron-controller_test.go
pkg/controller/datavolume/controller.go
pkg/controller/datavolume/import-controller_test.go
pkg/controller/util.go

/cc @mhenriks
Following on from 4fbcb2d509645752850baa33da05ad67a7897262 a requirement has arisen to expose the default instance type metadata as labels to allow callers such as the UI to have simple server side filtering of these resources.
This PR switches over to passing these labels down from a `DataImportCron` into the `DataVolume`, `DataSource` and `PVC` controlled by the import.
The unreleased feature implementation within KubeVirt has now switched to labels as of https://github.com/kubevirt/kubevirt/pull/9040.
Fixes #
```release-note …
```

dataimportcron: Pass KubeVirt instance type labels to DataVolume and DataSource

---

pkg/controller/dataimportcron-controller.go
pkg/controller/dataimportcron-controller_test.go

Keeping the last completed or failed job and pod for a while is needed for both functional tests and debugging. Since the ttl was not set, the jobs were not automatically deleted.
Fixes [bz 2158608](https://bugzilla.redhat.com/show_bug.cgi?id=2158608)
```release-note
BugFix: Failed/successful pods associated with DataImportCron Jobs need to be cleaned up
```

Set ttl for completed cron jobs

---

pkg/controller/dataimportcron-controller.go
pkg/controller/dataimportcron-controller_test.go
pkg/controller/datavolume/controller.go
tests/dataimportcron_test.go
tests/datasource_test.go

The PVC labelling is used for `DataImportCron` controller old import `PVCs` garbage collection, keeping only the last `importsToKeep` (3 by default) imported `PVCs` per `DIC`.
Fixes [bz 2156928](https://bugzilla.redhat.com/show_bug.cgi?id=2156928)
```release-note
BugFix: PVC garbage collection in DataImportCron fails when CDI DV garbage collection is disabled
```

Update succeeded DIC PVC labels also when no DV GC

---

pkg/controller/clone-controller.go
pkg/controller/clone-controller_test.go

#2410 had an unintended consequence of mounting block PVCs read/write when they were a clone source
This PR undoes that
Fixes #
```release-note
Mount block PVCs readonly when source of clone operation
```

mount block pvc readonly

---

pkg/controller/datavolume/clone-controller.go
pkg/controller/datavolume/clone-controller_test.go
pkg/controller/datavolume/controller.go
pkg/controller/datavolume/garbagecollect.go
pkg/controller/datavolume/import-controller.go
pkg/controller/datavolume/import-controller_test.go
pkg/controller/datavolume/upload-controller.go
pkg/controller/datavolume/util.go

Follow the model of controllers in kubevirt where `sync()` does the "work" of the controller (creating other resources, etc). The `sync()` for import/upload is just creating the pvc resource. For clones, it is more complicated depending on clone type and if cross-namespace or not. After `sync()`, `updateStatus()` is called, even if `sync()` returns an error. `updateStatus()` is conscious of all steps performed in `sync()` and updates the status of the reconciled resource based on what can be observed. The only k8s resource it creates/updates is the `DataVolume`. This split is especially nice for resources with status subresource enabled, which should be one of the ultimate goals of DV controllers …

Align DV controllers with kubevirt sync/updateStatus model

---

pkg/controller/dataimportcron-controller.go
pkg/controller/dataimportcron-controller_test.go
tests/dataimportcron_test.go
tests/datasource_test.go

Manual backport of #2539
The PVC labelling is used for `DataImportCron` controller old import `PVCs` garbage collection, keeping only the last `importsToKeep` (3 by default) imported `PVCs` per `DIC`.
Fixes [bz 2156928](https://bugzilla.redhat.com/show_bug.cgi?id=2156928)
```release-note
BugFix: PVC garbage collection in DataImportCron fails when CDI DV garbage collection is disabled
```

[release-v1.55] Update succeeded DIC PVC labels also when no DV GC

---

pkg/apiserver/webhooks/datavolume-validate.go
pkg/apiserver/webhooks/datavolume-validate_test.go

This PR improves the DataVolume admission webhook so it nil-checks the PVC field in DataSources before dereferencing it.
Fixes # https://github.com/kubevirt/containerized-data-importer/issues/2535
```release-note
NONE
```

Fix bug in DataVolume admission webhook when DataSource has a nil PVC field

---

pkg/operator/controller/callbacks.go
pkg/operator/controller/controller.go
tests/operator_test.go

Ensure Prometheus resources exist also when cdi-deployment is not ready. This is needed because currently when cdi deployment fails (e.g. wrong NodeSelector) the Prometheus resources are not created, so CDINotReady will not be fired although CDI is not ready.
Fixes bz 2145146
```release-note
Ensure Prometheus resources exist for CDINotReady
```

Ensure Prometheus resources exist for CDINotReady

---

pkg/storagecapabilities/storagecapabilities.go

Fixes # https://bugzilla.redhat.com/show_bug.cgi?id=2158521
```release-note
BugFix: storage profile missing defaults for LVMS "topolvm.io" provisioner and for cinder provisioner
```

[release-v1.55] Add topolvm.io and cinder to known provisioners (#2530) (#2507)

---

pkg/apiserver/webhooks/datavolume-validate.go
pkg/apiserver/webhooks/datavolume-validate_test.go

This change avoids the following valid `DataSource` and `DataVolume`
definitions from causing a panic within the `DataVolume` validation
webhook by ensuring `dv.spec.source` is at least provided before
checking `dv.spec.source.pvc`:
```
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataSource
metadata:
name: cirros
spec:
source:
pvc:
name: cirros
namespace: default
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
name: cirros-dv
spec:
storage: {}
sourceRef:
kind: DataSource
name: cirros
namespace: default
```
Fixes #2502 …

DataVolume: Check that DataVolumeSource is provided before checking DataVolumeSourcePVC

---

pkg/controller/datavolume/controller-base.go

Right now if cleanup finishes successfully we just keep going on in the reconcile loop, 
even though deletion timestamp is set.
Results in nil ptr when doing cross ns smart clone:
```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1543ec1]
goroutine 1133 [running]:
kubevirt.io/containerized-data-importer/pkg/controller/datavolume.(*PvcCloneReconciler).selectCloneStrategy(0xc001a69768, 0xc0050e65a0, 0x0)
/remote-source/app/pkg/controller/datavolume/pvc-clone-controller.go:489 +0x81
```
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the …

Don't go further in reconcile loop after cleanup finished successfully

---

cmd/cdi-controller/controller.go
pkg/operator/controller/callbacks.go
pkg/operator/controller/controller.go
tests/operator_test.go

Manual backport of #2546 and #2557
Ensure Prometheus resources exist also when cdi-deployment is not ready. This is needed because currently when cdi deployment fails (e.g. wrong NodeSelector) the Prometheus resources are not created, so CDINotReady will not be fired although CDI is not ready.
Also fix StorageProfile incomplete metric test flakiness.
Fixes bz 2145146
```release-note
Ensure Prometheus resources exist for CDINotReady
```

[release-v1.55] Ensure Prometheus resources exist for CDINotReady

---

pkg/controller/datavolume/controller-base.go

Now that we update status in the end of a loop regardless of err,
it is important that we have the PVC in place for that.
Otherwise, if we fail at cleanup/prepare, syncRes.pvc is nil,
and we get false status updates like the following:
```bash
NAMESPACE   NAME               PHASE                             PROGRESS   RESTARTS
default     cloned-target-dv   Succeeded                         N/A                   23s
default     cloned-target-dv   Pending                           N/A                   23s
default     cloned-target-dv   Pending                           N/A                   23s
default     cloned-target-dv   Pending                           N/A                   23s
NAMESPACE …
```

Grab target PVC early on to avoid false status updates

---

pkg/controller/dataimportcron-controller.go
tests/dataimportcron_test.go

DataImportCron PVC garbage collection is LRU-based, so it's broken when PVCs are not timestamped.
Fixes bz #2165793
```release-note
Fix DataImportCron PVC timestamping
```

Fix DataImportCron PVC timestamping

---

hack/build/bazel-docker.sh
hack/build/common.sh

The current implementation only works for rootless podman check if rootless works first, if not use root podman
Fixes #
```release-note
NONE
```

Allow root podman for cluster-sync

---

pkg/controller/dataimportcron-controller.go
tests/dataimportcron_test.go

Manual backport of #2566. Also fixed a short timeout (10sec) which may cause flakiness.
DataImportCron PVC garbage collection is LRU-based, so it's broken when PVCs are not timestamped.
Fixes bz #2165793
```release-note
Fix DataImportCron PVC timestamping
```

[release-v1.55] Fix DataImportCron PVC timestamping

---

pkg/operator/controller/callbacks.go
pkg/operator/controller/controller.go
pkg/operator/controller/cruft.go
pkg/operator/controller/reconciler-hooks.go
tests/operator_test.go

This is the last CRD of CDI that still has v1alpha1 version.
We left it because it appears in release YAMLs, and we want update through applying YAMLs to just work.
Technical debt left over from #2407.
We needed more complicated work to watch the CDI CRD.
This CRD is created by the release YAMLs and not owned by the controller, therefore we need custom watch code for it that isn't from controller-lifecycle-operator-sdk.
I've checked early in reconcile whether this is a CDI CRD and not a CDI CR - not sure how to integrate it with controller-lifecycle-operator-sdk. Not sure whether needing Update() is normal.
Perhaps it's not too bad as we already know we'll remove this code in under a year (once we've released a …

Remove v1alpha1 version from CDI CRD

---

hack/build/common.sh

Our CRI detection cod was looking for podman first then docker. If you have both installed it would find podman first and set that. Even if you preferred docker (need to properly configure podman).
This switches the check to look for docker first then podman. If you want to use podman you can set the KUBEVIRTCI_RUNTIME env variable to podman
Fixes #
```release-note
NONE
```

Check docker first

---

cmd/cdi-importer/importer.go

This PR slightly modifies cdi-importer behavior so, when an import of any kind fails, the termination message in the pod only contains the error and not the stack trace.
This makes the events in PVCs and DataVolumes cleaner and easier to understand for users. The stack trace will still appear on the pod logs for debugging purposes.
Fixes # https://bugzilla.redhat.com/show_bug.cgi?id=2143716
```release-note
NONE
```

Remove stack trace from PVC and DataVolume events in case of import error

---

pkg/controller/datavolume/pvc-clone-controller.go
tests/datasource_test.go

DV with sourceRef DataSource pointing to non-existing PVC, is to be reconciled when the PVC is created and populated and the DataSource is Ready.
Fixes bz #2156517
```release-note
BugFix: VM with DataSource referring a non-existing PVC won't start after DataSource fix
```

Watch DataSources in DV clone controller

---

tests/operator_test.go

Get rid of the assumption that CR name is cdi, so tests won't be skippd when CR name is not cdi.
Fixes #
```release-note
NONE
```

Fix operator_test CDI CR Gets

---

pkg/controller/datavolume-controller.go
tests/datasource_test.go

Manual backport of #2571.
DV with sourceRef DataSource pointing to non-existing PVC, is to be reconciled when the PVC is created and populated and the DataSource is Ready.
Fixes bz #2165083
```release-note
BugFix: VM with DataSource referring a non-existing PVC won't start after DataSource fix
```

[release-v1.55] Watch DataSources in DV controller

---

doc/clone-from-volumesnapshot-source.md
doc/datavolumes.md
doc/efficient-cloning.md

Fixes #
```release-note
NONE
```

Add clone from VolumeSnapshot docs

---

hack/build/docker/builder/Dockerfile

Update the builder to golang 1.19.5 so we can update the build to use go 1.19
Fixes #
```release-note
Enhancement: builds now use golang 1.19.5
```

Update builder image to use golang 1.19.5

---

pkg/image/nbdkit.go
pkg/image/qemu.go
pkg/image/qemu_test.go

Reduce the number of pod retries when there are failures in downloading images. Instead retry
inside the pod. This implements suggestion from https://github.com/kubevirt/containerized-data-importer/issues/2561.
Also fix some linter warnings in same package.
Fixes #
```release-note
BugFix: use retry filter in inline streaming conversion with qcow2 http endpoints.
```

Apply retry filter to ndkit conversions

---

cmd/cdi-importer/importer.go

This pull request enables deactivating preallocation on block imports.
Due to what seemed like a [bug](https://github.com/kubevirt/containerized-data-importer/issues/1980#issuecomment-940238434) in qemu-img, we started forcing preallocation on block imports as an arbitrary way to skip that specific error. This behavior was introduced in https://github.com/kubevirt/containerized-data-importer/pull/2001. After several updates in qemu and related dependencies, the bug is no longer reproducible. 
After some research, we've found a [bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1872633)  that seems to solve an oddly similar case. The described bugs and fixes are:
-  A race in the kernel solved in commit …

Stop forcing preallocation on block imports

---

tests/operator_test.go

Seems CDI delete&recreate in tests before 7965 makes things a little slower
(Prometheus resources recreating may add it's own overhead, for example)
Let's wait a little longer.
Fixes #
```release-note
NONE
```

Another attempt to stabilize storage profile metric tests

---

pkg/controller/common/BUILD.bazel
pkg/controller/common/util.go
pkg/controller/dataimportcron-controller.go
pkg/controller/datavolume/pvc-clone-controller.go
pkg/controller/datavolume/snapshot-clone-controller.go
pkg/controller/import-controller.go
pkg/controller/import-controller_test.go
pkg/controller/upload-controller.go
pkg/controller/util.go
tests/cloner_test.go
tests/datasource_test.go
tests/datavolume_test.go
tests/import_test.go
tests/utils/BUILD.bazel
tests/utils/common.go
tests/utils/dataimportcron.go
tests/utils/datavolume.go

`bind.immediate` is an annotation that says we should bypass "real" WFFC behavior by simply starting our worker pods
wherever.
Prior to this, we were only honoring it for import/upload/host-assisted clone, but we should definitely do the same for
opt out of other fancy clone methods when it is specified:
- CSI clone
- Smart clone
- Clone from snapshot source
Fixes #
```release-note
BugFix: Respect bind.immediate annotation on fancy clones by falling back to host assisted
```

Respect bind.immediate annotation by not attempting fancy clones

---

pkg/storagecapabilities/storagecapabilities.go

The manila provisioner is essentially an NFS provisioner so we can provide the appropriate defaults for that. The defaults are RWX and Filesystem
Fixes #
```release-note
Enhancement: Open Stack manila now has a complete storage profile
```

Add manila csi to list of known provisioners

---

tests/cloner_test.go
tests/utils/datavolume.go

We have started testing LVMS (LVM Storage) recently on OKD installs:
https://github.com/openshift/lvm-operator
and identified some issues with how our testing suite plays along with that.
Fixes #
This will need backports so we can test on older releases with WFFC snapshot capable storage
```release-note
NONE
```

Testing suite adjustments for testing on WFFC snapshot capable storage

---

hack/build/bazel-docker.sh

Added SYS_CHROOT cap to rsync in builder script to prevent rsync "chroot failed" errors when building. Removed unused environment variable from rsync call as well
Fixes #
```release-note
NONE
```

Add SYS_CHROOT cap to rsync in build

---

pkg/image/filefmt.go
pkg/image/validate.go
pkg/importer/BUILD.bazel
pkg/importer/format-readers.go
tests/datavolume_test.go
tests/utils/BUILD.bazel
tests/utils/datavolume.go
tests/utils/fileConversion.go
tools/cdi-func-test-file-host-init/main.go

add http zstd reader for cdi
```release-note
Enhancement: Support for zstd added
```

add http zstd reader for cdi

---

hack/build/docker/builder/Dockerfile

Needed to get the fix for
https://github.com/bazelbuild/rules_go/pull/3231 If we want to bump to 1.19
kubevirt already at this version with 1.19
https://github.com/kubevirt/kubevirt/commit/9e15eca23c8554a13f19cd71ff8f82052d73c35a
Fixes #
```release-note
NONE
```

Bump bazel version in builder

---

tests/framework/nodeplacement.go
tests/operator_test.go

Until recently, operator_test destructive tests were executed in CDI CI k8s lane, but they were rarely executed D/S on OpenShift cluster. To allow executing it D/S on a regular basis, as a follow-up to #2577, we fix a few test issues encountered on OpenShift cluster:
-Fix affinity to use a worker node instead of the first one
-Check only the storage-labeled pods, instead of all the pods in cdi namespace
-Check CDI UninstallStrategy to decide wheter to delete DVs beore deleting CDI
Fixes #
```release-note
NONE
```

Adapt operator_test to cover OpenShift

---

pkg/controller/datavolume/controller-base.go
pkg/controller/datavolume/import-controller_test.go
pkg/controller/datavolume/smart-clone-controller.go
pkg/controller/datavolume/smart-clone-controller_test.go
pkg/controller/datavolume/snapshot-clone-controller.go
tests/cloner_test.go
tests/datavolume_test.go

Pass all the DataVolume labels to its created PVC. It's fixing the current behavior which passes only specific labels, aligning it with DV annotations passing to the PVC.
Fixes #2533 
```release-note
Pass all the DataVolume labels to its created PVC
```

Pass DV labels to PVC

---

hack/build/bazel-docker.sh

In order to avoid
```
error obtaining VCS status: exit status 128
Use -buildvcs=false to disable VCS stamping.
```
we add `git config --global --add safe.directory /root/go/src/kubevirt.io/containerized-data-importer` in the builder container to tell git that the ownership not matching is not a problem and the rsync can work normally
buildvcs adds version information to the built binaries, would be lost if we directly add `-buildvcs=false` to the build command.
Fixes #
```release-note
NONE
```

Update git config to mark rsync directory as safe

---

pkg/storagecapabilities/storagecapabilities.go

This PR adds entry on nfs-subdir-external-provisioner to CapabilitiesByProvisionerKey mapping so storageprofile created for this profile during cdi initialization will have accessModes and volumeMode correctly set.
```release-note
NONE
```

Add nfs-subdir-external-provisioner to CapabilitiesByProvisionerKey

---

tests/cloner_test.go
tests/csiclone_test.go
tests/datavolume_test.go
tests/external_population_test.go
tests/framework/pvc.go
tests/import_test.go
tests/smartclone_test.go

Previous PR does not make our test suite completely WFFC-friendly,
as it turns out more follow-ups were needed.
This continues the work in https://github.com/kubevirt/containerized-data-importer/pull/2610
Fixes #
```release-note
NONE
```

Follow up for WFFC test suite adjustments

---

pkg/controller/dataimportcron-controller.go
pkg/controller/dataimportcron-controller_test.go
tests/import_proxy_test.go
tests/utils/dataimportcron.go

If the storage class binding mode is WaitForFirstConsumer, and the annotation was not explicitly added to the DIC DV template, the created DV will get stuck in WFFC phase.
Fixes [bz #2166394](https://bugzilla.redhat.com/show_bug.cgi?id=2166394)
```release-note
Annotate DataImportCron-created DataVolumes for immediate binding, so they will not get stuck in WaitForFirstConsumer phase.
```

Annotate DIC-created DV for immediate binding

---

pkg/controller/dataimportcron-controller.go
pkg/controller/dataimportcron-controller_test.go
tests/import_proxy_test.go
tests/utils/dataimportcron.go

Manual backport of #2650
If the storage class binding mode is WaitForFirstConsumer, and the annotation was not explicitly added to the DIC DV template, the created DV will get stuck in WFFC phase.
Fixes [bz #2180801](https://bugzilla.redhat.com/show_bug.cgi?id=2180801)
```release-note
Annotate DataImportCron-created DataVolumes for immediate binding, so they will not get stuck in WaitForFirstConsumer phase.
```

[release-v1.55] Annotate DIC-created DV for immediate binding

---

pkg/importer/data-processor.go
pkg/importer/data-processor_test.go
pkg/importer/gcs-datasource.go
pkg/importer/http-datasource.go
pkg/importer/imageio-datasource.go
pkg/importer/registry-datasource.go
pkg/importer/s3-datasource.go
pkg/importer/upload-datasource.go
pkg/importer/util.go
pkg/importer/util_test.go
pkg/importer/vddk-datasource_amd64.go
pkg/importer/vddk-datasource_test.go
pkg/uploadserver/uploadserver.go
pkg/util/util.go
tests/framework/pvc.go

Rather than cleaning up everything on target/scratch PVCs, only delete what we may have created
Fixes #2635
```release-note
More targeted cleanup of target/scratch pvcs (only delete what we may have created)
```

more targeted cleanup of target/scratch pvcs

---

pkg/controller/datavolume/smart-clone-controller.go
pkg/controller/datavolume/smart-clone-controller_test.go

Some CSI provisioner when making volume snapshots don't set the restore size because it is hard to figure out the value or the actual stored size on the storage is 0 (Copy on Write). There was a strict check in place in case of CSI drivers not allowing a restore to a size other than the restoreSize of the snapshot.
This makes the check more lenient that when we encounter a 0 size restoreSize, we can assume we can use the requested size value in the pvc
Fixes #2679 
```release-note
BugFix: Fixed failing snapshot clone if CSI driver set 0 to …
```

Allow restoreSize to be 0, and use request size if 0

---

tests/cloner_test.go

Also, make some changes to the test to catch
https://github.com/kubevirt/containerized-data-importer/issues/2550
Fixes #
```release-note
NONE
```

Ensure host assisted concurrent clone test runs on all storages

---

tests/framework/framework.go
tests/transfer_test.go

Apparently the correct way to understand if a quota is "ready" is to look at the keys in the `used` field.
Hopefully this eliminates error like these on test runs
```bash
persistentvolumeclaims "test-pvc" is forbidden: status unknown for quota: test-storage-quota
```
Sources:
https://github.com/kubernetes/apiserver/blob/a32e26b98aff9e1dfdf0fb8d0d49d9b56287b875/pkg/admission/plugin/resourcequota/controller.go#L473-L475 https://github.com/kubernetes/kubernetes/blob/a24aef65108bb3549c9ad31f51aab8097c640447/test/e2e/apimachinery/resource_quota.go#L2152
Fixes # …

Correctly wait for resourcequota "ready" state in tests

---

pkg/image/nbdkit.go

Currently importing QCoW files over HTTP takes an extremely long time. This is due to `qemu-img convert` launching a lot of small reads against the `nbd-kit curl` plugin. To speed this up, add the readahead filter since QEMU roughly reads through the input disk images in order, so a majority of reads are pre-fetch hits.
On my machine this reduces a Ubuntu cloud image import from 90 minutes to 1 minute.
Fixes #2358 
```release-note
Add readahead filter when importing files over HTTP.
```

Add the readahead filter to curl requests

---

pkg/controller/clone-controller.go
tests/cloner_test.go

Pods using the same PVC are scheduled on different nodes. We expect them to be scheduled on the same K8S node but they don't and thus cannot be attached to the PersistentVolume. The solution is to set [pod affinity](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity).
Fixes #2576
```release-note
Set pod affinity for host assisted clone source pods, in order to schedule them on the same K8S node.
```

Set pod affinity for host assisted clone

---

pkg/apiserver/webhooks/dataimportcron-validate.go
pkg/apiserver/webhooks/datavolume-validate.go
pkg/apiserver/webhooks/datavolume-validate_test.go
pkg/controller/common/util.go
pkg/controller/datavolume/conditions.go
pkg/controller/datavolume/conditions_test.go
pkg/controller/datavolume/controller-base.go
pkg/controller/datavolume/pvc-clone-controller.go
pkg/controller/datavolume/pvc-clone-controller_test.go
pkg/controller/datavolume/smart-clone-controller.go
pkg/controller/datavolume/util.go
tests/csiclone_test.go
tests/datasource_test.go
tests/datavolume_test.go

When `PVC` is created with `storageClassName` and the `SC` is not found, k8s looks for `PV` with the `storageClassName` for satisfying this claim. In this case k8s supports also a blank (“”, not the nil default one) `storageClassName`. To support this behavior we added:
- `DV` controller support for this flow (for both “” and non-existing `SC`)
- Condition update and event when `StorageSpec` `PVC` rendering errors and `PVC` is not created (e.g. missing both `AccessModes` and `SC`/`PV`)
- `PVC` is created even if a satisfying `SC`/`PV` doesn't exist if `spec.pvc/storage` `AccessModes` is set (otherwise k8s PVC validation fails). PVC/DV phase  will be `Pending` until a satisfying `SC`/`PV` is found
- `PV` watch to reconcile `DVs` waiting for the `PV` …

Create PVC if possible even if the StorageClass is missing

---

pkg/controller/populators/populator-base.go
pkg/controller/populators/util.go
tests/import_test.go

This Pull Request fixes a race condition in a test that checks for static binding in the import populator. We shouldn't worry about the PVC' being created in that case since the target PVC will be bound immediately afterward.
```release-note
NONE
```

Fix import populator static binding test

---

pkg/controller/BUILD.bazel
pkg/controller/dataimportcron-controller.go
pkg/controller/dataimportcron-controller_test.go
pkg/controller/import-controller_test.go

Fixes bz#2196429
```release-note
Propagate CDI workload NodePlacement to DataImportCron CronJob and initial Job
```

Propagate CDI workload NodePlacement to DIC CronJob and initial Job

---

pkg/storagecapabilities/storagecapabilities.go

Add StorageProfile default ClaimPropertySets (StorageCapabilities) for the provisioner.
```release-note
Add Hitachi to known provisioners
```

Add Hitachi to known provisioners

---

pkg/storagecapabilities/storagecapabilities.go

Manual backport of #2710 #2717
bz #2208838
Add StorageProfile default ClaimPropertySets (StorageCapabilities) for the provisioners.
```release-note
Add Dell EMC PowerFlex/Scale/Max/Store, HPE and Hitachi to known provisioners
```

[release-v1.56] Add Dell EMC, HPE & Hitachi to known provisioners

---

pkg/controller/datavolume/pvc-clone-controller.go

In Hypershift we use PVC smart cloning for the root volume disks for OCP worker nodes. When a cluster first comes online, we create a DV which imports the rhcos disk image into a pvc, and we immediately in parallel also create VMs which want to clone that source PVC as soon as it is available.
An issue we're encountering is that the smart clone can take up to around 16 minutes to even get triggered in our scenario due to the re-queue hitting the max rate limit backoff in the clone controller.
For example, all the DVs which have succeeded in the output below are sources to be cloned by the DVs stuck in `CloneScheduled`. The source PVCs have been imported, and there's nothing blocking the controller from starting the clone, but the controller simply isn't reconciling the DVs anymore due to …

Fixes issue with smart clone hanging while waiting for initial import

---

hack/README.md
pkg/common/common.go
pkg/controller/dataimportcron-controller.go
pkg/controller/import-controller.go
pkg/operator/controller/controller_test.go
pkg/operator/resources/namespaced/BUILD.bazel
pkg/operator/resources/namespaced/controller.go
tests/BUILD.bazel
tests/dataimportcron_test.go
tests/framework/pvc.go
tools/cdi-source-update-poller/main.go

- Remove obsoleted insecure registries ConfigMap
- Cleanup functests and add external poller test
- Remove irrelevant poller digest update check
Fixes #
```release-note
Remove obsoleted insecure registries ConfigMap
```

DataImportCron dusty stuff cleanups

---

staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/utils.go

kubevirt/kubevirt has to be aware of/handle this phase before it can consume a version of CDI that uses populators internally.  By "handle", I mean that it is okay start the VM if a DV is in this state.
Fixes #
```release-note
NONE
```

add PendingPopulation DataVolume phase

---

pkg/apiserver/webhooks/dataimportcron-validate.go
pkg/apiserver/webhooks/dataimportcron-validate_test.go
pkg/controller/dataimportcron-controller.go
pkg/controller/dataimportcron-controller_test.go
tests/dataimportcron_test.go

We would like to allow the user to disable the automatic updates in DataImportCron. In this situation, when a new update is released the user will have to trigger the import manually.
Fixes #2689 
```release-note
Enable external trigger import in DataImportCron. When the `schedule` property is an empty string (""), import the latest update.
```

Enable external trigger in DataImportCron

---

pkg/controller/datavolume/pvc-clone-controller.go
pkg/controller/datavolume/pvc-clone-controller_test.go

expand upon #2721
Need to replace requeue bool with requeue duration in a couple other spots.  Also linter did not like the name of duration variable
Fixes #
This will all be replaced soon (hopefully) with populatior integration, but adding this anyway just in case we don't make code freeze
```release-note
NONE
```

expand upon #2721

---

hack/build/build-go.sh

The current script always passes the static ldflag to the compiler which will result in a static binary. We would like to be able to build dynamic libraries instead.
cdi-containerimage-server has to be static because we are copying it into the context of a container disk container which is most likely based on a scratch container and has no libraries for us to use.
Fixes #
```release-note
NONE
```

Allow dynamic linked build for non bazel build

---

api/openapi-spec/swagger.json
doc/cdi-config.md
doc/datavolumes.md
pkg/apis/core/v1beta1/openapi_generated.go
pkg/apiserver/webhooks/datavolume-mutate.go
pkg/controller/common/util.go
pkg/controller/dataimportcron-controller.go
pkg/operator/resources/crds_generated.go
staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
tests/cloner_test.go
tests/dataimportcron_test.go
tests/utils/datavolume.go

`DataVolume` garbage collection is a nice feature, but unfortunately it violates fundamental principle of Kubernetes. CR should not be auto-deleted when it completes its role (`Job` with `TTLSecondsAfterFinished` is an exception), and once CR was created we can assume it is there until explicitly deleted. In addition, CR should keep idempotency, so the same CR manifest can be applied multiple times, as long as it is a valid update (e.g. `DataVolume` validation webhook does not allow updating the spec).
When GC is enabled, some systems (e.g GitOps / ArgoCD) may require a workaround (DV annotation `deleteAfterCompletion = false`) to prevent GC and function correctly.
On the next kubevirt-bot Bump kubevirtci PR (with bump-cdi), it will fail on all …

Disable DV GC by default

---

hack/build/build-go.sh

The current script always passes the static ldflag to the compiler which will result in a static binary. We would like to be able to build dynamic libraries instead.
cdi-containerimage-server has to be static because we are copying it into the context of a container disk container which is most likely based on a scratch container and has no libraries for us to use.
Fixes #
```release-note
NONE
```

[release-v1.43] Allow dynamic linked build for non bazel build (#2753)

---

pkg/controller/datavolume/controller-base.go
pkg/controller/datavolume/util.go
tests/cloner_test.go
tests/dataimportcron_test.go
tests/utils/datavolume.go

We were hitting a panic because we're passing the original DV object to renderPvcSpec (source is nil)
instead of the mutated DV which has sourceRef converted (source not nil)
Fixes #
```release-note
BugFix: sizeless clones cause panic for sourceRef data volumes
```

Fix sizeless clones for sourceRef data volumes

---

pkg/controller/common/util.go
pkg/controller/dataimportcron-controller.go
pkg/controller/dataimportcron-controller_test.go
pkg/controller/datavolume/import-controller_test.go

The label `kubevirt.io/dynamic-credentials-support` specifies if the OS supports dynamic SSH key change on a running VM.
This PR passes the label from DataImportCron to DataVolume and DataSource.
More information at: https://issues.redhat.com/browse/CNV-28212
```release-note
None
```

dataimportcron: Pass dynamic credential support label

---

doc/os-image-poll-and-update.md

Fixes #
```release-note
NONE
```

Add DataImportCron snapshot sources docs

---

OWNERS_ALIASES

I am nominating Alex to be a CDI approver.  He has been making meaningful contributions since 2020.  Here are some recent highlights:
[Allow snapshots as format for DataImportCron created sources](https://github.com/kubevirt/containerized-data-importer/pull/2700)
[Move pkg/clone/auth to API lib and introduce single dv.Authorize()](https://github.com/kubevirt/containerized-data-importer/pull/2636)
[Clone from VolumeSnapshot source](https://github.com/kubevirt/containerized-data-importer/pull/2522)
He is also an active reviewer with almost 100 reviews under his belt:  https://github.com/kubevirt/containerized-data-importer/pulls?q=is%3Apr+reviewed-by%3Aakalenyu
Alex is truly a pleasure to work with.  He is always respectful, endlessly curious, and …

akalenyu nomination to approver

---

tests/operator_test.go

From some debugging, it looks like the priority class tests don't properly wait for
redeploy to finish and thus the following tests get an initial wrong slice of cdiPods
(Consider 2 cdi-uploadproxy pods, one of which is terminating, making way to the new one)
Fixes #
```release-note
NONE
```

Fix test failure - missing pod following recreate of CDI

---

pkg/controller/dataimportcron-controller.go
tests/dataimportcron_test.go

We see a spike in failures for this test:
https://search.ci.kubevirt.io/?search=8033&maxAge=336h&context=1&type=bug%2Bissue%2Bjunit&name=containerized-data-importer&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
CDI controller crashes because of a nil pointer
Fixes #
```release-note
NONE
```

Handle nil ptr in dataimportcron controller

---

pkg/storagecapabilities/storagecapabilities.go

Add StorageProfile default ClaimPropertySets (StorageCapabilities) for the provisioners.
```release-note
Add IBM CSI to known provisioners
```

Add IBM CSI to known provisioners

---

pkg/storagecapabilities/storagecapabilities.go

Add StorageProfile default ClaimPropertySets (StorageCapabilities) for the provisioner.
```release-note
Add AWS EFS CSI to known provisioners
```

Add AWS EFS CSI to known provisioners

---

tests/upload_test.go

Partial backport of https://github.com/kubevirt/containerized-data-importer/pull/2677;
Skip TLS config test since our `reencrypt` route will terminate the client connection at the router (and lose tls context)
Fixes #
```release-note
NONE
```

[release-v1.55] Backport 'Skip tls config upload test when openshift route is used'

---

tests/cloner_test.go

One of these tests flakes, and the error is hard to debug because Gomega will yell about
`Unexpected non-nil/non-zero argument at index 0`
Instead of showing the error
Apparently, this is intended:
https://github.com/onsi/gomega/pull/480/files#diff-e696deff1a5be83ad03053b772926cb325cede3b33222fa76c2bb1fcf2efd809R186-R190
Fixes #
```release-note
NONE
```

Revert some gomega error checks that produce confusing output

---

Makefile
go.mod
go.sum
hack/ci/prom_metric_linter.sh
tools/prom-metrics-collector/metrics_collector.go
tools/prom-metrics-collector/metrics_json_generator.go
vendor/github.com/kubevirt/monitoring/pkg/metrics/parser/metrics_parser.go
vendor/modules.txt

This linter will lint the metrics in docs/metrics.md file. In order to run the linter:
1.make lint-metrics
jira-ticket: https://issues.redhat.com/browse/CNV-29824
**Reviewer notes**:
Linter output:
```
clone_progress: counter metrics should have "_total" or "_timestamp_seconds" suffix
clone_progress: name need to start with 'kubevirt_'
kubevirt_cdi_incomplete_storageprofiles_total: non-counter metrics should not have "_total" suffix
kubevirt_cdi_operator_up_total: non-counter metrics should not have "_total" suffix
make: *** [Makefile:213: lint-metrics] Error 1
```
note that we ignore all current errors until the metrics names will be fixed in:https://github.com/kubevirt/containerized-data-importer/issues/2773
```
Add a metrics …
```

[CI] Add metrics name linter

---

pkg/storagecapabilities/storagecapabilities.go

Manual backport of #2762 #2771
Add StorageProfile default ClaimPropertySets (StorageCapabilities) for the provisioners.
Fixes bz 2220844
```release-note
Add IBM and AWS EFS CSI to known provisioners
```

[release-v1.56] Add IBM and AWS EFS CSI to known provisioners

---

pkg/storagecapabilities/storagecapabilities.go

Manual backport of #2762 #2771
Add StorageProfile default ClaimPropertySets (StorageCapabilities) for the provisioners.
Fixes bz 2220843
```release-note
Add IBM and AWS EFS CSI to known provisioners
```

[release-v1.55] Add IBM and AWS EFS CSI to known provisioners

---

pkg/controller/clone-controller.go
pkg/controller/common/util.go
pkg/controller/datavolume/clone-controller-base.go
pkg/controller/datavolume/controller-base.go
pkg/controller/datavolume/import-controller.go
pkg/controller/datavolume/import-controller_test.go
pkg/controller/datavolume/pvc-clone-controller_test.go
pkg/controller/datavolume/snapshot-clone-controller_test.go
pkg/controller/datavolume/upload-controller.go
pkg/controller/import-controller.go
pkg/controller/populators/populator-base.go
pkg/controller/populators/util.go
pkg/controller/upload-controller.go
pkg/controller/util.go
tests/clone-populator_test.go
tests/cloner_test.go
tests/datasource_test.go
tests/datavolume_test.go
tests/import_test.go
tests/upload_test.go

In case of using PVC with populators if the PVC has this annotation we prevent from waiting for it to be schedueled and we proceed with the process.
When using datavolumes with populators in case the dv has the annotation it will be passed to the PVC. we prevent from being in pendingPopulation in case the created pvc has the annotaion.
Plus when having honorWaitForFirstConsumer feature gate disabled we will put on the target PVC the immediateBinding annotation. Now we allow to use populators when having the annotation the the feature gate disabled.
Fixes # …

Allow ImmediateBinding annotation when using populators

---

doc/cdi-populators.md

Fixes #
The documentation already takes into account all the code that should get in for the cdi populators i.e the integration with the datavolume clone and populators #2750 , supporting Immediate Binding annotation #2765 , supporting VDDK and Imagio sources #2767 
```release-note
Add documentation for cdi populators
```

Add documentation for cdi populators

---

pkg/controller/dataimportcron-controller.go

Fixed in #2696 in main/release-v1.57 as part of the linter error fixes.
PVC lastUseTime annotation was sometimes not updated so DataImportCron PVC garbage collection was misbehaving and deleting the latest imported PVC, which was then re-imported again until the update succeeded.
The issue was introduced by #2540 and found due to flaky [test_id:7406].
Fixes bz #2222011
```release-note
Fix DataImportCron PVC garbage collection by correctly updating PVC lastUseTime annotation
```

[release-v1.55] Fix DataImportCron PVC update error check

---

pkg/controller/dataimportcron-controller.go

Fixed in #2696 in main/release-v1.57 as part of the linter error fixes.
PVC lastUseTime annotation was sometimes not updated so DataImportCron PVC garbage collection was misbehaving and deleting the latest imported PVC, which was then re-imported again until the update succeeded.
The issue was introduced by #2539 and found due to flaky [test_id:7406].
Fixes bz #2221913
```release-note
Fix DataImportCron PVC garbage collection by correctly updating PVC lastUseTime annotation
```

[release-v1.56] Fix DataImportCron PVC update error check

---

tests/datavolume_test.go

This may be the reason for the flakes we're seeing: https://search.ci.kubevirt.io/?search=9924&maxAge=336h&context=1&type=bug%2Bissue%2Bjunit&name=containerized-data-importer&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
With GC on we want to delete the DV (PVC won't cut it)
We may have more cases like this one scattered around, so let's keep an eye
Not sure how populators DVs handle that situation but we see that the test PV is simply gone from artifacts
Fixes #
```release-note
NONE
```

Follow up for GC=on in some tests

---

pkg/controller/dataimportcron-controller.go
pkg/controller/dataimportcron-controller_test.go

Regression introduced in #2700
Fixes bz #2226982
```release-note
Fix DataImportCron ImageStream polling per schedule
```

Fix DIC returned reconcile.Result for ImageStream

---

pkg/controller/populators/import-populator.go
pkg/controller/populators/import-populator_test.go
pkg/controller/populators/populator-base.go
tests/import_test.go
tests/upload_test.go

This Pull Request fixes a race condition in CDI populators so we fetch the PVC' even if the population source doesn't exist.
This new behavior allows us to correctly delete the PVC' once the population has succeeded. We assume that, if PVC' already exists, all the requirements for population have already been met, so we don't need to check them all again.
Fixes # https://bugzilla.redhat.com/show_bug.cgi?id=2223361
```release-note
Bugfix: Clean up PVC' when population succeeds even if the population source doesn't exist
```

Fix race condition in populators so we clean up PVC' after population succeeds

---

pkg/controller/populators/import-populator_test.go
pkg/controller/populators/populator-base.go
tests/import_test.go
tests/upload_test.go

Manual cherry-pick of https://github.com/kubevirt/containerized-data-importer/pull/2821 since we can't backport the multi-stage import code. 
```release-note
Bugfix: Clean up PVC' when population succeeds even if the population source doesn't exist
```

[release-v1.57] Manual cherrypick of #2821

---

hack/gen-swagger-doc/gen-swagger-docs.sh

Our api-reference broke due to `quantity`'s description containing code-block formatting that's not rendered properly: https://kubevirt.io/cdi-api-reference/main/definitions.html.
Kubevirt [skips code-block formatting ](https://github.com/kubevirt/kubevirt/blob/main/hack/gen-swagger-doc/gen-swagger-docs.sh#L72)to avoid this behavior, so we should do the same.
Fixes # https://github.com/kubevirt/containerized-data-importer/issues/2827
```release-note
NONE
```

Skip code-block formatting from api-reference

---

pkg/controller/common/util.go
pkg/controller/dataimportcron-controller.go
pkg/controller/dataimportcron-controller_test.go
pkg/controller/datavolume/controller-base.go
pkg/controller/datavolume/import-controller_test.go
pkg/controller/datavolume/util.go
pkg/controller/datavolume/util_test.go
tests/datavolume_test.go

https://github.com/kubevirt/containerized-data-importer/commit/f229aeb5ff69b3d89b537b39f547eb6c2bc3d5de started to pass default instance type labels from
DataImportCrons to DataVolumes and DataVolumes to any associated
destination DataSources or PVCs. As documented in issue https://github.com/kubevirt/containerized-data-importer/issues/2782 this does
not however pass these labels from the initial source of a DataVolume to
either the DataVolume or the destination DataSources or PVCs
This change corrects this by updating DataVolumes when reconciled,
adding any labels found on PVC or DataSource sources. These labels will
then be passed on to the destination PVC or DataSources by the existing
functionality highlighted above.
Note that if any default …

dataVolume: Add default instance type labels from source

---

BUILD.bazel
pkg/common/common.go
pkg/controller/import-controller.go
pkg/controller/import-controller_test.go
pkg/image/qemu.go
pkg/importer/http-datasource.go
tests/BUILD.bazel
tests/import_test.go
tests/utils/datavolume.go

When importing via node container runtime, we always have the image available in the container filesystem,
so there should be no reason to use scratch space.
This manifests itself in the form of a bug where we loop over
```bash
E0813 13:32:38.443088       1 data-processor.go:251] scratch space required and none found
E0813 13:32:38.443102       1 importer.go:181] scratch space required and none found
```
On registry node pull imports when images are not raw. Testing for this is added in this PR
Fixes #
https://issues.redhat.com/browse/CNV-32010
**Release …

Don't use scratch space for registry node pull imports

---

pkg/operator/controller/cruft.go

Seen in practice when deleting CDI CR in issue #2852
Manual backport of #2856 for release-v1.56, resolving a conflict manually.
```release-note
Avoid crash of cdi-operator when CDI CR is deleted
```

[release-v1.56] Tolerate GetActiveCDI returning nil, nil

---

pkg/controller/clone-controller.go
pkg/controller/config-controller.go
pkg/controller/dataimportcron-controller.go
pkg/controller/datasource-controller.go
pkg/controller/datavolume/controller-base.go
pkg/controller/datavolume/external-population-controller.go
pkg/controller/datavolume/import-controller.go
pkg/controller/datavolume/pvc-clone-controller.go
pkg/controller/datavolume/snapshot-clone-controller.go
pkg/controller/datavolume/upload-controller.go
pkg/controller/import-controller.go
pkg/controller/populators/clone-populator.go
pkg/controller/populators/import-populator.go
pkg/controller/populators/upload-populator.go
pkg/controller/storageprofile-controller.go
pkg/controller/transfer/controller.go
pkg/controller/upload-controller.go
pkg/operator/controller/controller.go
pkg/operator/resources/namespaced/apiserver.go
pkg/operator/resources/namespaced/controller.go
pkg/operator/resources/namespaced/uploadproxy.go
pkg/operator/resources/operator/operator.go

This commit ups the cpu request for for all our installed compopents (cdi-deployment, cdi-apiserver, cdi-uploadproxy, cdi-operator) for 10m (1% of a core) to 100m (10% of a core).
Also make all controllers handle 3 concurrent requests.
Without this change, it is pretty easy to create a large number of concurrent clone operations and get token timeout errors. Upping resource requests and concurrency addresses the issue in a very direct way.
I experimented with a bunch of other approaches including creating a controller just for refreshing tokens but this is the lowest touch (codewise) and most highly effective solution.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the …

increase controller concurrency and cpu requests

---

pkg/controller/datavolume/controller-base.go
pkg/controller/datavolume/import-controller_test.go
pkg/controller/datavolume/util.go
tests/datavolume_test.go

Manual backport of #2860
Currently there is a repeating reconcile error due to exponential backoff: `DataVolume.storage spec is missing accessMode and no storageClass to choose profile`, however the error is not needed as we already have `StorageClass` watch for this case, e.g. when the `DataVolume` is using the default `StorageClass` but no default `StorageClass` is configured yet.
Note the SC Watch() was mistakenly looking for DVs with unset phase (like in the main/1.57 branch), but should look for Pending DVs instead.
Fixes bz #2232347 …

[release-v1.56] Do not fail DV reconcile if storage class is not found

---

pkg/controller/datavolume/controller-base.go
pkg/controller/datavolume/import-controller_test.go
pkg/controller/datavolume/util.go
tests/datavolume_test.go

Currently there is a repeating reconcile error due to exponential backoff: `DataVolume.storage spec is missing accessMode and no storageClass to choose profile`, however the error is not needed as we already have `StorageClass` watch for this case, e.g. when the `DataVolume` is using the default `StorageClass` but no default `StorageClass` is configured yet.
Fixes #
```release-note
Remove DataVolume reconcile error when storage class is not found yet
```

Do not fail DV reconcile if storage class is not found

---

pkg/controller/common/util.go
pkg/controller/datavolume/controller-base.go
pkg/controller/populators/clone-populator_test.go
pkg/controller/populators/import-populator_test.go
pkg/controller/populators/populator-base.go
pkg/controller/populators/upload-populator_test.go
tests/datavolume_test.go

Priority class was not being passed to the pvc prime from the PVC and thus was not being added to the importer pod populating the pvc prime. There is a list of allowed annotations that can be passed and the priority class annotation was not in it. This commit adds the annotation to the allowed list.
Cleaned up unneeded log argument to a function related to passing the annotations.
Fixes [RHBZ: 2231839](https://bugzilla.redhat.com/show_bug.cgi?id=2231839)
```release-note
BugFix: Fix not passing priority class to populator pod
```

Ensure priority class is assigned to pod populating pvc prime

---

pkg/controller/common/util.go
pkg/controller/datavolume/controller-base.go
pkg/controller/populators/clone-populator_test.go
pkg/controller/populators/import-populator_test.go
pkg/controller/populators/populator-base.go
pkg/controller/populators/upload-populator_test.go
tests/datavolume_test.go

Manual backport of #2864 
Fixes #
```release-note
NONE
```

[release-v1.57] Ensure priority class is assigned to pod populating pvc prime

---

hack/build/docker/builder/Dockerfile

Update the version used in the builder to golang 1.19.12
Fixes #
```release-note
NONE
```

[release-v1.56] Update golang builder for 1.56 to golang 1.19.12

---

hack/build/docker/builder/Dockerfile

Apparently still didn't have the right path for go install even though locally it had installed for me. This time verified with [documentation](https://onsi.github.io/ginkgo/MIGRATING_TO_V2) I have the right path.
Fixes #
```release-note
NONE
```

Fix gingko v2 path in builder

---

api/openapi-spec/swagger.json
pkg/apis/core/v1beta1/openapi_generated.go
pkg/controller/dataimportcron-controller.go
pkg/controller/dataimportcron-controller_test.go
pkg/operator/resources/crds_generated.go
staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/zz_generated.deepcopy.go

We support changing the storage class on DataImportCrons, so let's be more friendly
toward that and not attempt to make a snapshot of the old storage class PVC.
Also, make it more visible in which format the image gets stored (snap/pvc).
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=2227066
```release-note
BugFix: Avoid creating snapshot of old storage class DataImportCron PVCs
```

Avoid creating snapshot of old storage class DataImportCron PVCs

---

cmd/cdi-controller/BUILD.bazel
cmd/cdi-controller/controller.go
pkg/operator/controller/prometheus.go
pkg/operator/resources/cluster/apiserver.go
pkg/operator/resources/cluster/controller.go
pkg/operator/resources/namespaced/BUILD.bazel
pkg/operator/resources/namespaced/apiserver.go
pkg/operator/resources/namespaced/controller.go
pkg/operator/resources/namespaced/factory.go
pkg/operator/resources/namespaced/prometheus.go
pkg/operator/resources/namespaced/uploadproxy.go
pkg/operator/resources/operator/operator.go

There are some permissions that are logically not needed, and some others where we can just reduce the verb set.
Trying to follow https://kubernetes.io/docs/concepts/security/rbac-good-practices/
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=2183659
```release-note
BugFix: Global permissions [*] seen across CDI components
```

Audit RBAC, avoid global (*) permissions

---

pkg/controller/common/util.go
pkg/controller/dataimportcron-controller.go
pkg/controller/dataimportcron-controller_test.go
pkg/controller/datavolume/controller-base.go
pkg/controller/datavolume/import-controller_test.go
pkg/controller/datavolume/util.go
pkg/controller/datavolume/util_test.go
tests/datavolume_test.go

f229aeb started to pass default instance type labels from DataImportCrons to DataVolumes and DataVolumes to any associated destination DataSources or PVCs. As documented in issue #2782 this does not however pass these labels from the initial source of a DataVolume to either the DataVolume or the destination DataSources or PVCs
This change corrects this by updating DataVolumes when reconciled, adding any labels found on PVC or DataSource sources. These labels will then be passed on to the destination PVC or DataSources by the existing functionality highlighted above.
Note that if any default instance type labels already exist on the DataVolume then the process is skipped as it is assumed these are provided either directly by the user or via a …

[release-v1.57] dataVolume: Add default instance type labels from source (#2787)

---

pkg/storagecapabilities/storagecapabilities.go

Add preferred `ReadWriteMany, Filesystem` capability to the `pxd.portworx.com` provisioner.
Fixes #
```release-note
Add preferred ReadWriteMany, Filesystem capability to the pxd.portworx.com provisioner
```

Fix Portworx CSI storage capabilities

---

api/openapi-spec/swagger.json
doc/debug.md
pkg/apis/core/v1beta1/openapi_generated.go
pkg/operator/controller/controller_test.go
pkg/operator/controller/cr-manager.go
pkg/operator/resources/crds_generated.go
staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/zz_generated.deepcopy.go

This PR aims to make the debugging process of CDI easier, allowing changes in log verbosity from the CDI config.
It adds a new field in the `CDIConfig` API to allow specifying a different log verbosity level to re-initialize all loggers. Changes in this field will restart all CDI components to initialize all loggers with the new value.
**Special notes for your reviewer**:  
The new API looks like this:
```yaml
apiVersion: cdi.kubevirt.io/v1beta1
Kind: CDI
spec:
config:
logVerbosity: 4
```
I opted for a simpler API compared to [the one used in kubevirt](https://github.com/kubevirt/kubevirt/pull/4672/files#diff-5469726ef6ef072d9258db4593eb8811363099d9181a4e5dbd119af7b2b1414eR1614). I think the kubevirt API is overkill for CDI, but I can always change …

Allow modifying log verbosity in CDI

---

pkg/storagecapabilities/storagecapabilities.go

For some reason it was marked RWO instead of RWX.
Fixes #
```release-note
BugFix: Trident ontap-san supports RWX not just RWO
```

Update ontap-san to be RWX

---

pkg/controller/dataimportcron-controller.go
pkg/controller/dataimportcron-controller_test.go
tests/dataimportcron_test.go

In the old versions, the garbage collection label was added to DV only. In the new version, the GC looks for this label in the PVC, so it does not find it and does not delete the DV's from the old versions
Fixes bz #2209969
```release-note
Delete old version DV's with DIC garbage collector
```

Delete old version DVs with DIC GC

---

pkg/controller/datavolume/controller-base.go
pkg/controller/datavolume/import-controller_test.go
pkg/controller/populators/clone-populator.go
pkg/controller/populators/import-populator_test.go
pkg/controller/populators/populator-base.go
pkg/controller/populators/util.go
tests/cloner_test.go
tests/import_proxy_test.go
tests/import_test.go

When introducing populators we somehow assumed that having the PVC' in Lost phase would interfere with the behavior of `AnnPodRetainAfterCompletion`. After better testing, the pod state and logs are still fetchable after completion.
This PR allows the usage of this annotation.
Fixes #
**Special notes for your reviewer**: Let's see how tests behave.
```release-note
Allow the usage of AnnPodRetainAfterCompletion with populators
```

Allow the usage of AnnPodRetainAfterCompletion with populators

---

pkg/controller/storageprofile-controller.go
pkg/storagecapabilities/storagecapabilities.go

Manual backport of #2789
Fix Portworx provisioner cababilities and add preferred `ReadWriteMany, Filesystem`.
Fixes bz #2237872
```release-note
Fix Portworx provisioner cababilities and add preferred ReadWriteMany, Filesystem.
```

[release-v1.56] Fix Portworx CSI storage capabilities

---

tests/webhook_test.go

This is a partial backport of https://github.com/kubevirt/containerized-data-importer/pull/2636
This tends to flake often, especially in OpenShift testing.
Fixes #
```release-note
NONE
```

[release-v1.56] Fix flakes when using gigabytes intead of gibibytes

---

pkg/controller/storageprofile-controller.go
pkg/storagecapabilities/storagecapabilities.go

Manual backport of #2789, plus minor alignments with main branch.
Fix Portworx provisioner capabilities and add preferred `ReadWriteMany, Filesystem`.
Fixes bz #2237873
```release-note
Fix Portworx provisioner capabilities and add preferred ReadWriteMany, Filesystem.
```

[release-v1.55] Fix Portworx CSI storage capabilities

---

pkg/controller/datavolume/clone-controller-base.go
pkg/controller/datavolume/controller-base.go
pkg/controller/datavolume/pvc-clone-controller.go
pkg/controller/datavolume/snapshot-clone-controller.go
tests/dataimportcron_test.go

We slap on the clone-without-source index key regardless of source.PVC/source.Snapshot so
it was possible for a DV with PVC source to get queued for the snapshot controller
(and hence the nil ptr).
The test addition demonstrates a real use case where this would happen.
Fixes #
https://issues.redhat.com/browse/CNV-33002
```release-note
BugFix: nil ptr in snapshot clone controller
```

Fix possible nil ptr in snapshot/pvc clone controllers

---

pkg/controller/dataimportcron-controller.go
pkg/controller/dataimportcron-controller_test.go
tests/dataimportcron_test.go

Manual backport of #2749
In older CDI versions, the DIC garbage collection label was added to DV only. In newer versions, DIC GC looks for the label in the PVC, so it does not find it and does not delete the old version DVs.
Fixes bz #2209969
```release-note
Delete old version DVs with DIC garbage collector
```

[release-v1.57] Delete old version DVs with DIC GC

---

cmd/cdi-importer/importer.go
pkg/controller/import-controller.go
pkg/controller/import-controller_test.go
tests/import_test.go

We currently don't support the wffc override for blank block disks,
while there may be some use cases where that is desired.
Fixes #2915 
```release-note
BugFix: wffc override not respected for blank block disks
```

Respect wffc override for blank block disks

---

hack/build/docker/builder/Dockerfile

Update the builder to golang 1.20.10 and bazel 5.4.0
Fixes #
```release-note
Updated to bazel 5.4.0 and golang 1.20.10
```

Update builder to use golang 1.20.10 and bazel 5.4.0

---

pkg/controller/datavolume/controller-base.go
pkg/controller/datavolume/import-controller_test.go
pkg/controller/populators/clone-populator.go
pkg/controller/populators/import-populator_test.go
pkg/controller/populators/populator-base.go
pkg/controller/populators/util.go
tests/cloner_test.go
tests/import_proxy_test.go
tests/import_test.go

This is a manual backport of https://github.com/kubevirt/containerized-data-importer/pull/2873.
Fixes #
```release-note
Allow the usage of AnnPodRetainAfterCompletion with populators
```

[release-v1.57] Manual backport of AnnPodRetainAfterCompletion with populators

---

cmd/cdi-controller/controller.go
doc/metrics.md
pkg/controller/clone-controller.go
pkg/controller/common/util.go
pkg/controller/common/util_test.go
pkg/controller/dataimportcron-controller.go
pkg/controller/dataimportcron-controller_test.go
pkg/controller/datavolume/controller-base.go
pkg/controller/datavolume/util.go
pkg/controller/import-controller.go
pkg/controller/import-controller_test.go
pkg/controller/populators/import-populator.go
pkg/controller/populators/upload-populator.go
pkg/controller/populators/util.go
pkg/controller/storageprofile-controller.go
pkg/monitoring/metrics.go
pkg/operator/controller/prometheus.go
tests/clone-populator_test.go
tests/cloner_test.go
tests/datavolume_test.go
tests/framework/framework.go
tests/monitoring_test.go
tests/utils/datavolume.go

Storage providers in the field may supply many ways of utilizing a back end storage solution;  
They do so by providing different Kubernetes StorageClass parameters.
With the growth of kubevirt adoptions, we may sometimes see a certain combination of storage class parameters is preferrable for VM workloads.
This PR presents a possible way of steering kubevirt users
towards using such identified storage class.
Fixes #
Was considering not doing functional tests but this feels too important.
There is little to no penalty because the entire block of tests I'm …

Default storage class for virtualization purposes

---

WORKSPACE
hack/build/config.sh
vendor/golang.org/x/sys/windows/BUILD.bazel
vendor/sigs.k8s.io/json/internal/golang/encoding/json/BUILD.bazel

Updated builder used to tag 2310202104-20cced838, also updated bazel rules and gazelle version to match the new bazel in the builder
Fixes #
```release-note
Build with golang 1.20.10
```

Use golang 1.20.10 when building CDI

---

pkg/controller/datavolume/import-controller.go
pkg/controller/datavolume/import-controller_test.go
pkg/controller/datavolume/upload-controller.go
pkg/controller/datavolume/upload-controller_test.go
pkg/controller/populators/import-populator.go
pkg/controller/populators/import-populator_test.go

With the addition of populators into CDI, we introduced a minor divergence in the DataVolume status reporting between the new and the old flow to avoid checking PVC Prime from the legacy controllers.
Though it would be ideal to ignore the PVC Prime in the DV layer completely, there are certain cases where the reported status does not match the current behavior (check https://bugzilla.redhat.com/show_bug.cgi?id=2241637 for an example).
This PR aims to update the status reporting mechanism in import and upload controllers so both the old flow and the populator flow match.
Fixes # …

Improve DataVolume status reporting with populators

---

cmd/cdi-importer/importer.go
pkg/common/common.go
pkg/controller/datavolume/controller-base.go
pkg/controller/util.go
pkg/controller/util_test.go
pkg/importer/data-processor.go

When scratch space is needed during imports/uploads, the pod typically fails so it can be restarted with the required space. This is expected behavior that's automatically handled by CDI.
However, since we use an error exit code, the DataVolume condition that's triggered leads to unwanted VM statuses during provisioning in Kubevirt.
This PR aims to address this behavior by altering the condition, so kubevirt ignores it and the VM can be provisioned as expected.
Fixes # https://bugzilla.redhat.com/show_bug.cgi?id=2240963
```release-note …
```

Address error condition to avoid DataVolumeError status during VM provisioning

---

pkg/controller/clone-controller.go
pkg/controller/clone-controller_test.go
pkg/controller/common/util.go

Some CSI drivers [0] don't allow mounting block ro, so they simply cannot perform host assisted clones.
Host assisted clones are important as they are a last resort in some cases like switching over to a new storage provisioner.
This may or may not have some performance implications (parallel cloning from single source)
but we are choosing compatibility over performance in this case.
[0] https://github.com/dell/csi-unity/blob/76cb78decd0c7e0ae3bded9668e7fbe9b39dd2ff/service/node.go#L420-L424
Fixes #
https://issues.redhat.com/browse/CNV-33859 …

Mount block PVC rw in clone source pods

---

pkg/controller/datavolume/import-controller.go
pkg/controller/datavolume/import-controller_test.go
pkg/controller/datavolume/upload-controller.go
pkg/controller/datavolume/upload-controller_test.go
pkg/controller/populators/import-populator.go
pkg/controller/populators/import-populator_test.go

Manual backport of https://github.com/kubevirt/containerized-data-importer/pull/2928
Fixes #
Same code as the original, just removed a single line in the multi-stage import code.
```release-note
Bugfix: Improve DataVolume status reporting with populators
```

[release-v1.57] Check PVC Prime before updating DV status to improve status reporting

---

pkg/controller/populators/upload-populator.go
pkg/controller/populators/upload-populator_test.go

In our existing workflow, we aim to remove the AnnPVCPrimeName annotation from the target PVC once the upload populator succeeds. 
However, our current implementation of `updatePVCWithPVCPrimeAnnotations` only updates the PVC annotations when there is a modification to the object. This means that, since `AnnPVCPrimeName` annotation is removed in a separate function, there are scenarios where this change isn't reflected in the PVC as expected.
This PR aims to fix this behavior by removing the annotation inside `updatePVCWithPVCPrimeAnnotations`.  
Partial fix of https://bugzilla.redhat.com/show_bug.cgi?id=2241658.
```release-note
NONE
```

Ensure AnnPVCPrimeName annotation is always removed after upload succeeds

---

pkg/apis/core/v1beta1/openapi_generated.go
pkg/controller/clone/common.go
pkg/controller/clone/planner.go
pkg/controller/clone/planner_test.go
pkg/controller/common/util.go
pkg/controller/dataimportcron-controller.go
pkg/controller/dataimportcron-controller_test.go
pkg/controller/storageprofile-controller.go
pkg/controller/storageprofile-controller_test.go
pkg/operator/resources/crds_generated.go
staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/zz_generated.deepcopy.go

When there are several `VolumeSnapshotClasses` of the same provisioner but with different parameters, we would like to allow `StorageProfile` choose `VolumeSnapshotClass` for its `StorageClass`, so we won't choose the wrong one.
Fixes bz #2219774
```release-note
Allow StorageProfile to use a specific VolumeSnapshotClass
```

Allow StorageProfile to use a specific VolumeSnapshotClass

---

pkg/apiserver/BUILD.bazel
pkg/apiserver/apiserver.go

This missing field is reported by [ZAP](https://www.zaproxy.org/) when trying to discover the CDI API: `error: attribute info.version is missing`.
Adding this field makes ZAP happy and the scan can proceed.
Fixes https://issues.redhat.com/browse/CNV-34683
I copied KubeVirt implementation (https://github.com/kubevirt/kubevirt/blob/5d8c225/pkg/virt-api/api.go#L728)
```release-note
NONE
```

Add version field to the OpenAPI definition

---

doc/image-from-registry.md

Registry source requires .crt suffix for CA certificates. It is a feature of the library "github.com/containers/image": See https://github.com/kubevirt/containerized-data-importer/blob/536af6b1ad3d4ee44e3e746ce850fd7d36b08e75/vendor/github.com/containers/image/v5/pkg/tlsclientconfig/tlsclientconfig.go#L36
Fixes #
```release-note
```

fix(docs): registry datasource expect CA certs with .crt

---

pkg/controller/populators/upload-populator.go
tests/utils/pvc.go

This hot loop was causing the upload populator to constantly add and remove the annotation causing the node controller to always be outdated and never update the pvc to be bound causing the upload test to fail randomly.
Fixes #
```release-note
NONE
```

Prevent upload populator from hot looping prime annotation

---

cmd/cdi-cloner/cloner_startup.sh

When cloning an image from an existing DV/PVC, i found that the clone progress is not accurate. 
Because the cdi-cloner calculate the clone progress by **(transmitted Bytes)/(apparent size of disk.img) * 100**.
Actually the transmitted bytes is equal to the disk usage of the raw image file, not equal to the apparent size. 
For example：
```
/ # ls -lh /data/disk.img 
-rw-rw----    1 107      107        94.5G Nov 15 13:02 /data/disk.img
/ # qemu-img info /data/disk.img 
image: /data/disk.img
file format: raw
virtual size: 94.5 GiB (101468602368 bytes)
disk size: 30.8 GiB
Child node '/file':
filename: /data/disk.img
protocol type: file
file length: 94.5 GiB (101468602368 bytes)
disk size: 30.8 GiB
/ # du -sb /data/disk.img 
101468602368 …
```

fix: calculate clone progress from disk usage, not apparent-size

---

tests/dataimportcron_test.go

This issue prevents the common csi snapshot controller from removing it's PVC finalizer:
https://github.com/kubernetes-csi/external-snapshotter/issues/957
This causes us some pain in testing:
https://search.ci.kubevirt.io/?search=dataimportcron_test.go%3A138&maxAge=336h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
so let's try working around it.
Fixes #
```release-note
NONE
```

Work around common snapshot controller issue in tests

---

.bazelrc
cmd/cdi-apiserver/BUILD.bazel
hack/build/print-workspace-status.sh
pkg/version/def.bzl

This patch sets the version information on release images built by bazel.
Fixes #2979
I copied KubeVirt implementation
```release-note
NONE
```

Set CDI version/commit info on release images

---

pkg/operator/controller/prometheus.go

Update CDIMultipleDefaultVirtStorageClasses alert health impact labels to "none", since the issue of the alert doesn't impact the overall health of the operator.
Fixes #
https://issues.redhat.com/browse/CNV-35297
```release-note
NONE
```

Update CDIMultipleDefaultVirtStorageClasses alert

---

pkg/operator/resources/cluster/rbac.go
tests/rbac_test.go

Currently a (non-cluster-admin) namespace admin cannot create various CDI user-facing resources,
this PR grants the missing permissions.
Fixes #
https://issues.redhat.com/browse/CNV-36309
```release-note
BugFix: ns admin cannot create multiple user-facing CDI resources
```

Grant ns admin missing create RBAC for various CDI resources

---

hack/build/run-functional-tests.sh
pkg/monitoring/metrics.go
tests/framework/framework.go
tests/import_test.go
tests/monitoring_test.go

If CDI CR was deleted and re-created, the metric may have old instances of the old cdi-deployment pod IP.
Also added alerts Polarion test_ids and restore ginkgo output verbosity.
Fixes #
```release-note
NONE
```

Fix flakiness in waitForStorageProfileMetricInit

---

pkg/controller/dataimportcron-controller.go
tests/dataimportcron_test.go

PVC should be timestamped in creation and not only upon import completion, as it might be mistakenly GCed. LRU sort will choose PVC with empty timestamp as the first candidate for deletion. The PVC will be recreated by the controller and eventually timestamped, so this bug was hidden for a while.
Fixes CNV-36896
```release-note
Fix DataImportCron PVC timestamping for garbage collection
```

Fix DataImportCron PVC GC race and test flakiness

---

pkg/controller/common/util.go
pkg/controller/datavolume/garbagecollect.go
pkg/controller/datavolume/import-controller_test.go

This is needed for claim adoption with dataVolumeTemplates.  If anyone is using garbage collection feature we have to make sure that virt-controller will not continually keep creating DVs after they are garbage collected.
Fixes #
```release-note
cdi.kubevirt.io/garbageCollected added to PVCs when DataVolumes are garbage collected
```

add annotation to PVCs when DVs are garbage collected

---

pkg/controller/dataimportcron-controller.go
tests/dataimportcron_test.go

Manual backport of #3057
PVC should be timestamped in creation and not only upon import completion, as it might be mistakenly GCed. LRU sort will choose PVC with empty timestamp as the first candidate for deletion. The PVC will be recreated by the controller and eventually timestamped, so this bug was hidden for a while.
Fixes CNV-36896
```release-note
Fix DataImportCron PVC timestamping for garbage collection
```

[release-v1.58] Fix DataImportCron PVC GC race and test flakiness

---

pkg/controller/dataimportcron-controller.go
tests/dataimportcron_test.go

Manual backport of #3057
PVC should be timestamped in creation and not only upon import completion, as it might be mistakenly GCed. LRU sort will choose PVC with empty timestamp as the first candidate for deletion. The PVC will be recreated by the controller and eventually timestamped, so this bug was hidden for a while.
Fixes CNV-37181
```release-note
Fix DataImportCron PVC timestamping for garbage collection
```

[release-v1.57] Fix DataImportCron PVC GC race and test flakiness

---

pkg/controller/datavolume/controller-base.go
pkg/controller/datavolume/import-controller.go
pkg/controller/datavolume/import-controller_test.go
pkg/controller/datavolume/upload-controller.go
pkg/controller/datavolume/upload-controller_test.go
tests/cloner_test.go
tests/import_test.go
tests/utils/datavolume.go
tests/utils/pvc.go

This PR should fix this bug:
Jira-ticket: https://issues.redhat.com/browse/CNV-35085
Fixes #CNV-35085
```release-note
None
```

Fix populators not repopulating pvc after it was deleted

---

cmd/cdi-apiserver/BUILD.bazel
cmd/cdi-apiserver/apiserver.go
pkg/apiserver/BUILD.bazel
pkg/apiserver/apiserver.go
pkg/apiserver/auth-config_test.go
pkg/apiserver/webhooks/BUILD.bazel
pkg/apiserver/webhooks/datavolume-validate.go
pkg/apiserver/webhooks/datavolume-validate_test.go
pkg/apiserver/webhooks/handler.go
pkg/controller/common/util.go
pkg/controller/datavolume/clone-controller-base.go
pkg/controller/datavolume/controller-base.go
pkg/controller/datavolume/import-controller.go
pkg/controller/datavolume/import-controller_test.go
pkg/controller/datavolume/pvc-clone-controller.go
pkg/controller/datavolume/pvc-clone-controller_test.go
pkg/controller/datavolume/snapshot-clone-controller.go
pkg/controller/datavolume/upload-controller.go
pkg/controller/datavolume/upload-controller_test.go
pkg/controller/import-controller_test.go
pkg/controller/populators/import-populator_test.go
pkg/feature-gates/feature-gates.go
pkg/feature-gates/feature-gates_test.go
pkg/operator/resources/cluster/apiserver.go
tests/BUILD.bazel
tests/adopt-volume_test.go
tests/framework/pvc.go
tests/upload_test.go

In many DR/backup scenarios, a PVC may exist before a DataVolume.  Usually that results in an error when the DataVolume is created.  This PR provides two new mechanisms to avoid that error and allow the DataVolume controller to "adopt" an existing PVC.  Adoption of a PVC means that the DataVolume will immediately go to Succeeded state and not attempt to write any data to the PVC.
**DataVolumeClaimAdoption** feature gate:  This is a global setting to configure claim adoption for all PVCs in the system
**cdi.kubevirt.io/allowClaimAdoption** PVC annotation: This overrides any feature gate setting and and allows for one-off claim adoption.  It is also possible to add this annotation to PVCs indirectly when creating a DataVolume (PVCs inherit DataVolume …

Feature Gate and annotation for PVCs to be "adopted" by DataVolumes

---

tests/cloner_test.go

- Smart/CSI clone
These tests are by definition only running on CSI storage (IsCSIVolumeCloneStorageClassAvailable/IsSnapshotStorageClassAvailable)
- Snapshot clone
This test is always getting skipped, since snapshots always imply the storage is CSI
Fixes #
```release-note
NONE
```

Stop skipping advanced clone method tests with immediate bind annotation

---

pkg/controller/dataimportcron-controller.go
pkg/controller/dataimportcron-controller_test.go
pkg/controller/datavolume/controller-base.go

The `imports` local variable was not updated correctly, and later referenced, so another reconcile was required for the DV to be created.
Fixes CNV-33973
```release-note
Fix DataImportCron import DataVolume creation when last import is not found
```

Fix DataImportCron import DataVolume creation when last import is not found

---

pkg/operator/resources/cluster/apiserver.go

If cdi-apiserver gets in a bad state it may not allow CDI to be deleted.  Maybe when CDI webhook is served by cdi-operator we can put this back to Fail
Fixes #
https://issues.redhat.com/browse/CNV-36904
In the attached case, webhooks had to be manually deleted in order to uninstall CDI
```release-note
Change CDI webhook failure policy to Ignore
```

Change CDI webhook failure policy to Ignore

---

pkg/controller/common/BUILD.bazel
pkg/controller/common/util.go
pkg/controller/common/util_test.go
pkg/operator/controller/cr-manager.go

Was impossible for CDI to get out of `Error` phase once in it because `GetActiveCDI()` filtered out resources in `Error` state.  This change allows the function to return success if there is a single CDI in error state.
Fixes #
https://issues.redhat.com/browse/CNV-36904
If you look at attached issues, what appears to have happened is that CDI somehow got in an error state (not sure how but not that important).  Once in error state, cdi-operator reconcile loop would always error out.  Eventually certs would expire and you can't do anything CDI related.  Not …

Allow Deployed CDI to get out of Error Phase

---

pkg/operator/controller/callbacks.go
pkg/operator/controller/controller_test.go
pkg/operator/controller/cruft.go

This has been deprecated for years, and recently we even stopped creating it:
https://github.com/kubevirt/containerized-data-importer/pull/2723
https://github.com/kubevirt/containerized-data-importer/pull/1754
This PR is about removing the stray configmap on a user environment that kept carrying it through the versions.
Fixes #
```release-note
Remove deprecated insecure registries config map from a CDI install 
```

Remove deprecated insecure registries config map from user's install

---

pkg/controller/dataimportcron-controller.go
pkg/controller/dataimportcron-controller_test.go
pkg/controller/datavolume/controller-base.go

Manual backport of #3072
The `imports` local variable was not updated correctly, and later referenced, so another reconcile was required for the DV to be created.
Fixes CNV-37498
```release-note
Fix DataImportCron import DataVolume creation when last import is not found
```

[release-v1.57] Fix DIC DV creation when last import is not found

---

pkg/apis/core/v1beta1/openapi_generated.go
pkg/controller/storageprofile-controller.go
pkg/controller/storageprofile-controller_test.go
pkg/operator/resources/crds_generated.go
staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go

We have no reason to allow setting `StorageProfile` `ClaimPropertySet` missing either `VolumeMode` or `AccessModes`.
Jira-ticket: https://issues.redhat.com/browse/CNV-37991
```release-note
BugFix: StorageProfile ClaimPropertySets validation
```

Fix StorageProfile ClaimPropertySets validation

---

pkg/controller/util.go
pkg/controller/util_test.go
pkg/operator/controller/cr-manager.go

manual backport of https://github.com/kubevirt/containerized-data-importer/pull/3080
Fixes #
https://issues.redhat.com/browse/CNV-38364
```release-note
BugFix:  Allow Deployed CDI to get out of Error Phase
```

[release-v1.55] Allow Deployed CDI to get out of Error Phase

---

pkg/storagecapabilities/storagecapabilities.go

minikube (https://github.com/kubernetes/minikube) ships with its own default storage provider.
CDI does not detect the minikube default storage provider out of the box, requiring manual configuration by the user.
Fixes #
```release-note
Added the k8s.io/minikube-hostpath storage provider to the list of known storage providers to make the out of the box experience better with minikube.
```

Add storage capabilities for minikube's hostpath provider

---

pkg/apiserver/webhooks/datavolume-validate_test.go
pkg/controller/common/util.go
pkg/controller/datavolume/controller-base.go
pkg/controller/datavolume/import-controller_test.go
pkg/controller/datavolume/pvc-clone-controller_test.go
pkg/controller/datavolume/upload-controller_test.go
tests/adopt-volume_test.go

This allows for better backwards compatibality with DataVolumeTemplates
In implementing https://github.com/kubevirt/kubevirt/pull/11267 I came to the conclusion that it would be better to check for `cdi.kubevirt.io/allowClaimAdoption` annotation on the DataVolume rather than the PVC.  This will allow new an old DataVolumeTemplates (created pre claim adoption) to work in DR scenario.  Otherwise only new DVs (created post claim adoption) would have the annotation on the PVC.
Fixes #
```release-note
Refactor: Check for …
```

Check cdi.kubevirt.io/allowClaimAdoption on DataVolume rather than PVC

---

cmd/cdi-apiserver/BUILD.bazel
cmd/cdi-apiserver/apiserver.go
pkg/apiserver/BUILD.bazel
pkg/apiserver/apiserver.go
pkg/apiserver/auth-config_test.go
pkg/apiserver/webhooks/BUILD.bazel
pkg/apiserver/webhooks/datavolume-validate.go
pkg/apiserver/webhooks/datavolume-validate_test.go
pkg/apiserver/webhooks/handler.go
pkg/controller/common/util.go
pkg/controller/datavolume/clone-controller-base.go
pkg/controller/datavolume/controller-base.go
pkg/controller/datavolume/import-controller.go
pkg/controller/datavolume/import-controller_test.go
pkg/controller/datavolume/pvc-clone-controller.go
pkg/controller/datavolume/pvc-clone-controller_test.go
pkg/controller/datavolume/snapshot-clone-controller.go
pkg/controller/datavolume/upload-controller.go
pkg/controller/datavolume/upload-controller_test.go
pkg/controller/import-controller_test.go
pkg/controller/populators/import-populator_test.go
pkg/feature-gates/feature-gates.go
pkg/feature-gates/feature-gates_test.go
pkg/operator/resources/cluster/apiserver.go
tests/BUILD.bazel
tests/adopt-volume_test.go
tests/framework/pvc.go
tests/upload_test.go

Manual backport of #3029 and #3105
Fixes #
https://issues.redhat.com/browse/CNV-35100
```release-note
DataVolume supports PVC adoption via DataVolumeClaimAdoption feature gate and cdi.kubevirt.io/allowClaimAdoption annotation on PVC
```

[release-v1.58] Feature Gate and annotation for PVCs to be "adopted" by DataVolumes

---

pkg/controller/common/util.go
pkg/controller/datavolume/garbagecollect.go
pkg/controller/datavolume/import-controller_test.go

Manual backport of #3059
Fixes #
https://issues.redhat.com/browse/CNV-35100
```release-note
cdi.kubevirt.io/garbageCollected added to PVCs when DataVolumes are garbage collected
```

[release-v1.58] add annotation cdi.kubevirt.io/garbageCollected to PVCs when DVs are garbage collected

---

pkg/controller/dataimportcron-controller.go
pkg/controller/dataimportcron-controller_test.go
pkg/controller/datavolume/controller-base.go

Manual backport of #3072
The `imports` local variable was not updated correctly, and later referenced, so another reconcile was required for the DV to be created.
Fixes CNV-33973
```release-note
Fix DataImportCron import DataVolume creation when last import is not found
```

[release-v1.58] Fix DIC DV creation when last import is not found

---

pkg/apis/core/v1beta1/openapi_generated.go
pkg/controller/storageprofile-controller.go
pkg/controller/storageprofile-controller_test.go
pkg/operator/resources/crds_generated.go
staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go

Manual backport of #3096
Use CRD validation for StorageProfile ClaimPropertySets, and reject if ClaimPropertySet is missing either volume mode or access modes.
Jira-ticket: https://issues.redhat.com/browse/CNV-37991
```release-note
BugFix: StorageProfile ClaimPropertySets validation
```

[release-v1.58] Fix StorageProfile ClaimPropertySets validation

---

cmd/cdi-importer/importer.go
pkg/common/common.go
pkg/controller/import-controller.go
pkg/controller/import-controller_test.go
tests/datavolume_test.go

This pull request sets the exit code when scratch space is required to 0 so, when deleting the importer pod after exiting for scratchSpaceNeeded, we don't need to deal with unwanted automatic restarts (RestartPolicyOnFailure). This conflicting behavior caused some issues during termination while the pod was already restarting after scratchSpaceNeeded.
Importer pod lifecycle for a regular DV before the fix:
```sh
selecting docker as container runtime
exitCode: 42
exitCode: 42
exitCode: 42
exitCode: 42
exitCode: 2
exitCode: 42
exitCode: 2
exitCode: 42
exitCode: 2
exitCode: 0
exitCode: 0
```
After the fix:
```sh
selecting docker as container runtime
exitCode: 0
exitCode: 0
exitCode: 0
exitCode: 0
exitCode: 0
exitCode: 0
```
**Which issue(s) this PR …

Avoid race condition during importer termination

---

cmd/cdi-importer/BUILD.bazel
cmd/cdi-importer/importer.go
pkg/common/BUILD.bazel
pkg/common/common.go
pkg/common/common_suite_test.go
pkg/common/common_test.go
pkg/controller/clone-controller.go
pkg/controller/import-controller.go
pkg/controller/import-controller_test.go
pkg/controller/upload-controller.go
pkg/controller/util.go
pkg/controller/util_test.go
pkg/importer/data-processor.go
pkg/importer/data-processor_test.go
pkg/importer/gcs-datasource.go
pkg/importer/http-datasource.go
pkg/importer/imageio-datasource.go
pkg/importer/registry-datasource.go
pkg/importer/s3-datasource.go
pkg/importer/upload-datasource.go
pkg/importer/vddk-datasource_amd64.go
pkg/importer/vddk-datasource_arm64.go
pkg/importer/vddk-datasource_test.go
pkg/uploadserver/uploadserver_test.go
pkg/util/util.go
tests/datavolume_test.go

Make the communication of datasources in the importer explicit by adding
a GetTerminationMessage method to the DataSourceInterface.
Then use this method to communicate additional information to the import
controller once the importer pod has terminated, instead of writing
additional data to the termination message in the Close method of
datasources.
Fixes #
```release-note
None
```

feat: Make importer datasource communication explicit

---

pkg/controller/clone/prep-claim.go
pkg/controller/clone/prep-claim_test.go

This is part of a larger work to improve log reporting in CDI.
There is a short window of time where a bound PVC can have an unpopulated `capacity` field in its status. The clone-populator handles this case by returning an error.
This approach is overkill as the issue is usually fixed instantly and should hardly be considered an error as we will reconcile again once the status is updated. This pull request aims to improve the handling of this case and adds unit test coverage.
Fixes # https://issues.redhat.com/browse/CNV-35803
```release-note …
```

Improve handling of unpopulated capacity field in clone populator

---

pkg/controller/common/util.go
pkg/controller/datavolume/controller-base.go
pkg/controller/datavolume/import-controller.go
pkg/controller/datavolume/import-controller_test.go
pkg/controller/datavolume/pvc-clone-controller_test.go
pkg/controller/datavolume/upload-controller.go
pkg/controller/datavolume/upload-controller_test.go
tests/datavolume_test.go

Have to better track when a PVC was created for a particular DV (populate it) or created for someone else (adopt it)
Let's do this by adding a new annotation to a PVC created by the DataVolumeController
cdi.kubevirt.io/createdForDataVolume: "uid of datavolume"
Fixes #
https://issues.redhat.com/browse/CNV-39618
```release-note
BugFix for CNV-39618 - cdi.kubevirt.io/allowClaimAdoption annotation broken
```

cdi.kubevirt.io/allowClaimAdoption annotation breaking "regular" operations

---

pkg/storagecapabilities/storagecapabilities.go

Since version 2.4.1 the HPE CSI provisioner supports the RWX access mode for block volumes. We should update our storage profile to capture this.
Fixes # https://issues.redhat.com/browse/CNV-39704
```release-note
Add HPE RWX/Block capability
```

Add HPE RWX/Block capability

---

pkg/uploadproxy/uploadproxy.go
tests/upload_test.go

Manual backport of https://github.com/kubevirt/containerized-data-importer/pull/3131.
When upload content-type is invalid we post a error message with user-controlled parameters in our upload proxy. This makes the proxy vulnerable to XSS attacks as an user might maliciously inject a script into the content type.
This PR aims to fix this behavior by escaping the two user-controlled strings before posting them.
Fixes # https://issues.redhat.com/browse/CNV-36209
```release-note
Bugfix: Avoid XSS vulnerability in Upload proxy
```

[release-v1.55] Escape user-controlled strings in uploadproxy to avoid XSS attacks

---

pkg/controller/common/util.go
pkg/controller/datavolume/controller-base.go
pkg/controller/datavolume/import-controller.go
pkg/controller/datavolume/import-controller_test.go
pkg/controller/datavolume/pvc-clone-controller_test.go
pkg/controller/datavolume/upload-controller.go
pkg/controller/datavolume/upload-controller_test.go
tests/datavolume_test.go

Have to better track when a PVC was created for a particular DV (populate it) or createed for someone else (adopt it)
Fixes:  https://issues.redhat.com/browse/CNV-39618
manual backport of #3136
Fixes #
```release-note
BugFix for CNV-39618 - cdi.kubevirt.io/allowClaimAdoption annotation broken
```

[release-v1.58] cdi.kubevirt.io/allowClaimAdoption annotation breaking "regular" operations

---

pkg/common/common.go
pkg/controller/import-controller.go
pkg/controller/import-controller_test.go
pkg/controller/populators/import-populator.go
pkg/controller/populators/import-populator_test.go
pkg/controller/populators/populator-base.go
pkg/controller/populators/upload-populator.go
pkg/controller/populators/upload-populator_test.go
pkg/controller/util.go
pkg/controller/util_test.go
pkg/importer/BUILD.bazel
pkg/importer/http-datasource.go
pkg/importer/http-datasource_test.go
pkg/importer/imageio-datasource_test.go
pkg/importer/registry-datasource.go
pkg/importer/registry-datasource_test.go
pkg/importer/transport.go
pkg/importer/transport_test.go
pkg/importer/util.go
pkg/importer/util_test.go
tests/BUILD.bazel
tests/import_test.go
tools/cdi-containerimage-server/BUILD.bazel
tools/cdi-containerimage-server/main.go
tools/cdi-func-test-registry-init/populate-registry.sh

This allows to set labels on PVCs derived from env vars containing `KUBEVIRT_IO_` on containerdisks. Env vars on containerdisks were chosen because they can be accessed in both pullMethods pod and node. While the pod pullMethod is talking to the registry and can query for the `Labels` field in the image config, the pullMethod node cannot access the image config. However, the server running in the context of the containerdisk can still see all associated env vars of the containerdisk.
```
skopeo inspect docker://quay.io/containerdisks/fedora
{
"Name": "quay.io/containerdisks/fedora",
"Digest": "sha256:bbc58d0576a236bafe4917c0fbe40701c5164344a499af257ab61b29dacde57c",
"RepoTags": [
"35-2111250200",
"35-2112061510",
"35-1.2",
"35",
"36-2205130206", …
```

feat(import): Set PVC labels derived from env vars on containerdisks

---

pkg/controller/import-controller.go

Importer pod's creation code always seemed a bit redundant, with two functions (`makeNodeImporterPodSpec` and `makeImporterPodSpec`) sharing common code and logic.
This Pull Request aims to clean that code a bit, in an attempt to improve readability.
Summary of changes:
- `makeNodeImporterPodSpec` and `makeImporterPodSpec` have been merged into a single function.
- Most of the import-type specific logic has been moved to container, volume, and initContainer-specific functions.
- No need of `setImporterPodCommons` since now most of the code is shared between node and regular import.
```release-note
NONE
```

Improve readability of importer pod's creation code

---

pkg/uploadproxy/uploadproxy.go
tests/upload_test.go

Manual backport of https://github.com/kubevirt/containerized-data-importer/pull/3131.
When upload content-type is invalid we post a error message with user-controlled parameters in our upload proxy. This makes the proxy vulnerable to XSS attacks as an user might maliciously inject a script into the content type.
This PR aims to fix this behavior by escaping the two user-controlled strings before posting them.
Fixes # https://issues.redhat.com/browse/CNV-36211
```release-note
Bugfix: Avoid XSS vulnerability in Upload proxy
```

 [release-v1.56] Escape user-controlled strings in uploadproxy to avoid XSS attacks

---

pkg/controller/upload-controller.go
pkg/controller/upload-controller_test.go

Another PR in the fashion of https://github.com/kubevirt/containerized-data-importer/pull/3118, this time for the upload controller.
The upload-pod code is not as convoluted as the importer's, but can also benefit from some code separation as `makeUploadPodSpec` is too large, for example, by having separate functions to create the pod containers and volumes.
The PR also fixes some linter warnings by deleting unused struct fields and function parameters.
```release-note
NONE
```

Fix linter warnings and clean-up upload controller

---

pkg/controller/import-controller.go
pkg/controller/util.go
pkg/controller/util_test.go

Instead of changing the labels map that is passed in as parameter to the
setLabelsFromTerminationMessage function, it now returns a modified copy
of the passed in labels map and is renamed to
addLabelsFromTerminationMessage. If the passed in map is nil a new map
will be allocated and initialized.
Follow up to #3103 
```release-note
None
```

cleanup: Return modified labels added from termination message

---

hack/build/run-functional-tests.sh

We have some feedback from testing CDI on a different platform that this can work tests-wise
(but of course, not resource-wise, which we will see here).
Fixes #
```release-note
NONE
```

Double number of e2e parallel nodes from 3 to 6

---

doc/clone-from-volumesnapshot-source.md
pkg/controller/clone/planner.go
pkg/controller/clone/planner_test.go
pkg/controller/common/util.go
pkg/controller/dataimportcron-controller.go
pkg/controller/dataimportcron-controller_test.go

Sometimes with snapshot cloning we have to fall back to host assisted.
To do this, we create a temporary restore from the snapshot and initiate a host assisted clone
from that -> target PVC.
The issue this commit fixes is that we set the wrong access/volume modes on this temporary restore PVC
(we set it to the target's).
Fixes #
```release-note
BugFix: Clone from snapshot - fix volume/access mode inferring for temp host assisted source PVC
```

Fix volume/access mode inferring for temp host assisted source PVC in snapshot clones

---

pkg/controller/BUILD.bazel
pkg/controller/common/util.go
pkg/controller/dataimportcron-conditions.go
pkg/controller/dataimportcron-controller.go
pkg/controller/dataimportcron-controller_test.go
pkg/controller/datavolume/controller-base.go
pkg/monitoring/metrics/cdi-controller/dataimportcron.go
pkg/monitoring/rules/alerts/operator.go
tests/monitoring_test.go

This is a follow-up to #2998 introducing the following changes to alert rules:
- CDIDefaultStorageClassDegraded - do not fire when no default SC (either k8s or virt).
- CDIDataImportCronOutdated - do not fire when no default SC (either k8s or virt), as DIC import DVs use default SC.
- CDINoDefaultStorageClass - fire not only when there is a pending DV (and PVC) but also when DV has an empty status (waiting for default SC etc.)
Fixes #
```release-note
Suppress alerts to reduce noise of dependent ones
```

Suppress alerts to reduce noise of dependent ones

---

.golangci.yml
cmd/cdi-cloner/clone-source.go
cmd/cdi-importer/importer.go
pkg/controller/common/util.go
pkg/controller/common/util_test.go
pkg/controller/config-controller.go
pkg/controller/dataimportcron-controller_test.go
pkg/controller/datavolume/clone-controller-base.go
pkg/controller/datavolume/controller-base.go
pkg/controller/datavolume/snapshot-clone-controller_test.go
pkg/controller/populators/import-populator_test.go
pkg/controller/populators/upload-populator_test.go
pkg/importer/data-processor_test.go
pkg/importer/imageio-datasource.go
pkg/importer/util.go
pkg/importer/vddk-datasource_test.go
pkg/operator/controller/controller_test.go
pkg/operator/controller/route.go
tests/cloner_test.go
tests/imageio-inventory.go
tests/operator_test.go
tests/utils/datavolume.go
tools/cdi-func-test-sample-populator/main.go

I'd like to take the credit but it just a linter:
```
golangci-lint run ./... --enable misspell --fix
```
Just some housekeeping
These could be automated by adding the [`misspell`](https://golangci-lint.run/usage/linters/#misspell) linter to the golangci-lint file.
```release-note
Enable misspell linter and fix spelling errors in comments and strings
```

Enable misspell linter and fix spelling errors

---

pkg/controller/datavolume/clone-controller-base.go

Until now, the clone populator handled the error phase as "unknown". This triggered a minor log flood with the `Unknown populator phase` message, which wasn't descriptive enough.
To avoid this, we are now handling the phase as the others but still avoiding changing DV phase for consistency with the non-populator flow. If necessary, now a proper event will be recorded in the DataVolume. This addresses this card: https://issues.redhat.com/browse/CNV-35802.
Fixes # https://issues.redhat.com/browse/CNV-35802 (partially)
Still in progress, let's see how tests …

Stop handling error phase as "unknown" in clone-populator

---

doc/clone-from-volumesnapshot-source.md
pkg/controller/clone/planner.go
pkg/controller/clone/planner_test.go
pkg/controller/common/util.go
pkg/controller/dataimportcron-controller.go
pkg/controller/dataimportcron-controller_test.go
pkg/controller/datavolume/util.go

Manual backport of https://github.com/kubevirt/containerized-data-importer/pull/3155
Fixes #
I have exported RenderPvcSpec (under deprecated notice) as that seems to be the least intrusive
```release-note
BugFix: Clone from snapshot - fix volume/access mode inferring for temp host assisted source PVC
```

[release-v1.58] Fix inferring for temp host assisted source PVC in snapshot clones

---

doc/clone-from-volumesnapshot-source.md
pkg/controller/clone/BUILD.bazel
pkg/controller/clone/planner.go
pkg/controller/clone/planner_test.go
pkg/controller/common/util.go
pkg/controller/dataimportcron-controller.go
pkg/controller/dataimportcron-controller_test.go
pkg/controller/datavolume/util.go

Manual backport of https://github.com/kubevirt/containerized-data-importer/pull/3155
Fixes #
https://issues.redhat.com/browse/CNV-40627
```release-note
BugFix: Clone from snapshot - fix volume/access mode inferring for temp host assisted source PVC
```

[release-v1.57] Fix inferring for temp host assisted source PVC in snapshot clones

---

pkg/apiserver/webhooks/BUILD.bazel
pkg/apiserver/webhooks/datavolume-validate.go
pkg/apiserver/webhooks/datavolume-validate_test.go
pkg/controller/datavolume/BUILD.bazel
pkg/controller/datavolume/util.go
pkg/controller/datavolume/util_test.go

Kubevirt disks must be at least 1MiB to work. Smaller sizes are rejected [here](https://github.com/kubevirt/kubevirt/blob/main/pkg/util/util.go#L234). This issue is only reported inside the virt-launcher pod logs, which makes debugging difficult.
This Pull Request modifies our DV and PVC admission webhook to reject storage sizes smaller than 1MiB at an earlier phase, thus improving consistency with Kubevirt.
Fixes # https://issues.redhat.com/browse/CNV-35798 (partially)
```release-note
Reject volumes with storage smaller than 1MiB
```

Reject DataVolumes and PVCs with storage size smaller than 1MiB

---

.golangci.yml
pkg/apiserver/webhooks/populators-validate_test.go
pkg/controller/clone/prep-claim.go
pkg/controller/common/util.go
pkg/controller/config-controller_test.go
pkg/controller/datavolume/import-controller_test.go
pkg/controller/datavolume/pvc-clone-controller.go
pkg/controller/datavolume/pvc-clone-controller_test.go
pkg/controller/datavolume/util.go
pkg/controller/import-controller.go
pkg/controller/import-controller_test.go
pkg/controller/populators/upload-populator_test.go
pkg/controller/storageprofile-controller_test.go
pkg/operator/controller/route.go
pkg/util/util.go
pkg/util/util_test.go
pkg/version/verflag/verflag.go
tests/cloner_test.go
tests/external_population_test.go
tests/framework/framework.go
tests/framework/nfs-utils.go
tests/framework/pvc.go
tests/operator_test.go
tests/upload_test.go
tests/utils/datavolume.go
tests/utils/pod.go
tests/utils/pv.go
tests/utils/pvc.go
tests/webhook_test.go

Enables the `unconvert` golangci-lint linter, and fixes all its warnings.
This linter's doc describes it as:
> The unconvert program analyzes Go packages to identify unnecessary type conversions; i.e., expressions T(x) where x already has type T.
- https://golangci-lint.run/usage/linters/#unconvert
- https://github.com/mdempsky/unconvert?tab=readme-ov-file#about
```release-note
Enable unconvert linter and remove all redundant type conversions
```

Enable unconvert linter

---

pkg/storagecapabilities/storagecapabilities.go

This PR adds the upstream rook-ceph RGW StorageClass bucket provisioner to the compiled-in hashmap of unsupported provisioners for the purposes of metrics reporting.
For additional detail, see discussion on #3166 
I also separated out the ODF/OCS RGW StorageClass into a dedicated const so that Noobaa is consistent.
```release-note
Improve metrics reporting behavior for upstream rook-ceph deployments, identifying RGW bucket provisioners
```

fix: add rook-ceph upstream provisioner string to unsupported providers

---

pkg/controller/clone-controller.go
pkg/controller/clone/prep-claim.go
pkg/controller/common/util.go
pkg/controller/datavolume/pvc-clone-controller.go
pkg/controller/import-controller.go
pkg/controller/populators/populator-base.go
pkg/controller/upload-controller.go
tests/import_test.go

Mesh annotations are not replicating to pods set by the DV/PVCs. Allows users to unmesh these pods by default.
- Prep claim pod.
- Size detection pod.
- Importer pod.
- Clone source pod.
- Upload pod.
Fixes #
```release-note
Mesh annotations now copied from the DV/PVCs to the following pods.
- Prep claim pod.
- Size detection pod.
- Importer pod.
- Clone source pod.
- Upload pod.
```

fix: propagating mesh annotations to transient pods

---

pkg/storagecapabilities/storagecapabilities.go

Following some investigation we are now confident this tuning is benefical for LVMS:
1. CSI clone is effectively implemented the same as snapshotting because both already use lvm2 thinly provisioned snapshots under the hood
2. Snapshots being COW, it makes total sense to store cron sources in the snapshot format instead of PVC:
```
A snapshot of a thin logical volume also creates a thin logical volume.
This consumes no data space until a COW operation is required, or until the snapshot itself is written.
```
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/logical_volume_manager_administration/thinly-provisioned_snapshot_volumes
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes …

Change clone strategy and cron sources format for LVMS

---

pkg/importer/data-processor.go
pkg/importer/data-processor_test.go
pkg/importer/http-datasource.go
pkg/importer/imageio-datasource.go
pkg/importer/registry-datasource.go
pkg/importer/s3-datasource.go
pkg/importer/upload-datasource.go
pkg/importer/util.go
pkg/importer/util_test.go
pkg/importer/vddk-datasource_amd64.go
pkg/importer/vddk-datasource_test.go
pkg/uploadserver/uploadserver.go
pkg/util/util.go
tests/framework/pvc.go

**What this PR does / why we need it**: Backports PR #2676 
> Rather than cleaning up everything on target/scratch PVCs, only delete what we may have created
There was a merge conflict because the patch modifies `pkg/importer/gcs-datasource.go`. GCS support was added in v1.57 (#2615). I simply removed this file from the patch.
There were no more merge conflicts.
```release-note
More targeted cleanup of target/scratch pvcs (only delete what we may have created)
```

[release-v1.56] Backport more targeted cleanup of target/scratch pvcs (#2676)

---

cmd/cdi-importer/importer.go
pkg/common/common.go
pkg/controller/util.go
pkg/controller/util_test.go
pkg/importer/BUILD.bazel
pkg/importer/data-processor.go
pkg/importer/errors.go
pkg/importer/gcs-datasource.go
pkg/importer/http-datasource.go
pkg/importer/imageio-datasource.go
pkg/importer/s3-datasource.go
pkg/importer/transport.go
pkg/importer/upload-datasource.go
pkg/importer/util.go
pkg/importer/util_test.go
pkg/util/util.go
tests/import_test.go

When the image pull fails, the DataVolume Running condition, will have the Reason field of `ImagePullFailed`, to allow better error handling in code that uses it.
Also, moved the `StreamDataToFile` function from the `util` package to the `importer` package, and made to non-exported. This is done to allow calling the new `NewErrImagePullFailed` function from within `streamDataToFile`, and to avoid import cycle. In addition, the `streamDataToFile` is only used in the `importer` package and so it's better to define it there.
```release-note
When the image pull fails, the DataVolume Running condition, will have the Reason field of "ImagePullFailed"
```
```jira-ticket
https://issues.redhat.com/browse/CNV-39603
```

Add new DV reason: ImagePullFailed

---

.golangci.yml
cmd/cdi-cloner/clone-source.go
cmd/openstack-populator/openstack-populator.go
pkg/controller/clone-controller.go
pkg/controller/clone/planner.go
pkg/controller/common/util.go
pkg/controller/dataimportcron-controller.go
pkg/controller/datasource-controller.go
pkg/controller/datavolume/clone-controller-base.go
pkg/controller/datavolume/controller-base.go
pkg/controller/datavolume/pvc-clone-controller.go
pkg/controller/storageprofile-controller.go
pkg/image/qemu_test.go
pkg/util/util.go
tests/upload_test.go

> Checks that functions with naked returns are not longer than a maximum
> size (can be zero).
https://github.com/alexkohler/nakedret
Relevant from the GO style guide:
> Naked returns are okay if the function is a handful of lines. Once
> it’s a medium sized function, be explicit with your return values.
https://go.dev/wiki/CodeReviewComments#named-result-parameters
I think a naked return is never easier to read than a regular return,
so I set the linter to always complain about it. Disagreements are
welcome.
```release-note
Enable nakedret linter and populate all naked returns.
```

Enable nakedret linter

---

pkg/importer/data-processor.go
pkg/importer/data-processor_test.go
pkg/importer/http-datasource.go
pkg/importer/imageio-datasource.go
pkg/importer/registry-datasource.go
pkg/importer/s3-datasource.go
pkg/importer/upload-datasource.go
pkg/importer/util.go
pkg/importer/util_test.go
pkg/importer/vddk-datasource_amd64.go
pkg/importer/vddk-datasource_test.go
pkg/uploadserver/uploadserver.go
pkg/util/util.go
tests/framework/pvc.go

**What this PR does / why we need it**: Backports PR #2676 
> Rather than cleaning up everything on target/scratch PVCs, only delete what we may have created
Pretty much the same as #3200, now one version older.
```release-note
More targeted cleanup of target/scratch pvcs (only delete what we may have created)
```

[release-v1.55] Backport more targeted cleanup of target/scratch pvcs (#2676)

---

pkg/controller/dataimportcron-controller.go
tests/BUILD.bazel
tests/dataimportcron_test.go

The dataimportcron tests may affect existing crons in the environment (in addition to the ones deployed by testing)
so we are better off cleaning up after ourselves.
Fixes #
```release-note
NONE
```

Clean up leftover snapshot sources from DataImportCron tests

---

.golangci.yml
pkg/controller/clone/snap-clone_test.go
pkg/controller/populators/util.go
pkg/controller/upload-controller.go
pkg/image/qemu_test.go
pkg/operator/controller/controller_test.go
tests/framework/pvc.go

This PR enables the dupword linter:
> A linter that checks for duplicate words in the source code (usually miswritten)
https://github.com/Abirdcfly/dupword
https://golangci-lint.run/usage/linters/#dupword
It warns about comments and some strings. It does NOT warn about duplicated code (linter `dupl` does this).
-
```release-note
Enable linter dupword to avoid stuttering comments and strings
```

Enable dupword linter

---

Makefile
hack/build/run-vulncheck.sh

Adds a make target to run a vulnerability scan. In the future it would be a good idea to have this in CI.
At the moment there are 5 vulnerabilitites in our codebase:
<details>
<summary>Show vulnerabilities</summary>
```
./hack/build/bazel-docker.sh ./hack/build/run-vulncheck.sh
CDI_CRI: docker, CDI_CONTAINER_BUILDCMD: docker
Making sure output directory exists...
Starting rsyncd
Rsyncing /home/edu/containerized-data-importer to container
Starting bazel server
Go: go1.21.5
Scanner: govulncheck@v1.1.0
DB: https://vuln.go.dev
DB updated: 2024-04-17 19:55:00 +0000 UTC
Scanning your code and 1292 packages across 144 dependent modules for known vulnerabilities...
=== Symbol Results ===
Vulnerability #1: GO-2024-2687
HTTP/2 CONTINUATION flood in net/http …
```

Add make target to scan for vulnerabilities

---

pkg/importer/format-readers.go
pkg/importer/http-datasource.go
pkg/importer/http-datasource_test.go

Follow up for https://github.com/kubevirt/containerized-data-importer/pull/3212.
Due to some performance issues discussed in https://github.com/kubevirt/containerized-data-importer/issues/2809, we stopped using nbdkit for most http imports and decided to use our custom scratch space method for most imports. This new behavior introduced minor differences in some specific flows, such as stopping the [conversion](https://github.com/kubevirt/containerized-data-importer/blob/main/pkg/importer/data-processor.go#L268) of uncompressed raw images.
The conversion process made the actual size of raw images significantly smaller, probably because of qemu's handling of sparse images. The import of raw images without conversion ended up causing failures in some …

Improve http import flow to decide whether to use scratch space or not

---

pkg/storagecapabilities/storagecapabilities.go

There's a bug in the trident CSI driver that causes a snapshot to be left over following each CSI clone:
https://github.com/NetApp/trident/issues/901
This is becoming a problem rapidly once one hits the snapshot limit per volume (golden image): https://kb.netapp.com/onprem/ontap/os/Maximum_number_of_snapshots_supported_by_ONTAP
Fixes #
```release-note
Set default clone strategy for trident ONTAP to "snapshot"
```

Set default clone strategy for trident to snapshot

---

pkg/storagecapabilities/storagecapabilities.go

Fixes #
https://issues.redhat.com/browse/CNV-41449
```release-note
Update portworx CSI to have CSI-clone clone strategy
LVMS tuned to default to CSI clones & snapshot dataimportcron sources
Trident ONTAP tuned to default to snapshot clone strategy & snapshot dataimportcron sources
```

[release-v1.58] Backport profile tunings for several provisioners

---

pkg/monitoring/rules/alerts/operator.go
pkg/storagecapabilities/storagecapabilities.go

In addition add stork-snapshot to unsupported provisioners list, as stork snapshot provisioner does not work with CDI, and shouldn't cause CDIStorageProfilesIncomplete alert.
Fixes # https://issues.redhat.com/browse/CNV-39569
```release-note
```

CDIStorageProfilesIncomplete should not impact operator health

---

pkg/storagecapabilities/storagecapabilities.go

Fixes #
https://issues.redhat.com/browse/CNV-41450
```release-note
Update portworx CSI to have CSI-clone clone strategy
LVMS tuned to default to CSI clones & snapshot dataimportcron sources
Trident ONTAP tuned to default to snapshot clone strategy & snapshot dataimportcron sources
```

[release-v1.57] Backport profile tunings for several provisioners

---

pkg/operator/controller/prometheus.go

Somehow dropped from the manual backport due to monitoring refactoring. Missed by CI since it does not run the destructive lane where the CDIDefaultStorageClassDegraded alert is tested [test_id:10720]. The kubevirt_cdi_dataimportcron_outdated utest does not check the actual CDIDataImportCronOutdated alert but only the metric and labels, as decided in order to save CI time.
Fixes # https://issues.redhat.com/browse/CNV-38918
```release-note
Fix CDIDefaultStorageClassDegraded and CDIDataImportCronOutdated alerts expression
```

[release-v1.58] Fix backport PR #3181 alerts expression

---

pkg/importer/format-readers.go
pkg/importer/http-datasource.go
pkg/importer/http-datasource_test.go
tests/import_test.go

This is a manual backport of https://github.com/kubevirt/containerized-data-importer/pull/3219.
We needed to adapt a functional test to account for DV restarts caused by scratch space.
Fixes # https://issues.redhat.com/browse/CNV-36026
```release-note
Bugfix: Use scratch space when importing non-archived images
```

[release-v1.58] Manual backport of improve http import flow to decide whether to use scratch space or not

---

pkg/importer/format-readers.go
pkg/importer/http-datasource.go
pkg/importer/http-datasource_test.go
tests/import_test.go

This is a manual backport of https://github.com/kubevirt/containerized-data-importer/pull/3219.
We needed to adapt a functional test to account for DV restarts caused by scratch space.
Fixes # https://issues.redhat.com/browse/CNV-36026
```release-note
Bugfix: Use scratch space when importing non-archived images
```

[release-v1.57] Manual backport of improve http import flow to decide whether to use scratch space or not

---

pkg/operator/controller/prometheus.go

Somehow dropped from the manual backport due to monitoring refactoring. Missed by CI since it does not run the destructive lane where the CDIDefaultStorageClassDegraded alert is tested [test_id:10720]. The kubevirt_cdi_dataimportcron_outdated utest does not check the actual CDIDataImportCronOutdated alert but only the metric and labels, as decided in order to save CI time.
Fixes # https://issues.redhat.com/browse/CNV-40360
```release-note
Fix CDIDefaultStorageClassDegraded and CDIDataImportCronOutdated alerts expression
```

[release-v1.57] Fix backport PR #3185 alerts expression

---

pkg/operator/controller/prometheus.go
pkg/storagecapabilities/storagecapabilities.go

Manual backport of #3232
Fixes # https://issues.redhat.com/browse/CNV-41509
```release-note
```

[release-v1.56] CDIStorageProfilesIncomplete should not impact operator health

---

pkg/storagecapabilities/storagecapabilities.go

Manual backport of #3232 without the operator health impact change.
Fixes # https://issues.redhat.com/browse/CNV-41510
```release-note
Add unsupported provisioners for OCS bucket and Stork snapshot
```

[release-v1.55] Add unsupported provisioners for OCS bucket and Stork snapshot

---

pkg/operator/controller/prometheus.go
pkg/storagecapabilities/storagecapabilities.go

Manual backport of #3232
Fixes # https://issues.redhat.com/browse/CNV-41508
```release-note
```

[release-v1.58] CDIStorageProfilesIncomplete should not impact operator health

---

pkg/operator/controller/prometheus.go
pkg/storagecapabilities/storagecapabilities.go

Manual backport of #3232
Fixes # https://issues.redhat.com/browse/CNV-39569
```release-note
```

[release-v1.57] CDIStorageProfilesIncomplete should not impact operator health

---

pkg/monitoring/rules/alerts/operator.go
pkg/storagecapabilities/storagecapabilities.go

Manual backport of #3232
Fixes # https://issues.redhat.com/browse/CNV-41507
```release-note
```

[release-v1.59] CDIStorageProfilesIncomplete should not impact operator health

---

cluster-sync/install.sh

Fixes a line in the cluster-up script that was writing to file `./0` instead of performing a greater-than comparison.
I always had this suspicious file in my git diff and after a couple greps for `> 0`, I found the culprit.
```release-note
NONE
```

Fix cluster-sync wait_cdi_crd_installed timeout check

---

hack/build/docker/builder/Dockerfile

Fixes #3226 
```release-note
NONE
```

Update builder to use golang 1.22.3

---

doc/datavolumes.md
pkg/importer/vddk-datasource_amd64.go
pkg/importer/vddk-datasource_test.go

This pull request fixes the logic error pointed out in #3054, where the VDDK importer tries to merge smaller blocks into one big one, when mapping out the NBD status flags (basically zero, hole, or data) from the source disk. This code was incorrectly neglecting to add the length of the current block to the length of the previous block, so the combined result had the wrong length.
This pull request also avoids a potential integer overflow by changing the type of the struct field that receives this block length from a uint32 to an int64. It further changes the offset field in the same struct from a uint64 to an int64, to avoid a bunch of haphazard integer conversions. There are a few new conversions, but the net result is a bit more …

VDDK: Fix NBD status coalescing for large blocks.

---

pkg/controller/dataimportcron-controller.go

This change caused a unit test to be flaky:
https://github.com/kubevirt/containerized-data-importer/pull/3176/files#
Before, this code would round down to the second, and add 1. Essentially doing a "ceil" on the time delta.
After the change, the round-down part disappeared, so it became a plain +1 rather than a ceil.
The unit test in question has an assertion ensuring that this value is within 0 and 60.
If this value is within 59 and 60:
- Before PR 3176: rounds up to 60 (test passes)
- After PR 3176: is mapped to within 60 and 61 (test fails)
I didn't want to revert to the old code because it was a bit confusing, so I removed the +1, which I understand is there to make sure we don't undershoot (no longer necessary as we don't round down anymore). …

Fix flaky DataImportCron controller reconcile loop unit test

---

cmd/cdi-importer/importer.go
hack/build/bazel-docker.sh
pkg/common/common.go
pkg/controller/common/util.go
pkg/controller/import-controller.go
pkg/controller/import-controller_test.go
pkg/image/BUILD.bazel
pkg/image/directio.go
pkg/image/qemu.go
pkg/image/qemu_test.go
pkg/importer/data-processor.go
pkg/importer/data-processor_test.go
pkg/uploadserver/uploadserver.go
pkg/uploadserver/uploadserver_test.go

For a while now we have been switching between cache=none (direct io) and cache=writeback (page cache) for qemu-img's writes.
We have settled on cache=writeback for quite some time since https://github.com/kubevirt/containerized-data-importer/pull/1919,
however, this has proven to be problematic;
Our pod's live in a constrained memory environment (default limit 600M).
cgroupsv1 compares utilization of page cache vs the host's dirty_ratio.
This means that on a standard system (30% dirty ratio) pages only get forced to disk at 0.3 * HOST_MEM (basically never),
easily triggering OOM on hosts with lots of free memory.
cgroupsv2 does come to the rescue here:
- It considers dirty_ratio against CGROUP_MEM (forced to disk much faster, 0.3 * 600M)
- Has a …

Use direct io with qemu-img convert if pod is OOMKilled

---

hack/build/run-unit-tests.sh

As of Go 1.22, packages with no tests are included in the coverage report. For this project, it meant that the coverage plummeted from 61% down to 17%. This is not because of a lack of tests, but rather the inclusion of >60k lines of generated code that are now considered 'relevant lines'. The project size went from 22k to 90k relevant lines, diluting our coverage.
This PR filters out all the generated files from the coverage report, both in Goveralls and locally when running `make coverage`. This is done programmatically rather than using an allowlist/denylist so that we don't need to maintain it.
After this PR, the number of relevant lines becomes 27k, still greater than the pre-Go1.22 metric. This means that we have around 5k lines of code inside …

Filter out generated files from coverage report

---

go.mod
go.sum
hack/build/run-linters.sh
pkg/monitoring/rules/BUILD.bazel
pkg/monitoring/rules/rules_suite_test.go
pkg/monitoring/rules/rules_test.go
vendor/github.com/grafana/regexp/.gitignore
vendor/github.com/grafana/regexp/BUILD.bazel
vendor/github.com/grafana/regexp/LICENSE
vendor/github.com/grafana/regexp/README.md
vendor/github.com/grafana/regexp/backtrack.go
vendor/github.com/grafana/regexp/exec.go
vendor/github.com/grafana/regexp/onepass.go
vendor/github.com/grafana/regexp/regexp.go
vendor/github.com/machadovilaca/operator-observability/pkg/docs/metrics.go
vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/collector.go
vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/histogram.go
vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/histogram_vec.go
vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/summary.go
vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/summary_vec.go
vendor/github.com/machadovilaca/operator-observability/pkg/operatorrules/prometheusrules.go
vendor/github.com/machadovilaca/operator-observability/pkg/operatorrules/registry.go
vendor/github.com/machadovilaca/operator-observability/pkg/testutil/BUILD.bazel
vendor/github.com/machadovilaca/operator-observability/pkg/testutil/alert_custom_validations.go
vendor/github.com/machadovilaca/operator-observability/pkg/testutil/alert_validation.go
vendor/github.com/machadovilaca/operator-observability/pkg/testutil/linter.go
vendor/github.com/machadovilaca/operator-observability/pkg/testutil/problem.go
vendor/github.com/machadovilaca/operator-observability/pkg/testutil/recording_rule_validation.go
vendor/modules.txt

Apply the following linters:
- [monitoringlinter](https://github.com/kubevirt/monitoring/tree/main/monitoringlinter) that was implemented in https://github.com/kubevirt/monitoring/pull/221, and was designed to enforce https://github.com/kubevirt/community/pull/219.
This linter ensures that all monitoring-related practices are implemented within the `pkg/monitoring` directory using [operator-observability](https://github.com/machadovilaca/operator-observability/tree/main) methods. It verifies that all metrics, alerts and recording rules registrations are centralized in this directory, and restricts the direct use of [Prometheus registration methods](https://pkg.go.dev/github.com/prometheus/client_golang/prometheus#Registerer).
Example for a message …

Apply monitoring linters

---

.golangci.yml
hack/build/bazel-build-builder.sh
hack/update-codegen.sh
pkg/apiserver/apiserver.go
pkg/controller/common/util.go
pkg/controller/config-controller.go
pkg/controller/config-controller_test.go
pkg/controller/import-controller.go
pkg/image/qemu.go
pkg/image/qemu_test.go
pkg/importer/imageio-datasource.go
pkg/importer/vddk-datasource_amd64.go
pkg/importer/vddk-datasource_test.go
pkg/system/prlimit_test.go
tests/apiserver_test.go
tests/cdiconfig_test.go
tests/framework/framework.go
tests/monitoring_test.go
tests/operator_test.go
tools/cdi-func-test-bad-webserver/main.go
tools/cdi-func-test-proxy/main.go

Enables the revive linter:
> Fast, configurable, extensible, flexible, and beautiful linter for Go. Drop-in replacement of golint.
- https://golangci-lint.run/usage/linters/#revive
Golint itself has been deprecated for 3 years.
PR #3193 removes golint from the `make lint-metrics`target.
```release-note
NONE
```

Enable revive linter

---

pkg/controller/dataimportcron-controller.go

When the `DataImportCron` last import `DV` is manually deleted, the controller reconciles, but due to k8s default background cascading deletion, the `PVC` may still temporarily exist, so the controller will not re-create the `DV` even after the `PVC` is deleted, unless it reconciles due to other watched CR like `DataSource`. In the scenario of CNV-39688, since we move from `PVC` source format to snapshot, the `DataSource` won’t update until a snapshot is created, which will never happen. To solve it we add a watch for deletion of DataImportCron-labeled `PVCs`. The change was tested locally, but since it required two storage classes it’s currently out of scope for the existing CI lanes, so it requires tier-2 test. …

Add watch for DataImportCron-labeled PVCs deletion

---

.bazelrc
hack/build/rpm-deps.sh
repo.yaml

Add support for bazeldnf to maintain the rpm lists for s390x in BUILD.bazel
Add configurations necessary for bazeldnf to generate the rpm lists in WORKSPACE and BUILD.bazel, using the information for how to maintain these lists in .bazelrc, repo.yaml and hack/build/rpm-defs.sh as described in https://github.com/kubevirt/containerized-data-importer/issues/3089 and https://github.com/kubevirt/containerized-data-importer/pull/3090
Fixes #3202
- replaces draft PR https://github.com/kubevirt/containerized-data-importer/pull/3203
```release-note …
```

s390x rpm support

---

Makefile

The documentation on the Makefile was outdated and missing in some cases. This PR solves this in two ways:
- Add documentation to undocumented targets
- Re-design help target to make it easier to stay up-to-date.
Up until now, the `help` target was at the end of the file; easy to miss when adding or updating a target. Now, the help message is autogenerated by an awk script the following way:
- Targets with a comment (`target: dep1 dep2 ## COMMENT`): the comment is used in the help message. Having the help message next to the target hopefully makes it more likely to keep it up to date.
- Sections (`##@ SECTION NAME`) This makes the help message a bit easier to read as there are a lot of targets.
The end result is the following:
---
**Which issue(s) …

Update makefile documentation

---

tests/api_validation_test.go
tests/badserver_test.go
tests/cloner_test.go
tests/datavolume_test.go
tests/framework/pod.go
tests/import_proxy_test.go
tests/import_test.go
tests/operator_test.go
tests/smartclone_test.go
tests/upload_test.go

Several tests get information about the state of the cluster by parsing the logs.
Up until now, we had a loop fetching the entire log history and searching for a specific string on it. Local testing showed running the tests (focussed on a single entry in the table) would cause 8.1 MiB of log data to be fetched and parsed per test (with a subsequent enormous error message on failure. On certain test failure we could expect 364 MiB of logs per failed test (2.8 MiB/get * 0.5 gets/second * 270 second timeout).
I reduced this by exploiting two factors:
1. Consectuive GETs need only request new logs (8.1Mib -> 2.8MiB)
2. No need to get logs older than the test itself (2.7MiB -> 60 KiB)
I used this solution for all tests that showed up when grepping for …

Reduce amount of logs fetched by tests that assert on control plane pod logs

---

pkg/controller/dataimportcron-controller.go

Manual backport of #3285
When the DataImportCron last import DV is manually deleted, the controller reconciles, but due to k8s default background cascading deletion, the PVC may still temporarily exist, so the controller will not re-create the DV even after the PVC is deleted, unless it reconciles due to other watched CR like DataSource. In the scenario of CNV-39688, since we move from pvc source format to snapshot, the DataSource won’t update until a snapshot is created, which will never happen. To solve it we add a watch for deletion of DataImportCron-labeled PVCs. The change was tested locally, but since it required two storage classes it’s currently out of scope for the existing CI lanes, so it requires tier-2 test.
**Which issue(s) this PR …

[release-v1.58] Add watch for DataImportCron-labeled PVCs deletion

---

.golangci.yml
cmd/cdi-cloner/clone-source.go
pkg/apiserver/apiserver_test.go
pkg/apiserver/auth-config_test.go
pkg/apiserver/webhooks/datavolume-validate_test.go
pkg/controller/datavolume/import-controller_test.go
pkg/controller/populators/forklift-populator_test.go
pkg/controller/populators/import-populator_test.go
pkg/importer/http-datasource.go
pkg/importer/http-datasource_test.go
pkg/importer/imageio-datasource.go
pkg/uploadproxy/uploadproxy_test.go
pkg/uploadserver/uploadserver.go
pkg/uploadserver/uploadserver_test.go
tests/apiserver_test.go
tests/framework/prometheus.go
tests/upload_test.go
tools/cdi-func-test-bad-webserver/main.go

This linter recommends using standard library variables rather than magic constants, so for example `201` is replaced with `http.StatusAccept`.
```release-note
NONE
```

Enable usestdlibvars linter

---

pkg/controller/dataimportcron-controller.go

Manual backport of #3285
When the DataImportCron last import DV is manually deleted, the controller reconciles, but due to k8s default background cascading deletion, the PVC may still temporarily exist, so the controller will not re-create the DV even after the PVC is deleted, unless it reconciles due to other watched CR like DataSource. In the scenario of CNV-39688, since we move from pvc source format to snapshot, the DataSource won’t update until a snapshot is created, which will never happen. To solve it we add a watch for deletion of DataImportCron-labeled PVCs. The change was tested locally, but since it required two storage classes it’s currently out of scope for the existing CI lanes, so it requires tier-2 test.
**Which issue(s) this PR …

[release-v1.57] Add watch for DataImportCron-labeled PVCs deletion

---

doc/cdi-populators.md
pkg/client/clientset/versioned/typed/forklift/v1beta1/forklift_client.go
pkg/client/informers/externalversions/generic.go
pkg/controller/populators/forklift-populator.go
pkg/controller/populators/forklift-populator_test.go
pkg/operator/controller/controller_test.go
pkg/operator/resources/cluster/controller.go
pkg/operator/resources/crds_generated.go
staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/forklift/register.go
staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/forklift/v1beta1/doc.go

Since forklift 2.7 has to support OCP 4.15 we'll have 2 competing controllers, this PR changes the API group for CDI's so forklift can distinguish between them.
Fixes #
```release-note
Rename API group for forklift controllers to forklift.cdi.kubevirt.io
```

forklift: rename API group

---

tests/clone-populator_test.go
tests/cloner_test.go
tests/import_test.go
tests/upload_test.go

CI lanes have [lots of panicks](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/3292/pull-containerized-data-importer-e2e-nfs/1795116911005011968) in `AfterEach`.
Fixes #
```release-note
NONE
```

Add tests AfterEach nil checks

---

doc/cdi-populators.md
pkg/client/clientset/versioned/typed/forklift/v1beta1/forklift_client.go
pkg/client/informers/externalversions/generic.go
pkg/controller/populators/forklift-populator.go
pkg/controller/populators/forklift-populator_test.go
pkg/operator/controller/controller_test.go
pkg/operator/resources/cluster/controller.go
pkg/operator/resources/crds_generated.go
staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/forklift/register.go
staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/forklift/v1beta1/doc.go

Since forklift 2.7 has to support OCP 4.15 we'll have 2 competing controllers, this PR changes the API group for CDI's so forklift can distinguish between them.
Fixes #
```release-note
Rename API group for forklift controllers to forklift.cdi.kubevirt.io
```

[release-v1.59] manual backport of 'forklift: rename API group'

---

doc/annotations.md
doc/blank-raw-image.md
doc/clone-block-datavolume.md
doc/clone-datavolume.md
doc/clone-from-volumesnapshot-source.md
doc/datavolume-annotations.md
doc/datavolumes.md
doc/debug.md
doc/image-from-registry.md
doc/import-block-pv.md
doc/local-storage-selector.md
doc/preallocation.md
doc/upload.md
manifests/example/blank-image-datavolume.yaml
manifests/example/clone-block-datavolume.yaml
manifests/example/clone-datavolume.yaml
manifests/example/import-archive-block-datavolume.yaml
manifests/example/import-archive-datavolume.yaml
manifests/example/import-kubevirt-block-datavolume.yaml
manifests/example/import-kubevirt-datavolume-gcs.yaml
manifests/example/import-kubevirt-datavolume-secret.yaml
manifests/example/import-kubevirt-datavolume.yaml
manifests/example/registry-image-block-datavolume.yaml
manifests/example/registry-image-datavolume.yaml
manifests/example/upload-block-datavolume.yaml
manifests/example/upload-datavolume.yaml
manifests/templates/upgrade-testing-artifacts.yaml.in

Updates `DataVolume` examples and documentation so they use the `storage` API instead of the `pvc` API, except for a couple of places where the use of `pvc` is relevant (to contrast it to the `storage` API).
Furthermore:
- Removed the `ReadWriteOnce` argument as it is set by default when using the storage API.
- Removed the storage resources requests when cloning from a PVC.
https://issues.redhat.com/browse/CNV-38189
```release-note
NONE
```

Update DataVolume doc references from the 'pvc' API to the 'storage' API

---

cmd/cdi-importer/importer.go
hack/build/bazel-docker.sh
pkg/common/common.go
pkg/controller/common/util.go
pkg/controller/import-controller.go
pkg/controller/import-controller_test.go
pkg/image/BUILD.bazel
pkg/image/directio.go
pkg/image/qemu.go
pkg/image/qemu_test.go
pkg/importer/data-processor.go
pkg/importer/data-processor_test.go
pkg/uploadserver/uploadserver.go
pkg/uploadserver/uploadserver_test.go

Manual backport of https://github.com/kubevirt/containerized-data-importer/pull/3017
Fixes #
```release-note
Use direct io (cache=none) with qemu-img convert if target supports it in case of OOMKilled
```

[release-v1.58] Manual backport of "Use direct io with qemu-img convert if pod is OOMKilled"

---

cmd/cdi-importer/importer.go
hack/build/bazel-docker.sh
pkg/common/common.go
pkg/controller/common/util.go
pkg/controller/import-controller.go
pkg/controller/import-controller_test.go
pkg/image/BUILD.bazel
pkg/image/directio.go
pkg/image/qemu.go
pkg/image/qemu_test.go
pkg/importer/data-processor.go
pkg/importer/data-processor_test.go
pkg/uploadserver/uploadserver.go
pkg/uploadserver/uploadserver_test.go

Manual backport of https://github.com/kubevirt/containerized-data-importer/pull/3017
Fixes #
```release-note
Use direct io (cache=none) with qemu-img convert if target supports it in case of OOMKilled
```

[release-v1.57] Manual backport of "Use direct io with qemu-img convert if pod is OOMKilled"

---

pkg/uploadproxy/uploadproxy.go
pkg/uploadproxy/uploadproxy_test.go

Upload proxy uses the `httputil.ReverseProxy`.
When `httputil.ReverseProxy` fails, it sends a message down the standard library's default logger. This can be seen in the pod's log but the client simply receives a 5xx error and no context.
This PR redirects messages away from the standard logger and into both the k8s logger and the client.
**Changes in virtctl output**
BEFORE
```
unexpected return value 502,
```
AFTER
```
unexpected return value 502, error in upload-proxy: http: proxy error: dial tcp 10.101.34.134:443: connect: connection timed out
```
**Changes in upload-proxy logs**
BEFORE
```
2024/05/09 16:30:08 http: proxy error: dial tcp 172.30.111.109:443: connect: connection timed out
```
AFTER
```
E0605 11:02:45.551559       1 …
```

Make reverse proxy send error messages to klog and to virtctl

---

pkg/controller/populators/import-populator_test.go
pkg/controller/populators/populator-base.go

This makes the valid labels regex that is used to restrict labels that are transferred from a prime PVC to an actual PVC less restrictive, so labels like 'instancetype.kubevirt.io/default-preference' are transferred too.
Fixes #3315 
```release-note
fix: Properly transfer instancetype labels during containerdisk imports
```

fix: Make valid labels regex less restrictive

---

tests/tests_suite_test.go

Avoid panic in tests.
During test setup, pointer framework.ClientsInstance.K8sClient is assigned.  During the test AfterSuite phase, an Eventually loop accesses this pointer.
If the test fails before this assignment, the after-suite will panic.
Pointer assignment:
https://github.com/kubevirt/containerized-data-importer/blob/b6392df9bf943f00c70ae71d37106cc12a576f19/tests/tests_suite_test.go#L123
Panic in AfterSuite, when calling GetTestNamespaceList:
https://github.com/kubevirt/containerized-data-importer/blob/b6392df9bf943f00c70ae71d37106cc12a576f19/tests/tests_suite_test.go#L162
Which defereferences the client pointer in client.CoreV1():
https://github.com/kubevirt/containerized-data-importer/blob/b6392df9bf943f00c70ae71d37106cc12a576f19/tests/utils …

Prevent a panic in test clean-up

---

doc/metrics.md
pkg/controller/storageprofile-controller.go
pkg/controller/storageprofile-controller_test.go
pkg/monitoring/metrics/cdi-controller/storageprofile.go
pkg/monitoring/rules/alerts/operator.go
pkg/operator/resources/cluster/controller.go

On single-node OpenShift, even if none of the default/virt default storage classes supports `ReadWriteMany` (but supports smart clone), we will not fire the `CDIDefaultStorageClassDegraded` alert. We added `degraded` label to `kubevirt_cdi_storageprofile_info` to simplify the alert expression.
jira-ticket: https://issues.redhat.com/browse/CNV-40665
```release-note
Suppress CDIDefaultStorageClassDegraded alert on SNO
```

Suppress CDIDefaultStorageClassDegraded on SNO

---

pkg/storagecapabilities/storagecapabilities.go

Adding storagecapabilities to vSphere provisioner. 
According to the [VMware documentation](https://docs.vmware.com/en/VMware-vSphere-Container-Storage-Plug-in/3.0/vmware-vsphere-csp-getting-started/GUID-4CC48A47-21CC-453C-AC07-5BB95F384B40.html#GUID-4CC48A47-21CC-453C-AC07-5BB95F384B40) and the [compatibility matrices](https://docs.vmware.com/en/VMware-vSphere-Container-Storage-Plug-in/3.0/vmware-vsphere-csp-getting-started/GUID-D4AAD99E-9128-40CE-B89C-AD451DA8379D.html#GUID-D4AAD99E-9128-40CE-B89C-AD451DA8379D), raw block volumes support only `rwo` access:
> Use only single-access ReadWriteOnce raw block volumes. vSphere Container Storage Plug-in does not support raw block volume that use the …

Add vSphere storagecapabilities

---

doc/csi-cloning.md

Update CSI  clone prerequisites and remove the cross storage classes CSI clone limitation.
Fixes #
The CSI clone supports cross storage classes now. See https://github.com/kubernetes-csi/external-provisioner/pull/699
The limitation in CDI was removed in https://github.com/kubevirt/containerized-data-importer/pull/2750/files#diff-6a637cfe899a0436fa6e24865f2b9259f9b8504e40e080e03603830a5504a0c9L754
```release-note
NONE
```

Update csi-cloning prerequisites

---

cluster-sync/sync.sh
tests/upload_test.go

Attempting to use virtctl on this repository's cluster fails:
```
edu@fedora:~/containerized-data-importer$ virtctl image-upload dv hello-example --size=1Gi --image-path cirros-0.6.2-x86_64-disk.img --force-bind
Using existing PVC default/hello-example
the server could not find the requested resource
parse "127.0.0.1:32768": first path segment in URL cannot contain colon
```
This is because the upload proxy override is missing the https prefix:
```
edu@fedora:~/containerized-data-importer$ k describe cdiconfig | grep 'Upload Proxy'
Upload Proxy URL Override:  127.0.0.1:32814
Upload Proxy URL:             127.0.0.1:32814
```
After this fix:
```
edu@fedora:~/containerized-data-importer$ k describe cdiconfig | grep 'Upload Proxy'
Upload Proxy URL …
```

Fix uploadproxy override in cluster-sync

---

pkg/storagecapabilities/storagecapabilities.go

The [current storagecapabilities ](https://github.com/kubevirt/containerized-data-importer/blob/main/pkg/storagecapabilities/storagecapabilities.go#L295)for Dell PowerMax, PowerFlex, PowerScale and PowerStore are defined as: 
`{ {rwx, block}, {rwo, block}, {rwo,file} } `
According to the [DELL documentation](https://dell.github.io/csm-docs/docs/csidriver/), it should be:
PowerMax:
`{ {rwx, block}, {rwo, block}, {rwo, file}, {rox, block} } `
PowerFlex: 
`{ {rwx, block}, {rwo, block}, {rwo, file}, {rox, block}, {rox, file} } `
PowerScale  (block volume mode is not supported):
`{ {rwx, file}, {rwo, file}, {rox, file} } `
PowerStore: 
`{ {rwx, block}, {rwo, block}, {rwo, file}, {rox, block} } `
If the `nfs` …

Fix DELL storagecapabilities

---

api/openapi-spec/swagger.json
cmd/cdi-controller/BUILD.bazel
cmd/cdi-controller/controller.go
pkg/apis/core/v1beta1/openapi_generated.go
pkg/controller/config-controller.go
pkg/controller/config-controller_test.go
pkg/operator/resources/crds_generated.go
staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/zz_generated.deepcopy.go

As a VM owner I want to upload a VM disk to my cluster without needing to use an unsecured TLS connection. I want to import the upload proxy cert into my client.
https://issues.redhat.com/browse/CNV-21214
None of the config controller code is covered by tests, I tried to add test for `watchUploadProxyCA` but it was too much boilerplate and I didn't know what I was doing.
The reconciler is well tested (at least the happy paths) so I could add my own test easily.
```release-note
Expose the upload-proxy's certificate in the CDI config status
```

Expose Upload Proxy certificate in CDI Config status

---

pkg/storagecapabilities/storagecapabilities.go

Adding storagecapabilities to the Huawei provisioner. 
According to [eSDK Huawei Storage Kubernetes CSI Plugins V4.3.0 User Guide 02.pdf](https://github.com/kubevirt/containerized-data-importer/files/15321394/eSDK.Huawei.Storage.Kubernetes.CSI.Plugins.V4.3.0.User.Guide.02.pdf), the provisioner string is `csi.huawei.com` and the storage profile is `{ {rwx, file}, {rwo, file}, {rox, file} }` if `sc.Parameters["protocol"] == "nfs" `and `{ {rwx, block}, {rwo, block}, {rwo, file}, {rox, block}, {rox, file} }` otherwise:
> RWO/ROX/RWOP: supported by all types of volumes. RWOP is supported only by kubernetes 1.22 and later versions.
RWX: supported only by Raw Block volumes and NFS volumes
> Parameter: …

Add Huawei storagecapabilities

---

automation/test.sh
hack/README.md
hack/build/run-functional-tests.sh

Moves the ginkgo focus capabilities to `run-functional-tests.sh`, analogue to the kubevirt repo, so that `CDI_E2E_FOCUS` can be used with `make test-functional`. 
Also with this a go-file path can be passed to `CDI_E2E_FOCUS`  to focus a specific suite using the `--focus-file` ginkgo flag.
---
**Which issue(s) this PR fixes** **:
Fixes Include functional test focus capabilities #3335 
```release-note
NONE
```

Move and extend functional test focus flag

---

hack/build/bazel-docker.sh
pkg/image/directio.go
pkg/image/qemu.go
pkg/image/qemu_test.go

These tests relied on tmpfs not supporting direct IO, but that has changed recently with https://github.com/torvalds/linux/commit/e88e0d366f9cfbb810b0c8509dc5d130d5a53e02.
Refactored the direct IO utils in a way that allows testing without real filesystems.
Fixes #
```release-note
NONE
```

Fix qemu O_DIRECT refusing unit tests

---

tests/import_test.go

This test asserts that there are no failing datavolumes in the cluster, so it can't run in parallel to negative tests, and thus has to remain serial.
Fixes #
```release-note
NONE
```

Make restart count test serial

---

go.mod
go.sum
vendor/modules.txt

This updates the docker/docker library to v25.0.5
Fixes #
```release-note
NONE
```

[release-v1.59] Update docker/docker to v25.0.5

---

pkg/storagecapabilities/storagecapabilities.go

KubeSAN is a CSI plugin for creating volumes on a shared SAN LUN: https://gitlab.com/kubesan/kubesan
This PR makes CDI work out of the box with the KubeSAN CSI plugin.
Fixes #
```release-note
Added KubeSAN CSI plugin storage capabilities so the CDI StorageProfile is automatically populated.
```

Add KubeSAN capabilities

---

tests/monitoring_test.go

What this PR does / why we need it:
Fix runbook_url test to not expect the alert name as the URL suffix, as in some installations the alert name is not the URL suffix.
e.g. in openshift the runbooks are in https://github.com/openshift/runbooks/tree/master/alerts/openshift-virtualization-operator, and the suffix is `<alert-name>.md`.
```release-note
None
```

Fix runbook_url test

---

README.md

This PR updates the README to reflect that the `upload` source and `archive` contentType is a valid combination when using the CDI.  The feature already has a test in place (https://github.com/kubevirt/containerized-data-importer/blob/main/tests/upload_test.go#L353-L429) and I have tested it as well with the latest `virtctl image-upload` command. 
This was discussed on the #virtualization slack channel here: https://kubernetes.slack.com/archives/C8ED7RKFE/p1721845792329019
```release-note
NONE
```

updating documentation to reflect the ability to use the upload source and the archive contentType as a valid combination

---

pkg/importer/vddk-datasource_amd64.go

30 is far too small.  For "chatty" plugins like VDDK many more debugging lines will be printed for simple open calls.  For debugging it is vital that we do not lose this information.  Ideally I would set this to infinity.
Related: https://issues.redhat.com/browse/CNV-44894
```release-note
VDDK datasource: Increase number of nbdkit lines logged
```
CC @mrnold

pkg/importer: Increase number of nbdkit lines logged

---

pkg/controller/dataimportcron-controller.go
tests/dataimportcron_test.go

Recently we've had some back and forth about the appropriate source format for LVMS:
https://github.com/kubevirt/containerized-data-importer/pull/3196
https://github.com/kubevirt/containerized-data-importer/pull/3303
Which presented the need to support a seamless transition between snapshot->PVC sources which was never implemented in hopes that one would not go through such a transition.
Fixes #
```release-note
Allow dataimportcron snap->pvc automatic source switch
```

Allow dataimportcron snap->pvc automatic source switch

---

pkg/operator/controller/callbacks.go
pkg/operator/controller/controller.go
pkg/operator/controller/controller_test.go
pkg/operator/controller/route.go

Users want to create their own routes but certificate rotation make it difficult to keep them up to date
To take advantage of this feature, routes must meet the following restrictions:
1.  Be in the same namespace as cdi-operator
2. have `operator.cdi.kubevirt.io/injectUploadProxyCert: "true"` annotation
Fixes #
https://issues.redhat.com/browse/CNV-31492
```release-note
Inject cdi-uploadproxy CA cert into user created routes
```

Inject cdi-uploadproxy CA cert into user created routes

---

pkg/image/nbdkit.go

Generally use the recommended mix of -D (debug) flags for nbdkit VDDK plugin.  The result is less noisy while containing much useful information.
See also:
https://libguestfs.org/nbdkit-vddk-plugin.1.html#Troubleshooting-performance-problems
```release-note
NONE
```

nbdkit datapath debug

---

hack/build/bazel-build-builder.sh
hack/build/docker/builder/Dockerfile

There are two issues in the builder script atm
- `./hack/build/bazel-build-builder.sh: line 49: DOCKER_PREFIX: command not found`
- git diff returning non zero will exit the script immediately:
```bash
+ git diff-index --quiet HEAD~1 hack/build/docker
make: *** [Makefile:134: builder-push] Error 1
```
https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/logs/push-containerized-data-importer-builder
Fixes #
```release-note
NONE
```

Fix build-builder script

---

pkg/storagecapabilities/storagecapabilities.go

Adding storagecapabilities to Longhorn.
According to [Longhorn's documentation](https://longhorn.io/docs/1.6.1/nodes-and-volumes/volumes/rwx-volumes/) and other external sources, Longhorn supports `rwx` and `rwo` with `block` volume mode.
Fixes #[CNV-42268](https://issues.redhat.com/browse/CNV-42268)
```release-note
Adding storagecapabilities to the longhorn provisioner
```

Add Longhorn storagecapabilities

---

cluster-up/cluster/kind/common.sh
hack/build/bazel-build-builder.sh
hack/build/docker/builder/Dockerfile

This adds s390x support for the builder image, so that the unit tests can run.
Bazel is not necessary for unit testing and not supported for s390x yet, so we skip the installation here.
Fixes the cause of failure for [Add s390x unit test job #3552](https://github.com/kubevirt/project-infra/pull/3552)
Relates to [add s390x support for kubevirt builder. #11097](https://github.com/kubevirt/kubevirt/pull/11097)
```release-note
add s390x support for builder image
```

Add s390x support for cdi builder for unit tests

---

pkg/controller/datavolume/util.go
pkg/controller/datavolume/util_test.go
tests/BUILD.bazel
tests/datavolume_test.go
tools/cdi-func-test-registry-init/populate-registry.sh

de5ba85 started updating DataVolumes when reconciled, adding any labels found on PVC or DataSource sources. This PR is a follow up that starts adding labels also from VolumeSnapshots and from Registry imported PVCs.
Fixes #2839
```release-note
Default instance type labels are now added from cloned VolumeSnapshots to DataVolumes
Default instance type labels are now added from registry imported PVCs to DataVolumes
```

feat(DataVolume): Add default instance type labels from VolumeSnapshots and from Registry imports

---

pkg/uploadserver/uploadserver.go
pkg/util/BUILD.bazel
pkg/util/file.go
pkg/util/file_test.go
pkg/util/util.go
pkg/util/util_test.go
tests/cloner_test.go

Currently the DataVolume preallocation setting is only honored in filesystem->filesystem clones.  This PR adds support for:
filesystem->block
block->block
block->filesystem
It does this by breaking the image stream into 32k blocks.  If a block is all zeros, then the zeros will not be directly written.  Instead, zero ranges will be coalesced and the appropriate API for the target will be called to "mark" the zero range.  For filesystem volumes, truncate is called.  For block devices, the "hole punch" API is used.
Fixes #
https://issues.redhat.com/browse/CNV-39213
**Special notes for your …

Properly handle DataVolume preallocation setting for all host assisted (copy) clones

---

pkg/image/nbdkit.go
pkg/importer/http-datasource.go

Passing passwords on the command line is not secure.  nbdkit lets you pass them via several secure mechanisms, for this I used the password=+temporary method (where "temporary" is a filename).
```release-note
NONE
```

nbdkit: Use password=+temporary to send passwords securely

---

pkg/controller/common/util.go
pkg/controller/common/util_test.go
pkg/controller/dataimportcron-controller.go
pkg/controller/dataimportcron-controller_test.go
pkg/controller/datasource-controller.go
pkg/controller/datasource-controller_test.go
pkg/controller/populators/import-populator.go
pkg/controller/populators/populator-base.go
tests/dataimportcron_test.go
tests/datasource_test.go
tests/utils/populators.go

Copy labels from the source of a DataSource (DV/PVC/VolumeSnapshot) to the labels of the DataSource. This allows to make use of labels which were originally defined as env vars on a containerdisk.
Fixes #
```release-note
Copy labels from the source of a DataSource (DV/PVC/VolumeSnapshot)
```

feat: Copy labels from source to DataSource

---

BUILD.bazel
Makefile
hack/build/build-functest.sh
hack/build/build-ginkgo.sh
hack/build/config.sh
hack/ci/build-functest.sh

Today we have the ginkgo CLI brought into the builder and also to the project itself. This results in
```
Ginkgo detected a version mismatch between the Ginkgo CLI and the version of Ginkgo imported by your packages:
Ginkgo CLI Version:
2.12.0
Mismatched package versions found:
2.17.1 used by tests
```
This commit provides the necessary build adaptations to get rid of the builder ginkgo CLI dependency.
Fixes #
```release-note
NONE
```

Setup ginkgo cli build properly to avoid double dep

---

hack/build/docker/builder/Dockerfile

Fix flakiness of gradle builds by installing deps in builder container
changes based on: https://github.com/kubevirt/kubevirt/pull/12552
Fixes #
```release-note
apidocs: remove gradle dep (builder)
```

apidocs: remove gradle dep (builder)

---

hack/build/build-ginkgo.sh

The directory creation was covered by cluster-sync which is not used by postsubmits, and thus they are now broken:
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/push-containerized-data-importer-main/1824607154284269568
Fixes #
```release-note
NONE
```

Fix ginkgo build script that breaks postsubmits

---

pkg/image/nbdkit.go
pkg/importer/http-datasource.go
pkg/importer/vddk-datasource_amd64.go
pkg/importer/vddk-datasource_test.go
tools/vddk-test/vddk-test-plugin.c

Fixes #
```release-note
Add nbdkit command line parameters to improve reliability of multi-stage VDDK imports.
```

[release-v1.58] Manual backport for VDDK related PRs 3361, 3363, 3385

---

pkg/image/nbdkit.go
pkg/importer/vddk-datasource_amd64.go
pkg/importer/vddk-datasource_test.go
tools/vddk-test/vddk-test-plugin.c

As discussed in [CNV-44894](https://issues.redhat.com/browse/CNV-44894), some VMs show `Error 13 (You do not have access rights to this file) ` when attempting to access snapshots for a warm migration. This mostly appears to affect Windows VMs with VMware guest tools installed. Passing the `snapshot` parameter to nbdkit avoids the error and allows delta copies to be applied to a multi-stage data volume.
This pull request adds the `snapshot` parameter to the nbdkit command line when a VDDK data volume is given a checkpoint to copy. It also adds a `transports` parameter to avoid a crash in the VDDK (see [RHEL-54377](https://issues.redhat.com/browse/RHEL-54377)).
Fixes …

VDDK: pass snapshot ID through to nbdkit.

---

pkg/util/file.go

The linter find this error in some archs. Paradoxically it works on x86. This was introduced in the commit
3c06e26bacac7d0de43a8cf20884574c95237423
**What this PR does / why we need it**: s390x arch enablement
Fixes #
```release-note NONE
```

fix: mismatched type (stat.Bsize to int64)

---

pkg/controller/clone/csi-clone_test.go
pkg/controller/clone/planner_test.go
pkg/controller/clone/prep-claim.go
pkg/controller/clone/prep-claim_test.go
pkg/controller/clone/rebind_test.go
pkg/controller/clone/snap-clone_test.go
pkg/controller/common/util.go
pkg/controller/datavolume/static-volume_test.go
pkg/controller/populators/forklift-populator_test.go
pkg/controller/populators/import-populator_test.go
pkg/controller/populators/populator-base.go
pkg/controller/populators/upload-populator_test.go
pkg/controller/transfer/pvc.go

This Pull Request ensures that we only proceed with PVC' deletion after confirming the target PVC is rebound.
Fixes # https://issues.redhat.com/browse/CNV-45479
```release-note
Bugfix: Fix PVC deletion logic in CDI populators
```

Fix PVC deletion logic in populators

---

pkg/operator/controller/callbacks.go
pkg/operator/controller/controller.go
pkg/operator/controller/controller_test.go
pkg/operator/controller/route.go

manual backport of #3380
Fixes #
```release-note
Inject cdi-uploadproxy CA cert into user created routes
```

[release-v1.59] Inject cdi-uploadproxy CA cert into user created routes

---

hack/build/bazel-build-builder.sh

There was an issue building the builder image with emulation.
The git diff check seemed to prevent the build to run, which should also be done in prow.
The Plattform check is made more readable as well as use the rpm list instead of a specific location.
```release-note
NONE
```

Remove git diff, refine plattform check for multiarch builder

---

pkg/controller/populators/import-populator.go

Similar to 2fa5f27, make copying of annotations from a prime PVC to a target PVC more robust, by moving it before rebinding the PV from prime to target. This way we can ensure the annotations are already present once the PVC becomes ready.
Fixes #
```release-note
None
```

fix(import-populator): Make copying of annotations more robust

---

hack/build/config.sh

Following the fix to the muliarch build of the builder image - aarch64 and s390x builder images are now available.
Update to use this new image.
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/push-containerized-data-importer-builder/1829421194286206976
Fixes #
/cc @akalenyu @awels 
```release-note
NONE
```

builder: Update to latest builder version which includes s390x image

---

hack/build/docker/builder/Dockerfile

Apparently some folks are running the builder as non-root and thus cannot use the bazel binary.
Fixes #
```release-note
NONE
```

Make bazel binary world executable

---

pkg/controller/import-controller.go
pkg/controller/import-controller_test.go
pkg/controller/storageprofile-controller_test.go
pkg/controller/util.go
pkg/controller/util_test.go
pkg/util/util.go
tests/cloner_test.go

It is possible the source image is fully allocated and in that case the scratch space would not be large enough to hold the disk image. This takes fsOverhead into account when calculating the scratch space size.
Fixes #
```release-note
Increased size of scratch space to take fs overhead into account.
```

Ensure scratch space is large enough to hold disk image

---

pkg/controller/import-controller.go
pkg/controller/import-controller_test.go
pkg/controller/storageprofile-controller_test.go
pkg/controller/util.go
pkg/controller/util_test.go
pkg/util/util.go
tests/cloner_test.go

Manual backport of https://github.com/kubevirt/containerized-data-importer/pull/3384
```release-note
Increased size of scratch space to take fs overhead into account.
```

[release-v1.59] Ensure scratch space is large enough to hold disk image

---

pkg/controller/BUILD.bazel
pkg/controller/dataimportcron-controller.go
pkg/controller/dataimportcron-controller_test.go

Until now we've never performed the necessary adjustments when the desired storage class changed.
Instead, we documented it and relied on the user to perform the cleanup of actual sources.
This commit starts doing that on behalf of the user.
Fixes #
```release-note
Handle desired storage class changes automatically in cron controller by deleting old storage class sources
```

Handle storage class changes automatically in cron controller

---

pkg/apis/core/v1beta1/openapi_generated.go
pkg/apiserver/webhooks/transfer-validate.go
pkg/apiserver/webhooks/transfer-validate_test.go
pkg/operator/resources/cluster/BUILD.bazel
pkg/operator/resources/cluster/object-transfer.go
pkg/operator/resources/crds_generated.go
staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_transfer.go

Added warnings and comments to ObjectTransfer crd and webhook.
Reference to relevant github issue:
https://github.com/kubevirt/containerized-data-importer/issues/3417
```release-note
Deprecating ObjectTransfer feature
```

Deprecate ObjectTransfer feature

---

BUILD.bazel
Makefile

Need to build e2e and functional tests for s390x. Therefore need to incorporate a `container bundle` for s390x test images that omits tests for features that are unsupported on s390x such as vddk, ovirt, tinycore and cirros. 
Fixes #3423 
@jschintag the test for this mod is in https://gist.github.com/cfilleke/8df35222b7066ac38981e2b7fb2f79d6
```release-note
provides s390x support for functional tests
```

define container bundles for s390x test images that omit tests for features unsupported in s390x

---

Makefile

When building natively on ARM or s390x, the default architecture is set to x86_64. This can lead to issues, as Bazel may not be able to find the corresponding toolchain, resulting in a failed build process.
**What this PR does / why we need it**: multiarch
Fixes #
```release-note NONE
NONE
```

feat: Set default host architecture in makefile

---

Makefile
hack/build/in-docker.sh

As we don't really need bazel for the unit tests I'd run them using `in-docker.sh` instead of `bazel-docker.sh`
This would also solve some issues on `s390x` where bazel is currently not available.
Fixes https://github.com/kubevirt/project-infra/pull/3552
```release-note
NONE
```

Run unit-tests without bazel

---

automation/prow_periodic_push.sh

As a prerequisite for the s390x nightly build prow job (https://github.com/kubevirt/project-infra/pull/3627), an additional `BUILD_ARCH` is necessary. 
I decided to catch the architecture (_e.g. s390x_) and the crossbuild version (_e.g. crossbuild_s390x_)  to give the CI the freedom to either change the `BUILD_ARCH` parameter in the future or support native builds.
```release-note
Add s390x nightly build automation
```

Add s390x and native BUILD_ARCH in periodic automation

---

hack/build/docker/builder/Dockerfile

The builder on this branch [can't](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/push-containerized-data-importer-builder/1835304934338203648) be built with `latest` for some tools:
```
go: golang.org/x/tools/cmd/goimports@latest (in golang.org/x/tools@v0.25.0): go.mod:3: invalid go version '1.22.0': must match format 1.23
```
Freezing to current versions in known & working builder.
Fixes #
```release-note
NONE
```

[release-v1.58] Freeze some go tool versions in corresponding builder

---

pkg/controller/import-controller.go
pkg/controller/import-controller_test.go
pkg/controller/storageprofile-controller_test.go
pkg/controller/util.go
pkg/controller/util_test.go
pkg/image/nbdkit.go
pkg/util/util.go
tests/cloner_test.go

Manual backport of https://github.com/kubevirt/containerized-data-importer/pull/3384
```release-note
Increased size of scratch space to take fs overhead into account.
```

[release-v1.58] Ensure scratch space is large enough to hold disk image

---

tools/cdi-func-test-file-host-init/BUILD.bazel

s390x nginx in functional tests helper images needs to be installed when `BUILD_ARCH` is `s390x` or `crossbuild-s390x`
```release-note
NONE
```

bug fix nginx arch in BUILD.bazel

---

pkg/storagecapabilities/storagecapabilities.go

Add static provisioning to the `UnsupportedProvisioners` list to reduce alert noise, as it's not helpful in this case. Currently in static provisioning we try to populate the `StorageProfile` with `ClaimPropertySets` based on the existing PVs, and if not found the `CDIStorageProfilesIncomplete` alert is fired.
jira-ticket: https://issues.redhat.com/browse/CNV-44335
```release-note
Suppress alerting for static provisioning
```

Suppress alerting for kubernetes.io/no-provisioner

---

doc/datavolumes.md
doc/os-image-poll-and-update.md

Fixes #
```release-note
NONE
```

Docs for dataimportcron storage class switching

---

pkg/storagecapabilities/storagecapabilities.go

Manual backport of #3449
Add static provisioning to the unsupported provisioners list to reduce alert noise, as it's not helpful in this case. Currently in static provisioning we try to populate the `StorageProfile` with `ClaimPropertySets`based on the existing PVs, and if not found the `CDIStorageProfilesIncomplete` alert is fired.
jira-ticket: https://issues.redhat.com/browse/CNV-44335
```release-note
Suppress alerting for static provisioning
```

[release-v1.59] Suppress alerting for kubernetes.io/no-provisioner

---

doc/block_cri_ownership_config.md

Hi, in the [Cozystack](github.com/aenix-io/cozystack) project, we recently upgraded to Containerd v2 and noticed that the old option is no longer functioning. It has now been moved to a different section. I'd like to update the documentation to help others quickly find the solution.
I prepared a set of fixes:
- Original issue https://github.com/aenix-io/cozystack/issues/397
- CDI docs: https://github.com/kubevirt/containerized-data-importer/pull/3452
- Kubernetes docs: https://github.com/kubernetes/website/pull/48198
Cheers
fixes #3455
```release-note
Document device_ownership_from_security_context=true for Containerd v2
```

Document device_ownership_from_security_context=true for Containerd v2

---

pkg/importer/data-processor.go

Various storage providers may provision block devices larger than the size requested by the user. This is often due to LVM or ZFS rounding up to the nearest extent size. (see https://github.com/LINBIT/linstor-server/issues/421#issuecomment-2407406702 and https://github.com/kubevirt/containerized-data-importer/issues/3159#issuecomment-2410182504)
Currently, CDI checks the requested size in the PVC and fails the upload if the original block device is larger than the requested size. 
This PR changes logic to take requestImageSize into account only for filesystem volumes
Another try to fix https://github.com/kubevirt/containerized-data-importer/issues/3159 …

Fix uploading for block devices that exceed requested size

---

pkg/system/prlimit_test.go

Fix the prlimit unit test error on Arm64 platform
Fixes #3467
```release-note
NONE
```

unit-test, arm64: Add memory limit for prlimit test

---

pkg/importer/vddk-datasource_amd64.go
pkg/importer/vddk-datasource_test.go

Instead of going to resize phase, go directly to completed phase for apply the delta snapshot. Resizing has already happened when importing the initial snapshot.
This will cause validation of the size to not happen every single delta. Since the resize steps validates the available space on the target.
This was causing issues on filesystem volumes where the space was being used and the available space is less than the virtual size of the disk. We don't care about the available space at this point since we already verified there was enough space on the initial snapshot import.
Fixes …

Go to completed phase after apply delta on warm import

---

pkg/operator/resources/namespaced/apiserver.go

We have a use case where we run `kubevirt/cdi` with `HostNetwork=true`
This PR is just adding `containerPort` explicitly when creating the deployment for `cdi-apiserver` so that Kubernetes can pro-actively detect if a pod needs to be assigned to other nodes in case the port is already taken.
```release-note
Explicitly declaring containerPort in cdi-apiserver deployment
```

Add default containerPort for cdi-apiserver deployment

---

pkg/operator/controller/callbacks.go
pkg/operator/controller/scc.go

"Successfully ensured SecurityContextConstraint exists" Event was being created every time cdi-operator reconciled.
Reduced to only when SCC is created/updated
Fixes #
```release-note
Reduce frequency of SCC management Events
```

Reduce frequency of SCC management Events

---

pkg/controller/dataimportcron-controller.go

If the dataimportcron status has an empty currentImports, the returned PVC will be nil and
handleSnapshot will be called. handleSnapshot should check for nil PVC before proceeding.
This can happen when installing CDI and KubeVirt together with ceph on a cloud platform. The cloud platform will have a default storage class, which causes the imports to start. Then ceph becomes ready and switches the default virt class to itself. This then causes the imports to switch and somehow the currentImports is empty which causes the PVC to be nil and that causes a 
nil pointer exception in handleSnapshots. …

Handle potential nil pointer in handleSnapshot

---

pkg/apiserver/webhooks/datavolume-validate.go

There is an open issue in github to remove the claim adoption feature gate:
https://github.com/kubevirt/containerized-data-importer/issues/3480 Once the FG is removed we should remove the check in the webhook that verifies if it allowed to have an existing PVC.
Fixes #
```release-note
NONE
```

webhooks/datavolume: comment about remove check of claim adoption

---

cluster-sync/sync.sh

`vddk` and `imagio` in not available on s390x and won't be in the near future.
Because of this I propose a exclusion of the corresponding func-test images, when calling `cluster-sync`
```release-note
NONE
```

Exclude Unsupported Func-Test Images for s390x

---

doc/datavolumes.md
pkg/importer/vddk-datasource_amd64.go
pkg/importer/vddk-datasource_test.go

Manual backport of #3242
Fixes #
https://issues.redhat.com/browse/CNV-50393
```release-note
Fix issue #3054, VDDK failure with "No new block status data at offset" messages.
```

[release-v1.58] Fix NBD status coalescing for large blocks

---

pkg/storagecapabilities/storagecapabilities.go

Manual backport of #3290
jira-ticket: https://issues.redhat.com/browse/CNV-50475
```release-note
Add storagecapabilities for longhorn provisioner
```

[release-v1.59] Add Longhorn storagecapabilities

---

pkg/operator/resources/utils/common.go

Make sure TerminationMessagePolicy/Path are set when creating cdi-apiserver
Fixing regression introduced in #3465
Fixes #
```release-note
Make sure TerminationMessagePolicy/Path are set when creating cdi-apiserver
```

cdi-operator updating cdi-apiserver all the time

---

pkg/controller/clone/csi-clone.go
pkg/controller/clone/csi-clone_test.go
pkg/controller/clone/host-clone.go
pkg/controller/clone/host-clone_test.go
pkg/controller/clone/snap-clone.go
pkg/controller/clone/snap-clone_test.go
pkg/controller/common/util.go
pkg/controller/populators/import-populator_test.go
pkg/controller/populators/populator-base.go
pkg/controller/populators/upload-populator_test.go

When backing up with Velero if a PVC is terminating then the backup is marked as PartiallyFailed, while the backup is still valid to use and its more of a warning, PVC' should be transparent to the user so have the backup partiallyFailed because of PVC' is a bad user experience. To fix that added to all our PVC' an annotation so it will be excluded from the Velero backup.
```release-note
NONE
```

Populators: Add to PVC' exclude velero backup annotation

---

go.mod
staging/src/kubevirt.io/containerized-data-importer-api/go.mod
vendor/modules.txt

This seems to be the standard, plus, if we don't do this we break the importing project's go.mod with our preferred specified patch version.
https://github.com/kubevirt/kubevirt/pull/12584/commits/73f66750d10bff34551404803d115469088a8ca7
Hitting an issue at https://github.com/kubevirt/kubevirt/pull/13152/files#r1824875505
Fixes #
```release-note
Standardize go.mod to not specify patch version
```

Standardize setting go.mod to minor

---

automation/prow_periodic_push.sh

This will allow user to query (amd64):
curl -sL https://storage.googleapis.com/kubevirt-prow/devel/nightly/release/kubevirt/containerized-data-importer/latest"
For arm64, it will be:
curl -sL https://storage.googleapis.com/kubevirt-prow/devel/nightly/release/kubevirt/containerized-data-importer/latest-arm64"
and for s390:
curl -sL https://storage.googleapis.com/kubevirt-prow/devel/nightly/release/kubevirt/containerized-data-importer/latest-s390x"
That follows kubevirt/kubevirt standard
```release-note
None
```

Add the "latest" endpoint for the nightly manifest

---

doc/datavolumes.md
pkg/importer/vddk-datasource_amd64.go
pkg/importer/vddk-datasource_test.go

This backports #3242 to 1.57, which gets all the currently known VDDK warm-migration fixes into CNV 4.14. Follow-on for #3501. 
```release-note
Fix issue #3054, VDDK failure with "No new block status data at offset" messages
```

[release-v1.57] Backport 3242 VDDK: Fix NBD status coalescing for large blocks.

---

cmd/cdi-controller/controller.go

This is tech debt that was left from https://github.com/kubevirt/containerized-data-importer/pull/3314#discussion_r1660113610;
Basically, the config-controller is broken when using ingress, as the first
GET call for the secret attempts to start caching them, and the RBAC for that is missing.
https://sdk.operatorframework.io/docs/faqs/#after-deploying-my-operator-i-see-errors-like-failed-to-watch-external-type
Fixes #3515 
```release-note
BugFix: config controller broken with ingresses
```

Limit secret caching to CDI namespace

---

automation/prow_periodic_push.sh

The nightly build commit file should be under the specific build directory, but was placed under the parent directory by mistake.
This PR fixes the commit file location.
The right location is:
https://storage.googleapis.com/kubevirt-prow/devel/nightly/release/kubevirt/containerized-data-importer/{latest}/commit
(while "latest" is https://storage.googleapis.com/kubevirt-prow/devel/nightly/release/kubevirt/containerized-data-importer/latest)
The wrong location is here:
https://storage.googleapis.com/kubevirt-prow/devel/nightly/release/kubevirt/containerized-data-importer/commit
```release-note
None
```

Fix the location of the nightly commit file

---

pkg/controller/clone/csi-clone.go
pkg/controller/clone/csi-clone_test.go
pkg/controller/clone/host-clone.go
pkg/controller/clone/host-clone_test.go
pkg/controller/clone/snap-clone.go
pkg/controller/clone/snap-clone_test.go
pkg/controller/common/util.go
pkg/controller/populators/import-populator_test.go
pkg/controller/populators/populator-base.go
pkg/controller/populators/upload-populator_test.go

When backing up with Velero if a PVC is terminating then the backup is marked as PartiallyFailed, while the backup is still valid to use and its more of a warning, PVC' should be transparent to the user so have the backup partiallyFailed because of PVC' is a bad user experience. To fix that added to all our PVC' an label so it will be excluded from the Velero backup.
This is a fix for previous PR
https://github.com/kubevirt/containerized-data-importer/pull/3500 Which added an annotation instead of label by accident.
Jira-ticket: https://issues.redhat.com/browse/CNV-51023
Fixes #
**Special notes …

Populators: Add to PVC' exclude velero backup label

---

pkg/controller/upload-controller.go
pkg/controller/upload-controller_test.go
pkg/uploadserver/uploadserver.go
pkg/uploadserver/uploadserver_test.go

healthcheck used to be on a dedicated port for "reasons" and by that I mean I was too lazy to properly set up the tls configuration and check authz in upload handlers
This one is for @akalenyu and @0xFelix: I know I told you this wasn't possible but here you go.
Fixes #3450
```release-note
BugFix: cdi-uploadserver reporting readiness more honestly resulting in concurrent image uploads failing less
```

cdi-uploadserver: healthcheck and application use same port

---

pkg/importer/vddk-datasource_amd64.go
pkg/importer/vddk-datasource_test.go

Manual cherry pick of https://github.com/kubevirt/containerized-data-importer/pull/3534 to speed things up
Fixes #
```release-note
VDDK Fix Incomplete transfer of change blocks leads to data corruption
```

[release-v1.60] Manual cherry pick of CNV-51521 fix

---

pkg/importer/vddk-datasource_amd64.go
pkg/importer/vddk-datasource_test.go

**Fix**: Query the changed areas by every 2000 block chunks, combine the chunks together and request the next QueryChangedDiskAreas to start from the end of the last block. Once the QueryChangedDiskAreas returns less than 2000 blocks we know that it was the last chunk and can continue with the disk import.
**Issue**: When the user has a large disk with over 2000 changed blocks the QueryChangedDiskAreas returns only first 2000 changed blocks. The disk is not getting all the changes from the VMware Change Block Tracking and this can cause disk corruption.
Fixes https://issues.redhat.com/browse/CNV-51521
```release-note
VDDK Fix Incomplete transfer of change blocks …
```

CNV-51521 | Fix Incomplete transfer of change blocks leads to data corruption

---

pkg/storagecapabilities/storagecapabilities.go

add IBM Block Storage CSI driver support for RWX in the default storage profile. this is required, as upcoming IBM Block Storage CSI driver will add support for RWX. We have several customers that would like to Beta test the upcoming IBM Block Storage CSI driver release, specifically for VM virtualization and live-migration, and we need Openshift to be updated accordingly
Fixes #
Add RWX to the IBM Block Storage CSI driver default storage profile
```release-note
IBM Block Storage CSI driver now supports RWX access mode
```

add IBM Block Storage CSI driver support for RWX

---

pkg/apiserver/webhooks/BUILD.bazel
pkg/apiserver/webhooks/pvc-mutate_test.go
pkg/controller/datavolume/util.go

When there is no default `StorageClass` and no virt default `StorageClass`, creating a `PVC` with no `StorageClass` specified will cause a segfault in the webhook:
```
Error from server (InternalError): error when creating
"pvc_render.yaml": Internal error occurred: failed calling webhook
"pvc-mutate.cdi.kubevirt.io": failed to call webhook: Post
"[https://cdi-api.cdi.svc:443/pvc-mutate?timeout=10s](https://cdi-api.cdi.svc/pvc-mutate?timeout=10s)": EOF
```
In cdi-apiserver log:
```
panic({0x1b49360?, 0x3295550?})
GOROOT/src/runtime/panic.go:770 +0x132
kubevirt.io/containerized-data-importer/pkg/controller/datavolume.
renderPvcSpecVolumeModeAndAccessModesAndStorageClass({0x2164d00,
0xc000156090}, {0x0, 0x0}, 0x0?, 0x0, 0xc0002e86a8, {0x1e09ed8?, …
```

Fix PVC webhook rendering segfault

---

automation/test.sh
pkg/controller/datavolume/clone-controller-base.go
pkg/controller/datavolume/pvc-clone-controller.go
pkg/controller/datavolume/pvc-clone-controller_test.go
pkg/controller/datavolume/snapshot-clone-controller.go
tests/cloner_test.go

Apparently, it's possible that the size detection pod
sticks around even if the dv is succeeded/deleted.
I think this belongs in the cleanup loop anyway
Fixes #
https://issues.redhat.com/browse/CNV-52272
```release-note
BugFix: size-detection pod is not always cleaned after it completes
```

Move size detection pod deletion to cleanup

---

automation/test.sh
pkg/controller/datavolume/clone-controller-base.go
pkg/controller/datavolume/pvc-clone-controller.go
pkg/controller/datavolume/pvc-clone-controller_test.go
pkg/controller/datavolume/snapshot-clone-controller.go
tests/cloner_test.go

Manual backport of https://github.com/kubevirt/containerized-data-importer/pull/3553
Fixes #
```release-note
BugFix: size-detection pod is not always cleaned after it completes
```

[release-v1.61] Manual backport "Move size detection pod deletion to cleanup"

---

pkg/controller/dataimportcron-controller.go
pkg/controller/util.go
tests/dataimportcron_test.go

Add `DataVolume` not-`Running` condition reason `ImagePullFailedReason` for `DataImportCron` controller deletion of erroneous DVs.
In `[test_id:8266] succeed deleting error DVs`, we exercise this flow by injecting a nonexistent digest for the registry import, which did not lead us to the `ImagePullFailed` flow but the usual `GenericError` one, as the container status got the `InvalidImageName` reason because the digest was not 64 long. Fixed that.
Added `InvalidImageName` reason as a trigger of `ImagePullFailed` as well.
Fixes #
```release-note
Fix ImagePullFailed handling in DataImportCron controller
```

Fix ImagePullFailed handling in DIC controller

---

tests/dataimportcron_test.go

As commented by @akalenyu : the condition check flakes because the switch to snapshot boot sources is almost instant. The `DataImportCron` never becomes "not ready" following the switch. We also moved the DIC "ready" check after the snapshot "ready" check, otherwise we may check it before it's "not ready", which checks nothing.
jira-ticket: https://issues.redhat.com/browse/CNV-40016
```release-note
NONE
```

Fix flaky DataImportCron volume snapshot test

---

BUILD.bazel
automation/test.sh
cluster-sync/ephemeral_provider.sh
cluster-sync/sync.sh
tests/datavolume_test.go
tests/framework/pvc.go
tests/import_test.go
tests/upload_test.go

Enable e2e test works on Arm64 platform.
1. Make cluster-sync work on kind provider
2. Disable VDDK deployment on Arm64
3. Label VDDK e2e tests, thus we can skip them
4. Fix several e2e tests
Fixes #3466
```release-note
None
```

e2e, arm64: make the e2e tests works of Arm64 platform

---

pkg/controller/datavolume/conditions.go
pkg/controller/datavolume/conditions_test.go
pkg/controller/datavolume/import-controller_test.go
tests/csiclone_test.go
tests/datasource_test.go
tests/datavolume_test.go

Align `DataVolume` `Bound` condition with the `Ready` condition when the `PVC` does not exist or has no phase set.
Fixes #
```release-note
Set DataVolume Bound condition to False instead of Unknown
```

Set DV Bound condition to False instead of Unknown

---

Makefile
automation/prow_periodic_push.sh
hack/build/bazel-build-images.sh
hack/build/bazel-generate.sh
hack/build/bazel-push-images.sh
hack/build/common.sh
hack/build/multi-arch.sh
hack/build/push-container-manifest.sh

Build and publish multi-arch images and manifest, include: x86_64, arm64 and s390x
Fixes #3556
```release-note
NONE
```

Build and publish multi-arch images and manifest

---

hack/build/run-functional-tests.sh

While using ginkgos `--label-filter` through `$CDI_LABEL_FILTER` [with operators](https://onsi.github.io/ginkgo/#spec-labels) the whitespaces and special characters result in a faulty final command.
For example in the current state when having `CDI_LABEL_FILTER='!VDDK && !ImageIO'` we get:
```shell
ginkgo '--label-filter=!VDDK' '&&' '!ImageIO' 
```
This only filters out VDDK and ignores ImageIO.
To overcome this I propose to use a bash array to construct the final command, enabling the use of operators without having to use escaping or `eval`
```release-note
NONE
```

switch to bash array to construct ginkgo cmd

---

doc/datavolumes.md
manifests/example/vddk-args-annotation.yaml
manifests/example/vddk-args-configmap.yaml
pkg/common/common.go
pkg/controller/common/util.go
pkg/controller/import-controller.go
pkg/controller/import-controller_test.go
pkg/controller/populators/import-populator_test.go
pkg/controller/populators/populator-base.go
pkg/image/nbdkit.go
tests/datavolume_test.go
tools/vddk-test/vddk-test-plugin.c

This is a 1.58 cherry-pick of https://github.com/kubevirt/containerized-data-importer/pull/3572
```release-note
Allow extra VDDK configuration parameters to be passed to VDDK importer pods.
```

[release-v1.58] CNV-52722: Pass through extra VDDK configuration options to importer pod.

---

doc/os-image-poll-and-update.md
pkg/apiserver/webhooks/dataimportcron-validate.go
pkg/controller/dataimportcron-controller.go
pkg/controller/dataimportcron-controller_test.go

A `PVC` from any namespace can now be the source for a `DataImportCron`. The source digest is based on the `PVC` `UID`, which is polled by the schedule similarly to `ImageStream`, so when a new `PVC` is detected it will be imported.
jira-ticket: https://issues.redhat.com/browse/CNV-55496
```release-note
Add PVC source support for DataImportCron
```

Add PVC source support for DataImportCron

---

automation/test.sh
pkg/controller/datavolume/clone-controller-base.go
pkg/controller/datavolume/pvc-clone-controller.go
pkg/controller/datavolume/pvc-clone-controller_test.go
pkg/controller/datavolume/snapshot-clone-controller.go
tests/cloner_test.go

Manual backport of https://github.com/kubevirt/containerized-data-importer/pull/3553
Fixes #
```release-note
BugFix: size-detection pod is not always cleaned after it completes
```

[release-v1.59] Manual backport "Move size detection pod deletion to cleanup"

---

pkg/monitoring/rules/alerts/operator.go

This PR Updates CDIDataVolumeUnusualRestartCount alert
and sets the health impact label to "none", since 
it only impact specific VMs and not the operator health.
Fixes #https://issues.redhat.com/browse/CNV-56026
```release-note
NONE
```

Update CDIDataVolumeUnusualRestartCount alert

---

pkg/storagecapabilities/storagecapabilities.go

PowerStore has a limit of 32 to 64 writable snapshots which prevents to create more VMs from a base OS.
Fixes #
```release-note
* Dell PowerStore uses `cloneStrategy: copy` over `csi-clone` to avoid array snapshot limits
```

Change clone strategy to avoid PowerStore snapshot limits

---

pkg/storagecapabilities/storagecapabilities.go

This PR adds the following volume capabilities:
```go
// Oracle cloud
"blockvolume.csi.oraclecloud.com": {{rwx, block}, {rwo, block}, {rwo, file}}
```
We've observed some issues with backend storage logic in Kubevirt choosing `RWX` and `Filesystem` for PVC creation. Setting this volume capabilities should help.
```release-note
Add volume capabilities for Oracle Cloud
```

Add volume capabilities for Oracle Cloud

---

pkg/controller/populators/forklift-populator.go
pkg/controller/populators/import-populator.go

Just a small fix to avoid printing the `%s/%s` in this error message. 
```release-note
NONE
```

Fix error formatting in populators

---

hack/build/docker/builder/Dockerfile

Updates golang to 1.23.6 so libraries that require it can be used.
Fixes #
```release-note
Using golang 1.23.6
```

Update golang to 1.23.6 in cdi builder

---

pkg/storagecapabilities/storagecapabilities.go

- Add RWX Block to supported hyperdisk types
- Use snapshot for clone and for DataImportCron created boot sources
```release-note
Add GCP hyperdisk capabilities
```

Add GCP hyperdisk capabilities

---

tests/BUILD.bazel
tests/dataimportcron_test.go

This reverts commit 21be57add80c01e0a6dd0c618b70de84d5caca25.
Not needed since snap->pvc format switch is automated
Fixes #
```release-note
NONE
```

Revert "Clean up leftover snapshot sources from DataImportCron tests"

---

tests/BUILD.bazel
tests/dataimportcron_test.go

This reverts commit 21be57add80c01e0a6dd0c618b70de84d5caca25.
Manual cherry pick of #3667
Fixes #
```release-note
NONE
```

[release-v1.60] Revert "Clean up leftover snapshot sources from DataImportCron tests"

---

pkg/importer/registry-datasource.go

This PR introduces an additional if statement to ensure that proxy certificates remain available even when the certConfigMap field is not present.
Currently, if certConfigMap is missing while pulling from a registry, the proxy certificates are not utilized, which can lead to trust issues. This change ensures that proxy certificates are always accessible when configured, regardless of if certConfigMap field is present or not in the DataVolumeSourceRegistry section.
```release-note
NONE
```

Adding an if statement for the case that the certDir is not configured

---

pkg/importer/vddk-datasource_amd64.go
pkg/importer/vddk-datasource_test.go

From [this conversation](https://github.com/kubevirt/containerized-data-importer/pull/3534#discussion_r1850773134), this pull request avoids storing all results from QueryChangedDiskAreas during a VDDK warm migration. A disk with a lot of small evenly-spaced changes could get the importer to create a huge list, which might exceed the pod's memory limit. This change iterates over one result from QueryChangedDiskAreas at a time, which so far seems to be limited to 2000 changed extent entries.
Fixes [MTV-1699](https://issues.redhat.com/browse/MTV-1699)
```release-note
Reduce memory usage for multi-stage VDDK imports when the source snapshot has many changes.
```

MTV-1699 Avoid potentially exceeding memory limit in multi-stage VDDK imports.

---

api/openapi-spec/swagger.json
doc/datavolumes.md
manifests/example/vddk-args-field.yaml
pkg/apis/core/v1beta1/openapi_generated.go
pkg/controller/common/util.go
pkg/controller/datavolume/import-controller_test.go
pkg/operator/resources/crds_generated.go
staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
tests/datavolume_test.go

As requested in [3572](https://github.com/kubevirt/containerized-data-importer/pull/3572#issuecomment-2596091372), adds a CRD field for extra VDDK arguments going forward. Most of the implementation is preserved from #3572, this just needed an extra copy to the PVC annotations.
```release-note
VDDK: add CRD field for extra configuration arguments.
```

VDDK: Add CRD field for extra configuration arguments

---

pkg/controller/clone/host-clone.go
pkg/controller/common/util.go
pkg/controller/datavolume/controller-base.go
pkg/controller/populators/forklift-populator.go
pkg/controller/populators/import-populator.go

Pretty sure we lose a worker thread whenever the GET call to /metrics
gets issued against a completed pod. Reducing the timeout to 2 seconds
should minimize that window.
```
{"level":"error","ts":"2025-03-17T20:40:34Z","logger":"controller.import-populator","msg":"Failed to update import progress for pvc <NAME/NS>","error":"Get \"https://<IP>:8443/metrics\": dial tcp <IP>:8443: i/o timeout"
```
Fixes #
```release-note
BugFix: decrease timeout trying to derive progress from a completed pod to avoid delaying progress updates
```

Avoid waiting out entire tcp timeout in progress call

---

pkg/controller/clone/planner.go
pkg/controller/clone/planner_test.go

We've been copying all annotations over from the target,
which includes the delayed binding related selected-node annotation.
This causes issues with non topology constrained provisioners,
that have no topology keys
(not sure how it wasn't an issue up until now)
There should be absolutely no need to copy that over since the volume
will either not need it (immediate) or gets it once target (and thus host assisted pod) is scheduled
(wffc).
Fixes #
https://issues.redhat.com/browse/CNV-60348
```release-note
BugFix: selected-node annotation …
```

Drop selected-node annotation from temp restore PVC

---

pkg/storagecapabilities/storagecapabilities.go

When the storage class parameters specifies `migratable: "true"` it supports RWX Block but not Filesystem:
https://github.com/longhorn/longhorn/blob/master/enhancements/20241206-v2-volume-live-migration.md https://github.com/longhorn/longhorn/blob/master/enhancements/20210216-volume-live-migration.md
RWX Filesystem is preferred when `nfsOptions` are specified:
https://longhorn.io/docs/1.8.1/nodes-and-volumes/volumes/rwx-volumes/
RWO Filesystem is preferred when `fsType` is specified.
Fixes #3680
```release-note
Fix Longhorn Filesystem capabilities
```

Fix Longhorn Filesystem capabilities

---

doc/datavolumes.md

Fix documentation on DataVolumes using PVCs as a source
```release-note
NONE
```

chore(doc): wrong source used for pvc in docs

---

pkg/controller/datavolume/BUILD.bazel
pkg/controller/datavolume/util.go
pkg/controller/datavolume/util_test.go
tests/datavolume_test.go

When rendering a `DataVolume` storage-api-defined PVC:
We should not set its missing `VolumeMode` to any value if its specified `AccessMode` has no match in the relevant `StorageProfile`. In this case, fallback to k8s default (`Filesysetem`).
Similarly, we should not set its missing `AccessModes` if its specified `VolumeMode` has no match in the relevant `StorageProfile`. In that case, return an error as the PVC spec is incomplete.
Fixes #3680
We should consider adding relevant utests
```release-note
Fix StorageProfile PVC rendering when there is no AccessMode or VolumeMode match
```

Fix StorageProfile PVC rendering when there is no AccessMode or VolumeMode match

---

pkg/controller/common/util.go
pkg/controller/datavolume/util.go
pkg/controller/datavolume/util_test.go

Supports both `DataVolume` PVC rendering and PVC mutating webhook rendering, so it can cover the kubevirt-side created `TPM` small PVC and any other PVC created by `DataVolume` or independently. For independent PVCs they should be labeled with `cdi.kubevirt.io/applyStorageProfile: "true"` and CDI featureGate `WebhookPvcRendering` should be enabled. A `StorageProfile` can be annotated with its minimum supported volume size with e.g.:
`cdi.kubevirt.io/minimumSupportedPvcSize: 4Gi`
Fixes #
```release-note
Allow increasing PVC size to the minimum supported by its storage class
```

Allow increasing PVC size to the minimum supported by its storage class

---

pkg/storagecapabilities/storagecapabilities.go

remove RWX for filesystem PVC capability from default profile of IBM Block Storage CSI driver
please see discussion in PR #3546 
```release-note
Remove RWX for filesystem PVC capability from default profile of IBM Block Storage CSI driver
```

remove RWX for filesystem PVC capability from default profile of IBM Block Storage CSI driver

---

pkg/controller/datavolume/BUILD.bazel
pkg/controller/datavolume/util.go
pkg/controller/datavolume/util_test.go
tests/datavolume_test.go

Manual backport of #3709
When rendering a `DataVolume` storage-api-defined PVC:
We should not set its missing `VolumeMode` to any value if its specified `AccessMode` has no match in the relevant `StorageProfile`. In this case, fallback to k8s default (`Filesysetem`).
Similarly, we should not set its missing `AccessModes` if its specified `VolumeMode` has no match in the relevant `StorageProfile`. In that case, return an error as the PVC spec is incomplete.
```release-note
Fix StorageProfile PVC rendering when there is no AccessMode or VolumeMode match
```

[release-v1.60] Fix StorageProfile PVC rendering

---

pkg/controller/datavolume/BUILD.bazel
pkg/controller/datavolume/util.go
pkg/controller/datavolume/util_test.go
tests/datavolume_test.go

Manual backport of #3709
When rendering a `DataVolume` storage-api-defined PVC:
We should not set its missing `VolumeMode` to any value if its specified `AccessMode` has no match in the relevant `StorageProfile`. In this case, fallback to k8s default (`Filesysetem`).
Similarly, we should not set its missing `AccessModes` if its specified `VolumeMode` has no match in the relevant `StorageProfile`. In that case, return an error as the PVC spec is incomplete.
```release-note
Fix StorageProfile PVC rendering when there is no AccessMode or VolumeMode match
```

[release-v1.59] Fix StorageProfile PVC rendering

---

doc/pvc-mutating-webhook-rendering.md
manifests/templates/release/cdi-cr.yaml.in
tests/BUILD.bazel
tests/clone-populator_test.go
tests/datavolume_test.go
tests/framework/framework.go
tests/import_test.go

The feature is available since v1.59, and we enable it by default to allow increasing PVC size to the minimum supported by its provisioner (#3711), and mainly in order to support https://github.com/kubevirt/kubevirt/pull/14637.
As a bonus, the related Serial tests are now parallel. Thanks @akalenyu :)
```release-note
Enable WebhookPvcRendering feature gate by default
```

Enable WebhookPvcRendering feature gate by default

---

pkg/controller/import-controller.go
pkg/controller/populators/populator-base.go
pkg/util/util.go
pkg/util/util_test.go
tests/import_test.go

Fixes #3674 
During the creation of the Importer Pod, append any labels from the PVC. This allows for labels to be passed from a Data Volume.
```release-note
Labels on DataVolumes are now copied to the importer pod
```

Append Labels From DV to Importer Pod

---

hack/build/build-functest.sh

I've been running recently into
```bash
eval ./hack/build/build-functest.sh
./hack/build/build-functest.sh: 15: set: Illegal option -o pipefail
```
Adding a shebang solved that, so I'd include this for compatibility.
```release-note
NONE
```

add build functest shebang

---

pkg/storagecapabilities/storagecapabilities.go

Per request by Ankit Gohil <agohil@purestorage.com> and Ninoy Radhakrishnan <nradhakrishnan@purestorage.com>.
See [reference](https://docs.portworx.com/portworx-enterprise/operations/operate-kubernetes/storage-operations/manage-kubevirt-vms.html#create-a-storageclass).
Also drop `pxd.openstorage.org` which is obsolete.
```release-note
Conditionally add ReadWriteMany Block to Portworx capabilities
```

Conditionally add RWX block to Portworx capabilities

---

pkg/controller/storageprofile-controller.go
pkg/controller/storageprofile-controller_test.go
pkg/storagecapabilities/storagecapabilities.go

Follow-up of #3711, annotating specifically:
- `pd.csi.storage.gke.io hyperdisk` (4Gi)
- `ebs.csi.aws.com io1/io2` (4Gi) & `gp2/gp3` (1Gi)
```release-note
Annotate StorageProfiles with provisioner minimum supported PVC size
```

Annotate StorageProfiles with provisioner minimum supported PVC size

---

pkg/image/qemu.go
pkg/importer/data-processor.go
pkg/importer/data-processor_test.go
pkg/importer/http-datasource.go
pkg/importer/http-datasource_test.go

Leverage nbdkit to make a best effort check of whether the effective size of the target VM image is bigger than available scratch space and return early if it is.
Fixes: #3682 
```release-note
none
```

http-datasource: validate image size before transfer

---

pkg/storagecapabilities/storagecapabilities.go

Customers that would like to clone VMs while using the IBM Block Storage CSI driver provider should default to using a clone strategy of "csi-clone"
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*: without this fix, customers are required to manually edit the storageprofile in their cluster to indicate that csi-clone cloneStrategy should be used with the IBM Block Storage CSI driver
Fixes #
```release-note
IBM Block Storage CSI driver storageprofile will use 'csi-clone' as the default cloneStrategy
```

IBM Block Storage CSI driver default cloneStrategy should be csi-clone

---

pkg/controller/util.go
pkg/controller/util_test.go

Add to scratch pvcs a label to be able
to exclude it from velero backups.
This pvcs are temporary and should not be
backedup.
fixes: https://github.com/kubevirt/containerized-data-importer/issues/3647
```release-note
Exclude scratch pvcs from velero backup
```

Exclude scratch pvcs from velero backup

---

pkg/storagecapabilities/storagecapabilities.go

add rwo,file and rook_cephfs to cephfs capabilities
Update pkg/storagecapabilities/storagecapabilities.go to include rook-ceph.cephfs.csi.ceph.com in CapabilitiesByProvisionerKey for Ceph provisioner. Add rwo file capability to address missing support, fixing incorrect storageprofile status and claimPropertySets generation that impacted functionality.
Also related to this PR: https://github.com/kubevirt/containerized-data-importer/pull/3793
Fixes #
cephfs sc deploy by rook-ceph:
```yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: …
```

add rwo,file and rook_cephfs to cephfs capabilities

---

pkg/controller/datavolume/conditions.go

With https://github.com/kubevirt/containerized-data-importer/pull/3753 a new annotation AnnPodSchedulable was introduced to allow updating the running condition of an importer Pod that was unschedulable.
This PR makes it so the unschedulable condition takes precedence over AnnRunningCondition otherwise a race can occur where initial Pod creation failure sets the running condition to an erroneous one indefinitely as the Pod never finishes scheduling and thus never updates.
Fixes #
```release-note
NONE
```

dv, conditions: AnnRunningCondition should not take precedence over AnnPodSchedulable

---

cmd/cdi-cloner/clone-source.go
pkg/apiserver/apiserver.go
pkg/uploadproxy/uploadproxy.go
pkg/uploadserver/uploadserver_test.go

Remove BuildNameToCertifcate function call which is deprecated since Go 1.14. Mapping is instead built automatically based on present certificates at request time.
Also, CDI doesn't make use of the `NameToCertificate` configuration field anyhow, making it safe to remove the calls.
Fixes #
https://github.com/golang/go/commit/67d894ee652a3c6fd0a883a33b86686371b96a0e
```release-note
NONE
```

chore: remove deprecated BuildNameToCertifcate function call

---

pkg/operator/controller/controller_test.go
pkg/operator/resources/cluster/controller.go
pkg/operator/resources/cluster/rbac.go

This continues pull request #3320 to address feedback on the forklift populator policy rules.
Hopefully fixes [CNV-64424](https://issues.redhat.com/browse/CNV-64424), and a bunch of older clones
This passes the previously failing unit tests that check for wildcards in the verb lists, and gets `system:cluster-readers` to show up in the output of the `oc adm policy who-can get` commands shown in [CNV-64424](https://issues.redhat.com/browse/CNV-64424). I don't have a deep enough understanding of RBAC to tell if anything else is missing though.
```release-note
Add missing RBAC for ovirt and openstack volume populator CRDs
```

Add missing RBAC to forklift volume populator CRDs.

---

pkg/controller/dataimportcron-controller.go
pkg/controller/dataimportcron-controller_test.go
tests/dataimportcron_test.go

It allows the `DataImportCron` controller to fetch a registry `containerImage` `imageID` digest by a do-nothing image-puller container, without depending on `OpenShift` `ImageStream` or `cronJobs`. k8s node caching makes it also quite cheap. If the image was not updated, it is already cached. If the image is a new one, k8s will pull and cache it, so in the following import it will be retrieved from the cache, assuming both pods are scheduled on the same node.
```release-note
Support DataImportCron DataVolume node pullMethod for update polling
```

Support DIC DV node pullMethod for update polling

---

cmd/cdi-controller/BUILD.bazel
cmd/cdi-controller/controller.go
cmd/cdi-operator/BUILD.bazel
cmd/cdi-operator/operator.go
pkg/operator/controller/prometheus.go
pkg/operator/resources/namespaced/controller.go
pkg/operator/resources/operator/operator.go

As part of an effort to standardize metric exposure across KubeVirt components on port 8443, we are transitioning to HTTPS with TLS encryption for the metrics-server.
To facilitate this, we leverage the controller-runtime's SecureServing option, which creates a self-signed certificate and configures it as the server certificate for the metrics endpoint when no external certificate is provided[1].
Subsequent PRs will replace this self-signed certificate with a CDI generated one to enable a fully trusted and secure connection between the Prometheus instance and the target metrics endpoints as specified by the CDI ServiceMonitor. Until that integration is complete, the ServiceMonitor will be configured with insecureSkipVerify to allow scraping despite …

metrics-server: use SecureServing option

---

pkg/controller/clone-controller.go
pkg/controller/common/util.go
pkg/controller/common/util_test.go
pkg/controller/datavolume/conditions.go
pkg/controller/datavolume/controller-base.go
pkg/controller/datavolume/import-controller.go
pkg/controller/import-controller.go
pkg/controller/populators/clone-populator.go
pkg/controller/populators/import-populator.go
pkg/controller/populators/populator-base.go
pkg/controller/populators/upload-populator.go
pkg/controller/populators/upload-populator_test.go
pkg/controller/populators/util.go
pkg/controller/upload-controller.go
pkg/operator/resources/cluster/controller.go
pkg/uploadproxy/uploadproxy.go
tests/basic_sanity_test.go
tests/datavolume_test.go

Add new functionality to watch for any new events that come from a prime PVC, these events will be re-emitted to the regular PVC along with a prefix to indicate the prime PVC's name. Additionally while the DV's bound condition is set to pending, the prime PVC name as well as the latest event message from the prime PVC will be appended to the message which will allow for easier debugging if a provisioning problem occurs.
```release-note
DV will now contain events from PVC Prime and DV bound condition message will be updated to contain latest PVC Prime event message while bound condition is pending"
```

Populate DV with events from PVC Prime

---

api/openapi-spec/swagger.json
doc/cdi-config.md
pkg/apis/core/v1beta1/openapi_generated.go
pkg/common/common.go
pkg/controller/import-controller_test.go
pkg/importer/data-processor_test.go
pkg/operator/resources/crds_generated.go
pkg/uploadserver/uploadserver_test.go
pkg/util/util_test.go
staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
tests/import_test.go
tests/upload_test.go

The previous default of 5.5% was originally chosen to account for filesystem overhead. Due to inaccuracies in our overhead inflation calculations, the actual effective overhead was closer to 5.8%.
Now that the calculation functions have been fixed in https://github.com/kubevirt/containerized-data-importer/pull/3779, we're increasing the default to 6% to ensure sufficient inflation for typical filesystem overhead and avoid under-provisioning.
Feel free to propose a different value. 7% was considered in the past (I think around https://github.com/kubevirt/kubevirt/pull/13326 was merged) but 6% is closer to the original and apparently solves the issue we had with smaller PVCs. 
```release-note
Increase default filesystem overhead to …
```

Increase default filesystem overhead to 6%

---

api/openapi-spec/swagger.json
doc/cdi-config.md
pkg/apis/core/v1beta1/openapi_generated.go
pkg/common/common.go
pkg/controller/common/util.go
pkg/controller/datavolume/BUILD.bazel
pkg/controller/datavolume/import-controller_test.go
pkg/controller/datavolume/util_test.go
pkg/controller/import-controller_test.go
pkg/controller/util.go
pkg/controller/util_test.go
pkg/importer/data-processor_test.go
pkg/operator/resources/crds_generated.go
pkg/uploadserver/uploadserver_test.go
pkg/util/util.go
pkg/util/util_test.go
staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
tests/datavolume_test.go
tests/import_test.go
tests/upload_test.go

This is a manual backport of https://github.com/kubevirt/containerized-data-importer/pull/3812 and https://github.com/kubevirt/containerized-data-importer/pull/3779. These two PRs need to be backported together to ensure consistent behavior and minimize impact on the overhead calculation results.
No major conflicts needed to be addressed, just some minor ones in unit tests.
```release-note
Bugfix: Fix math in overhead size calculations:
- When using the storage API, PVC disk size is now correctly inflated to account for filesystem overhead.
- When using the PVC API, usable disk space is now calculated more accurately with "allocatedSize / (1 + overhead)". This may result in changes in usable …
```

[release-v1.61] Fix math in overhead size calculations and increase default overhead

---

tests/import_test.go

This test has been flaky for a long time: https://issues.redhat.com/browse/CNV-40015.
The issue seems to be caused by an inline DV declaration in the Eventually block, which leads to outdated data in the final check. This PR ensures we use the updated DV when comparing with the VolumeImportSource.
```release-note
NONE
```

 [release-v1.59] Tests: Fix Get assignment in multi-stage import test 

---

pkg/controller/datasource-controller.go
tests/datasource_test.go

Previously when a datasource reference status would change pointers to
said reference wouldn't reconcile to reflect the latest status.
This commit takes care to update them accordingly.
Fixes #
With this change we now reconcile the datasource keys and other datasources which reference it as source for either a spec change or a condition reason/message change specifically to avoid redundant requeues (i.e., comparing conditions directly would be problematic due to timestamps). `status.Source` can be evaluated instead.
```release-note
bugfix: …
```

Bugfix: Reconcile pointer datasource on reference status update

---

pkg/controller/dataimportcron-controller.go
tests/dataimportcron_test.go

All registry DataImportCron import settings would ignore the architecture setting, resulting in scenarios where the resulting populated datasource would contain an incorrect image.
This PR introduces support for architecture support in DICs for both pull method node, which was the only mode that suffered from the issue. Other modes correctly delegate the inference logic to the importer pod.
Fixes https://issues.redhat.com/browse/CNV-68812
```release-note
Bugfix: DataImportCrons now respects the platform.architecture setting in all modes.
```

Bugfix: dataimportcron, cdi-source-update-poller should acknowledge architecture setting

---

hack/README.md
pkg/storagecapabilities/storagecapabilities.go

Manual backport of https://github.com/kubevirt/containerized-data-importer/pull/3806. 
Backporting this will make other storage capabilities cherry-picks more straightforward. It's also worth having in previous versions.
Fixes #
/cc @akalenyu 
```release-note
1. Defined storagecapabilities for the synology-csi driver, fully populating the storageprofile for related synology storage classes.
```

[release-v1.62] added defaults to support synology csi driver storageprofile creation

---

pkg/storagecapabilities/storagecapabilities.go

This PR sets the default clone strategy for OCI to csi-clone.
```release-note
NONE
```

[release-v1.60] Oracle Cloud: Set default clone strategy to csi-clone

---

pkg/controller/BUILD.bazel
pkg/controller/storageprofile-controller.go
pkg/controller/storageprofile-controller_test.go
pkg/operator/resources/crds_generated.go
staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go

We have been observing flaky failures in the StorageProfile functional tests.
The root cause appears to be a race condition. Each test resets the spec upon completion, but the controller is likely still processing the previous state when the next test begins. Without a status field, the test has no way to confirm that the controller has finished reconciling the previous state.
This change introduces a status subresource to the StorageProfile. This allows tests and clients to observe the resource's actual state and wait for the status field to be populated - signaling that reconciliation is complete before proceeding.
The implementation includes:
1. Adding the +kubebuilder:subresource:status annotation to the StorageProfile type.
2. Updating the controller to handle status updates …

Add status subresource to StorageProfile
