kubevirt/containerized-data-importer

- pkg/controller/controller.go
- pkg/controller/util.go
A general skeleton for `processItem`. Lots TODO but it compiles.
> controller action skeleton

- pkg/controller/controller.go
- pkg/controller/util.go
TODO: use secret to populate remaining env fields in importer pod
> generate podName, create pod

- pkg/controller/controller.go
- pkg/controller/util.go
importer pod's `Env:` looks correct. But the pod remains in "ContainerCreating" state.
> secret added to pod

- cmd/controller/controller.go
- pkg/controller/controller.go
- pkg/controller/util.go
controller watch will only pay attention to pvc add events. Update and Delete event are now ignored.
Also, the pvc's status annotation is replaced with the name of the importer pod that was created due to this pvc.
> replace status anno with importPodName, remove UpdateFunc and DeleteFunc

- pkg/controller/controller.go
- pkg/controller/util.go
per Coreos operator video, use pvc.Patch instead of pvc.Update to add the pvc podName annotation.
> use Patch to update pvc anno

- Makefile
- pkg/controller/controller_test.go
- pkg/controller/util.go
To prevent naming collisions with existing or completed importer pods, use `generateName` for importer pod.
Also removed platform and architecture variables from Makefile `test` recipe.   This allows go test to be run on platforms other than linux
> Unique importer names

- pkg/image/validation_test.go
- pkg/importer/dataStream.go
- pkg/importer/importer_test.go
Fixes part of https://github.com/kubevirt/containerized-data-importer/issues/58
and revise some of the ut issues, the variable assignment should be out of `It(` block
> fix unit test and basic auth issues

- .travis.yml
- Makefile
This PR does the following:
- Add .travis.yml
- Hook this repo up to travis
- Setup minikube
- Deploy KubeVirt
- Deploy CDI
Signed-off-by: Fabian Deutsch <fabiand@fedoraproject.org>
> Add .travis.yml for basic CI

- README.md
- cmd/controller/controller.go
- manifests/controller/cdi-controller-deployment.yaml
- pkg/controller/util.go
Support new use-case which allows a user to import a VM image into their namespace. This image will be consumed by Kubevirt w/o the need to be cloned. This imported image is mutable and not part of a "golden image" repository.
> support multiple namespaces

- pkg/common/common.go
- pkg/controller/controller.go
- pkg/controller/controller_test.go
- pkg/controller/util.go
- pkg/importer/dataStream.go
- pkg/importer/importer_test.go
fixes some issues with the unit tests:
.  no `BeforeEach`'s inside `for` loops
.  pvc anno set correctly
.  local assignments in `for` loop containing `It`'s
.  dataStream.DataRdr used for importer tests
.  only pre-create file in importer test when needed.
> unit test refactor

- Makefile
- build/importer/Dockerfile
- pkg/controller/controller_suite_test.go
- pkg/image/validate.go
- pkg/image/validation_suite_test.go
- pkg/importer/importer_suite_test.go
- test/datastream/datastream_suite_test.go
- test/datastream/datastream_test.go
- test/framework/fileConversion.go
fixes: #77 
Add a functional testing framework of the importer's in-stream data decompression, unarchiving, and qcow2 conversion.
Included tinyCore.iso as a base image for testing
Some basic logic using func stubs to plan file conversion logic.
> Add Functional tests for supported data processing

- test/datastream/datastream_test.go
@jeffvance - this is a WIP with initial investigation, It may be my lack of understanding at this point, but I think it might be worth while to add another field into the tests to indicate if the filename should be manipulated or not based on the action that is being taken, right now I'm only manipulating the filename based on the fact that is is `qemu` everything else I leave as is...so it does get by step 3 but fails on the last step now where it is comparing source file size vs output/converted file size ...
```
should convert .qcow2
/home/screeley/git/go/src/github.com/kubevirt/containerized-data-importer/test/datastream/datastream_test.go:84
STEP: Stating the source image file
STEP: Converting sample file to format: [.qcow2]
STEP: Confirming sample file name "tinyCore.qcow2" matches …
```
> WIP - fix qemu functional test

- cmd/importer/importer.go
- pkg/controller/controller_test.go
- pkg/image/decompress.go
- pkg/image/qemu.go
- pkg/image/validate.go
- pkg/image/validation_test.go
- pkg/importer/dataStream.go
- pkg/importer/importer_test.go
- test/datastream/datastream_test.go
- test/framework/fileConversion.go
Fixes #74 
Restructure all Readers so that each reader's close is called within the same scope as the reader's creation.
@copejon @screeley44
> Refactor readers so Close() is called

- Makefile
- cmd/controller/controller.go
- manifests/controller/cdi-controller-deployment.yaml
- manifests/example/endpoint-secret.yaml
- manifests/example/golden-pvc.yaml
- manifests/importer/importer-pod.yaml
- pkg/common/common.go
- pkg/controller/controller.go
- pkg/controller/controller_test.go
- pkg/controller/util.go
Refactor the SharedInformerFactory to properly use a pvc informer This should be done before addressing  [pod monitoring](#83 )
> refactor cdi controller for modern use of informer factories

- cmd/controller/controller.go
- manifests/controller/cdi-controller-deployment.yaml
- pkg/common/common.go
- pkg/controller/controller.go
- pkg/controller/controller_test.go
- pkg/controller/util.go
Default pull policies to IfNotPreset unless env var CDI_PULL_POLICY is set.  Unfortunately, both the controller pull policy must be set to Always and the env var set to `CDI_PULL_POLICY: Always`; this field is covered by the DownwardApi.
> Change default pull policy to IfNotPresent to support offline demoing.

- pkg/controller/controller.go
- pkg/controller/controller_test.go
- pkg/controller/util.go
[121](https://github.com/kubevirt/containerized-data-importer/pull/121) added code to Get the latest pvc so that the most recent annotations could be checked. However, an error returned from `Get` was treated as _success_, meaning ok to create the importer pod. 
This pr causes a `Get` error to not create the importer pod and to remember the key so it can be retried.
This also requires controller unit test to populate the fake client with the tested pvc.
> refactor Get of pvc to recognize err

- Makefile
- build/controller/Dockerfile
- build/importer/Dockerfile
Formatting ENTRYPOINT's into exec form.
We want to be able to pass custom flags to the importer binary via it's pod definition.  Currently, the controller and importer ENTRYPOINT vars are defined in docker's "shell form".  However, k8s sets the custom flags defined in the `args:` list as "exec form" (a json formatted array).
By design, docker ENTRYPOINTs defined in shell form will ignore CMDs in exec form.  Converted the ENTRYPOINTs to exec form causes docker to perform as expected, passing the exec form args list to the ENTRYPOINT.
> Changed Dockerfile ENTRYPOINT to exec form in controller and importer

- .travis.yml
Travis deploy stage compiles and builds images twice before releasing them
> Removed redundant compile and image building

- .travis.yml
- Makefile
- hack/version-and-deploy.sh
To implement a common workflow using git tags to trigger versioning operations via Travis CI.
On pushing a git tag, Travis will execute a script that takes the tag value (`v*.*.*...`) and propagates it to specified locations where version is hard coded.  It commits this change and pushes it to master.  Next it deletes the human defined git tag and sets it again for the current commit (containing the updated versions).
Images are then built and published with the new version tag.
> Automated Versioning with Git Tags

- pkg/controller/import-controller.go
Motivation is to keep cdi more independent of kubevirt for future cdi generality.
Fixes #191
> change controller labels from 'kubevirt.io' to 'cdi.io'

- pkg/controller/import-controller.go
Roll back annotation changes to release a stable pre-change image
> Revert "change controller labels from 'kubevirt.io' to 'cdi.io'"

- .travis.yml
- Makefile
Travis will only deploy versioned releases when a new git tag is pushed.
> Reinstate travis deployment, but only on tag pushes

- README.md
- doc/design.md
- manifests/example/golden-pvc.yaml
- pkg/controller/import-controller.go
This pr will require cdi consumers that use explict annotation in the triggering pvc to change to the new annotations.
> change cdi anno from `kubevirt.io/` to `cdi.kubevirt.io/`

- Makefile
`docker ps` prints some value to stdin/stderr regardless of whether it passes, making it inadequate for testing if docker is running.  This PR captures the exit code instead to `DOCKER_OUT`.
> Discard docker ps output and capture exit code

- cmd/importer/importer.go
- hack/README.md
- pkg/image/filefmt.go
- pkg/image/validate.go
- pkg/importer/dataStream.go
- pkg/importer/util.go
- pkg/lib/size/size.go
- test/framework/fileConversion.go
- test/functional/controller/controller_test.go
- test/functional/image/validation_test.go
- test/functional/importer/datastream_test.go
- test/functional/importer/importer_test.go
Instead of using file extension strings, determine file type based on its magic number. This becomes the foundation for providing the source endpoint file size, as needed by the data-controller CRD, without decompressing and copying the entire file.
Potential Issues:
1. file extensions are completely ignored so no error/warning is reported if the inferred file type differs from its extension
2. Matt Holt's [tar archiver](https://github.com/mholt/archiver) uses file extensions first and introspection second to determine file type.
3. the `dataStream` struct contains a 512 byte buffer -- the exact size of a tar header. A larger buffer  leaves residual bytes in the multi-reader that are added back to the unarchived target file. It's possible that this buffer could be increased if point 4 …
> [WIP] introspect file formats

- pkg/controller/util.go
- pkg/controller/util_test.go
* Ensures import pod is not created until PVC is bound.  Fixes import pod being indefinitely stuck in "pending" state if PVC can not be bound.
* Adds owner references to import pods. Fixes "pending" pods from never being cleaned up.
* Adds unit tests to verify fixes
> Import Controller Fixes

- pkg/controller/datavolume-controller_test.go
sometimes the datavolume tests fail because I wasn't properly filtering out list/watch actions.
> fix transient failure in datavolume unit tests

- pkg/importer/dataStream_test.go
- test/functional/controller/controller_test.go
The datastream implementations in datastream_test.go misdefine the datastream's `qemu` field as `Qemu`, causing the tests to fail.   This PR renames the field to `qemu` to fix conflicts with the datastream struct definition.
> Fix improperly exported field in test struct

- pkg/importer/dataStream_test.go
- pkg/importer/util_test.go
```
kubevirt.io/containerized-data-importer/pkg/importer/dataStream.go:78:	NewDataStream		93.8%
kubevirt.io/containerized-data-importer/pkg/importer/dataStream.go:113:	Read			100.0%
kubevirt.io/containerized-data-importer/pkg/importer/dataStream.go:118:	Close			100.0%
kubevirt.io/containerized-data-importer/pkg/importer/dataStream.go:124:	dataStreamSelector	90.0%
kubevirt.io/containerized-data-importer/pkg/importer/dataStream.go:143:	s3			0.0%
kubevirt.io/containerized-data-importer/pkg/importer/dataStream.go:159:	http			50.0%
kubevirt.io/containerized-data-importer/pkg/importer/dataStream.go:185:	local			100.0%
kubevirt.io/containerized-data-importer/pkg/importer/dataStream.go:196:	CopyImage		100.0%
kubevirt.io/containerized-data-importer/pkg/importer/dataStream.go:227:	constructReaders …
```
> add initial unit tests for importer package

- pkg/controller/util.go
Issue:
https://github.com/kubevirt/containerized-data-importer/issues/279
If we remove the cloning label from the target pod then the target pod will be scheduled on the same node as the source pod.
> Remove cloning label from target pods to fix pod affinity. 

- pkg/controller/util.go
- pkg/controller/util_test.go
The api group should be v1 not appsv1.  Fixes #292.
> Use the correct API group for import pod owner reference

- cmd/cdi-cloner/cloner_startup.sh
When cloning we were invoking tar at the container root in the source
mode and within the volume mount in target mode.  The result was the
disk.img file appearing in a tmp/clone/image subdirectory in the target
pvc instead of being copied exactly.  Fixes #296 
> Invoke tar from same location in source and target mode

- cmd/cdi-cloner/script.sh
- pkg/controller/util.go
This backports two fixes from master to fix the following issues:
Fixes #298 
> When cloning a source pvc to a target pvc the target pvc has a different file hierarchy. This is because tar is invoked at the container root in the source case but expanded inside the pvc volume mount in the target case. Fix by using pushd in the source case as well.
Fixes #302 
> Having the cloning label in the target pod, make the pod affinity fails.
The target pod looks for a pod with a specific label (specified in the pod affinity) that matches the source pod label.
> In my case the target pod included this label as well, so we can see that the target pod found matching pod, but it is the WRONG pod. It's itself!!
> The target was running without finding the source pod first.
> If we remove this label from …
> Backports of Cloning PRs #280 and #297 to 1.1 branch

- manifests/templates/cdi-controller.yaml.in
The finalizer permissions didn't make it into the manifest template.
> Add finalizer permissions to manifest template

- hack/build/build-manifests.sh
- hack/build/config.sh
- manifests/templates/cdi-controller.yaml.in
- tools/manifest-generator/manifest-generator.go
Right now we assume everything is installed into the default namespace. This should be configurable and ideally we should be installing into a more secure namespace like kube-system instead.
This patch adds namespace to the manifest templates and changes the default install namespace to kube-system, which is what kubevirt does as well.
> add namespace template parameter for cdi manifests

- README.md
- cmd/cdi-cloner/cloner_startup.sh
and increase num of retries in _cloner-startup.sh_ script to account for slower nodes.
Note: all feature gates mentioned in this pr default to true in k8s 1.10 and later. I expect the addition to the readme to be short-lived but still worthwhile as long as cdi is used on k8s 1.9 and earlier clusters.
Fixes #306 
Feature gate statuses:  https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/
> add cluster considerations for cloning to readme

- .gitignore
- Makefile
- cluster/cli.sh
- cluster/down.sh
- cluster/gocli.sh
- cluster/kubectl.sh
- cluster/sync.sh
- cluster/up.sh
- hack/README.md
- hack/build/config.sh
- Added ability to call make cluster-up to start a kubevirt cluster.
- Added ability to call make cluster-down to stop a kubevirt cluster.
- Added ability to call make cluster-sync to build CDI and sync it with
the running cluster. This allows for testing during development.
- Added cli.sh and kubectl.sh just like kubevirt, in the CDI project to
manipulate a running cluster.
> Add kubevirt cluster environment with sync

- pkg/image/filefmt.go
Fixes #318 
Truncate the magic number slice for tar to match all tarball identifies.
> Bug Fix - Match all tar magic numbers

- manifests/controller/cdi-controller-deployment.yaml
This will sync up release-v1.1 branch that addressed issue #287 - but only addressed the templates and not the manifests - so master is in sync with PR #308 but release-v1.1 still has out-dated manifests yaml based on datavolume resource and rbac perms that do not work
> backport manifests rbac

- README.md
- pkg/importer/dataStream.go
Cherry Pick of PR #312 (9f6455)
Adds documentation explaining that `file:///` endpoint  is strictly for debugging in non-containerized run times.
> Add disclaimer and a log warning about local (:file//) endpoints (#312)

- pkg/importer/dataStream.go
- pkg/importer/dataStream_test.go
fixes #324 
One of the dataStream unit tests called `constructReaders` twice per dataStream. Instead, that test now tests that the number of readers in the _Readers_ slice matches the expected size.
Also, `constructReaders` now exits its `for` loop once a _qcow2_ file header is detected. Previously, the loop did an extra (unnecessary) iteration resulting in an additional multi-reader being appended to the _Readers_ slice.
@copejon @screeley44 @mhenriks
> fix dataStream reader and test bugs

- tests/pvc_utils.go
Removed default timeout declaration that was duplicated in two files.
make functest will not compile without this.
> Remove duplicate default timeout

- Makefile
- hack/build/build-cdi-func-test-file-host.sh
- hack/build/build-docker.sh
- hack/build/build-go.sh
- hack/build/docker/cdi-func-test-file-host-http/Dockerfile
- hack/build/docker/cdi-func-test-file-host-http/nginx.conf
- hack/build/docker/cdi-func-test-file-host-init/Dockerfile
- manifests/templates/file-host.yaml.in
- test/framework/fileConversion.go
- tools/cdi-func-test-file-host-init/main.go
In support of future functional testing, adds a container that will host all permutations of an image that the datastream can handle.  This will enable us to test the actual s3 and http pipelines of the importer.
Dependent on #313
> Add simple http & s3 file server as func test source

- README.md
- cmd/cdi-importer/importer.go
- pkg/importer/dataStream.go
- pkg/lib/size/size_test.go
- test/functional/importer/datastream/datastream_test.go
partially fixes #338 
A separate issue and pr will be created to remove the code supporting and testing local file import. This pr just announces the deprecation of this feature via doc, code statements, and importer logs.
> local (file://) endpoint deprecation notice

- Makefile
- hack/build/build-cdi-func-test-file-host.sh
Fixes #350 
This PR alters the build flow for the functional test image host to perform some copy ops in a container.
The problem is that the container writes files as root, which then breaks copy ops in the host env when running as a regular user.  This is a long lived complaint with docker is not a configurable behavior, requiring a workaround.
> Tweak functest-image-host build flow to fix perm issues

- README.md
In releases after v1.1.0 the correct CDI controller release manifest appears to be:
https://github.com/kubevirt/containerized-data-importer/releases/download/$VERSION/cdi-controller.yaml
The URL previous to this change appears to be the one mentioned further down as deprecated which was removed in later releases resulting in a 404.
> Use correct release manifest for CDI controller

- pkg/importer/datastream_ginkgo_test.go
Unblocks PRs affected by #335 by disabling the the `.tar.xz` test.
> Disable .tar.xz until issue 335 is resolved

- hack/build/run-functional-tests.sh
- The default was set to kubesystem, instead of kube-system.
> Fix default CDI namespace typo

- tests/basic_sanity_test.go
- tests/framework/framework.go
- tests/import_test.go
- Not all tests require a namespace to run, add the ability
to skip creating the generated namespace.
> Add skip namespace creation flag.

- pkg/apis/datavolumecontroller/v1alpha1/types.go
- pkg/common/common.go
- pkg/controller/clone-controller.go
- pkg/controller/import_controller_ginkgo_test.go
- pkg/controller/util.go
- pkg/controller/util_test.go
- pkg/importer/dataStream_test.go
- pkg/importer/datastream_ginkgo_test.go
- pkg/importer/datastream_suite_test.go
- pkg/lib/size/size_test.go
- pkg/util/util.go
- pkg/util/util_test.go
Just do a simple `gofmt -s -w` on pkg, tests and controller directories
to fix the misc space/tab mixes and some other ez formatting issues.
> Run gofmt on our directories

- .travis.yml
- Makefile
- hack/build/run-lint-checks.sh
- tests/reporters/reporters.go
Add checkformat to Makefile and add Travis check                                                                                                              
This adds a super simple gofmt check for Travis to run.  If there are                                                                                         
files that gofmt recommends updating, the check fails, if there aren't                                                                                        
it passes.
> Add gofmt check to makefile and travis

- hack/build/docker/cdi-cloner/Dockerfile
- pkg/common/common.go
- pkg/controller/util.go
- Updated controller to use ENTRYPOINT (no cmd) instead of /bin/sh
- Updated Dockerfile to set path to /usr/bin/cloner_startup.sh instead of /tmp
- Updated Dockerfile to use ENTRYPOINT.
Fixes issue #374
> cloner image uses ENTRYPOINT instead of hard coded path

- tests/datavolume_test.go
- tests/utils/datavolume.go
This PR is adding initial functional tests for DataVolumes into cdi
I've added hostpath PVs and an http import server to help with testing. This will help the importer and clone tests as well.
> DataVolume functional test suite

- hack/README.md
Re-worded the description on using `TEST_ARGS`.
This may not be how we intended to use `TEST_ARGS` for functional tests, but it explains the way it works currently.
> improve hack/readme for TEST_ARGS

- tests/cloner_test.go
- tests/utils/pod.go
Apply two fixes to the clone tests:
- check for the correct PVC annotation
- Poll pods to check onto which node they were scheduled.
> Fix clone tests

- tests/cloner_test.go
Mismatched function names: PodNode should be PodGetNode.
> tests: Fix PR #386

- hack/build/docker/cdi-func-test-file-host-http/Dockerfile
- hack/build/docker/cdi-func-test-file-host-http/htpasswd
- hack/build/docker/cdi-func-test-file-host-http/nginx.conf
- manifests/templates/file-host.yaml.in
- tests/tests_suite_test.go
- tests/transport_test.go
- tests/utils/common.go
- tests/utils/deployments.go
- tests/utils/pod.go
- tests/utils/pvc.go
- tests/utils/secrets.go
- tests/utils/services.go
- Adds tests that create PVCs in a cluster with the endpoint of the file host pod.   This test exercises the import pod's ability to connect to real host over supported protocols.
- Adds utility funcs for services and deployments.
cc @jeffvance @awels
> E2E Testing - transport protocols

- tests/basic_sanity_test.go
- tests/cloner_test.go
- tests/datavolume_test.go
- tests/framework/framework.go
- tests/import_test.go
Replace the common functional test pattern of:
```
f, err := framework.NewFramework("foo", framework.Config{})
if err != nil {
Fail("...")
}
```
with
```
f := framework.NewFrameworkOrDie("foo")
```
Note that the Config parameter is optional now.
> `NewFrameworkOrDie`

- hack/build/docker/cdi-func-test-file-host-http/nginx.conf
Moves `servername` directive to appropriate config blocks.
> Set file host nginx servernames

- tests/framework/framework.go
This pr gets `NewFramework` back to how it originally handled printing of the passed-in flags.
Currently, the flags are displayed every time a test calls `NewFramework`. With this pr the flags will be displayed once per test binary run. This is sufficient for debugging and seeing what flags are set.
> don't show test flags every time NewFramework invoked

- cluster/sync.sh
- pkg/controller/util.go
- tests/import_test.go
- Set verbosity on controller to 3 to enable simpler tests.
- Updated test to check controller log for skipping PVC
- Updated message in log to include PVC and NS.
> Update no annotation PVC import test.

- cmd/cdi-controller/controller.go
- cmd/cdi-importer/importer.go
- pkg/common/common.go
- pkg/controller/clone-controller.go
- pkg/controller/datavolume-controller.go
- pkg/controller/import-controller.go
- pkg/controller/import_controller_ginkgo_test.go
- pkg/controller/util.go
- pkg/expectations/expectations.go
- pkg/image/filefmt.go
- pkg/importer/dataStream.go
- pkg/importer/util.go
This change just removes the log level constants that were set in
pkg/common/common.go and falls back to just using the int arguments (1,
2 or 3) to glog.  While the constants are handy to limit the choices for example it also introduces a pkg dependency on common.go.  It seems just as easy to type 1, 2 or 3 and if we want to enforce the use of levels inclusive of a certain range we can do that through lint checks or review criteria.  I'm not advocating we do that, just mentioning that if that's a restriction we want we can certainly make it work.
Now instead of issuing a log call with the constant:
`glog.V(common.Vuser)`
We just provide the argument as an int:
`glog.V(1)`
I started doing this as part of the effort to fix linting, but that's
going package by package and it was rightly …
> Remove log-level constants

- hack/build/docker/builder/Dockerfile
- hack/build/run-lint-checks.sh
Now that the updates have merged to fix golint errors in all of the
CDI pkgs (except common) turn on lint checks to keep things up to date.
This patch does that by:
1.  Adding a check in hack/build/run-lint-checks.sh
NOTE:  We temporarily set a list variable in the script to indicate
the directories that we've fixed and want to enforce.  This will be
removed when common is "lintified"
2.  Adding golint to our build containers Dockerfile
> Add golint enforcement to all pkgs but common

- pkg/controller/clone-controller.go
- pkg/controller/datavolume-controller.go
- pkg/controller/import-controller.go
- pkg/controller/util.go
- pkg/controller/util_test.go
We're supposed to be cleaning up the expectation keys as objects are deleted from the cluster.
> Ensure expectation keys are deleted when object is deleted from cluster

- hack/build/run-functional-tests.sh
- Fixed the retry counter not incrementing properly thus causing an
endless loop.
- Added printing of the pods every minute to help debug which pods are
not in the correct state.
> Fix CDI pod waiting retry counter.

- cmd/cdi-controller/controller.go
- cmd/cdi-importer/importer.go
- hack/build/run-lint-checks.sh
- pkg/common/common.go
- pkg/controller/clone-controller.go
- pkg/controller/clone-controller_test.go
- pkg/controller/import-controller.go
- pkg/controller/import-controller_test.go
- pkg/controller/import_controller_ginkgo_test.go
- pkg/controller/util.go
- pkg/controller/util_test.go
- pkg/importer/dataStream.go
- pkg/importer/datastream_ginkgo_test.go
- pkg/importer/util.go
- pkg/importer/util_test.go
- tests/cloner_test.go
- tests/framework/framework.go
- tests/framework/pod.go
- tests/transport_test.go
This change just updates the common package to pass golint.  Of course
that has some reaching implications into other packages with renaming of
constants.
I've intentionally kept this patch set to the bare minimum for the lint
test, I do think that we should put some effort into our use of
constants (especially those in common.go) in the future.
Ideally we'd declare constants where they're used, and we wouldn't
export them if they don't need to be.  There are some in here that
are only used in one or two packages, and that can be cleaned up pretty
easily however it's likely that there might be plans to use them
elsewhere in the future.
> Fix lint errors on common package

- pkg/image/qemu.go
- pkg/system/prlimit.go
- pkg/system/prlimit_test.go
This PR shows the QEMU progress in the importer pod log, this is useful for seeing status progress on converting large images. It can also help debug issues stemming from slow network or disks as you can see some progress happening.
Fixes #
```release-note
Importer POD now shows progress in the log.
```
> Display QEMU conversion progress in importer pod log.

- .travis.yml
This PR calls a refresh on goreport on each PR submitted, so we are never out of sync much.
Fixes #
```release-note
NONE
```
> Refresh goreport after each PR push

- glide.lock
- pkg/system/prlimit.go
- tests/transport_test.go
- tests/utils.go
- tests/utils/pod.go
- vendor/github.com/go-ini/ini/README.md
- vendor/github.com/pkg/errors/errors.go
- vendor/gopkg.in/square/go-jose.v2/jwk.go
- vendor/gopkg.in/square/go-jose.v2/jwk_test.go
- vendor/gopkg.in/square/go-jose.v2/jwt/validation.go
The http transport test is failing intermittently because the qemu process stdout/err are not always fully read. This PR adds some debugging information and fixes the issue.
Fixes #
```release-note
NONE
```
> Fix flaky transport test

- hack/build/docker/cdi-func-test-file-host-http/Dockerfile
- pkg/image/qemu.go
Currently, if "qemu-img convert" does not complete successfully (usually because of a segfault) it is possible that the output file exists.  This pr will delete the file when that happens.
Fixes #
```release-note
NONE
```
> clean up if qemu-img fails

- hack/build/run-lint-checks.sh
Remove the commented out code in run-lint-checks.sh, this was leftover
from when we were only linting the pkg directory, we've now extended
that out to the other .go folders in the project and this was commented
out but should've been removed.
```release-note
NONE
```
> Remove old commented out lintcheck code

- pkg/controller/clone-controller.go
- pkg/controller/import-controller.go
- pkg/controller/upload-controller.go
- pkg/controller/upload-controller_test.go
- pkg/controller/util.go
- pkg/controller/util_test.go
- tests/cloner_test.go
- tests/framework/pvc.go
- tests/transport_test.go
- tests/upload_test.go
- tests/utils.go
This patch does two things:
1. We modify the restart policy from never to "OnFailure" for the
Importer (we already did this for Upload, and we don't want to do it yet
for the Clone pods)
2. Upon successful completion delete our worker pods
We're not doing this on failed pods right now because in general an
admin will likely want to inspect the pod to see why it failed.
The first question someone will likely ask is "well what about a node
failure", well in the case of a node failure for CDI we have a bigger
outstanding issue remaining to figure out how to deal with volume
connections.  We can't just simply reschedule the job.
Partial Fixes #400
```Image pods now use RestartOnFailure (Cloner pods …
```
> Set pod restart policy to "OnFailure" and cleanup succesful pods

- pkg/common/common.go
Fixed a couple of typos in common.go file.
```release-note
NONE
```
> Fix typos in common.go

- cmd/cdi-cloner/clonertarget.go
- cmd/cdi-cloner/clonertarget_test.go
- pkg/importer/dataStream.go
- pkg/importer/dataStream_test.go
- pkg/util/util.go
This PR allows for rolling timeouts on long transfers. As long as there is some activity for 10 minutes the transfer will continue. Right now we have a timeout on imports of one hour, anything that takes longer will abort regardless of progress being made. This allows for long running imports to not abort as long as progress is happening, and for it to abort if the other end is really not sending anything.
```release-note
Rolling timeouts on long imports, as long as there is activity within the last 10 minutes the import will not timeout
```
> Rolling timeout on streaming transfer.

- cmd/cdi-apiserver/apiserver.go
- pkg/apiserver/apiserver.go
- pkg/apiserver/apiserver_test.go
Since API Server isn't upload specific anymore we should change the name into  cdiAPIServer and cdiApiAppm according to @mhenriks suggestion in #500 .
```release-note
NONE
```
> change api server name to CdiAPIServer

- doc/local-pv-allocation.md
- manifests/example/local-pv-allocation-claim.yaml
- manifests/example/local-pv-allocation.yaml
With this PR one can choose the node where  a VM disk will be provisioned so that the VM can run on this specific node.
```release-note
Provision a VM disk on a specific node with Local Volume
```
> Determine node where local PV is allocated

- cmd/cdi-importer/importer.go
- doc/annotations.md
- pkg/common/common.go
- pkg/controller/import-controller.go
- pkg/controller/util.go
- pkg/controller/util_test.go
- pkg/importer/dataStream.go
- pkg/importer/dataStream_test.go
- tools/cdi-func-test-file-host-init/main.go
This PR adds new annotations to help determine the source and content type used for an import.
```release-note
New annotation for source: cdi.kubevirt.io/storage.import.source
New annotation for content-type: cdi.kubevirt.io/storage.contentType
```
> Add source and contentType annotations

- manifests/example/upload-datavolume.yaml
fix upload-datavolume example manifest. upload source can't be empty and should be an empty struct.
```release-note
None
```
> fix upload-datavolume manifest

- cmd/cdi-importer/importer.go
- pkg/common/common.go
- pkg/controller/import-controller.go
- pkg/controller/import_controller_ginkgo_test.go
- pkg/controller/util.go
- pkg/controller/util_test.go
- pkg/image/qemu.go
- pkg/importer/dataStream.go
- pkg/importer/dataStream_test.go
- pkg/util/util.go
- pkg/util/util_test.go
Combined code from #489 and #490 by
@gites and
@danielerez
Added some tests and rebased on current master.
This PR calculates the needed image size based on the PVC request size (Not the actual PVC size), and resizes the image to match.
Fixes #482 
This should finally get the feature in CDI.
```release-note
Disk images are resized to the PVC request size.
```
Co-authored-by: Tomasz Pawelczak <gites@users.noreply.github.com>
Co-authored-by: Daniel Erez <danielerez@users.noreply.github.com>
> Specify image size

- pkg/image/qemu.go
- pkg/image/qemu_test.go
- pkg/importer/dataStream.go
- pkg/importer/dataStream_test.go
- pkg/util/util_test.go
- tests/transport_test.go
- tests/utils.go
Resize was not being called in all paths, specifically the streaming path was not working.
Updated unit and functional tests to take resize into account.
Fixes #
```release-note
NONE
```
> Fixes incorrect call of resize.

- cluster/clean.sh
- manifests/templates/cdi-controller.yaml.in
cdi-apiserver always needs permission to read the `extension-apiserver-authentication` configmap in kube-system.  Currently, this is not an issue as CDI is installed in kube-system.  But in order to support CDI in a different namespace, let's explicitly give the appropriate permissions to cdi-apiserver.
Fixes #531 
```release-note
NONE
```
> Support CDI in any namespace

- pkg/image/qemu.go
Fix string formatting of size arg, to resolve: "Sprintf format %s has arg size of wrong type .../resource.Quantity"
Fixes #
```release-note
None
```
> image: fix size (Quantity) string format

- manifests/example/local-pv-allocation-claim.yaml
manifest/example/local-pv-allocation-claim.yaml fails on validation as 'annotations' tag is missing
Fixes #565 
```release-note
None
```
> manifest/example/local-pv-allocation-claim.yaml fails on validation #565

- pkg/apiserver/apiserver.go
The recent kubernetes CVE got me thinking about our api server security.  Turns out it didn't validate that requests were coming from the kubernetes api server.  Still required a client cert.  But could have been any cert.
Fixes #
```release-note
NONE
```
> api server not validating client cert

- cmd/cdi-cloner/cloner_startup.sh
Add `--sparse` to tar on `cloner-startup.sh` so sparse files are not unsparsified when cloned.
Fixes #574
Fixes [BZ#1658615](https://bugzilla.redhat.com/show_bug.cgi?id=1658615)
```release-note
Handle sparse files when cloning PVCs.
```
Signed-off-by: Sergi Jimenez <sjr@redhat.com>
> fix: Handle sparse files when cloning

- doc/image-from-registry.md
- manifests/example/registry-image-pvc.yaml
Change-Id: I3cd19b512ff46e295ae4a093400c5cac9b189652
- Added an example yaml of import registry image (to manifest/example/).
- Updated import-from-registry.md.
Fixes #
```release-note
None
```
> manifests example: import registry image

- pkg/apiserver/apiserver.go
- pkg/apiserver/apiserver_test.go
(At least) by convention names and singularNames are all lower case. If
they're not, it might confuse client libraries that don't lowercase
everything proactively. Example:
https://github.com/openshift/openshift-restclient-python/pull/250
Release note:
```release-note
Correct API discovery for UploadTokenRequests
```
> Correct singularName for UploadTokenRequests

- manifests/example/datavolume.yaml
"hostpath" storage class probably doesn't exist so don't explecitly specify it
Fixes #
```release-note
NONE
```
> don't specify storage class in example dv manifest

- doc/exposing-upload-proxy.md
- manifests/templates/cdi-uploadproxy-ingress.yaml.in
- manifests/templates/cdi-uploadproxy-route.yaml.in
create an ingress/route that will enable uploading data from outside of the cluster
```release-note
Added Ingress and Route manifests for uploading images from outside of the cluster
```
> Ingress/Route manifests for Upload

- pkg/importer/dataStream_test.go
disable temporarily qcow2 and qcow2.xz data stream tests since they are sporadically failing, as described in #580.
```release-note
NONE
```
> disable more data stream tests

- pkg/apiserver/webhooks/validating-webhook/validating-webhook.go
Webhook validation for Blank image source in datavolume, is missing.
Fixes #571 
```release-note
NONE
```
> Add Blank Image source to Datavolume validation

- manifests/templates/cdi-uploadproxy-ingress.yaml.in
missing ```"``` in ```proxy-body-size``` field, causing an error when trying to apply the manifest.
Fixes #
```release-note
NONE
```
> fix typo in cdi-uploadproxy-ingress manifest

- hack/update-codegen.sh
Turns out wildcards aren't evaluated by bash when executing a script.  
Fixes #
```release-note
NONE
```
> make sure all generated client code actually gets deleted

- api/openapi-spec/swagger.json
- cmd/cdi-importer/importer.go
- manifests/example/import-archive-datavolume.yaml
- manifests/example/import-archive-pvc.yaml
- pkg/apis/datavolumecontroller/v1alpha1/openapi_generated.go
- pkg/apis/datavolumecontroller/v1alpha1/types.go
- pkg/apis/datavolumecontroller/v1alpha1/types_swagger_generated.go
- pkg/controller/datavolume-controller.go
- pkg/controller/util.go
- pkg/controller/util_test.go
- pkg/importer/dataStream.go
- pkg/importer/dataStream_test.go
- pkg/importer/registry_test.go
- tests/import_test.go
- tests/local_volume_test.go
Adding DataVolume support for unpacking imported archive
```release-note
Adding DataVolume support for unpacking imported archive
```
> Adding DataVolume support for unpacking imported archive

- cluster/sync.sh
- cluster/up.sh
- tests/datavolume_test.go
- tests/utils/datavolume.go
This PR adds functional tests for testing importing from registry.
Fixes #
Added a line that tests that DataVolume can be created with import from registry source. The registry utilized is cdi-docker-registry-host.kube-system used by functional tests.
```release-note
None
```
> Integration test between DataVolume and import from registry 

- tests/api_validation_test.go
- tests/basic_sanity_test.go
- tests/cloner_test.go
- tests/datavolume_test.go
- tests/import_test.go
- tests/leaderelection_test.go
- tests/local_volume_test.go
- tests/upload_test.go
Changed all test to have rfe id, test id, criticality etc attributes
based on issue
https://github.com/kubevirt/containerized-data-importer/issues/359
Updated most of the existing tests, so we will be able to auto create them in Polarion from the code.
There are 2 steps to it:
first, we create the tests without test ids (if they are new tests)
after running the script which creates the tests in Polarion (kubevirt/qe-tools/polarion-generator), each one gets its own ID,
and we can than add the test ids to the test code (this will allow reporting & changing the test in the future).
```release-note
NONE
```
> Add test attributes

- automation/test.sh
The CI is no longer generating junit reports because we switched directory that we are running in. This patch fixes the path in which the junit report output directory is being created.
```release-note
NONE
```
> Fixed junit report not getting generated.

- api/openapi-spec/swagger.json
- pkg/apis/core/v1alpha1/openapi_generated.go
- pkg/apis/core/v1alpha1/types.go
This PR makes the data volume status object optional.
Fixes #
```release-note
NONE
```
> Make data volume status optional.

- .travis.yml
- pkg/apiserver/apiserver_test.go
- pkg/util/util_test.go
This PR removes the useless creation of minikube (v1.9) and the deployment of CDI (latest) and kubevirt(0.4) from the travis build. We now have much better tests of if CDI can be deployed and it wasn't testing the correct version of CDI anyway.
Fixes #
```release-note
NONE
```
> Remove minikube deployment from travis.

- manifests/templates/cdi-operator.yaml.in
The CDI operator CRD does not have a label.  This makes it hard to identify what resources are associated with the operator.
KubeVirt's CI needs a label to make tearing down the cluster work properly. I've already fixed this in the KubeVirt CDI related manifests that we test with https://github.com/kubevirt/kubevirt/pull/1953  We should go ahead and address the issue here as well. 
```release-note
NONE
```
> The Operator CRD needs the operator.cdi.kubevirt.io label

- .travis.yml
This PR enables the api reference documentation generation.
Fixes #
```release-note
API reference documentation is now generated on release.
```
> Enable api reference guide generation.

- pkg/controller/datavolume-controller.go
- tests/datavolume_test.go
Sometimes, creating/deleting/creating the same datavolume causes datavolume controller to be in a sad state.
Fixes #636 
```release-note
NONE
```
> fix for issue #636: can't create/delete/create the same datavolume

- cmd/cdi-importer/importer.go
- pkg/importer/dataStream.go
- pkg/importer/dataStream_test.go
- pkg/importer/registry_test.go
This PR fixes an issue where we check the available space after we have downloaded the image, but before we resize the image. This causes the resize to be of the wrong size (available - image size). This PR fixes that.
Fixes #
```release-note
Resize now properly counts the available space before downloading an image.
```
> Check space before importing to report correct image resize size.

- pkg/controller/import-controller.go
- pkg/controller/import-controller_test.go
The import controller was marking import pods as failed when they were starting up.  This was not playing well with kubevirt as it deletes/recreates dataolumes on when they enter failed state.  Basically, datavolumes were getting deleted before they were populated.
For now, just making sure we don't mark failure when starting up but bigger conversation is necessary to determine exactly if/when an import pod should be marked as failed.
#646 and #495 related
Fixes #
```release-note
NONE
```
> Import pod status should not be 'Failed' when starting up

- doc.go
This PR fixes issue #654. This is would help us vendor the library using dep.
More details about a similar problem is found [here](https://github.com/kubevirt/kubevirt/issues/2017).
```
add a doc.go file in project root to make vedoring work with dep
```
> add a random go file to satisfy dep package manager

- pkg/importer/dataStream.go
- tests/transport_test.go
An ISO file should not be resized to the requested PVC size as an iso file is likely an installation media and resizing it doesn't make sense.
```release-note
Imported iso image file should not be resized
```
> Imported iso image file should not be resized

- pkg/controller/controller.go
- pkg/controller/datavolume-controller.go
- pkg/controller/import-controller.go
- pkg/controller/upload-controller.go
- tests/import_test.go
Related to issue #525, we have a similar situation when using PVCs
without DataVolumes.  The user requests a PVC with CDI Importer
annotations, if the Importer POD is in a fail/retry loop and the user
requests deletion of the PVC the PVC will be stuck in terminating
waiting for the user to forcibly delete the running Import POD.
This PR adds a check for PVC delete in the import controller and
will delete the POD explicitly if it sees a PVC delete request.  This
will also be picked up for Import DataVolumes, so we can remove the
extra checks that were previously added in the DV controller.
fixes #649
fixes #525
```release-note
NONE
```
> Delete importer pod on pvc delete request

- cmd/cdi-importer/importer.go
- pkg/common/common.go
- pkg/controller/import-controller.go
- pkg/controller/util.go
- pkg/controller/util_test.go
- pkg/image/qemu_test.go
- pkg/image/skopeo.go
- pkg/image/skopeo_test.go
- pkg/importer/dataStream.go
- pkg/importer/dataStream_test.go
- pkg/importer/registry_test.go
- pkg/operator/controller/controller.go
- pkg/operator/controller/controller_test.go
- pkg/operator/resources/namespaced/controller.go
- tests/transport_test.go
- tests/utils/configmaps.go
Allow users to specify insecure registries via `cdi-insecure-registries` configmap.
Whenever a user imports from registry, the controller will check if the registry exists in the configmap.  If so, the importer pod is allowed to do an insecure import.
Fixes #
```release-note
Insecure registry support
```
> add configmap for insecure registries

- api/openapi-spec/swagger.json
- cmd/cdi-controller/controller.go
- pkg/apis/core/v1alpha1/types.go
- pkg/client/clientset/versioned/typed/core/v1alpha1/cdi.go
- pkg/client/clientset/versioned/typed/core/v1alpha1/cdiconfig.go
- pkg/client/clientset/versioned/typed/core/v1alpha1/core_client.go
- pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_cdi.go
- pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_cdiconfig.go
- pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_core_client.go
- pkg/client/informers/externalversions/core/v1alpha1/cdi.go
- pkg/client/informers/externalversions/core/v1alpha1/cdiconfig.go
- pkg/client/informers/externalversions/core/v1alpha1/interface.go
- pkg/client/listers/core/v1alpha1/cdi.go
- pkg/client/listers/core/v1alpha1/cdiconfig.go
- pkg/client/listers/core/v1alpha1/expansion_generated.go
- pkg/controller/config-controller.go
- pkg/controller/config-controller_test.go
- pkg/controller/util.go
- pkg/controller/util_test.go
The controller was crashing occasionally.  I think this will fix it.  Basically, update was being called with an object not returned from the API (and had no resource version)
Also, made the generated clients cluster scoped and therefor less awkward to use.
Fixes #
```release-note
NONE
```
> make CDIConfig client cluster scoped and fix occasional crash

- cluster/sync.sh
- hack/build/config.sh
- manifests/templates/cdi-operator.yaml.in
- pkg/operator/resources/namespaced/controller.go
Did you ever notice that `make cluster sync` doesn't work so great on OpenShift?  Like, if you make a change locally, it doesn't get reflected in the cluster?
Turns out that OpenShift actually respects the pullPolicy param when the tag is `latest`.  Looks like k8s always pulls `latest` regardless of pullPolicy.
Fixes #
```release-note
NONE
```
> use pullPolicy=Always for openshift

- manifests/example/registry-image-datavolume.yaml
**What this PR does / why we need it**: fix example manifest
Correct syntax as per code: https://github.com/kubevirt/containerized-data-importer/blob/master/pkg/apis/core/v1alpha1/types.go#L92
> Correct datavol src:registry example manifest

- doc/exposing-upload-proxy.md
- doc/upload.md
Uploadproxy routs should be reencrypt by default.  But show how to do passthrough with customer generated certs.
Fixes #
```release-note
NONE
```
> refresh docs for uploadproxy reencrypt routes

- cmd/cdi-uploadserver/uploadserver.go
- pkg/common/common.go
- pkg/controller/util.go
- pkg/controller/util_test.go
- pkg/importer/dataStream.go
- pkg/importer/dataStream_test.go
- pkg/uploadserver/uploadserver.go
- pkg/uploadserver/uploadserver_test.go
- tests/framework/pvc.go
- tests/upload_test.go
- tests/utils/upload.go
This PR allows uploaded images to be resized to the PVC request size like with an import.
Fixes #698 
```release-note
Uploaded images are now resized like import.
```
> Resize on upload.

- pkg/operator/resources/namespaced/controller.go
Without TypeMeta, controller manifest generated by manifest-generator
lacks Kind attribute for the ConfigMap, which makes `oc` fail as
follows:
error validating "cdi-controller.yaml": error validating data:
[apiVersion not set, kind not set]; if you choose to ignore these
errors, turn validation off with --validate=false
```release-note
NONE
```
> Add type metadata to cdi-insecure registries ConfigMap

- cmd/cdi-importer/importer.go
- pkg/importer/dataStream.go
- pkg/importer/dataStream_test.go
- pkg/importer/registry_test.go
This PR fixes an issue where validating how much space was available the wrong value was being passed to the validation, and thus it would fail in several instances. In particular it would fail for upload validation checking.
Fixes #
```release-note
NONE
```
> Fix wrong value being passed to validation.

- cmd/cdi-apiserver/apiserver.go
- hack/build/build-go.sh
- hack/build/common.sh
- hack/build/version.sh
- pkg/version/base.go
- pkg/version/types.go
- pkg/version/verflag/verflag.go
- pkg/version/version.go
This PR adds a `--version` command line flag to cdi-apiserver to help identify CDI version running in a container.
Example output:
> kubectl --namespace=cdi exec cdi-apiserver-7dcd78644b-jztpw -- virt-cdi-apiserver --version
Containerized Data Importer v1.6.0-86+cbadd09168e863
Fixes #667
This code has been copy/pasted from KubeVirt and Kubernetes implementations.
The command line flag has been added only to cdi-apiserver command. It's just a matter of one import and one function call to add it to other cdi-* commands (e.g: cdi-operator) if needed.
The version …
> Add a --version flag to cdi-apiserver

- cmd/cdi-controller/controller.go
- doc/cdi-config.md
- doc/scratch-space.md
- pkg/apis/core/v1alpha1/deepcopy_generated.go
- pkg/apis/core/v1alpha1/openapi_generated.go
- pkg/apis/core/v1alpha1/types.go
- pkg/controller/config-controller.go
- pkg/controller/config-controller_test.go
- pkg/controller/import-controller.go
- pkg/controller/import_controller_ginkgo_test.go
- pkg/controller/upload-controller.go
- pkg/controller/upload-controller_test.go
- pkg/controller/util.go
- pkg/controller/util_test.go
Allow admins to specify which storage class to use for scratch space using the CDIConfig object.
Fixes #
```release-note
Scratch storage class can be specified using the CDIConfig CRD
```
> Use CDIConfig for scratch storage class.

- hack/build/docker/cdi-func-test-file-host-http/nginx.conf
- manifests/templates/cdi-operator.yaml.in
- manifests/templates/file-host.yaml.in
- manifests/templates/registry-host.yaml.in
- tests/framework/framework.go
Looks like all the registry related functional tests have been failing for awhile.  Maybe this long overdue change will help us figure out what's going on.
Fixes #
```release-note
NONE
```
> dump logs when functional tests fail

- pkg/controller/import-controller.go
- pkg/controller/upload-controller.go
- pkg/controller/util.go
- pkg/controller/util_test.go
Allow scratch space without storage class.
Fixes #
#726
```release-note
Allow scratch space without requiring storage class.
```
> Allow missing storage class for scratch space, if none exists, create scratch PVC without SC

- pkg/controller/config-controller.go
- tests/cdiconfig_test.go
The cdi config controller would hang waiting for a cache sync on routes that will never happen in k8s, thus it would not update the CDIConfig object and the scratch storage class would not be correctly found.
Fixes #
```release-note
NONE
```
> Fix issue with the cdi config controller hanging in k8s

- pkg/controller/clone-controller.go
Fixes a bug where the target namespace pod cloning pod was not being cleaned up properly.
Fixes #
```release-note
Target pod is now cleaned up properly when cloning across namespaces.
```
> Fix target pod cleanup across namespaces

- pkg/operator/resources/cluster/datavolume.go
- tests/api_validation_test.go
- tests/manifests/dvMissingPVCAccessModes.yaml
Fixes #735
```release-note
DataVolume creation is rejected if PVC accessModes field is missing
```
> PVC accessModes should be a required field

- pkg/controller/config-controller_test.go
Disable a flaky CDI Config unit test that causes travis failures every other time.
Fixes #
```release-note
NONE
```
> Disable flaky unit test related to CDI Config

- pkg/controller/clone-controller.go
- pkg/controller/clone-controller_test.go
- pkg/controller/util.go
- pkg/controller/util_test.go
Description of problem:
When a VM is created with long enough name, and than this VM is cloned, the cloning process fails on error:
E0319 12:24:27.745852       1 clone-controller.go:215] error processing pvc "default/vm-url-test-jwbfh-clone-vm-url-test-jwbfh-rootdisk-clone": invalid label value: "vm-url-test-jwbfh-clone-vm-url-test-jwbfh-rootdisk-clone-source-pod": must be no more than 63 characters
Result: Cloned VM is stuck on pending, cdi-deployment pod fails on error mentioned above
Fixes #1690415
```release-note
None
```
> Fix for issue #1690415 - CDI appends 'source pod' to a label and may fail on error that label must not be longer than 63 characters

- api/openapi-spec/swagger.json
- pkg/apis/core/v1alpha1/openapi_generated.go
- pkg/apis/core/v1alpha1/types.go
- pkg/controller/datavolume-controller.go
- pkg/controller/datavolume-controller_test.go
- tests/datavolume_test.go
- tests/framework/framework.go
- tests/utils/datavolume.go
This PR adds DataVolume status field for import/clone progress.
Fixes #
```release-note
DataVolume status now has a progress field that is updated during import/clone.
```
> Update Datavolume status to include progress

- pkg/controller/datavolume-controller.go
If the controller was unable to get pod metrics it was reporting an error in the log while it then ignored the problem and tried again. So changed the error to be a log message in debug mode.
Fixes #
```release-note
NONE
```
> Unable to get progress metrics is not an error.

- doc/datavolumes.md
Describe how to change a datavolume manifest to support import/clone/upload to a raw block persistent volume. 
```release-note
none
```
> Adding a description about Block volumeMode field in a DataVolume manifest

- pkg/common/common.go
Changes the prometheus label used by CDI components to not clash with kubevirt.
Fixes #753 
```release-note
NONE
```
> Change the prometheus label used by cdi.

- pkg/apiserver/apiserver.go
- pkg/apiserver/apiserver_test.go
The CDI apiserver does not work (and is breaking other stuff like KubeVirt install) on OCP 4 because the aggregation layer is expecting all extension apiservers to return a RootPaths struct when GETting the root ("/") of the apiserver.  
Fixes #
```release-note
NONE
```
> apiserver should return RootPaths

- pkg/apiserver/apiserver.go
- pkg/apiserver/apiserver_test.go
Would be nice to backport this.
Fixes #
```release-note
NONE
```
> BACKPORT to 1.8 - apiserver should return RootPaths

- cmd/cdi-controller/controller.go
- pkg/controller/config-controller.go
- pkg/controller/config-controller_test.go
Removed label from Ingress Informer Factory. Ingress created for CDI services doesn't need a label.
Fixes #761 
```release-note
NONE
```
> Ingress should not be required to have a label

- cluster/clean.sh
We were missing some resources in the cleanup on make cluster-clean
(when running against an external cluster).  We also weren't patching
any of the finalizers so the result is a delete of the cdi namespace
would hang in terminating state forever.
This change explicitly checks all resources on the cluster for a cdi
label and it also patches the cdi objects to clear out the finalizer.
Fixes #774
```release-note
NONE
```
> Fix cluster-clean

- pkg/operator/resources/cluster/cdiconfig.go
- pkg/operator/resources/cluster/datavolume.go
- pkg/operator/resources/operator/operator.go
This adds the `all` category to the CDI objects.  Currently CDI objects
aren't returned from a get all request, adding the category all
parameter to the objects fixes that.
With this change a `get all` will include things like a users DataVolumes.
Note, this is NOT allowed for tokens, so we don't set that on upload
tokens.
```release-note
Make CDI objects visible to `get all` queries.
```
> Enable return of CDI objects from `get all`

- cmd/cdi-apiserver/apiserver.go
- pkg/apiserver/apiserver.go
- pkg/apiserver/apiserver_test.go
- pkg/apiserver/auth-config.go
- pkg/apiserver/auth-config_test.go
- pkg/apiserver/authorizer.go
- pkg/apiserver/authorizer_test.go
- pkg/apiserver/util.go
- pkg/controller/upload-controller.go
- pkg/controller/upload-controller_test.go
- pkg/operator/resources/namespaced/apiserver.go
**What this PR does / why we need it**:  On OCP 4, the apiserver rotates the proxy CA cert daily.  This caused the CDI apiserver to be unusable after a day or so.  The cdi apiserver was rejecting the new client cert because it was not aware the rotation occurred.
Fixes #
In my testing, the easiest way to reproduce the issue is with the kubevirtci os-3.11 build.  Do the following:
```bash
export KUBEVIRT_PROVIDER=os-3.11.0
make cluster-up cluster-sync
k -v 8 apply -f manifests/example/upload-datavolume.yaml -o yaml
k -v 8 apply -f manifests/example/upload-datavolume-token.yaml -o yaml …
```
> watch extension-apiserver-authentication configmap and refresh client CA

- cmd/cdi-importer/importer.go
- pkg/apiserver/webhooks/validating-webhook/validating-webhook.go
- pkg/controller/datavolume-controller.go
fixing a bug where we allow import from registry when contentType is not kubevirt
Fixes #808 
```release-note
BugFix: The check not to allow import from registry if contentType is not 'kubevirt' was removed #808 
```
> Adding code to not allow importing from registry when contenType is not kubevirt

- automation/check-patch.yumrepos
- hack/build/docker/builder/fedora.repo
Accidentally put in directive to ignore /etc/yum.repos.d where I put the altered repo files.
Fixes #
```release-note
NONE
```
> Fix microdnf not using the repo files in /etc/yum.repos.d

- tests/transport_test.go
CI sometimes fails when it was simply waiting for the verify pod to start on a slow CI system. Increasing the timeout to 90 seconds instead of 20.
Fixes #
```release-note
NONE
```
> Increase verify pod timeout to 90 seconds.

- pkg/operator/resources/utils/common.go
We would like all cdi pods to be labeled with cdi.kubevirt.io label when deployed via OLM.
Untill now cdi-operator pod did not have its operator.cdi.kubevirt.io label when deployed via OLM.
This PR fixes it. Now when deployed:
```
cdi-apiserver-799b86cd47-67lxq                   1/1       Running   0          2m        cdi.kubevirt.io=cdi-apiserver,pod-template-hash=799b86cd47
cdi-deployment-67855b764d-kscbn                  1/1       Running   0          2m        app=containerized-data-importer,cdi.kubevirt.io=,pod-template-hash=67855b764d
cdi-operator-694dc4dcd-zcwk2                     1/1       Running   0          4m        name=cdi-operator,operator.cdi.kubevirt.io=,pod-template-hash=694dc4dcd
cdi-uploadproxy-7cd5bdb789-4r247 …
```
> Set label operator.cdi.kubevirt.io to deployment spec of cdi-operator

- cmd/cdi-importer/importer.go
- pkg/common/common.go
- pkg/controller/clone-controller.go
- pkg/controller/datavolume-controller.go
- pkg/importer/data-processor.go
- pkg/util/util.go
This PR sends importer pod errors to the PVC event log to indicate why imports failed.
Fixes #
```release-note
PVC event log now contains import failure messages.
```
> Add pod messages to PVC events.

- cmd/cdi-controller/controller.go
- tests/leaderelection_test.go
Ready checks were added to the CDI controller after leader election.  Unfortunately, there was a bug.  The controller would only be ready after becoming leader.  But in the case a new deployment rollout, the new pod must be ready for the old pod to be killed.  That would obviously never happen.
**What this PR does / why we need it**:  Make the controller be "Ready" once the leader election thread is started.  Not after becoming leader.
Fixes #824
```release-note
NONE
```
> Controller leader election broken

- doc/image-from-registry.md
- manifests/templates/registry-host.yaml.in
- pkg/controller/util.go
- pkg/controller/util_test.go
- tests/transport_test.go
- tests/utils/configmaps.go
**What this PR does / why we need it**:  Turns out you can't have `:` in a configmap key.  Which means no host:port combos in the cdi-insecure-registries configmap.  Which is probably necessary for many internal registries.
Didn't catch this in testing because our functional test registry listens on port 443.
Fixes #833
Fixed by using the `value` fields of the configmap.  Keys can be anything. 
```release-note
NONE
```
> fix host:port not allowed in insecure registry configmap

- doc/image-from-registry.md
- manifests/templates/registry-host.yaml.in
- pkg/controller/util.go
- pkg/controller/util_test.go
- tests/transport_test.go
- tests/utils/configmaps.go
This is a backport of PR #832 
```
Turns out you can't have : in a configmap key. Which means no host:port combos in the cdi-insecure-registries configmap. Which is probably necessary for many internal registries.
Didn't catch this in testing because our functional test registry listens on port 443.
```
Fixes #
#833 
```release-note
NONE
```
> fix host:port not allowed in insecure registry configmap 

- tests/leaderelection_test.go
Change what we call the new deployment in the leader election test so it doesn't match the check to see if we have multiple deployments in pre test checks. Sometimes it takes a little bit before the test deployment is removed, and this causes test failures that aren't actually failures.
Fixes #
```release-note
NONE
```
> Change name of new deployment in leader election test.

- tests/upload_test.go
Upload tests from tests/transport_tests.go sometimes fail with the following error:
```
/go/src/kubevirt.io/containerized-data-importer/vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:46
Unexpected error:
<*errors.errorString | 0xc000079800>: {
s: "timed out waiting for the condition",
}
timed out waiting for the condition
occurred
```
This PR increase the timeout for those tests so that the cdi-upload pod has enough time to start and get ready. 
```release-note
NONE
```
> tests: wait more time for cdi-upload pod to be ready

- pkg/operator/resources/cluster/factory.go
- pkg/operator/resources/cluster/uploadproxy.go
- pkg/operator/resources/namespaced/uploadproxy.go
- pkg/uploadproxy/uploadproxy.go
- pkg/uploadproxy/uploadproxy_test.go
- tests/upload_test.go
When trying to upload to a pvc, before trying to connect to the upload pod, we check if this pod exists.
If it doesn't exist it means we already uploaded to this pvc so we should fail before trying to connect:
The new check returns:
From `cdi-uploadproxy` logs:
```
Rejecting Upload Request for Pod cdi-upload-upload-datavolume that doesn't exist
```
Fixes #
```release-note
BugFix: provide meaningful error if trying to upload again to the same pvc.
```
> Upload to the same target PVC should have a meaningful error

- pkg/controller/util.go
- pkg/controller/util_test.go
Sets the user the importer and upload are running as so we have no issues when trying to read the home directory (for instance skopeo uses /home/cdi-importer/.docker/ to get some user information. If the user is not set this will fail.
Fixes #
```release-note
NONE
```
> Set RunAsUser to the one defined in the docker file.

- pkg/operator/controller/route.go
Increased cdi-uploadproxy timeout as a workaround to `virtctl` receiving OpenShift route timeout when uploading large qcow images.
Fixes #
```release-note
BugFix: set a higher connection timeout for cdi-uploadproxy route.
```
> increase uploadproxy route timeout

- doc/scratch-space.md
Document current limitation requiring a file-based storage class for scratch space.
Fixes #
```release-note
NONE
```
> Document file mode limitation for scratch space

- doc/datavolumes.md
- doc/image-from-registry.md
**What this PR does / why we need it**:    
Not clear to users that certConfigMap must be in the same namespace as as theDataVolum/PVC.
Relevant bz: https://bugzilla.redhat.com/show_bug.cgi?id=1715413
I hope this helps.
Fixes #
```release-note
NONE
```
> Better document certConfigMap

- tests/leaderelection_test.go
Add a functional test that verifies that switching leader during an import will not interrupt the import.
Fixes #
```release-note
NONE
```
> Added leader election functional test

- cluster-sync/okd-4.1.2/provider.sh
Fixes issue where using the okd-4.1.2 provider you end up in the local-storage namespace instead of the default namespace after syncing the first time.
Fixes #
```release-note
NONE
```
> Switch to default namespace after creating local storage.

- Makefile
make docker failswith error, since it expects olm manifests
since olm catalog source support, docker target in Makefile requires manifests to be prepared
Fixes #
since olm catalog source support, docker target in Makefile requires manifests to be prepared
```release-note
NONE
```
> * make file fix: all target requires manifests 

- pkg/operator/resources/operator/components.go
Since the operator name is different on
downstream (cnv-cdi-operator), adding the option
to change it when creating the deployment manifest.
This is important for automating the build process
upstream and downstream for the HCO.
Signed-off-by: Ido Rosenzwig <irosenzw@redhat.com>
> Add the option to change the operator name

- README.md
This got missed with the CR.yaml rename.
```release-note
NONE
```
> Fix install instruction for 1.10+

- pkg/apiserver/apiserver.go
- pkg/apiserver/apiserver_test.go
**What this PR does / why we need it**: 
Copy/paste error, was using the validating webhook name for the mutating webhook registration
Fixes #
We should backport this.
```release-note
NONE
```
> mutating webhook registration broken

- pkg/controller/datavolume-controller.go
- pkg/controller/datavolume-controller_test.go
Pass annotations from Data Volume to PVC.
Fixes #
```release-note
NONE
```
> Pass annotations from DV to PVC.

- pkg/apiserver/webhooks/datavolume-validate.go
- pkg/apiserver/webhooks/datavolume-validate_test.go
Fix #895 
Fixes #895 
```release-note
Adding webhook validation for length of DataVolume name
```
> Adding webhook validation for length of DataVolume name

- tests/test.go
- tests/utils/common.go
- tests/utils/datavolume.go
- tests/utils/pvc.go
Added support for hostpath-provisioner in functional tests:
* Introduced 'AddProvisionOnNodeToAnn' func for adding
'kubevirt.io/provisionOnNode' annotaion when hostpath-provisioner
is the default storage class.
* pvc -> NewPVCDefinition and datavolume -> CreateDataVolumeFromDefinition:
invoke 'AddProvisionOnNodeToAnn' when needed.
```release-note
NONE
```
> func-tests: support hostpath-provisioner

- hack/build/docker/cdi-olm-catalog/Dockerfile
Set testing olm catalog container version to 4.1.0.
Fixes #
```release-note
NONE
```
> Downgrade to 4.1.0 version, 4.2.0 is broken.

- tests/test.go
- tests/utils/common.go
- tests/utils/datavolume.go
- tests/utils/pvc.go
Introduced 'AddProvisionOnNodeToAnn' func for adding
'kubevirt.io/provisionOnNode' annotaion when hostpath-provisioner
is the default storage class.
pvc -> NewPVCDefinition and datavolume -> CreateDataVolumeFromDefinition:
invoke 'AddProvisionOnNodeToAnn' when needed.
Fixes #
```release-note
None
```
> Added support for hostpath-provisioner in functional tests: (#912)

- hack/build/olm.sh
Prevent pushing OLM bundle with CSV_VERSION = 0.0.0 to quay
CSV Version 0.0.0 is a default one and is used by travis 
Fixes #
Prevent pushing OLM bundle with CSV_VERSION = 0.0.0 to quay
CSV Version 0.0.0 is a default one and is used by travis 
```release-note
prevent CSV_VERSION=0.0.0 from being pushed to quay
```
> * Prevent pushing OLM bundle with CSV_VERSION = 0.0.0 to quay

- automation/check-patch.yumrepos
- hack/build/build-cdi-func-test-file-host.sh
- hack/build/docker/builder/Dockerfile
- hack/build/docker/builder/fedora.repo
- hack/build/docker/cdi-apiserver/Dockerfile
- hack/build/docker/cdi-cloner/Dockerfile
- hack/build/docker/cdi-controller/Dockerfile
- hack/build/docker/cdi-func-test-block-device/Dockerfile
- hack/build/docker/cdi-func-test-file-host-http/Dockerfile
- hack/build/docker/cdi-func-test-file-host-init/Dockerfile
- hack/build/docker/cdi-func-test-registry-init/Dockerfile
- hack/build/docker/cdi-func-test-registry-populate/Dockerfile
- hack/build/docker/cdi-importer/Dockerfile
- hack/build/docker/cdi-operator/Dockerfile
- hack/build/docker/cdi-uploadproxy/Dockerfile
- hack/build/docker/cdi-uploadserver/Dockerfile
- tests/datavolume_test.go
- tests/utils/datavolume.go
- tests/utils/pod.go
- tools/cdi-func-test-file-host-init/main.go
The newer version of qemu-img (3.1.0) that ships in Fedora 30 has issues
with streaming conversions whereby it hangs during the conversion
process.  Rather than try to force a downgrade of qemu when building
images instead, let's try reverting back to Fedora29 minimal which has
qemu-img version  3.0.0.
This issue has also exposed the fact that we aren't performing any
testing against streaming external images, we're only testing against
images that we've pulled in to our test infrastructure.  So add a
functional test that builds a DataVolume directly from the cirros site.
It's been discovered that qemu-img version 3.1.0 which ships in Fedora-30 hangs when trying to do a streaming conversion of the external cirros image.  It also turns out that we …
> Fallback to Fedora29 minimal for images

- .travis.yml
This PR strips the 'v' from the CSV_VERSION environment variable as the CSV parser doesn't like its numbers to start with v.
Fixes #
```release-note
NONE
```
> Strip 'v' from CSV_VERSION.

- hack/build/release-description.sh
Add link to cdi operator in release description script.
Fixes #
```release-note
NONE
```
> Update release message to include link to operator

- pkg/system/prlimit.go
Because cmd.wait blocked first, it was possible for it to close stdout/err before anything was read by the reader. This caused intermittent JSON parsing errors in the validation function.
Fixes #
```release-note
BugFix: Fixed race between cmd.Wait and stdout/err readers.
```
> Fix race in prlimit ExecWithLimits

- .travis.yml
Fixes #
```release-note
NONE
```
> Can't use skip_cleanup as it will think 0.0.0 is already published.

- .travis.yml
The olm manifests weren't being generated when creating a new release.
Fixes #
```release-note
NONE
```
> Run make manfiest and make olm-verify before pushing to quay.

- tests/framework/pvc.go
- tests/import_test.go
- tests/transport_test.go
Using ceph (and other dynamic provisioners) with file system volume mode, the transport tests would not have enough space to complete due to file system overhead. This PR fixes it.
Fixes #
```release-note
NONE
```
> Fix transport tests to work with ceph file system.

- automation/test.sh
- cluster-sync/install.sh
- cluster-sync/okd-4.1/install.sh
- cluster-sync/sync.sh
- pkg/operator/controller/controller.go
Switch OKD-4.1 provider from olm install to operator install.
Automatically test upgrade during CI runs.
Switch OKD 4.1 provider install from olm to operator.
Fixes #
```release-note
NONE
```
> Add upgrade from release version 1.10.4 to current master.

- hack/build/docker/cdi-olm-catalog/Dockerfile
The --chown option to the docker COPY command is only supported in
docker 17.09+.  This creates a dependency on docker-ce which is not
available in some distributions.  We can make our build work on more
environments if we use a separate chown command after the COPY.
Fixes #
```release-note
NONE
```
> Restore backwards compatible docker syntax

- cluster-sync/k8s-1.13.3/provider.sh
- tests/framework/pvc.go
- tests/local_volume_test.go
For the k8s lane set ceph to be the default storage class.
Fixes #
```release-note
NONE
```
> set ceph to be default sc

- cluster-sync/k8s-1.13.3/provider.sh
- cluster-sync/k8s-1.15.1/provider.sh
- tests/cloner_test.go
- tests/framework/pvc.go
- tests/import_test.go
- tests/smartclone_test.go
- tests/transport_test.go
- tests/upload_test.go
- tests/utils/upload.go
Previous PR was on wrong provider, k8s-1.13.3 while we use k8s-1.15.1 for CI.
Verify the flag is set before attempting to switch default classes.
Fixes #
```release-note
NONE
```
> Use right lane k8s-1.15.1, and verify that --enable-ceph is set.

- tests/operator_test.go
Functional test hard coded the name of the operator operand to be 'cdi' which is not always true. This PR improves the test by not assuming the name is 'cdi' but instead assuming there is only one operand and using that.
Fixes #
```release-note
NONE
```
> Don't hard code CDI CR object name to be cdi in tests.

- manifests/templates/release/cdi-operator.yaml.in
- pkg/operator/resources/cluster/factory.go
- pkg/operator/resources/cluster/rbac.go
- pkg/operator/resources/operator/operator.go
- tests/rbac_test.go
- tests/webhook_test.go
- tools/manifest-generator/manifest-generator.go
Signed-off-by: Michael Henriksen mhenriks@redhat.com
Create cluster roles that aggregate to admin/edit/view cluster roles.  This allows users with say the "admin" cluster role in any namespace to do whatever they want with CDI
Fixes #
CDI is not included in any of this.  Should it be?  Assumption is that we only want cluster admins messing with that.
```release-note
admin/view/edit aggregate cluster roles
```
> create aggregate cluster roles

- cluster-sync/k8s-1.15.1/provider.sh
- cmd/cdi-cloner/cloner_startup.sh
Make xfs default fs for ceph in k8s provider.
Fix issue when cloning in XFS the target would take more space than the source due to not being sparsified.
Update default FS on ceph to be xfs instead of ext4
Fixes #
```release-note
BugFix: cloning using xfs file system to same size PVC
```
> Sparsify clone tarring

- tests/rbac_test.go
These tests are causing an issue with OLM based install.  I also think they are unnecessary.  Who cares if there are extra rules as long as the ones we install are there?  
Fixes #
```release-note
NONE
```
> delete RBAC tests for unexpected aggregated PolicyRules

- pkg/image/qemu.go
- pkg/image/qemu_test.go
- pkg/importer/data-processor.go
- pkg/util/util.go
- pkg/util/util_test.go
- tests/cloner_test.go
- tests/framework/pvc.go
- tests/import_test.go
- tests/transport_test.go
- tests/upload_test.go
- tests/utils/pod.go
Use falloc when resizing/creating blank to make sure we can guarantee the space reported is available for VMs.
Fixes #
```release-note
Resize/Blank disk now use falloc instead of being sparse to guarantee available space.
```
> falloc on resize and blank disk.

- cluster-sync/k8s-1.15.1/provider.sh
- cmd/cdi-cloner/cloner_startup.sh
Make xfs default fs for ceph in k8s provider.
Backport of #966 
Fixes #
```release-note
None
```
> Sparsify clone tarring. (#966)

- tests/framework/pvc.go
- tests/import_test.go
- tests/transport_test.go
- tests/upload_test.go
- tests/utils/pod.go
In case of cluster with multiple nodes, the VerifyPvcEmpty pod could be scheduled on a different node than the importer, then it will fail to attach the PVC. (At least on CEPH/RBD/File).
Fixes #
```release-note
NONE
```
Co-authored-by: Daniel Erez <derez@redhat.com>
Signed-off-by: Fred Rolland <frolland@redhat.com>
> Add node selector for VerifyPvcEmpty pod

- pkg/apiserver/authorizer.go
- pkg/apiserver/authorizer_test.go
- pkg/operator/resources/cluster/rbac.go
- tests/rbac_test.go
apiserver should translate POST requests to "create".
also allowing admin/edit to do everything with uploadtokenrequests
Fixes #
```release-note
NONE
```
> apiserver not translating HTTP method

- cluster-sync/okd-4.1/provider.sh
- tests/leaderelection_test.go
The OKD sometimes take a bit to get the local storage class available, this PR adds a wait to make sure the local SC is available before setting it as default.
Fixes #
```release-note
NONE
```
> Wait for SC to be available before making it default

- tests/cloner_test.go
- tests/utils/datavolume.go
In case of a cluster with multiple nodes, the parallel cloning can take more time as the source pods can be scheduled on different nodes and the PVC cannot be attached on different nodes at the same time.
Fixes #
```release-note
NONE
```
Co-authored-by: Daniel Erez <derez@redhat.com>
Signed-off-by: Fred Rolland <frolland@redhat.com>
> Increase DV state timeout for multiple clone tests

- cmd/cdi-uploadserver/uploadserver.go
- pkg/controller/clone-controller.go
- pkg/controller/clone-controller_test.go
- pkg/controller/controller.go
- pkg/controller/controller_test.go
- pkg/controller/import-controller.go
- pkg/controller/upload-controller.go
- pkg/controller/upload-controller_test.go
- pkg/controller/util.go
- pkg/controller/util_test.go
- pkg/uploadserver/uploadserver.go
- pkg/uploadserver/uploadserver_test.go
- tests/cloner_test.go
Clone source pods currently use the same TLS client key/cert as uploadproxy.  This is a potential security concern because an attacker could do the following:
1) Create clone in namespace they have admin/edit access to
2) Get TLS key/cert from clone source pod environment
3) Use key/cert to upload to any uploadserver pod in the cluster
Addressing this by: 
1) Assigning unique CN for each source/target pod combo
2) Uploadserver pod validates CN
Fixes #
```release-note
Unique TLS key/cert per clone source pod
```
> Unique client cert per clone source pod

- pkg/operator/resources/cluster/uploadproxy.go
- pkg/uploadproxy/BUILD.bazel
- pkg/uploadproxy/uploadproxy.go
- pkg/uploadproxy/uploadproxy_test.go
- tests/upload_test.go
- tests/utils/pvc.go
- tests/utils/upload.go
The upload controller sets "ready" annotation on a PVC when the Pod should be ready to accept uploads.  This is a better thing to check than whatever we were doing before.
Fixes #
This may help with flaky upload tests
```release-note
NONE
```
> uploadproxy should use pod ready annotation

- cluster-sync/okd-4.1/provider.sh
cluster sync would fail if the Local storage was not available fast enough due to set -e, this disables set -e while waiting for Local storage class to become available
Fixes #
```release-note
NONE
```
> Don't fail immediately when Local is not found when syncing.

- cluster-up/cluster/okd-4.1/provider.sh
- hack/update-codegen.sh
Update OKD lane to use image with working certs: https://github.com/kubevirt/kubevirtci/pull/172
Fixes #
```release-note
NONE
```
> Update the kubevirtci OKD image to fix cert issue.

- doc/supported_operations.md
Update the support matrix to clarify how files are handled when
content-type is kubevirt and to explicitly state that disk images should
not be encapsulated in a tar archive.
Fixes #
```release-note
NONE
```
> doc: Clarify supported kubevirt formats

- go.mod
- pkg/controller/clone-controller.go
- pkg/controller/config-controller.go
- pkg/controller/datavolume-controller.go
- pkg/controller/import-controller.go
- pkg/controller/upload-controller.go
Fixes requeuing of objects for processing on failure. The sample controller https://github.com/kubernetes/sample-controller/blob/master/controller.go#L219-L223 shows we should requeue on failure.
Note this doesn't include the smart clone controller
Fixes #
```release-note
BugFix: Controllers now properly requeue objects on failures.
```
> Requeue on failure like sample k8s controller

- pkg/controller/util.go
Use the term that appears in YAML files, volumeMode, and print
which one it is (may be an implicit value picked from the default)
```release-note
Improve volumeMode mismatch error reports
```
> Provide a more verbose error.

- pkg/operator/resources/cluster/controller.go
- tests/basic_sanity_test.go
PR #1012 was a little too aggressive on the CRD permissions. This resulted in the following message in the controller logs:
```
1120 20:47:45.837940       1 reflector.go:134] pkg/client/informers/externalversions/factory.go:117: Failed to list *v1beta1.CustomResourceDefinition: customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:cdi:cdi-sa" cannot list resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
```
It didn't appear to actually affect the controller, but having it spam the log is annoying.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the …
> Fix RBAC for CRDS to stop error message in deployment/operator log.

- Makefile
- automation/test.sh
- hack/build/run-functional-tests.sh
- hack/build/run-unit-tests.sh
The unit and functional tests were called the same script in the end, and we had an if statement determining which one to call. There really is no reason for it, and now we can combine test-functional and test-functional-ci into the same call, and run that to functional tests.
It combines functional-test and functional-test-ci into one call, and splits unit-test into its own script. This will help with making the unit tests be called from bazel as well as give immediate output during functional test runs.
Fixes #
**Special notes for your …
> Split unit and functional test into own script,

- .travis.yml
- Makefile
- hack/build/bazel-build-builder.sh
This is the first step in using a prebuild builder images. This puts in the code to build and push the container image on merge. Then #997 can be modified the use the builder image.
Fixes #
```release-note
NONE
```
> Push builder image to dockerhub

- cluster-sync/okd-4.3/ceph_sc.yaml
- cluster-sync/okd-4.3/provider.sh
- cluster-sync/okd-4.3/rook_ceph.yaml
- cluster-up/cluster/okd-4.3/provider.sh
Add cluster-sync for okd 4.3 lane.
Fixes #
```release-note
NONE
```
> Added support for OKD-4.3 lane

- go.mod
- pkg/controller/config-controller.go
Ingress HTTP rule is optional field and can be nil. If we create a ingress with no http rule nil pointer exception is occur. Add nil check for ingress http rule.
Fixes #1048
NONE
```release-note
NONE
```
> Add nil check for ingress http rule

- hack/build/bazel-build-builder.sh
- hack/build/bazel-docker.sh
- hack/build/config.sh
- hack/build/in-docker.sh
Fixes #
```release-note
NONE
```
> Use an existing bazel-builder image instead of building it every time

- hack/build/bazel-build-builder.sh
When building and pushing a new bazel builder image we do not want to use the
sha hash of the current builder image.  We should strip this off to get the
image name and just use :latest.
Fixes #
```release-note
NONE
```
> Fix build and push of builder image

- pkg/util/util.go
In a normal Linux container, /sys/class/block/ is inherited from the host, and the result presented by lsblk is the metadata of the host, which does not effectively capture the size of the block device transmitted to the container
Signed-off-by: clarklee92 <clarklee1992@hotmail.com>
Fixes #1064
```release-note
NONE
```
> Fix `GetAvailableSpaceBlock` always return -1 in LXC

- doc/design.md
golden-pvc.yaml was removed in a refactor, so the document is out of date.  
This is a simple attempt at updating the document.
```release-note
NONE
```
> Update design doc

- cmd/cdi-controller/controller.go
- go.mod
- pkg/apis/core/v1alpha1/deepcopy_generated.go
- pkg/apis/core/v1alpha1/openapi_generated.go
- pkg/apis/core/v1alpha1/types.go
- pkg/controller/BUILD.bazel
- pkg/controller/clone-controller.go
- pkg/controller/clone-controller_test.go
- pkg/controller/config-controller.go
- pkg/controller/config-controller_test.go
- pkg/controller/import-controller.go
- pkg/controller/import-controller_test.go
- pkg/controller/upload-controller.go
- pkg/controller/util.go
- pkg/controller/util_test.go
If we create a temporary pod in the namespace which has resource quota, `must specify quota` error occurs. Fix to create temporary pod with default resource quota.
Fixes #1043
for now, I just added for the ImporterPod only. Could you please take a look? After the review, I will add for the CloneSourcePod and UploadPod.
```release-note
- Fix to apply default quota if namespace does not have a quota
```
> Fix to create temporary pod with default resource quota

- hack/build/bazel-build-builder.sh
- hack/build/bazel-docker.sh
- hack/build/config.sh
- hack/build/docker/builder/Dockerfile
- hack/build/in-docker.sh
update builder to k8s 1.16.4  and refactor image building to use tags for easier management
Fixes #
```release-note
NONE
```
> update builder to k8s 1.16.4 and use tags for builder image

- go.mod
- pkg/operator/resources/cluster/datavolume.go
Print phase and progress with kubectl get in addition to the name and age.
Fixes #1069 
```release-note
Data volumes now print additional columns Phase/Progress with kubectl get
```
> Print additional information with kubectl get dv

- automation/test.sh
- cluster-sync/install.sh
- cluster-sync/sync.sh
Force kill operator during upgrade to test resilience
Allow multiple previous release when upgrading, tests that they get upgraded in sequence specified.
Force delete operator pod during upgrade to test resilience.
Fixes #
```release-note
NONE
```
> Allow multiple previous versions to upgrade from

- automation/test.sh
The check was using -z instead of -n, so the condition was reverse of what it should be, this PR fixes it.
Fixes #
```release-note
NONE
```
> Reverse the check for multi upgrade.

- cluster-sync/ephemeral_provider.sh
- cluster-sync/k8s-1.16.2/provider.sh
- cluster-sync/nfs/nfs-sc.yaml
- cluster-sync/nfs/nfs-server.yaml
- cluster-sync/nfs/nfs-service.yaml
- cluster-sync/sync.sh
- go.mod
- tests/framework/BUILD.bazel
- tests/framework/framework.go
- tests/framework/nfs-utils.go
- tests/utils/common.go
Adds NFS storage to the CI test matrix.
Fixes #
```release-note
NONE
```
> Add NFS as KUBEVIRT_STORAGE to cluster-sync

- pkg/controller/util.go
- pkg/operator/resources/cluster/controller.go
- pkg/operator/resources/namespaced/controller.go
- tests/basic_sanity_test.go
Currently CDI has permission to get secrets in any namespace.  This is obviously a security concern.  It is also not necessary.
Fixes #
Related issue in Kubevirt
https://github.com/kubevirt/kubevirt/issues/2967
```release-note
NONE
```
> remove permission to get secrets at cluster scope

- doc/basic_pv_pvc_dv.md
- doc/exposing-upload-proxy.md
Fix examples that reference extension/v1beta1 API as its deprecated.
Fixes #1100 
```release-note
NONE
```
> Remove references to extensions/v1beta1 in examples

- pkg/image/qemu.go
When converting images the qemu-img command uses a writeback cache mode
by default.  This means that writes to a block device go through the
host page cache and are lazily flushed to the storage device.  When
using this cache mode, the process can exit before all writes have
reached storage and our DataVolume could appear ready to use before all
I/O has completed.  This becomes a problem with shared storage because a
second host does not have the benefit of the first host's page cache
when reading.  To prevent this problem we must perform I/O directly to
the storage device.  This behavior is selected by passing "-t" "none" to
qemu-img.
This problem will not arise with "create", "info", or "resize" qemu-img
commands because those are metadata operations.
The following document provides …
> Disable caching when converting qcow2 images

- doc/upload.md
- pkg/common/common.go
- pkg/controller/upload-controller.go
- pkg/controller/util.go
- pkg/controller/util_test.go
- pkg/importer/data-processor.go
- pkg/importer/data-processor_test.go
- pkg/importer/upload-datasource.go
- pkg/importer/upload-datasource_test.go
- pkg/uploadproxy/BUILD.bazel
- pkg/uploadproxy/uploadproxy.go
- pkg/uploadproxy/uploadproxy_test.go
- pkg/uploadserver/BUILD.bazel
- pkg/uploadserver/uploadserver.go
- pkg/uploadserver/uploadserver_test.go
after transfer completes and then continues background processing.
This PR adds an async endpoint to the upload server and proxy. When an upload is called using this endpoint the connection is closed immediately as soon as the data has been received. But the uploadserver will continue to process until the entire process is complete.
This is backwards compatible with virtctl that doesn't handle this.
Fixes #
```release-note
CDI now has asynchronous upload endpoint.
```
> Add async endpoint for upload that closes connection immediately

- pkg/operator/controller/callbacks.go
- pkg/operator/controller/controller.go
- pkg/operator/controller/controller_test.go
- tests/operator_test.go
The operator was no longer cleaning up orphaned import/upload/clone pods when CDI is deleted.  This is because #1091 switched controller runtime client config.
Fixes #1106 
Functional test here is pretty risky.  actually uninstalls/reinstalls CDI.
```release-note
NONE
```
> operator needs to use uncached client in certain places

- pkg/common/common.go
- pkg/controller/import-controller.go
- pkg/controller/util.go
- pkg/controller/util_test.go
- tests/datavolume_test.go
but NOT cdi.kubevirt.io as those are what triggers import/upload/clone.
In general we do not want to copy over annotations from the original PVC to the scratch space PVC. For instance if provisioners use annotations do to special things to a PVC. However in certain situations we would like to copy them if the annotations are part of kubevirt.io. This PR copies kubevirt.io annotations from the PVC to the scratch space PVC, but not cdi.kubevirt.io because those are the annotations that trigger import/upload/clone and thus would cause the scratch space to be imported/uploaded/cloned to.
We want to copy the kubevirt.io/provisionOn annotation for the host path provisioner, so we can guarantee that the …
> Copy kubevirt.io annotations to scratch space pvc

- go.mod
- tests/cloner_test.go
- tests/datavolume_test.go
- tests/import_test.go
- tests/utils.go
- tests/utils/datavolume.go
- tests/utils/pvc.go
CI has been failed a lot on pods that are getting ready but just take longer than the timeout. This PR increases the timeout to hopefully cut down on failures due to the CI being slow.
Fixes #
```release-note
NONE
```
> Increase test timeouts to account for slower CI

- pkg/controller/import-controller_test.go
Unit tests would sometimes fail with
```
•! Panic [0.000 seconds]
Create Importer Pod
/go/src/kubevirt.io/containerized-data-importer/pkg/controller/import-controller_test.go:311
should
/go/src/kubevirt.io/containerized-data-importer/vendor/github.com/onsi/ginkgo/extensions/table/table.go:92
should create pod with block volume mode and scratchspace [It]
/go/src/kubevirt.io/containerized-data-importer/vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:46
Test Panicked
failed to add object &{{ } {config      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[app:containerized-data-importer cdi.kubevirt.io:] map[] [] []  []} {<nil> <nil> nil} {<nil> test-sc nil}} to fake client: no kind is …
```
> Added missing cdiv1 scheme in import controller unit test.

- manifests/templates/release/cdi-cr.yaml.in
- tests/operator_test.go
When CDI is installed by HCO, skip CDI CR delete tests
Fixes #
```release-note
NONE
```
> skip CDI CR delete tests when expected name does not exist

- doc/scratch-space.md
- pkg/controller/util.go
- match comments on scratch space storage class with
the source code
Signed-off-by: anencore94 <anencore94@kaist.ac.kr>
After this [commit](https://github.com/kubevirt/containerized-data-importer/commit/889f231300d8d4a0feb1dea9d64ca837c8cf150a), the field `scratchSpaceStorageClass` in `CDI config` checks the `default storage class` in config-controller's reconcile loop.
Thus the function `GetScratchPvcStorageClass` in `pkg/controller/util.go` no longer checks default storageclass, just uses the value in `scratchspacestorageclass`.
However, the comments says the old logic. Thus, update those to match with the source code.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the …
> Update comments on scratch space

- tests/cdiconfig_test.go
If we have a storage class without annotations, then running the cdi config tests will generate a nil pointer error because I forget to check for a nil. This PR fixes that.
Fixes #
```release-note
NONE
```
> Make sure the storage class annotations are not nil.

- pkg/image/qemu.go
- pkg/image/qemu_test.go
- pkg/importer/data-processor.go
- pkg/util/util.go
- pkg/util/util_test.go
- tests/cloner_test.go
- tests/framework/pvc.go
- tests/import_test.go
- tests/transport_test.go
- tests/upload_test.go
(Leaving in some of the checks introduced in that change)
Having sparse disks works better with external storage being
monitored for low capacity. If we allocate the full size at
start, it shows up as a disk capacity alert immediately.
Another motivation to pre-allocate was that cloning would
sometimes fail for capacity reasons.
We now validate available size before cloning, so we don't
expect that problem to return.
```release-note
Images are again allocated sparsely.
This means that at first, the actual disk usage will be less than the full size of the image.
```
> Restore sparse images as the default (revert #970)

- pkg/operator/controller/controller.go
Avoid failing reconciliation on new CR
If the user explicitly delete CDI cr,
HCO will quickly try to create a new one.
If HCO is quick enough, CDI operator can
enter the reconciliation loop when an older
cdi-config config-map is still there although
marked for deletion.
In that case CDI operator was not going to create
a new config-map but was then marking the new CDI CR
in error phase just because it's still not controlled
by the config map pending for deletion.
On the next run, CDI operator was not going to create a
new config map just because the new CR is already marked
with phase=Errror.
Skip the controlled-by check on config maps marked for
deletion to avoid this bad loop.
```release-note
Fixes: https://bugzilla.redhat.com/1809872
```
> Avoid failing reconciliation on new CR

- pkg/uploadproxy/uploadproxy.go
The timeout value used by the uploadproxy client sets an upper limit on
the amount of time an upload can take.  After this limit is reached the
proxy will close the connection with the uploadserver resulting in a
failed upload.  We do want a reasonable timeout to prevent zombie upload
connections from persisting forever but we don't want to prevent
legitimate operations.  Increase the timeout value to 24 hours which
should be enough even for reasonably large images over relatively slow
connections.  Uploads that take longer than one day should probably be
done with an import process anyway.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will …
> Use long timeout for uploadproxy client

- tools/cdi-func-test-file-host-init/nginx.conf
Enable ipv6 for the cdi file hosts in case of an ipv6 only cluster for testing. The registry file host is already ipv6 enabled from what I could tell.
Fixes #
```release-note
NONE
```
> Enable IPv6 on cdi http file host.

- pkg/operator/resources/operator/operator.go
Fixes #
Mostly removed permission but needed to add permission to delete some stuff, like CRDs, apiserver, and webhook configurations
```release-note
NONE
```
> operator permissions still not right

- cmd/cdi-importer/importer.go
- doc/datavolumes.md
Make sure you can only do kubevirt content type for image IO
Add documentation for image IO sources.
Make sure kubevirt content type is used with image IO sources in importer.
Fixes #
```release-note
NONE
```
> Add oVirt imageIO documentation

- tests/datavolume_test.go
To test for the hostpath provisioner not accidentally getting the target and scratch space on different nodes, we repeat one test 10 times in quick succession to verify it works. However in the case of NFS this would give the recycler fits and it would not be able to clean up fast enough, and eventually we will run out of PVs to bind. This PR makes it so it only does the repeating if we are running hostpath provisioner lane.
Fixes #
```release-note
NONE
```
> Only have hostpath provisioner repeat test with scratch space.

- Makefile
- cluster-sync/sync.sh
The timeout to wait for cdi to be available is hard coded, the os-3.11-crio lane seems to take a lot longer in certain cases. This PR allows us to read the timeout from an environment variable which we can then set in the lane configuration.
Fixes #
```release-note
NONE
```
> Read timeout from environment variable instead of hard coding it.

- BUILD.bazel
- WORKSPACE
- cluster-sync/ember/ember-csi-lvm.yaml
- cluster-sync/ember/loop_back.yaml
- cluster-sync/ember/snapshot-class.yaml
- cluster-sync/ephemeral_provider.sh
- cluster-sync/k8s-1.16.2/provider.sh
- cluster-sync/k8s-1.17.0/provider.sh
- hack/build/run-tests.sh
- tests/import_test.go
- tools/loop-back-lvm/BUILD.bazel
- tools/loop-back-lvm/create_lvm.sh
- tools/loop-back-lvm/entrypoint.sh
Add ember csi as a storage provider for make cluster-sync, this involves:
- Adding a loopback device container that creates a new loopback device. The path and size are parameters that can be changed.
- Adding a new item to the list of storage providers, ember_lvm. It can be enabled by setting the KUBEVIRT_STORAGE environment variable to ember_lvm
- A script to identify the host the loopback container is running on and running some pvcreate and vgcreate commands to create the needed lvm objects.
- Yaml to create a new ember-csi-lvm namespace and creating the ember csi objects in that namespace.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` …
> Add ember csi lane

- api/openapi-spec/swagger.json
- pkg/apis/core/v1alpha1/openapi_generated.go
- pkg/apis/core/v1alpha1/types.go
- pkg/controller/clone-controller.go
- pkg/controller/clone-controller_test.go
- pkg/controller/datavolume-controller.go
- pkg/controller/datavolume-controller_test.go
- pkg/controller/import-controller.go
- pkg/controller/import-controller_test.go
- pkg/controller/upload-controller.go
- pkg/controller/upload-controller_test.go
- pkg/controller/util.go
- pkg/operator/resources/cluster/datavolume.go
- tests/datavolume_test.go
- tests/utils/datavolume.go
Add a field to DataVolume to track the number of retries. 
Some background: A DataVolume will create a PVC with a specific annotation, that will trigger a CDI controller to create a pod (import/clone/upload) that will populate the PVC with a disk image. Things can potentially go wrong during the import (or upload/clone, I will talk only import from now on) causing the pod to fail and restart. Kubernetes when you get a pod will list the number or restarts:
```
$ k get pods
```
```
NAME                             READY   STATUS   RESTARTS   AGE
local-volume-provisioner-tgktc   1/1     Running  0          116m
local-volume-provisioner-w6dkt   1/1     Running  0          115m
```
This change adds …
> Add a field to DataVolume to track the number of retries/pod restarts

- cluster-sync/sync.sh
- go.mod
Change the way we wait for CDI to be ready for OS-3.11.0-crio provider. Apparently there is a [bug]( https://github.com/openshift/origin/issues/22384) in wait for openshift that causes issues. So instead of using 'wait for' just loop and check if the field is true or not. This should decrease the CI failures on the OS lane.
Fixes #
```release-note
NONE
```
> Change how we wait for CDI to be ready for OS-3.11.0-crio provider.

- automation/test.sh
- cluster-sync/sync.sh
We are having frequent CI failures on the upgrade lane because we don't wait long enough for the upgrade to complete. Also made it an environment variable so we can change it from a lane perspective. Added more versions to upgrade to.
Fixes #
```release-note
NONE
```
> Increase time we wait for operator upgrade to complete.

- pkg/image/qemu.go
- pkg/image/qemu_test.go
When a user imports into a PVC that is not large enough we print an
error stating that "shrink not supported".  When this situation happens
it is far more likely that the user simply used a PVC that is too small
to hold the image.  Let's make it easier for them to debug by suggesting
this.  The verbage about shrinking is simply confusing.
Fixes #
```release-note
NONE
```
> ux: Clarify message when PVC is too small

- cluster-sync/sync.sh
The newly added code to check for OS-3.11-crio provider had a bug where it would always follow that path. It doesn't actually cause issues, but it is not what we expected to happen.
Fixes #
```release-note
NONE
```
> Fix os-3.11.0-crio comparison so it follow the right path on other provider.

- tests/cloner_test.go
Sometimes the label would be put on the NFS bound PV, and that would cause the pod to not be schedulable because no PVs with the right label could be bound because the PV was already bound. This fixes that by excluding bound PVs from the labelling process.
Fixes #
```release-note
NONE
```
> Fix should clone across multiple nodes on NFS lane.

- pkg/importer/http-datasource.go
- pkg/importer/http-datasource_test.go
Some servers reject such requests, and if Content-Length is available,
it's going to be sent in GET requests as well.
Some servers reject HEAD requests but allow GET, this causes 403 Failed errors.
Example: https://download.cirros-cloud.net/0.4.0/cirros-0.4.0-x86_64-disk.img fails (this is also listed as one of our examples).
This is one step towards a solution but doesn't actually solve the problem.
It's not complete because later we invoke qemu-img on the same URL and it suffers from the same limitation.
A complete solution will probably involve saving the file to disk and passing the saved file to qemu-img, but I don't want to block others until I finish writing that.
```release-note
NONE
```
> Eliminate the need for HEAD requests in the Go HTTP download client.

- pkg/common/common.go
- pkg/operator/controller/controller_test.go
- pkg/operator/resources/namespaced/controller.go
- pkg/operator/resources/utils/common.go
- tests/operator_test.go
Have the operator create a prometheus service that matches the correct label.
Fixes #
```release-note
Enhancement: Operator now creates prometheus service in cdi namespace
```
> Create prometheus service in cdi namespace.

- hack/build/docker/builder/Dockerfile
klog/v2 repo is no longer available due to klog releasing v2 a few days ago. Anything referencing v2 is breaking. This is a hack to symlink v2 to klog as they are now the same.
Fixes #
```release-note
NONE
```
> Fix builder build image.

- pkg/importer/registry-datasource.go
- pkg/importer/registry-datasource_test.go
The kubevirt containerDisk container format expects only a single file to exist
in the disk directory of the container.  Rather than assuming that this is the
case we should check explicitly and fail rather than guessing which file to
use.
Fixes #
```release-note
NONE
```
> Fail to import a containerDisk containing more than one file

- go.mod
- tests/operator_test.go
Sometimes if the quota tests would run right after the CDI operator delete tests, the CDI Config object would not exist yet, and the test would fail. This PR modified the test to be tolerant of the CDI config object not existing yet, and waiting for it to become available.
Fixes #
```release-note
NONE
```
> Wait for CDI config to be available if not found during functional tests

- manifests/example/import-kubevirt-block-datavolume.yaml
Signed-off-by: isueyoon <sueyoon@protonmail.com>
It's a very tiny fix to an example yaml file, import-kubevirt-block-datavolume.yaml. Moved storageClassName key, value under the pvc.
I copy and pasted this example to create a data volume, and noticed why it didn't work.
Fixes #
It's a same request as #1173 which I closed few days ago by mistake. 
```release-note
NONE
```
> Minor fix to a manifest example, import-kubevirt-block-datavolume

- tests/cloner_test.go
- tests/datavolume_test.go
- tests/framework/exec_util.go
- tests/import_test.go
- tests/upload_test.go
- tests/utils/pod.go
New functional tests for new RESTARTS column in DataVolume (done in PR
https://github.com/kubevirt/containerized-data-importer/pull/1155). 
Fixes #
```release-note
NONE
```
> Add DV restarts test for upload controller

- pkg/controller/datavolume-controller.go
- tests/import_test.go
Fixed test to check for error on phase detection.
Fix a bug where DataVolume phase was not being updated for a block blank disk. A block blank disk is a no-op for CDI, however we need to still to update the DataVolume phase to be successful. There was a race condition in the code that caused it to not update the DataVolume if the PVC was bound already.
Fixes #
```release-note
BugFix: Fixed race condition in blank block disks.
```
> Fixed race for block blank disks 

- pkg/controller/datavolume-controller.go
- pkg/importer/imageio-datasource.go
No progress is being reported because the total is 0, if the total is 0 try the content-length header to find the total.
Fixes #1190
```release-note
BugFix: imageio import was not reporting progress.
```
> For imageio data source, try content-length header if total 0

- tests/cloner_test.go
- tests/framework/pod.go
Shouldn't be checking fsgroup on a block device.  Also delete pod function was always timing out for alternate namespaces
Fixes #
```release-note
NONE
```
> fix broken clone test

- tests/framework/pvc.go
Change the gid check in functional tests to use ln -ln instead of stat, as stat might not be available in the container that we use for the verifier pod.
Fixes #
```release-note
NONE
```
> Change gid check to use ls instead of stat

- cmd/cdi-controller/controller.go
Stop smart clone controller being registered twice and causing error messages about duplicate metrics.
If smart clone controller is registered, it would get registered twice and cause duplicate metrics errors in the log from prometheus. This PR fixes that.
Fixes #
```release-note
BugFix: Duplicate metrics message in controller log when smart clone is available
```
> Stop smart clone controller being registered twice

- cluster-sync/ephemeral_provider.sh
Increase timeout waiting for ceph to be ready, also print ceph namespace pods every 30 seconds
The ceph lane fails to start due to ceph not being ready in the allotted time, however it due to ci being busy, so just waiting longer should allow the test to run.
Also print the ceph namespace pod every 30 seconds so we can look at the progress on failures.
Fixes #
```release-note
NONE
```
> Increase timeout waiting for ceph to be ready

- pkg/operator/controller/controller.go
- pkg/operator/controller/controller_test.go
- pkg/operator/controller/cr.go
**What this PR does / why we need it**
Make sure that the `Status.ObservedVersion` field  on upgrade, even if it was not set in the previous version.
when PR gets merged)*:
Fixes #1212 
**Special notes for your reviewer**
Previous version `OPERATOR_VERSION` environment variable was not set by HCO. That was fixed in https://github.com/kubevirt/hyperconverged-cluster-operator/pull/588
```release-note
Make sure that the `Status.ObservedVersion` field  on upgrade, even if it was not set in the previous version.
```
Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>
> [Upgrade Operator] Make sure that ObservedVersion is updated

- tests/datavolume_test.go
- tests/utils/datavolume.go
Add a new functional test for https endpoint with qcow2 to ensure we test scratch space pod recreation logic.
Fixes #
```release-note
NONE
```
> Add https qcow2 endpoint test to exercise the scratch space logic

- go.mod
- hack/build/bazel-docker.sh
- hack/build/build-manifests.sh
- hack/build/config.sh
- hack/build/docker/builder/entrypoint.sh
- hack/build/in-docker.sh
Enable the use of podman to start the kubevirtci cluster, and make cluster-sync
Currently kubevirtci uses docker everywhere, and gocli is also tied to docker. For newer fedora (31+) docker no longer works out of the box (it doesn't support cgroupsv2 yet) and we don't know when docker will work. In order for our developers to use a newer fedora we have to support podman which does support cgroupsv2.
Luckily for us, some work has already happened to get a drop in replacement for gocli called [pack8s](https://github.com/kubevirt/kubevirtci/tree/master/pack8s) that can be enabled by setting the KUBEVIRTCI_RUNTIME to podman
```bash
$ export KUBEVIRTCI_RUNTIME=podman
```
This PR enables the rest of our tool …
> Enable the use of podman

- tests/cloner_test.go
due to it attempting to get gid but this test uses local volumes and thus shouldn't test for matching gids.
The functional tests tries to get the GID of the disk.img, but those aren't supported on local volumes. So added code to skip that.
Fixes #
```release-note
NONE
```
> Fix cloner across tests failing on ceph lane

- hack/build/config.sh
- hack/build/docker/builder/Dockerfile
The 0.0.3 builder doesn't have diff installed, so we can't use it. This PR fixes that.
Fixes #
```release-note
NONE
```
> Added missing diff to builder image

- go.mod
- hack/build/config.sh
Finish updating builder image to latest so podman will work while syncing.
Fixes #
```release-note
NONE
```
> Update builder image to allow podman to work.

- tests/utils.go
The cdi config test checks the version of kubernetes, in newer versions the version can now have +<hash> in the version string. The existing regex failed to match, this PR fixes the regex.
Fixes #
```release-note
NONE
```
> Update regex that matches version to accept +hash in version string

- pkg/apiserver/apiserver.go
- pkg/apiserver/apiserver_test.go
- pkg/uploadproxy/uploadproxy.go
- pkg/uploadproxy/uploadproxy_test.go
The proxy will reject upload requests.
Put error in body returned by proxy.
We were not allowing tokens to be created until the PVC existed, however the error message was getting mangled by the k8s api server. So instead allow the token and rely on the proxy server to reject the upload request because the PVC doesn't exist. Also return the message in the body of the 
Fixes #
```release-note
BugFix: Upload tokens are now allowed for PVCs that do not exist. The upload will fail regardless …
```
> Allow tokens for PVCs that do not exist.

- cmd/cdi-cloner/clone-source.go
cdi-cloner support filesystem-clone/blockdevice-clone content types, but they don't appear on the flags
```release-note
NONE
```
> Add missing content types to clone source flag

- pkg/apiserver/apiserver.go
- pkg/apiserver/apiserver_test.go
- pkg/uploadproxy/uploadproxy.go
- pkg/uploadproxy/uploadproxy_test.go
* Allow tokens for PVCs that do not exist, the proxy will reject upload requests.
Put error in body returned by proxy.
* Addressed comments on PR.
backport of #1233 
Fixes #
```release-note
NONE
```
> Allow tokens for PVCs that do not exist. (#1233)

- tests/utils/common.go
- tests/utils/datavolume.go
- tests/utils/pvc.go
as it causes a race with the kubernetes scheduler. (#1157)
Backport of #1157 to fix testing.
Fixes #
```release-note
NONE
```
> [release-v1.13] Don't annotate pvc/dvs with provisionOnNode

- tests/utils/common.go
Bad cherry-pick, the conflict was resolved wrong and fmt should have been removed.
Last merge the cherrypick broke compiling the tests. This fixes it.
Fixes #
```release-note
NONE
```
> Fix tests compile.

- pkg/apis/core/v1alpha1/types.go
Adds a new phase: WaitForFirstConsumer to the Datavolume API. This phase means that the underlying storage binding mode is WaitForFirstConsumer so the PVC will not be bound until first consumer pod is created. Any CDI action will be paused until the PVC is bound by the consumer pod. 
Fixes #
This is prerequisite for https://github.com/kubevirt/containerized-data-importer/pull/1242
```release-note
A new DataVolumePhase was added: WaitForFirstConsumer. This phase means that the underlying …
```
> Add new dv phase WaitForFirstConsumer

- tests/cloner_test.go
The populator and verifier pods where still there, which caused multi attach issues in the ceph lane. This PR makes sure the populator and verifier pod are deleted before cloning.
Fixes #
```release-note
NONE
```
> Block clone across namespace, delete populator/verifier pod

- tests/framework/exec_util.go
- tests/framework/pvc.go
It was hard to determine why verifier pods failed because they weren't printing stderr. This fixes that and should now print stderr on failure. This should allow us to debug the failures of the verifier pods more easily with more information.
Fixes #
```release-note
NONE
```
> Return stderr from verifier pods

- tests/cloner_test.go
- tests/framework/pvc.go
- tests/import_test.go
- tests/upload_test.go
**What this PR does / why we need it**:  Address flakes like this:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1260/pull-containerized-data-importer-e2e-k8s-1.17-ceph/1275904563907399680
Fixes #
```release-note
NONE
```
> [flaky test] verifier pods hanging around keeps cloning from working

- pkg/controller/datavolume-controller.go
- pkg/controller/datavolume-controller_test.go
Hopefully help address upload flakiness.  Let's wait until pods are ready, not just running.
Fixes #
```release-note
NONE
```
> [flaky test] datavolume should not say upload is ready until pod is running

- cmd/cdi-cloner/cloner_startup.sh
lsblk does not work with raw block devices that are backed by
dm-multipath because the container does not populate the /dev/mapper
symlinks
blockdev comes from util-linux as well and already exists in the
cdi-cloner image so it should be a drop-in replacement
```release-note
Use blockdev instead of lsblk for getting raw block device size
```
> Use blockdev instead of lsblk for getting block device size

- pkg/controller/import-controller.go
- pkg/controller/import-controller_test.go
We print some of the annotations when updating a PVC when something changes. This PR prints all the annotations. It also fixes a race condition where if the cluster is slow the scratch space exit code might cause the importer pod to report success instead of starting a new pod with scratch space.
Fixes #1241
```release-note
BugFix: Scratchspace detection could cause an import to be marked succeeded while the actual import never happened.
```
> Don't mark DV succeeded during scratch space pod delete/create

- pkg/controller/BUILD.bazel
- pkg/controller/clone-controller.go
- pkg/controller/clone-controller_test.go
- pkg/controller/datavolume-controller.go
- pkg/controller/datavolume-controller_test.go
- pkg/controller/upload-controller.go
- pkg/controller/upload-controller_test.go
- pkg/controller/util.go
- pkg/controller/util_test.go
- tests/cloner_test.go
- tests/framework/pvc.go
- tests/smartclone_test.go
There is no way to 100% safely guard against data corruption when cloning in k8s.  But this improves our situation a bit by at least verifying that source PVCs are not being used in an unsafe way before the clone operation is started.  For smart clone (using snapshots) that means that the PVC cannot be mounted in any Pod.  Things are less strict with dumb cloning (copying over the network).  In that case, read only mounts are okay.
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=1845901
```release-note
Wait for PVCs to be unused before …
```
> Wait for PVCs to be unused before initiating clone operations

- tests/framework/pvc.go
instead of creating another one. They will get deleted at the end of the test by the framework.
This PR fixes breaking the ember_lvm lane because multiple pods want to the use the same RWO pod. #1231 changed the behavior and now the verifier pods live longer. So we should re-use them otherwise tests will fail. Together with #1255 this PR should fix the ember_lvm lane.
Fixes #
```release-note
NONE
```
> Have transport tests re-use the verifier pod

- tests/datavolume_test.go
- tests/framework/pvc.go
- tests/utils/pvc.go
This PR provides an automated test for deleting a PVC during import. CDI then recreates a PVC and restarts the import.
Fixes #
```release-note
NONE
```
> PVC deleted during import - tier1 test

- pkg/common/common.go
- pkg/uploadproxy/uploadproxy.go
- pkg/uploadproxy/uploadproxy_test.go
- pkg/uploadserver/uploadserver.go
- pkg/uploadserver/uploadserver_test.go
- tests/upload_test.go
The existing binary upload format does not work well for a browser.
Added `v1alpha1/upload-form` and `v1alpha1/upload-form-async` to support form data uploads
Fixes #
```release-note
New UploadProxy endpoints for form based uploads "v1alpha1/upload-form" and "vialpha1/upload-form-async"
```
> Support form based uploads 

- pkg/apiserver/apiserver.go
- pkg/apiserver/auth-config.go
- pkg/apiserver/auth-config_test.go
`kube-apiserver` was not able to communicate with `cdi-apiserver` on Azure.  Was determined that the root cause was the lack of any value for `requestheader-allowed-names` in `extension-apiserver-authentication` configmap.  Although probably not ideal, that is a valid configuration per this:  https://kubernetes.io/docs/tasks/extend-kubernetes/configure-aggregation-layer/#kubernetes-apiserver-client-authentication
Fixes #1295 
```release-note
NONE
```
> Fix CDI apiserver authentication on AKS

- tests/cloner_test.go
- tests/upload_test.go
This function has no side effects and we ignore the return value.
While here, use the same function instead of hard-coding the name.
Might be a bit cleaner.
```release-note
NONE
```
> Non-functional change cleanup: remove unused calls to UploadPodName

- pkg/importer/data-processor.go
- pkg/importer/upload-datasource.go
- pkg/importer/upload-datasource_test.go
- pkg/uploadserver/uploadserver.go
- tests/upload_test.go
- tests/utils/upload.go
This is to give immediate feedback to the user when uploading.
Virtctl now supports asynchronous uploads, after the data has been transferred the connection is closed and post processing happens (convert/resize/etc) which may take a while. As part of that post processing we do a size validation. If the virtual disk image is > PVC size, the upload is considered failed. But with the async upload the connection is already closed and unless the user looks at the DataVolume, they will have a hard time understanding what happened.
This PR returns an 400 (BadRequest) and a message in the body based on the validation BEFORE we close the connection, so we can give more immediate feedback to the user. Currently …
> Run size validation before returning success on upload.

- hack/build/docker/builder/Dockerfile
This PR updates builder image with packages required to build images API. Images API is needed to replace/optimize skopeo.
Fixes #
```release-note
NONE
```
> build: Add btrfs-progs-devel and device-mapper-devel to builder image

- hack/build/config.sh
- hack/build/docker/builder/Dockerfile
- hack/build/run-functional-tests.sh
- tests/alpha_test.go
- tests/api_validation_test.go
- tests/badserver_test.go
- tests/basic_sanity_test.go
- tests/cdiconfig_test.go
- tests/certrotation_test.go
- tests/cloner_test.go
- tests/datavolume_test.go
- tests/framework/BUILD.bazel
- tests/framework/framework.go
- tests/import_test.go
- tests/leaderelection_test.go
- tests/local_volume_test.go
- tests/operator_test.go
- tests/rbac_test.go
- tests/smartclone_test.go
- tests/tests_suite_test.go
- tests/transport_test.go
- tests/upload_test.go
- tests/webhook_test.go
Fix functional test framework to work with go >= 1.13. We were not
using the ginkgo ordering correctly, and our framework would call
flag.Parse() too soon, and mess with the go testing flag parsing.
As a result we had to alter some of the variables that we use to build
urls to be functions so that when called the required information is
available.
Fixed several tests not checking for errors.
Fixed dumping code being initialized several times messing with the
order in which failures were reported.
Fixes # …
> Update cdi-builder to use go version 1.14.6 (current latest)

- pkg/controller/datavolume-controller.go
- pkg/controller/datavolume-controller_test.go
Remove last remaining location where we could set a DV to failed during normal operations. We can still get in failed state due to the PVC claim being lost, but that is the only possibility at this point.
Fixes #
```release-note
NONE
```
> Remove potential failed state from DV

- pkg/operator/controller/BUILD.bazel
- pkg/operator/controller/controller.go
- pkg/operator/controller/util.go
- pkg/operator/controller/util_test.go
- pkg/operator/resources/cluster/apiserver.go
- pkg/operator/resources/namespaced/apiserver.go
- pkg/operator/resources/namespaced/controller.go
- pkg/operator/resources/namespaced/uploadproxy.go
- pkg/operator/resources/utils/common.go
This stops the operator controller from trying to modify the CRDs in each reconcile loop.
The operator tries to update the CRDs in each reconcile loop because the desired object status is empty and k8s will have populated some status. Then the operator removes the status because it expects there to be none, which in turn will cause k8s to set the status again. On each reconcile loop this ping pong happened. This PR changes the code to strip the status value from the current object so the comparison will cause not fail due to a minor status change.
Also added default values for deployments that would be filled in by k8s as well as defaults for the webhooks
**Which issue(s) this PR fixes** *(optional, …
> Strip status from objects in operator reconcile loop

- hack/build/build-functest.sh
- hack/build/build-manifests.sh
- hack/build/run-unit-tests.sh
- hack/update-codegen.sh
- pkg/apiserver/webhooks/BUILD.bazel
- pkg/apiserver/webhooks/cdi-validate.go
- pkg/apiserver/webhooks/datavolume-mutate.go
- pkg/apiserver/webhooks/handler.go
- pkg/apiserver/webhooks/scheme.go
- pkg/operator/resources/cluster/BUILD.bazel
- pkg/operator/resources/cluster/apiserver.go
- tests/BUILD.bazel
- tests/alpha_test.go
- tests/basic_sanity_test.go
- tests/framework/framework.go
- tests/manifests/dvAlphaMissingAccessModes.yaml
- tests/operator_test.go
- tests/transport_test.go
- vendor/github.com/onsi/ginkgo/reporters/junit_reporter.go
Shamefully forgot to include webhooks in #1232 
Fixes #
now that alpha go packages added back, using them in functional test.
```release-note
Enable webhooks for v1alpha1 resources
```
> enable webhooks for alpha resources

- hack/build/config.sh
- hack/build/docker/builder/Dockerfile
Add controller-gen binary to builder image so we can use it.
Fixes #
```release-note
NONE
```
> Update builder to v0.0.6 and include controller-gen install

- hack/build/bazel-build-builder.sh
Just hard code instead of trying to determine from previous image.
The way we determine the builder image base would fail if we didn't specify the sha256 in the original. And it would fail if we used anything but kubevirt/kubevirt-cdi-bazel-buider. So just hard code instead of doing matching.
Fixes #
```release-note
NONE
```
> Fix how we determine base builder image.

- hack/update-codegen.sh
- hack/verify-codegen.sh
- pkg/operator/resources/cluster/datavolume.go
- tools/schema-exporter/schema-exporter.go
Over time the schema generated from types.go and the schema encoded in golang started to diverge. Most of the time this meant that types.go was ahead of the schema encoded in golang code. This PR generates yaml from both types.go and the golang code, and compares them with yq to ensure that both remain in sync. This will ensure that if new fields are added or fields are remove, or fields are modified both need to get changed or the build will fail.
Fixes #
```release-note
NONE
```
> verify schema is synchronized using travis.

- pkg/importer/http-datasource.go
- pkg/importer/http-datasource_test.go
- tests/badserver_test.go
- tools/cdi-func-test-bad-webserver/main.go
Some servers don't support range requests, and we have existing fallback for when qemu-img doesn't work, to fetch the file to scratch space and pass the pathname to qemu-img rather than URL. Let's use it.
Fixes #1073
Wrote some tests. Could've probably combined some unit tests in a table, but I'd have to pass a function for every table entry, which seems a bit convoluted.
```release-note
Support importing from web servers that don't support range requests (used to fail with non-raw images)
```
> Make it possible to import images needing conversion from servers that don't support range requests

- tools.go
so that make deps-update will not ignore it and properly vendor in k8s.io/code-generator.
By using the +build tag will cause the build to not include this code
during a build unless the codegen tag is used.
// +build ignore is special apparently
https://github.com/golang/go/issues/29598
Fix make deps-update to properly vendor in code-generator.
Fixes #
```release-note
NONE
```
> Change +build ignore tag in tools.go to +build codegen

- cluster-sync/sync.sh
- pkg/operator/controller/callbacks.go
- pkg/operator/controller/cruft.go
Explaining CRDs was broken when upgrading.  So, I diff'd a upgraded crd and a newly created crd.  The only meaningful difference was `spec. preserveUnknownFields`.  It was true for the upgraded resources.  Setting it to false (the default with CRD v1) fixed the issue.
Fixes #
Unfortunately, this could only be fixed in a callback function.  This is because `preserveUnknownFields` is a bool with `omitempty` json tag.  Therefore, it doesn't get considered in our json merge algorithm.  Really wish it was a …
> fix crd explain

- hack/build/config.sh
- hack/build/docker/builder/Dockerfile
Adds nbdkit-devel to builder image for vddk-datasource. Also fix some tabbing issues with the Dockerfile
Fixes #
```release-note
NONE
```
> Add nbdkit-devel to builder image

- tests/cloner_test.go
- tests/import_test.go
instead of status value. This was causing random CI failures.
#1353 modified the logic that restores quota. However I missed that for import and clone I was saving from the status instead of the spec, causing random CI failures if the order of the tests was just right. This PR fixes that by saving the right original value.
Fixes #1354, #1358 
```release-note
NONE
```
> Fix quota restore function by storing correct original value

- pkg/apis/core/v1beta1/types.go
- pkg/apis/core/v1beta1/types_swagger_generated.go
- pkg/apis/core/v1beta1/zz_generated.deepcopy.go
- pkg/controller/clone-controller.go
- pkg/controller/import-controller.go
- pkg/controller/import-controller_test.go
- pkg/controller/upload-controller.go
- pkg/operator/resources/utils/common.go
- tests/utils.go
But omitting +listType=set because it introduces errors.
Kubevirt wanted to make a small change.
We haven't made a release yet, so it's probably OK to make this change.
[HCO change](https://github.com/kubevirt/hyperconverged-cluster-operator/commit/8dd4177f1eeb906ad6e9e67b400ce5f5e5388aad)
[WIP kubevirt change](https://github.com/kubevirt/kubevirt/pull/4092/files#diff-4e3a0eed2e1047fddf0f53e6778e4daaR31)
```release-note
NONE
```
> Sync with HCO definition of node placement values.

- go.mod
- go.sum
- vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/README.md
- vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/polarion_reporter.go
- vendor/modules.txt
We vendored the v0.1.3 version, but our vendoring code picked a
few commits before it, missing out on code we need.
```release-note
NONE
```
> Update qe-tools dependency to avoid a cryptic Go module issue.

- pkg/operator/resources/cluster/datavolume.go
- pkg/operator/resources/operator/operator.go
The new 'generator' way does not work when go is not installed. So this PR reverts that code, and adds all the required code to match the current state.
Fixes #
```release-note
NONE
```
> Fix code schema to match what is generated by types.go

- pkg/operator/controller/controller.go
- pkg/operator/resources/operator/BUILD.bazel
Instead of trying to do it during the reconcile object creation, do it during the reconcile loop where
we already look up the CR anyway, and setting the value is free.
This PR fixes an issue where we tried to look up the CR to find the node placement information during the creation of the reconciler. The CR might not exist at that point in time and it would fail. For example here: https://github.com/kubevirt/hyperconverged-cluster-operator/pull/803 Instead set the node placement information during the reconcile loop since we are
already looking up the CR there anyway.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) …
> Change how we look up the node placement.

- hack/build/build-manifests.sh
- pkg/apiserver/webhooks/BUILD.bazel
- pkg/apiserver/webhooks/datavolume-validate.go
- pkg/apiserver/webhooks/datavolume-validate_test.go
- tests/api_validation_test.go
- tests/manifests/templates/dv1024MiPVC.yaml.in
As discussed in #1341 datavolume-controller mistakenly used reflect.DeepEqual() to check DV spec is not updated, however it rejected even a no-change (of size 4096Mi to 4Gi). This fix uses semantic.DeepEqual() instead so it won't be rejected.
Fixes #1341
```release-note
Fixed a bug that prevented adding DataVolumes of sizes which are a multiple of 1024 (e.g 5120Mi).
```
> Use semantic DeepEqual check on DV update

- tests/import_test.go
For example if it's deployed by HCO
Follow up to #1383, this is how the operator_tests.go code handles it.
```release-note
NONE
```
> Skip the test if CDI CR is called something else

- automation/test.sh
Don't test the upgrade from latest release to current PR if RANDOM_CR variable is set. If it is set, then the wait will fail because it is looking for the wrong CR name. If it is set we explicitly want a different CR name.
Fixes #
```release-note
NONE
```
> Only test upgrading from latest release to current if random_cr not set

- pkg/clone/auth.go
- pkg/controller/BUILD.bazel
- pkg/operator/resources/cluster/rbac.go
- tests/webhook_test.go
Need this in order easily implement cloning from "golden namespace"
Fixes #
```release-note
NONE
```
> Clone auth for serviceaccounts should include groups

- pkg/apiserver/webhooks/BUILD.bazel
- pkg/apiserver/webhooks/datavolume-mutate.go
- pkg/apiserver/webhooks/handler.go
- pkg/clone/BUILD.bazel
- pkg/clone/auth.go
- tests/BUILD.bazel
- tests/webhook_test.go
KubeVirt is on old k8s client so can't share any code that references k8s client directly
Fixes #
```release-note
NONE
```
> Change clone authorization api to allow any k8s client version

- pkg/controller/BUILD.bazel
- tests/cloner_test.go
- tests/framework/framework.go
target NS does not, the clone should fail.
Added missing functional test to complete test plan
Fixes #
```release-note
NONE
```
> Add functional test for cloning if source NS has enought quota and

- pkg/importer/s3-datasource.go
Signed-off-by: Yao-Tsung Hsu <ytsunghsu@gmail.com>
In Amazon S3, path-style URLs follow the format `https://s3.<region>.amazonaws.com/<bucket-name>/<key-name>`. 
(Reference: https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html)
In this PR, the extractRegion function uses regular expression to see whether the endpoint is an aws s3 endpoint.
If it is an aws s3 endpoint, extract region from the submatch; otherwise, fallback to the original method of extracting the region.
Fixes #1381
```release-note
NONE
```
> Fix incorrect region parsing from aws s3 endpoint

- hack/ci/Dockerfile.ci
When there is a problem with dependencies, the build fails for the
entire CDI.
Failure when building a OR CI image should not fail the entire CDI build.
Fixes #
```release-note
NONE
```
> Remove dependency update when building the OR CI build image

- pkg/apis/core/v1alpha1/BUILD.bazel
- pkg/apis/core/v1alpha1/utils.go
- pkg/apis/core/v1beta1/BUILD.bazel
- pkg/apis/core/v1beta1/utils.go
- pkg/controller/BUILD.bazel
- pkg/controller/clone-controller.go
- pkg/controller/clone-controller_test.go
- pkg/controller/datavolume-controller.go
- pkg/controller/datavolume-controller_test.go
- pkg/controller/util.go
- tests/cloner_test.go
Added a library function that checks if a PVC is fully populated. The logic is as following:
If PVC has no ownerRef, then we assume something else fully populated it and
will return true
If PVC has an ownerRef and its a DataVolume, then look up the DataVolume
If DV.status.Phase == succeeded, return true, return false otherwise.
Fixes #
```release-note
Enhancement: When cloning a source owned by a DV, the clone now waits for the source to be fully populated before cloning
```
> Add library function to determine if a PVC has been populated fully.

- manifests/templates/vcenter.yaml.in
- pkg/importer/vddk-datasource.go
- tests/datavolume_test.go
- tests/utils/configmaps.go
This allows people to run the test outside of the kubevirtci
environment and have it complete successfully.
Added configmap to vcenter.yaml.in that creates the CM that
lets users specify which init container to use. The default
is the test init container
Fixes #
```release-note
NONE
```
> Removed hard coded registry:5000 for vddk datasource test.

- cmd/cdi-cloner/BUILD.bazel
- cmd/cdi-cloner/clone-source.go
- go.mod
- go.sum
- pkg/uploadserver/BUILD.bazel
- pkg/uploadserver/uploadserver.go
- tests/cloner_test.go
- vendor/github.com/golang/snappy/.gitignore
- vendor/github.com/golang/snappy/AUTHORS
- vendor/github.com/golang/snappy/BUILD.bazel
- vendor/github.com/golang/snappy/CONTRIBUTORS
- vendor/github.com/golang/snappy/LICENSE
- vendor/github.com/golang/snappy/README
- vendor/github.com/golang/snappy/decode.go
- vendor/github.com/golang/snappy/decode_amd64.s
- vendor/github.com/golang/snappy/decode_arm64.s
- vendor/github.com/golang/snappy/decode_asm.go
- vendor/github.com/golang/snappy/decode_other.go
- vendor/github.com/golang/snappy/encode.go
- vendor/github.com/golang/snappy/encode_amd64.s
- vendor/github.com/golang/snappy/encode_arm64.s
- vendor/github.com/golang/snappy/encode_asm.go
- vendor/github.com/golang/snappy/encode_other.go
- vendor/github.com/golang/snappy/go.mod
- vendor/github.com/golang/snappy/snappy.go
- vendor/modules.txt
Snappy is optimized for high throughput and performs much better than gzip for our use case
Fixes #
```release-note
Use Snappy compression for network cloning
```
> use snappy compression for cloning instead of gzip

- doc/smart-clone.md
- tests/smartclone_test.go
Ceph no longer allows target size > source size when restoring from snapshot.
Fixes some failures on ceph which do not allow source PVC size < target PVC size when restoring from snapshots.
Fixes #
```release-note
NONE
```
> Fix size mismatch between source and target in smart clone tests.

- tests/cdiconfig_test.go
- tests/upload_test.go
Add test IDs, cover a few more cases, and avoid introducing a flaky test by waiting for the config controller to run.
```release-note
NONE
```
> Touch ups for filesystem overhead test cases

- pkg/common/common.go
- pkg/controller/clone-controller.go
- pkg/controller/clone-controller_test.go
- pkg/controller/upload-controller.go
- pkg/controller/upload-controller_test.go
This may help clone performance.  Shouldn't make it worse.  Wonder if there's a reason why we haven't done this yet?
Should probably revisit the fact that data is compressed in transit.  Maybe we shouldn't do it at all?  Or only do it when pods are on different nodes?
Fixes #
```release-note
Try to schedule clone source/target pods on same host
```
> Attempt to schedule clone source/target pods on same node

- pkg/importer/transport.go
Files in tar archives can have paths relative to `./`. In such case tar entries in tar header have names prefixed with "./". This PR adds code to hande such case.
Fixes #
```release-note
NONE
```
> Files in tar archives can have paths relative to ./

- tests/upload_test.go
We have flaky upload tests because we try to upload when the server pod is not 100% ready. This PR makes us retry the upload in those cases.
Fixes #
```release-note
NONE
```
> Retry upload in case upload pod wasn't 100% ready when attempting upload

- tests/cloner_test.go
OCS doesn't allow snapshot restore into larger PVC than the PVC the snapshot was created from. This PR fixes a test that fails in case of OCS because the source was smaller than the target.
Fixes #
```release-note
NONE
```
> Fix cloning checking fsGroup test in case of use with OCS.

- cluster-sync/nfs/nfs-server.yaml
- manifests/templates/release/cdi-cr.yaml.in
- pkg/operator/resources/utils/common.go
- tests/BUILD.bazel
- tests/operator_test.go
While here, mark cdi-operator as linux-only, it doesn't take
its value from the CDI CR.
To cite Daniel Belenky that posted a pull request for this same feature,
> By toleratin the CriticalAddonsOnly taint, we ensure that our components
> will get a reserved spot for critical addons in case they are being
> evicted. This will reduce of chance of CDI component/s starving for a
> place on a node and permanently unavailable.
Fixes #1152
```release-note
Add the CriticalAddonsOnly toleration to CDI infrastructure deployments
```
> Make CDI infra deployments as critical addons.

- pkg/controller/clone-controller.go
- pkg/controller/clone-controller_test.go
Should address the condition described here:  https://bugzilla.redhat.com/show_bug.cgi?id=1866593#c20
Currently, the finalizer is added to the target PVC after the clone source pod is created.  This means that the source pod may get orphaned if the target PVC is deleted before the finalizer is added
Fixes #
```release-note
NONE
```
> add finalizer to target PVC before creating clone source pod

- Makefile
- cluster-sync/sync.sh
- hack/build/cluster-sync-test.sh
CDI developer would prefer not to redeploy test containers on each cluster-sync. Currently each time we cluster-sync, it un-installs all of CDI, including test containers, and then re-installs newly compiled CDI containers, and then re-installs the test containers. The test containers don't change often, so it makes sense to not always reinstall them. This is helpful when you are developing and  not interested in the tests. It saves a lot of time.
```NONE```
> Add make targets cluster-sync-cdi & cluster-sync-test-infra

- tests/cloner_test.go
- tests/framework/framework.go
- tests/framework/nfs-utils.go
- tests/framework/pvc.go
- tests/import_test.go
- tests/tests_suite_test.go
- tests/utils/common.go
- tests/utils/pod.go
- tests/utils/pv.go
During each test run, we wait until the NS of the current test is fully deleted before moving to the next test. This PR we just delete the NS, and continue to the next test while letting the system clean up the old ns. In theory this should shorten the runtime of a lane.
Fixes #
```release-note
NONE
```
> Don't wait for NS to deleted in test before starting next test

- WORKSPACE
This will still be problematic the moment the packages are updated,
but it's at least going to give us a fallback for the one CI server
that is failing to resolve the mirror it's being redirected to, and
give valid URLs that can be mirrored.
```release-note
NONE
```
> Update WORKSPACE packages to non-404 ones, and add a second mirror.

- cluster-sync/nfs/nfs-server.yaml
- pkg/controller/import-controller.go
- pkg/controller/import-controller_test.go
- pkg/controller/util.go
- tests/datavolume_test.go
- tests/framework/nfs-utils.go
- tests/utils/datavolume.go
- tests/utils/pod.go
Fixed the creation of scratch space (after it is being deleted) in some rare scenarios.
Here is the scenario that is fixed by the PR - after requesting the creation of the pod and the scratch-space:
1. The Pod is being created so it shows in the system as Pending (waits for all PVC to be available), this is observed in controller and it tries to create scratch again, but scratch is already in the system (also Pending), so controller sets  condition "Claim Pending" and returns.
2. Some external action - be it a script or a user - removes PVC (if I am not mistaken the finalizer: "kubernetes.io/pvc-protection" does not work if pod is Pending/not yet scheduled), now the only thing the controller can see is a PVC event, but the scratch PVC is not found …
> Scratch import bug

- pkg/importer/data-processor.go
- pkg/importer/data-processor_test.go
- pkg/importer/http-datasource.go
- pkg/importer/http-datasource_test.go
- pkg/importer/imageio-datasource.go
- pkg/importer/imageio-datasource_test.go
- pkg/importer/registry-datasource.go
- pkg/importer/registry-datasource_test.go
- pkg/importer/s3-datasource.go
- pkg/importer/s3-datasource_test.go
- pkg/importer/upload-datasource.go
- pkg/importer/upload-datasource_test.go
- pkg/importer/vddk-datasource.go
This phase can mean three things:
HTTP, imageio, s3, upload: Go directly to Convert
VDDK: unreachable code, points to arbitrary other phase.
registry: do minor processing after transfer.
Only registry makes actual use of this phase.
Point all current users directly to Convert, and fold the
work done in the registry Process phase into the previous
phase.
I did some reading of the state diagram for the purpose of adding an unconditional validation, it was pretty complicated and this seems like a possible simplification. Let me know if you disagree. 
```release-note
NONE
```
> Remove the "Process" data processor phase, simplify state machine.

- api/openapi-spec/swagger.json
- pkg/apis/core/v1alpha1/openapi_generated.go
- pkg/apis/core/v1alpha1/types.go
- pkg/apis/core/v1alpha1/types_swagger_generated.go
- pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/core/v1beta1/openapi_generated.go
- pkg/apis/core/v1beta1/types.go
- pkg/apis/core/v1beta1/types_swagger_generated.go
- pkg/apis/core/v1beta1/zz_generated.deepcopy.go
- pkg/controller/config-controller.go
- pkg/controller/config-controller_test.go
- pkg/controller/util.go
- pkg/controller/util_test.go
- pkg/operator/resources/operator/operator.go
- tests/cdiconfig_test.go
- tests/cloner_test.go
- tests/datavolume_test.go
- tests/framework/framework.go
- tests/import_test.go
- tests/rbac_test.go
- tests/upload_test.go
- tests/utils/BUILD.bazel
- tests/utils/common.go
Make CDIConfig singleton mirror data in "active" CDI
CDI is now _the_ place for setting CDIConfig.  The singleton CDIConfig instance is still created.  But the spec mirrors whatever is in CDI.
Fixes #
```release-note
Embedded CDIConfigSpec in CDI resource
```
> Add CDIConfig to CDI

- tests/framework/framework.go
Endpoints objects indicates which pods related to a service, it helps debugging a Service.
Add Endpoints logging to test framework. After failed tests a new endpoints log will be available to help troubleshooting.
Fixes #
```release-note
NONE
```
> k8s-reporter: Add Endpoints logging

- pkg/importer/vddk-datasource.go
This pull request adds some extra logging to the VDDK importer.
Fixes #1464
One useful piece of this ended up in a different pull request: [this goroutine that logs nbdkit's stdout/stderr](https://github.com/mrnold/containerized-data-importer/commit/7edbcbb7fb6b93ec91e8bc25cfa9b34ca300ba33#diff-c46055929ede7b3ba517257f9a8614ee9507c33a99c80b8d51933e143c6fb864R242). I am only mentioning this in case anyone needs to backport this to CNV 2.5 without taking all of #1448. 
```release-note
NONE
```
> VDDK: Add more debug logging around nbdkit.

- cluster-sync/sync.sh
Move configure_storage to test setup.
Some of the storage setup involves deploying pods, and they
are labelled with cdi.kubevirt.io/testing for the benefit of
the "CriticalAddonsTolerations" test.
The test setup deleted all the test pods before deploying,
which means that the storage pods were killed, breaking
KUBEVIRT_STORAGE=nfs make cluster-sync
```release-note
NONE
```
> fix KUBEVIRT_STORAGE=nfs make cluster-sync

- pkg/controller/clone-controller.go
- pkg/controller/clone-controller_test.go
- pkg/controller/datavolume-controller_test.go
- pkg/controller/import-controller.go
- pkg/controller/import-controller_test.go
- pkg/controller/upload-controller.go
- pkg/controller/upload-controller_test.go
- pkg/controller/util.go
- tests/datavolume_test.go
- tests/utils/datavolume.go
Specific PVC annotations are passed to the import/upload/clone pods.
The currently passed annotations are:
```
k8s.v1.cni.cncf.io/networks: "some-network"
sidecar.istio.io/inject: "true"/"false"
```
Fixes #1364 
Fixes Bugzilla #1883232
```release-note
Specific PVC annotations are passed to the import/upload/clone pods.
```
> Pass specific PVC annotations to the transfer pods

- Makefile
- cluster-sync/clean.sh
- cluster-sync/sync.sh
- hack/README.md
`make cluster-sync-cdi` now depends on the new `cluster-clean-cdi` target which does not deletes the entire cdi namespace, and keeps the test pods running. Also, `make cluster-sync-test-infra` now depends on the new `cluster-clean-test-infra` target.
Fixes #1496 
```release-note
NONE
```
> Fix make target cluster-sync-cdi, add cluster-clean-cdi & cluster-clean-test-infra

- hack/build/config.sh
- hack/build/docker/builder/Dockerfile
Update the parent image of `kubevirt-cdi-bazel-builder` image to fedora 33
```release-note
Update the parent image of kubevirt-cdi-bazel-builder to fedora 33
```
> Update builder to fedora 33

- pkg/controller/config-controller.go
- pkg/controller/config-controller_test.go
- pkg/operator/controller/BUILD.bazel
- pkg/operator/controller/callbacks.go
- pkg/operator/controller/controller_test.go
- tests/operator_test.go
Formally designate CDI as CDIConfig authority by adding annotation `cdi.kubevirt.io/configAuthority` to CDI after copying values from existing CDIConfig.
If the annotation does not exist, the config controller will ignore values in CDI
Fixes #
```release-note
NONE
```
> Designate CDI as CDIConfig authority

- tools/cdi-func-test-registry-init/populate-registry.sh
Fixes #1468 
```release-note
NONE
```
> Allow specifying in an environment variable the name of the container disk used during init of the registry-file-host

- cmd/cdi-cloner/clone-source.go
- cmd/cdi-cloner/cloner_startup.sh
- pkg/controller/clone-controller.go
Tar errors were basically ignored as tar output was piped into the clone-source program.  Not the clone-source program executes tar and can therefore abort on error.  This will allow failures to be retried.
Also fixed a couple regressions in clone controller.  Should watch clone source pods.  Also better handle upload pod readiness.
Fixes #
This is one part of a two PR fix for https://bugzilla.redhat.com/show_bug.cgi?id=1893363
It does not address the root cause which is filesystem permission issues.  But it will correctly abort an upload …
> Clone source pod abort on tar error

- pkg/controller/clone-controller.go
- pkg/controller/clone-controller_test.go
- pkg/controller/util.go
- pkg/operator/controller/callbacks.go
- pkg/operator/controller/cruft.go
- pkg/operator/controller/scc.go
Read/write mounts will minimize errors when a source PVC is mounted multiple times on the same node.
Fixes #
This is two part of a two PR fix for https://bugzilla.redhat.com/show_bug.cgi?id=1893363
Once this and #521 are merged I will add a new functional test to stress cloning hard
```release-note
Clone source pods mount PVCs read-only
```
> Read-only mounts in clone source pods

- api/openapi-spec/swagger.json
- pkg/apis/core/v1alpha1/openapi_generated.go
- pkg/apis/core/v1alpha1/types.go
- pkg/apis/core/v1alpha1/types_swagger_generated.go
- pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/core/v1beta1/openapi_generated.go
- pkg/apis/core/v1beta1/types.go
- pkg/apis/core/v1beta1/types_swagger_generated.go
- pkg/apis/core/v1beta1/zz_generated.deepcopy.go
- pkg/controller/datavolume-controller.go
- pkg/controller/datavolume-controller_test.go
- pkg/operator/resources/operator/operator.go
- tests/smartclone_test.go
We used to detect the possibility of smart-cloning and always use it
if it's there. This might not be the desirable behaviour if:
- Snapshots cost more money than a host-assisted clone
- Snapshots are broken
The API is:
kubectl edit cdi
cdi.Spec.cloneStrategyOverride = "Host"
We use an enum rather than a boolean for this in an attempt to future
proof if more strategies are available, but only the value that is
currently necessary is used.
If no value is defined, we continue with the existing behaviour of
preferring smart clone if possible.
I've only defined a value in the spec portion of the CDI CR, and not in the status, or in CDIConfig.
Avoiding the config controller feels like it might be the right move, but we have spoken about this enough that I'm …
> Add an API for disabling smart-cloning.

- WORKSPACE
```release-note
BUGFIX: fix build failing as some Fedora servers have moved RPMs fetched as part of the build process to the archive.
```
> [release-v1.23] fix travis build

- pkg/controller/util.go
Multus adds an extra nic to the pod as passed by annotation `k8s.v1.cni.cncf.io/networks` from the dv, but to set it as default nic of the pod we need to pass `v1.multus-cni.io/default-network` annotation instead.
```release-note
NONE
```
> Allow passing default multus network annotation to transfer pods

- cmd/cdi-cloner/clone-source.go
- cmd/cdi-cloner/cloner_startup.sh
- pkg/controller/clone-controller.go
Cherrypick of #1521 
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=1907623
```release-note
Bugfix: Clone source pod will detect tar errors and abort rather than silently ignore
```
> [release-v1.23] Clone source pod abort on tar error

- hack/build/build-cdi-func-test-file-host.sh
- tools/cdi-func-test-file-host-init/main.go
same goals as #1462 but without significant functional changes.
As a side effect, this means all the test-images file group (specified in BUILD.bazel) will be available through the file host, and not just the subset that was specified in tools/cdi-func-test-file-host-init/main.go.
```release-note
NONE
```
> Simplify file host, now a new image only has to be added to bazel.

- pkg/image/qemu.go
- tests/import_test.go
- tests/upload_test.go
- D/S the importer pod has verbosity=1 => the preallocation messages are not present in log
- Due to this, we hit an infinite loop in the preallocation tests
(Import completed without preallocation message => pod doesn't exist anymore but sampling continues)
Fixes #
```release-note
NONE
```
> Change verbosity for preallocation messages, avoid infinite loop

- cmd/cdi-importer/importer.go
- pkg/controller/import-controller.go
- tests/import_test.go
This fixes a bug where blank image disks were not preallocated.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1914177
```release-note
NONE
```
> core: Preallocate blank image disks as well

- tests/cloner_test.go
- tests/import_test.go
Some OpenShift versions seem to not add spaces between different
components of the message, become more resilient for this scenario.
```release-note
Fix some tests failing in newer versions of OpenShift due to whitespace differences
```
> Compare logs while ignoring differences in spaces

- pkg/controller/import-controller.go
- pkg/controller/import-controller_test.go
- pkg/controller/upload-controller.go
- pkg/controller/util.go
- tests/datavolume_test.go
- tests/utils/datavolume.go
When the annotation is applied the CDI will force bind the PVC (by scheduling worker pods), ignoring the logic to handle WaitForFirstConsumer binding mode.
This is useful when uploading "template" images to the cluster on local storage with WaitForFirstConsumer binding. In this case the image has to be available somewhere on the cluster, the actual placement of image on specific node is not important, so the CDI worker node can be used as a first consumer.
For storage with immediate binging it is effectively a NOOP.
Fixes #
**Special notes for …
> Add a DV/PVC annotation "storage.bind.immediate.requested"

- cmd/cdi-importer/importer.go
- pkg/importer/BUILD.bazel
- pkg/importer/vddk-datasource.go
- pkg/importer/vddk-datasource_test.go
- tests/datavolume_test.go
- tests/utils/datavolume.go
**What this PR does / why we need it**: Addresses BZ 1913756, where VDDK disk imports fail with block device destinations.
Fixes #1563 
```release-note
BZ 1913756: fix VDDK import to block device destination volumes.
```
> VDDK: work with block devices better (BZ 1913756).

- pkg/controller/util.go
Printing just the name of the storageclass is just as descriptive
as printing the entire structure, and V(3) is probably preferred
for debug output.
```release-note
Reduce the amount of output generated by the filesystem overhead functionality.
```
> Reduce the noise from the filesystem overhead functionality

- tests/datavolume_test.go
- tests/operator_test.go
- tests/utils.go
We have a different build which uses a different versioned qemu-img.
This test only fails on newer versions of qemu-img, and it's causing our differential build to always have a single failure.
Skipping on OpenShift to ensure that no regressions enter - we still test kubernetes lanes.
Fixes #
This can probably be reverted once #1466 merges.
But I would like to have it in previous release branches too.
```release-note
NONE
```
> Skip test 2555 if running on openshift

- tests/datavolume_test.go
- tests/operator_test.go
- tests/utils.go
* Move "isOpenshift" to utils and make public.
No functional change.
Signed-off-by: Maya Rashish <mrashish@redhat.com>
* Skip malformed too large qcow2 on openshift.
Whether this test fails depends on the qemu-img version. The way we
build and test it in this repo is fine, but external builds may fail.
Skipping only on OpenShift means we will continue testing it and
finding regressions.
Signed-off-by: Maya Rashish <mrashish@redhat.com>
Backport of #1572 
Fixes #
```release-note
NONE
```
> [release-v1.28] Skip test 2555 if running on openshift (#1572)

- cmd/cdi-importer/importer.go
- pkg/controller/import-controller.go
- pkg/image/qemu.go
- tests/import_test.go
Importer pod needs to be started for blank block volumes and it needs to
handle the case.
Fixes #
```release-note
NONE
```
> core: Preallocate blank block volumes

- doc/datavolume-annotations.md
- doc/datavolumes.md
Explain using specific annotations to a DV or PVC to be passed to the Transfer Pods and control their behavior.
```release-note
NONE
```
> Add Data Volume annotations documentation

- cmd/cdi-importer/importer.go
- pkg/common/common.go
- pkg/importer/data-processor.go
- pkg/uploadserver/uploadserver.go
- pkg/uploadserver/uploadserver_test.go
Instead of (ab)using raw strings, preallocation status in importer and
uploader use now a custom type.
Fixes #
```release-note
NONE
```
> Typedef for preallocation status

- tests/framework/framework.go
Datavolumes made for archive volumes are expected to contain a directory
called "data" with the archive contents, and we want to clean those up as
well.
See the following run for an example: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1558/pull-containerized-data-importer-e2e-k8s-1.18-nfs/1349861219908980736
If we look at the build-log.txt, we see messages like:
```
STEP: Destroying namespace "cdi-e2e-tests-cdiconfig-test-r2kfb" for this suite.
STEP: Deleting NFS PVs after the test
[WARN] error executing command ["/bin/sh" "-c" "/bin/rm -f /data/nfs/disk3/*"], error: command terminated with exit code 1
INFO: cleaning up nfs disk3 failed: , rm: '/data/nfs/disk3/disk' is a directory
[WARN] error …
```
> When cleaning up NFS disks, recursively delete their contents.

- tests/upload_test.go
We always use port-forward in our upload tests, but port-forward fails often and does not recover. This PR attempts to use the proxy URL specified in the CDIConfig instead before attempting port-forward. If the cluster being tested on has a more stable proxy URL it will be used instead.
Fixes #
```release-note
NONE
```
> Try to use the CDIConfig proxy URL if it is set, if not use port-forward

- cmd/cdi-cloner/cloner_startup.sh
- tests/cloner_test.go
If a block device has been populated with a disk image, lsblk (as we invoke it) will return two rows of data. The first is the size of the entire device. The second is the size of the embedded disk image partition.
This was not an issue until we added the -mount param to the clone-source program.
Newer code uses `blockdev` instead of `lsblk` so apparently not a problem.
Fixes #
```release-note
BugFix: fix lsblk output parsing
```
> fix lsblk handling

- tests/datavolume_test.go
Open Shift 4.6 qemu now puts quotes around part of the message, and upstream qemu does not. This causes the test to fail in Open Shift. This PR removes the part that gets quoted which should allow the test to pass in both places without loss of fidelity in the checks.
Fixes #
```release-note
NONE
```
> Make string comparison less strict.

- tests/cloner_test.go
If the verifier runs first, it seems to crash repeatedly and
never lets the clone proceed, hitting a timeout.
Failure seen here: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1600/pull-containerized-data-importer-e2e-k8s-1.18-upg/1352653678372196352
```release-note
NONEe
```
> Wait for clone to succeed before checking MD5.

- automation/test.sh
- tests/operator_test.go
Sometimes destructive tests wouldn't clean up properly ruining the rest
of the run. This makes it so we can focus and skip the destructive
tests based on the lane settings. In combination with some changes to the
lanes we can speed up testing and have a separate lane for running destructive
tests.
Fixes #
https://github.com/kubevirt/project-infra/pull/890 needs to be merged in order to test this properly.
```release-note
NONE
```
> Add focus for destructive tests.

- pkg/controller/import-controller.go
- pkg/controller/import-controller_test.go
VMware imports need to have a v2v-vmware ConfigMap defined so the importer can make use of VDDK libraries. It is easy to forget this step, and it is not obvious when the importer is waiting for it. This pull request raises the visibility of this error up to the Bound condition on the DataVolume.
Partial fix to help address BZ#1886566, requested by QE. 
```release-note
Raise visibility of "missing VDDK image" error up to DV Bound condition.
```
> Update DV status to indicate when VDDK configmap is missing.

- pkg/apiserver/webhooks/datavolume-validate.go
- pkg/controller/clone-controller.go
- pkg/controller/clone-controller_test.go
- pkg/controller/datavolume-controller.go
- pkg/controller/upload-controller.go
- pkg/controller/upload-controller_test.go
- pkg/feature-gates/BUILD.bazel
- pkg/uploadserver/uploadserver.go
- tests/cloner_test.go
* validate source and target pvcs has the same content type - for all clones
* if source and target volume modes are different, validate content type is kubevirt, and fallback to host-assisted cloning
* unit & func tests
Fixes #
```release-note
Add support for cloning kubevirt disk residing on a filesystem mode PV to another PV that is block mode, and vice-versa.
```
> Support cloning from Filesystem to Block and vice-versa

- doc/datavolumes.md
Removes a documentation note about VMware imports not working with VDDK 7. This was true with the initial implementation, but the update to Fedora 33 included a version of nbdkit that works with VDDK 7.
```release-note
Remove documentation note about VDDK 7 restriction.
```
> Remove documentation note about VDDK 7 restriction.

- tests/datavolume_test.go
We are seeing failures because the pods are disappearing too fast. Attempt to fix this
by polling much faster so the odds of us being able to get both pods is increased.
Fixes #
```release-note
NONE
```
> Increase polling speed for upload annotation test

- pkg/controller/import-controller.go
- pkg/controller/import-controller_test.go
- pkg/controller/upload-controller.go
By having the function itself grab things it needs and are easily
obtained.
```release-note
NONE
```
> Simplify shouldReconcile function arguments.

- pkg/importer/vddk-datasource.go
- pkg/importer/vddk-datasource_test.go
This pull request avoids a VDDK importer crash when the specified disk is not in the source VM's hardware configuration, and the VM has never had any snapshots taken. Now it will return a slightly more helpful error message.
Fixes #1634
```release-note
Avoid VDDK importer crash when source VM does not contain specified disk.
```
> VDDK: avoid crash when specified disk isn't in VM.

- tests/operator_test.go
Operator cert config tests fails sometimes during CI. This PR adds
some diagnostic output that can help understand the failure.
Fixes #
```release-note
NONE
```
> Add diagnostic to flaky test

- .travis.yml
- WORKSPACE
- cmd/cdi-cloner/BUILD.bazel
- cmd/cdi-importer/BUILD.bazel
- cmd/cdi-uploadserver/BUILD.bazel
- pkg/feature-gates/BUILD.bazel
- tools/vddk-test/BUILD.bazel
With the dockerhub rate limit, we are seeing a lot of CI failures due to rate limits on dockerhub. This PR makes it so we release on quay.io instead which doesn't have the rate limit.
Fixes #
```release-note
NONE
```
> Release to quay.io instead of docker

- tests/datavolume_test.go
Sometimes the test fails because `ls` called in a container returns an
empty string. The fix is surround the test with a `Eventually` clause,
so that the command is retried when needed.
Example failure: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1603/pull-containerized-data-importer-e2e-k8s-1.18-hpp/1355110491671760896
Fixes #
```release-note
NONE
```
> Fix flaky test: failure when checking permissions

- hack/build/bazel-build-builder.sh
During release we are logged into quay.io now, and we are attempting to push the builder to dockerhub, which obviously will fail. This PR switches the push to quay as well.
Fixes #
On this is merged, and we are successfully pushing to quay.io, we need to alter config.sh to pull the builder image from quay.io as well
```release-note
NONE
```
> Push builder to quay.io as well

- tests/utils/pod.go
This is part of #1603 split into its own change.
I would like to have this as its own change so we can backport it right away, whereas #1603 is something we'd like to test to see if it's stable for a while.
```release-note
NONE
```
> Fix inverted logic - wait for the pod to stop existing.

- doc/clone-block-datavolume.md
- doc/clone-datavolume.md
What this PR does / why we need it:
Update the documentation following [PR 1597](https://github.com/kubevirt/containerized-data-importer/pull/1597).
Release note:
```release-note
NONE
```
> Update cross volume mode DV clone doc

- cmd/cdi-importer/importer.go
- cmd/cdi-uploadserver/uploadserver.go
- pkg/common/common.go
- pkg/controller/import-controller.go
- pkg/controller/upload-controller.go
- pkg/importer/data-processor.go
- pkg/importer/data-processor_test.go
- pkg/uploadserver/uploadserver.go
- pkg/uploadserver/uploadserver_test.go
This PR removes "skipped" condition for preallocation. Importer/uploader
will preallocate to the available size.
Fixes #
```release-note
NONE
```
> Preallocate even if the size is too small

- cmd/cdi-importer/importer.go
- cmd/cdi-uploadserver/uploadserver.go
- pkg/controller/import-controller.go
- pkg/controller/upload-controller.go
- pkg/importer/data-processor.go
- pkg/importer/data-processor_test.go
- pkg/uploadserver/uploadserver.go
- pkg/uploadserver/uploadserver_test.go
- pkg/util/util.go
This PR removes "skipped" condition for preallocation. Importer/uploader
will preallocate to the available size. Filesystem overhead needs to be
taken into account.
This is a cherry-pick from #1637 
Signed-off-by: Tomasz Barański <tomob@users.noreply.github.com>
Fixes #
```release-note
None
```
> [release-v1.28] Preallocate even if the size is too small

- hack/build/osci-image-builder.sh
- hack/build/release-description.sh
- hack/ci/Dockerfile.ci
I missed a few references to dockerhub that causes the travis job to fail to push the images.
Fixes #
```release-note
NONE
```
> Fix a few more remaining references to docker.

- .travis.yml
We renamed the branch, but the release was looking for master. This
fixes travis to look for main.
Fixes #
```release-note
NONE
```
> Fix travis nightly to push from main.

- api/openapi-spec/swagger.json
- cmd/cdi-importer/importer.go
- pkg/apis/core/v1alpha1/openapi_generated.go
- pkg/apis/core/v1alpha1/types.go
- pkg/apis/core/v1alpha1/types_swagger_generated.go
- pkg/apis/core/v1beta1/openapi_generated.go
- pkg/apis/core/v1beta1/types.go
- pkg/apis/core/v1beta1/types_swagger_generated.go
- pkg/controller/datavolume-controller.go
- pkg/importer/s3-datasource.go
- pkg/importer/s3-datasource_test.go
- pkg/operator/resources/cluster/datavolume.go
Currently, custom CA endpoints are only allowed to be http datasources. This PR implements the same feature for s3 endpoints.
Fixes #1506
The implementation for s3 reuses the features from http datasources. Two alternatives were evaluated, first was using CustomCACerts from aws s3 library, but it overwrites the system certs, so the second one was selected, using a custom httpclient with new certs implemented reusing http datasource code.
A new test case has also been implemented for invalid certs as in http datasource tests.
```release-note
- New field in s3 datasources for custom CA Config Map like in http datasources
```
> Implement certConfigMap for s3 datasources, reported missing on #1506

- pkg/apiserver/webhooks/datavolume-validate.go
- pkg/controller/clone-controller.go
- pkg/controller/import-controller.go
- pkg/controller/import-controller_test.go
Fix content type validation for cloning, where the source content type is an empty string, which defaults to kubevirt.
Fixes #1656
```release-note
NONE
```
> Fix default content type validation for cloning

- pkg/common/common.go
- pkg/controller/datavolume-controller.go
- pkg/uploadserver/uploadserver.go
- pkg/uploadserver/uploadserver_test.go
Uploadserver and healthz run in separate goroutine, so we need
to synchronize them. This seems to be the easiest way.
Alternative paths considered:
- Unifying them.
This is troublesome, because the uploadserver requires client certs, and the kubernetes readiness probe doesn't provide them.
- Synchronize using some builtin: somewhat difficult because we either use a blocking function, or a separate goroutine, which means we don't know if it started.
- 
```release-note
Eliminate a very short window where an upload pod is UploadReady but an upload would fail.
```
> Have the healthz server check for the uploadserver first.

- pkg/importer/imageio-datasource.go
- pkg/importer/imageio-datasource_test.go
- pkg/importer/util.go
- pkg/importer/util_test.go
- pkg/importer/vddk-datasource.go
- pkg/importer/vddk-datasource_test.go
For ImageIO and VDDK data sources, this pull request allows the importer pod to catch SIGTERM and cleanly close any connections to RHEV or VMware. This is more important for ImageIO because RHEV can leave the disk locked, preventing another import attempt until a timeout (potentially several hours).
Fixes #1633 
RHBZ[#1924560](https://bugzilla.redhat.com/show_bug.cgi?id=1924560)
```release-note
Unlock ImageIO disks when importer pod is terminated.
```
> VDDK/ImageIO cleanup after importer termination.

- pkg/controller/clone-controller_test.go
- pkg/controller/import-controller_test.go
- pkg/controller/upload-controller_test.go
- pkg/controller/util.go
- tests/datavolume_test.go
when the annotation is not set explicitly in the DV/PVC
Disable Istio sidecar injection to transfer pods by default, as the pods currently don't support it and may crash during transfer. 
Default can be overridden using `sidecar.istio.io/inject` annotation in the DV/PVC.
Fixes #1914833
```release-note
Disable Istio sidecar injection to transfer pods by default.
Default can be overridden using `sidecar.istio.io/inject` annotation in the DV/PVC.
```
> Allow passing default annotation value to transfer pods

- hack/build/run-functional-tests.sh
This requires removing set -u because kubevirtci's scripts
use [ -z $KUBEVIRTCI_PATH ] to test for it being defined
and set -u makes this fail.
```release-note
NONE
```
> Setup a default KUBEVIRT_PROVIDER for make functional-test

- tests/framework/pvc.go
- tests/import_test.go
- tests/upload_test.go
This commit adds a test that verifies, that filesystem overhead is taken
into account when creating a blank image (with preallocation).
Also, some test cleanup.
Fixes #
```release-note
NONE
```
> Test filesystem overhead on blank images

- Makefile
- hack/build/config.sh
- hack/build/gosec.sh
Adding [gosec](https://github.com/securego/gosec) to the repo.
Fixes # https://github.com/kubevirt/containerized-data-importer/issues/1615
```release-note
Support to run gosec security scanner
```
> Adding support for gosec scan on CDI repo

- hack/build/release-description.sh
We've changed links to CDI containers to Quay, but the description still mentions DOcker Hub.
```release-note
NONE
```
> Update release description template (Docker Hub -> Quay.io)

- cmd/cdi-importer/importer.go
- pkg/controller/import-controller.go
- pkg/image/qemu.go
- pkg/importer/data-processor.go
- tests/import_test.go
Importer pod needs to be started for blank block volumes and it needs to
handle the case.
This is a cherry-pick from #1559 
Fixes #
```release-note
NONE
```
> [release-v1.28] Preallocate blank block volumes (#1559)

- pkg/importer/imageio-datasource.go
- pkg/importer/imageio-datasource_test.go
- pkg/importer/util.go
- pkg/importer/util_test.go
- pkg/importer/vddk-datasource.go
- pkg/importer/vddk-datasource_test.go
This is a cherry pick of #1670.
For ImageIO and VDDK data sources, this pull request allows the importer pod to catch SIGTERM and cleanly close any connections to RHEV or VMware. This is more important for ImageIO because RHEV can leave the disk locked, preventing another import attempt until a timeout (potentially several hours).
Fixes #1633
RHBZ#1924560
```release-note
Unlock ImageIO disks when importer pod is terminated.
```
> [release-v1.28] VDDK/ImageIO cleanup after importer termination.

- cluster-sync/external/resources/machineconfig-worker.yaml
- cluster-sync/k8s-1.17/provider.sh
- cluster-sync/k8s-1.18/provider.sh
- cluster-up/cluster/ephemeral-provider-common.sh
- cluster-up/cluster/k8s-1.17/dev-guide.md
- cluster-up/cluster/k8s-1.18/dev-guide.md
- cluster-up/cluster/k8s-1.19/dev-guide.md
- cluster-up/cluster/k8s-1.20/dev-guide.md
- cluster-up/cluster/kind-k8s-sriov-1.17.0/README.md
- cluster-up/cluster/kind-k8s-sriov-1.17.0/config_sriov.sh
- cluster-up/cluster/kind-k8s-sriov-1.17.0/provider.sh
- cluster-up/cluster/kind/common.sh
- cluster-up/hack/common.sh
- hack/update-kubevirtci.sh
This is the first part of updating to newer rook ceph.  Tests will still use old ceph until project-infra is updated.  Once project-infra is updated we can remove the ceph manifests here
Fixes #
```release-note
NONE
```
> update to kubevirtci with builtin rook/ceph

- automation/git-askpass.sh
- automation/release.sh
- hack/gen-swagger-doc/deploy.sh
This PR includes the necessary scripts that will allow prow jobs to make releases based on tags pushed to the repo.
Fixes #
```release-note
Enhancement: Releases are now done using PROW instead of travis.
```
> Add scripts to do releases with PROW

- manifests/templates/file-host.yaml.in
- manifests/templates/imageio.yaml.in
Found a few more locations that were using dockerhub which is now not usable for CI. This replaces it will the same images from quay.io.
Fixes #
```release-note
NONE
```
> Replace dockerhub references with quay.io

- hack/build/run-unit-tests.sh
Unit tests sometimes fail because of a timout related to controller
plane.
Fixes #
```release-note
NONE
```
> Increasing timeout for controller plane

- pkg/image/nbdkit.go
- tools/vddk-test/vddk-test-plugin.c
This pull request splits nbdkit plugin parameters into separate command line arguments instead of concatenating them into one string, so VDDK imports will work again.
Fixes #1700 
This also adds a quick parameter count check so that functional tests will fail if the same problem happens again, and formats the relevant log message so it's easier to see which parameters are stuck together.
```release-note
NONE
```
> Separate nbdkit plugin arguments.

- pkg/image/nbdkit.go
- pkg/image/qemu.go
- pkg/importer/data-processor.go
- tests/import_test.go
If the falloc mode is not supported, try full first and then zero-sized
sparse blocks.
Bugzilla-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1928730
Fixes #
```release-note
NONE
```
> Try different modes of preallocation

- BUILD.bazel
- hack/build/bazel-push-images.sh
Moved the cdi core components containers into their own push so we don't overwhelm the registry and get rate limited.
Fixes #
```release-note
NONE
```
> Move the cdi core containers out of push bundle to limit the push rate.

- pkg/image/qemu.go
- pkg/importer/data-processor.go
- tests/import_test.go
If the falloc mode is not supported, try full first and then zero-sized
sparse blocks.
Bugzilla-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1928730
Signed-off-by: Tomasz Barański <tomob@users.noreply.github.com>
Fixes #
```release-note
NONE
```
> [release-v1.28] Try different modes of preallocation (#1663)

- Makefile
When the system C headers change, sometimes we have bizarre failures from bazel.
We usually end up telling people to delete all their containers, but a lighter weight option is to run `bazel clean --expunge` in the bazel container.
To make this easier to do, add it to the clean target. 
```release-note
NONE
```
> Add `bazel clean --expunge` to the clean make target

- hack/build/bazel-build-images.sh
This PR fixes the make bazel-build-images make target.
Fixes #
```release-note
NONE
```
> Forgot to update bazel-build-images when splitting pushing.

- pkg/image/qemu.go
- pkg/image/qemu_test.go
- pkg/importer/data-processor.go
- pkg/importer/data-processor_test.go
- pkg/importer/vddk-datasource.go
- pkg/importer/vddk-datasource_test.go
- tests/import_test.go
- tests/transport_test.go
- tests/upload_test.go
- tests/utils/datavolume.go
When qemu image is resized, it needs to be preallocated to the requested
size. In-place preallocation (using convert function of qemu-img)
cleans the data.
With this PR preallocation is applied simply when the image is resized.
Fixes #
```release-note
None
```
> Bugfix: preallocating resized image erases data

- pkg/image/qemu.go
- pkg/image/qemu_test.go
- pkg/importer/data-processor.go
- pkg/importer/data-processor_test.go
- tests/import_test.go
- tests/transport_test.go
- tests/upload_test.go
- tests/utils/datavolume.go
* When qemu image is resized, it needs to be preallocated to the requested
size. In-place preallocation (using convert function of qemu-img)
cleans the data.
With this PR preallocation is applied simply when the image is resized.
* Functional tests for preallocation verify content (MD5).
Signed-off-by: Tomasz Barański <tomob@users.noreply.github.com>
Fixes #
```release-note
NONE
```
> [release-v1.28] Bugfix: preallocating resized image erases data (#1747)

- pkg/image/qemu.go
- pkg/importer/http-datasource.go
- pkg/importer/http-datasource_test.go
Change the old nbd style nbd:unix to nbd+unix:///?socket=socket
Signed-off-by: Alice Frosi <afrosi@redhat.com>
Fixes #
```release-note
None
```
> nbd: use modern uri for nbd

- api/openapi-spec/swagger.json
- doc/cdi-config.md
- doc/image-from-registry.md
- pkg/apis/core/v1alpha1/openapi_generated.go
- pkg/apis/core/v1alpha1/types.go
- pkg/apis/core/v1alpha1/types_swagger_generated.go
- pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/core/v1beta1/openapi_generated.go
- pkg/apis/core/v1beta1/types.go
- pkg/apis/core/v1beta1/types_swagger_generated.go
- pkg/apis/core/v1beta1/zz_generated.deepcopy.go
- pkg/controller/import-controller.go
- pkg/controller/import-controller_test.go
- pkg/operator/resources/cluster/cdiconfig.go
- tests/transport_test.go
- tests/utils/BUILD.bazel
- tests/utils/common.go
- tests/utils/configmaps.go
Keep supporting original ConfigMap for upgrade.
This change will allow HCO to expose a configuration to disable TLS for a container registries
```release-note
Add insecure registries to CDIConfig, but keep supporting original ConfigMap for upgrade
```
> Add insecureRegistries to CDIConfig

- pkg/controller/clone-controller.go
- pkg/controller/clone-controller_test.go
When the cloning is complete, the conditions to set `AnnCloneOf` annotation and status annotations (`AnnSourceRunningCondition*`) are different: the former is set when the cloning is done, while the latter depend on clone pod to finish. Sometimes `AnnCloneOf` is set, while the others are not, because even though the cloning is done, the pod is still in the running state. As a result, during the next reconciliation loop the pod is cleared and the status annotations are not set at all.
This PR adds a verification that the pod actually finishes (succeeds or fails) before `AnnCloneOf` is set.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, …
> Hold off AnnCloneOf until the target PVC is correctly updated.

- tests/framework/pvc.go
- tests/import_test.go
- tests/upload_test.go
This PR adds a step to prellocation verification tests which looks at the output of qemu-img and compares actual and virtual sizes of the image. 
Fixes #
```release-note
None
```
> Verify with qemu-img that image has been preallocated

- tests/import_proxy_test.go
- tests/tests_suite_test.go
We were setting the cluster proxy noProxy to * to have it ignore
all URLs, but then set it to "" in CDI CR without cleaning up.
This PR leaves it blank.
Fixes PROXY test on Open Shift with a cluster wide proxy.
Also improve some of the error logging to understand why clients cannot be created.
Fixes #
```release-note
NONE
```
> Fix cluster proxy part of proxy test

- pkg/operator/controller/certrotation_test.go
- pkg/operator/controller/controller.go
- pkg/operator/controller/controller_test.go
- pkg/operator/resources/cert/factory.go
- tests/certrotation_test.go
- tests/operator_test.go
We stole the idea of `Duration` and `RenewBefore` from cert-manager.  See here for interpretation: https://github.com/kubevirt/containerized-data-importer/blob/main/pkg/apis/core/v1beta1/types.go#L388-L393
We were not handling `RenewBefore` correctly.  It is supposed to be time before a cert's "not after."  But we were treating it is time from "not before".
Conversion is easy and will be done automatically on all certs after upgrade.
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=1957521
**Release …
> [Bugfix] wrong interpretation of custom cert rotation params

- hack/build/run-functional-tests.sh
Dump pod yamls and describes on failure so we can identify what went wrong.
Fixes #
```release-note
NONE
```
> Add extra information when CDI pods are not ready

- tests/datavolume_test.go
Instead of hard coding 'local' as a storage profile without access mode,
look up all the storage profiles and check if their access mode is empty.
If it is empty, return the storage class name to the test. If no storage
class is found then skip the test.
Fixes #
```release-note
NONE
```
> Fix noaccess mode storage profile test

- doc/scratch-space.md
- pkg/importer/http-datasource.go
- tests/datavolume_test.go
- tests/utils/configmaps.go
This restores support for the following scenarios:
- Now the system certs are considered as valid when a custom CA is used.
- The custom CA will be accepted regardless of the key value used in the configmap.
Add a test for the second scenario.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1946100
The scenario of system-wide certs is not tested because it requires using an external server.
```release-note
Restore compatibility: users are once again able to specify custom CAs for use in import in names other than tls.crt
```
> Restore compatibility in specifying custom CAs by using Go client

- tests/framework/pvc.go
Smartclone can begin its clone prior to the pod-using-PVC being gone.
We need this wait to guarantee that there are no pending writes in
the kernel cache.
Intended to fix a flaky test, seen failing here:
https://prow.ci.kubevirt.io/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1752/pull-containerized-data-importer-e2e-k8s-1.17-ceph/1390637610644279296
```release-note
NONE
```
> Use a method of deleting the pod that waits for it to no longer exist

- WORKSPACE
Updates the base fedora container hash, now that it changed again.
Fixes #
```release-note
NONE
```
> New release of fedora caused change in hash again.

- tests/cloner_test.go
The clone across nodes checks if we have at least 2 nodes with local PVs, before attempting to run the test. However the test assumes those are filesystem PVs because it writes a file which is then cloned. This fails when you only have local block PVs in your cluster. Our test was not properly filtering out those types of PVs, this PR resolves that.
Fixes #
```release-note
NONE
```
> Only run clone across nodes on filesystem PVs only.

- pkg/controller/datavolume-controller.go
- pkg/controller/datavolume-controller_test.go
- tests/datavolume_test.go
Correctly compute fs overhead for an effective VolumeMode. Effective, means one that is computed based on value in storage spec and the storageProfile.
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=1961227
```release-note
NONE
```
> Fix: Compute fs overhead only for fs volumeMode

- pkg/controller/datavolume-controller.go
- pkg/controller/datavolume-controller_test.go
- tests/datavolume_test.go
Manual cherry pick of #1791 
```release-note
NONE
```
> [release-v1.34] Fix: Compute fs overhead only for fs volumeMode #1791

- tests/transport_test.go
For context, was disabled as part of:
https://github.com/kubevirt/containerized-data-importer/pull/1119#issuecomment-595205735
But seems to pass comfortably now on NFS as well.
Fixes #
```release-note
NONE
```
> Enable test case 5072 - registry import, image contains valid archived raw file

- pkg/controller/datavolume-controller.go
- pkg/controller/datavolume-controller_test.go
An error in the logic that updates DV, it would ignore errors
during the update. Also small typo in tests corrected.
Fixes #
```release-note
NONE
```
> Fix - ignoring errors

- tests/leaderelection_test.go
Add some logging to figure out what is in the log why it is not being matched
The leader election tests are failing often, and it appears to fail in some log matching and I am guessing a new k8s version logs something different. This PR attempts to fix the tests.
Fixes #
```release-note
NONE
```
> Fix leader election test that is failing.

- cluster-sync/nfs/nfs-server.yaml
dockerhub rate limit strikes again. Move the nfs-server image to quay.io/awels so we don't run into that problem.
Fixes #
```release-note
NONE
```
> Move nfs-server images to quay.io

- tests/cloner_test.go
Our cloning tests use G instead of Gi, and it seems to sometimes create some confusion on the actual size, especially with ceph as the storage class. This PR turns everything in Gi.
Fixes #
```release-note
NONE
```
> Use gibi for cloning tests.

- cmd/cdi-apiserver/BUILD.bazel
- cmd/cdi-apiserver/apiserver.go
- cmd/cdi-controller/BUILD.bazel
- cmd/cdi-controller/controller.go
- cmd/cdi-uploadproxy/BUILD.bazel
- cmd/cdi-uploadproxy/uploadproxy.go
- pkg/util/cert/fetcher/certfetcher.go
Signed-off-by: Vishesh Ajay Tanksale <vtanksale@apple.com>
- Add flags to API Server, Controller and upload proxy to specify custom certificate paths. Custom certs path can be used to populate externally managed certs.
Fixes #
```release-note
NONE
```
> Adding support to specify externally managed certs

- pkg/importer/vddk-datasource.go
- pkg/importer/vddk-datasource_test.go
For VDDK data sources, this pull request encodes the login credentials so that they can be used in VMware login URLs. Without this, special characters in the username or password can cause immediate importer failures.
This also tries to avoid printing passwords in related error messages.
Fixes [RHBZ#1972895](https://bugzilla.redhat.com/show_bug.cgi?id=1972895)
```release-note
VDDK: handle special characters in login credentials.
```
> URL-encode special characters in VDDK credentials.

- pkg/common/common.go
- pkg/controller/datavolume-conditions.go
- pkg/controller/datavolume-conditions_test.go
- pkg/controller/import-controller.go
- pkg/controller/import-controller_test.go
- tests/datavolume_test.go
When waiting for the PVC to be bound, copy the PVC's condition reason to the DataVolume instead of just "Pending".
Fixes [BZ#1965181](https://bugzilla.redhat.com/show_bug.cgi?id=1965181)
```release-note
Copy AwaitingVDDK condition reason to DV when PVC is waiting for v2v-vmware ConfigMap to be created.
```
> Add "AwaitingVDDK" back to condition reason.

- pkg/controller/datavolume-controller.go
- pkg/controller/datavolume-controller_test.go
- tests/alpha_test.go
- tests/framework/pvc.go
- tests/smartclone_test.go
- tests/transport_test.go
Updated tests to use a real image instead of data that is filled.
Fixes #
```release-note
BugFix: Smart clone was not always used if the provisioner was slow to allocate the PV.
```
> Fix smartclone sometimes not triggering due to capicity not being reported.

- doc/datavolumes.md
- doc/debug.md
- pkg/controller/clone-controller.go
- pkg/controller/import-controller.go
- pkg/controller/upload-controller.go
- pkg/controller/util.go
- tests/cloner_test.go
- tests/datavolume_test.go
- tests/framework/pod.go
- tests/import_test.go
- tests/utils/pod.go
Add DV annotation which if set will cause CDI transfer pods to be retained after a failed/successful completion. This will make debugging and testing easier, as developers an get the pod logs etc.
- Annotation: `cdi.kubevirt.io/storage.pod.retainAfterCompletion=true`
- Pod will be retained after both successful and failed completion.
- User is responsible to delete the pods. They will be deleted anyway when their dv is deleted.
```release-note
Add optional DataVolume annotation to retain the transfer pods after completion
```
> Add DataVolume annotation to retain the transfer pods after completion

- pkg/controller/clone-controller_test.go
- pkg/controller/config-controller.go
- pkg/controller/config-controller_test.go
- pkg/controller/upload-controller_test.go
- pkg/controller/util_test.go
Instead of setting 0/0 for cpu/mem request and limits, set something reasonable in case we have an incomplete LimitRange in the namespace. This would cause pods to not get created due to invalid resource request values. With this change we should have something reasonable that always works.
Fixes #1666
```release-note
Enhancement: Set reasonable default values for request/limits of workload pods.
```
> Set some reasonable requests/limits for workloads

- pkg/common/common.go
- pkg/controller/clone-controller.go
- pkg/controller/import-controller.go
- pkg/controller/upload-controller.go
- pkg/controller/util.go
- pkg/controller/util_test.go
- pkg/image/nbdkit.go
- pkg/image/qemu.go
- pkg/util/util.go
- tests/datavolume_test.go
- tests/import_test.go
- tests/utils.go
- Make sure that the nbdkit messages are in the terminating message, and appear at the exit.
- Avoid newlines in the terminating message, as they don't appear in the `kubectl get pod .. -o yaml` view.
- Avoid CrashLoopBackOff becoming a condition, we prefer to know why the crash had happened.
- If the message is a known long message about the image being too small, pass that stirng.
Tests are adjusted to take advantage of this condition.
This is intended for [BZ #1893526](https://bugzilla.redhat.com/show_bug.cgi?id=1893526).
Makes it easier to tell that the DV failed because it's too small - for humans and programmers alike.
**Special …
> Add a datavolume condition for the image being too large

- pkg/common/common.go
- pkg/controller/datavolume-conditions.go
- pkg/controller/datavolume-conditions_test.go
- pkg/controller/import-controller.go
- pkg/controller/import-controller_test.go
- tests/datavolume_test.go
This is a cherry pick of #1627 and #1816 to the 1.28 release branch.
Addresses [RHBZ#1965181](https://bugzilla.redhat.com/show_bug.cgi?id=1965181).
```release-note
Add AwaitingVDDK condition reason to data volume when v2v-vmware ConfigMap is missing.
```
> [release-v1.28] Add "AwaitingVDDK" back to condition reason.

- pkg/apiserver/apiserver.go
- pkg/apiserver/webhooks/datavolume-mutate.go
- pkg/apiserver/webhooks/datavolume-mutate_test.go
- pkg/apiserver/webhooks/datavolume-validate.go
- pkg/apiserver/webhooks/datavolume-validate_test.go
- pkg/apiserver/webhooks/handler.go
- pkg/controller/datavolume-controller.go
- pkg/operator/resources/cluster/apiserver.go
- tests/api_validation_test.go
- tests/cloner_test.go
- tests/manifests/dvBothSourceAndSourceRef.yaml
- tests/utils/datavolume.go
A `DataSource` is an abstraction that points to the place we'd like to import/clone from. A `DataVolume` can either have an inlined `dataVolume.Spec.Source` as it exists today, or reference a `DataSource` object via `dataVolume.Spec.SourceRef` to perform the same action. The latter allows us to decouple the inlined source from a DataVolume so we can have a static link that points to a DataSource which is mutable.
For more details, view the [design document](https://github.com/kubevirt/community/blob/master/design-proposals/golden-image-delivery-and-update-pipeline.md).
- currently only DataSource sourceRef kind is supported
- currently only PVC DataSource source is …
> Add DataSource as an optional sourceRef for DataVolumes

- pkg/controller/config-controller.go
- pkg/controller/config-controller_test.go
- tests/cdiconfig_test.go
It was possible to create a npe on an Ingress without a default backend service due to missing check for nil. This PR fixes that.
Fixes #1868 
```release-note
BugFix: Fixed controller crash with ingress without default backend service.
```
> Fix crash on ingress without default backend service.

- pkg/operator/resources/namespaced/controller.go
Since #1864 we're seeing spam in the operator logs:
`[{\"op\":\"remove\",\"path\":\"/spec/template/spec/containers/0/env/6/valueFrom/fieldRef/apiVersion\"},`
This happens because we don't specify the fieldRef's apiVersion explicitly when creating the controller,
so k8s populates it for us -> causing us to reconcile it back.
Will now set the apiVersion explicitly to avoid this spam.
Fixes #
```release-note
NONE
```
> Fix fieldRef apiVersion spam

- automation/prow_periodic_push.sh
Combine commands we run in prow for periodic pushes into a single script so we can manage it from cdi repo instead of project-infra.
Fixes #
```release-note
NONE
```
> add script that is called from prow for pushing images

- pkg/operator/resources/namespaced/uploadproxy.go
If someone edited the upload service owned by the operator to type NodePort, the operator would not fix it back to cluster ip. This PR specifies we want the service to be clusterIp only, and that ensures the operator reconciles the service back to clusterIp
Fixes #1871 
```release-note
NONE
```
> Fix operator not reconciling changing of service type

- pkg/importer/http-datasource.go
We are unable to directly convert using nbdkit with the gz filter because it has to download the entire file to get the info. This causes the PR limit to timeout on larger files. This forces us to use scratch space for qcow2.gz files.
Fixes #
```release-note
BugFix: large qcow2.gz files failed to import due to pr limit
```
> Use scratch space for qcow2.gz files.

- pkg/apis/core/v1beta1/types_transfer.go
- pkg/operator/resources/crds_generated.go
It removes 'all' alias for objecttransfers.cdi.kubevirt.io CRD. Based on [this](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-cli/kubectl-conventions.md#rules-for-extending-special-resource-alias---all) cluster scoped resources should not be part of the `kubectl get all` output.
Fixes #
```release-note
NONE
```
> Removing 'all' alias for objecttransfers.cdi.kubevirt.io CRD

- pkg/controller/datavolume-controller.go
- pkg/importer/data-processor.go
- pkg/importer/data-processor_test.go
- pkg/util/util.go
- pkg/util/util_test.go
- tests/datavolume_test.go
We had hardcoded the block size at 512 bytes, which can cause alignment issues when the hardware is a 4k block device. This will manifest itself as
```
{"component":"virt-launcher","level":"error","msg":"internal error: qemu unexpectedly closed the monitor: 2021-06-15T15:16:06.788431Z qemu-kvm: -device virtio-blk-pci-non-transitional,bus=pci.6,addr=0x0,drive=li
bvirt-1-format,id=ua-disk-0,write-cache=on: Cannot get 'write' permission without 'resize': Image size is not a multiple of request alignment","pos":"qemuProcessReportLogError:2111","subcomponent":"libvirt","thread":"290","timestamp":"2021-06-15T15:16:06.811000Z"}
```
in KubeVirt as reported in …
> Default disk alignment to 1Mi instead of 512 bytes

- pkg/importer/vddk-datasource_amd64.go
- pkg/importer/vddk-datasource_test.go
This pull request checks if the VDDK endpoint is vCenter or a direct connection to ESX. When the endpoint is vCenter, reduce the read request size to 2MB. This reduces the frequency of the "Failed to allocate the requested 24117272 bytes" errors that interfere with migrations running multiple imports in parallel. It is still possible to hit, but less likely - 2MB matches the previous qemu-img implementation.
For direct ESX connections, this pull request does nothing different. That should leave the door open for users to try for faster transfers with direct connections, if needed.
Fixes [RHBZ#1984775](https://bugzilla.redhat.com/show_bug.cgi?id=1984775) …
> VDDK: Reduce read size when connecting to vCenter.

- pkg/importer/data-processor.go
- pkg/importer/data-processor_test.go
- pkg/util/util.go
- pkg/util/util_test.go
- tests/datavolume_test.go
backport of #1873
Fixes #
```release-note
BugFix: Align disk image size to 1Mi instead of 512 bytes.
```
> [release-v1.28] Default disk alignment to 1Mi instead of 512 bytes

- pkg/common/common.go
- pkg/operator/controller/controller_test.go
- pkg/operator/resources/namespaced/controller.go
- tests/operator_test.go
Signed-off-by: Vishesh Ajay Tanksale <vtanksale@apple.com>
The service cdi-prometheus-metrics is not used anywhere. It is being removed from the CDI installation.
Fixes #
https://github.com/kubevirt/containerized-data-importer/issues/1890
```release-note
Removed cdi-prometheus-metrics service
```
> Removing cdi-prometheus-metrics service for CDI installation

- tests/cdiconfig_test.go
- tests/upload_test.go
- `[test_id:4952]Should re-create the object if deleted`
This test deletes the CDIConfig and waits for it to recreate with a different UID.
However, this condition alone will not suffice as the CDIConfig status might still be empty for a few seconds,
causing havoc in following tests.
Will now wait for .status to not be empty, and marking test as destructive.
- `[test_id:2330]Verify failure on sync upload if virtual size > pvc size`
Test looks for **any** error after making the HTTP request for upload from the host, which doesn't cut it;
That could be an EOF (witnessed), port-forward, etc -> while the only error that would guarantee the upload process
actually got triggered is `Unexpected return …
> Fix 2 common flakes

- tests/csiclone_test.go
- tests/framework/pvc.go
- tests/import_test.go
- tests/smartclone_test.go
- tests/transport_test.go
- tests/utils/datavolume.go
A problem was found with the way verification command is run. 
```
head -c [numBytes] [fileName] | md5sum
```
This command fails when the file path is bad, but the empty output is piped to md5 and the result is success with md5 of empty input.
In effect some tests were always passing. This was corrected.
Fixes #
```release-note
NONE
```
> Correct md5sum verification in tests

- api/openapi-spec/swagger.json
- go.mod
- pkg/apis/core/v1beta1/openapi_generated.go
- pkg/apis/core/v1beta1/types.go
- pkg/apis/core/v1beta1/types_swagger_generated.go
- pkg/apis/core/v1beta1/zz_generated.deepcopy.go
- pkg/operator/controller/BUILD.bazel
- pkg/operator/controller/cr-manager.go
- pkg/operator/resources/cluster/controller.go
- pkg/operator/resources/crds_generated.go
- pkg/operator/resources/namespaced/apiserver.go
- pkg/operator/resources/namespaced/controller.go
- pkg/operator/resources/namespaced/factory.go
- pkg/operator/resources/namespaced/uploadproxy.go
- tests/BUILD.bazel
- tests/cdiconfig_test.go
- tests/leaderelection_test.go
- tests/operator_test.go
- tests/utils/pod.go
- vendor/modules.txt
Allow users to specify the priority class of the CDI control
plane using the CDI CR. Verifies that the set value is valid
before passing to the deployments.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1953484
```release-note
Enhancement: Allow admin user to specify priority class of CDI control plane
```
> Allow admin user to set CDI control plane priority class via CDI cr.

- cluster-sync/clean.sh
- cluster-sync/sync.sh
- manifests/templates/uploadproxy-nodeport.yaml.in
- tests/cdiconfig_test.go
Follow up for #1886, we now have a kubevirtci version that gives us a free port.
We can use that to make the switch from `kubectl port-forward` which has been known to cause many flakes in our CI.
Fixes #
We are only going to fall back to `kubectl port-forward` when override is not set:
https://github.com/kubevirt/containerized-data-importer/blob/main/tests/upload_test.go#L74-L78
```release-note
NONE
```
> Use NodePort instead of kubectl port-forward for upload tests

- Makefile
- cluster-sync/sync-os-ci.sh
- cluster-sync/sync.sh
- hack/build/config.sh
`make cluster-sync` was ignoring `PULL_POLICY`  and used the default `IfNotPresent`
This was found while cluster-sync'ing with `KUBEVIRT_PROVIDER=external` to an existing cluster. 
```release-note
NONE
```
> Fix cluster-sync PULL_POLICY usage

- tests/datavolume_test.go
- tests/utils/datavolume.go
Verifies https://bugzilla.redhat.com/show_bug.cgi?id=1989170 which was fixed by https://github.com/kubevirt/containerized-data-importer/pull/1878.
Reverted the fix to ensure we hit the problem:
```bash
I0823 15:07:03.730128       1 http-datasource.go:296] Attempting to get object "http://cdi-file-host.cdi:82/tinyCore.qcow2.gz" via http client
I0823 15:07:03.730503       1 data-processor.go:323] Calculating available size
...
...
...
I0823 15:07:04.233156       1 prlimit.go:128] Setting CPU limit to 30
I0823 15:07:04.233931       1 prlimit.go:159] Setting Address space limit to 1073741824
E0823 15:07:34.234196       1 prlimit.go:174] qemu-img failed output is:
E0823 15:07:34.234240       1 …
```
> Add test for ratelimited qcow2.gz

- cmd/cdi-apiserver/BUILD.bazel
- cmd/cdi-apiserver/apiserver.go
- pkg/apiserver/apiserver.go
- pkg/apiserver/auth-config_test.go
- pkg/keys/BUILD.bazel
- pkg/keys/keystest/keystest.go
- pkg/keys/keystore.go
- pkg/keys/keystore_test.go
- pkg/operator/resources/namespaced/apiserver.go
`cdi-api-signing-key` Secret is not being labeled currently, this PR handles that.
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=1994389
```release-note
BugFix: Some of the cdi resources missing app labels
```
> Add missing relationship labels on cdi-api-signing-key secret

- cluster-sync/sync.sh
- manifests/templates/cdi-testing-sa.yaml.in
- manifests/templates/cdi-testing-scc.yaml.in
- manifests/templates/file-host.yaml.in
- manifests/templates/imageio.yaml.in
- manifests/templates/registry-host.yaml.in
- manifests/templates/test-proxy.yaml.in
- manifests/templates/vcenter.yaml.in
Instead of using our production SA with test manifests, let's have a dedicated & minimal one.
Also provide SCC in case test suite is ran on OpenShift (needed to provide capability to `cdi-docker-registry-host`).
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=1996407
```release-note
BugFix: cdi-docker-registry-host Pod fails to start on OpenShift
```
> Use dedicated ServiceAccount for test manifests

- pkg/apiserver/BUILD.bazel
- tests/cdiconfig_test.go
The test was not testing against an ingress with no service. Also it would fail if a route exists, it would return the value of the route instead.
Fixes #
```release-note
NONE
```
> Fix ingress test with no service to test right ingress

- pkg/controller/datavolume-controller.go
This pull request avoids calling updateProgressUsingPod when the importer pod exists but is not running. This prevents a 30-second delay in the phase transition to Paused in multi-stage imports. 
No issue or bug, just noticed this while working on #1903.
```release-note
Avoid trying to get metrics from non-running pod. 
```
> Avoid trying to get metrics from non-running pod.

- pkg/controller/datavolume-controller.go
- pkg/controller/datavolume-controller_test.go
- pkg/importer/data-processor.go
- pkg/importer/data-processor_test.go
- tests/upload_test.go
Fixes #
Bugfix: Fix fsoverhead calculation.
AS it looks  #1924 depends on #1923, this PR joins them together.
```release-note
Bugfix: Fix fsoverhead calculation
```
> Overhead on profile and usable space toghether

- pkg/controller/datavolume-controller.go
- pkg/controller/datavolume-controller_test.go
- pkg/importer/data-processor.go
- pkg/importer/data-processor_test.go
- tests/upload_test.go
Manual cherry-pick of #1926
Fixes #
```release-note
Bugfix: Fix fsoverhead calculation
```
> [release-v1.34] Overhead on profile and usable space toghether (#1926)

- pkg/controller/datavolume-controller.go
- pkg/controller/datavolume-controller_test.go
- pkg/importer/data-processor.go
- pkg/importer/data-processor_test.go
- tests/upload_test.go
Manual cherry-pick of #1926
Fixes #
```release-note
Bugfix: Fix fsoverhead calculation
```
> [release-v1.38] Overhead on profile and usable space toghether (#1926)

- pkg/importer/vddk-datasource.go
- pkg/importer/vddk-datasource_test.go
This is a backport of #1881 to v1.28.
Fixes [RHBZ#2003691](https://bugzilla.redhat.com/show_bug.cgi?id=2003691)
```release-note
Lower VDDK read size for vCenter connections to reduce incidence of allocation failures caused by simultaneous imports. 
```
> [release-v1.28] VDDK: Reduce read size when connecting to vCenter.

- pkg/image/qemu.go
- pkg/image/qemu_test.go
- tests/import_test.go
Since #1102 our `qemu-img convert` writes use the "none" cache mode;
This is because with [default](https://github.com/qemu/qemu/blob/master/qemu-img.c#L151) "unsafe" cache mode its possible that the process can exit before all writes have
reached storage (lazily flushed). Also note "unsafe" [ignores flushes](https://documentation.suse.com/sles/11-SP4/html/SLES-kvm4zseries/cha-qemu-cachemodes.html#id-1.10.6.6.5).
This might be an expensive approach to fix the problem since "none" bypasses the host cache.
We can instead tackle this situation differently by sticking to "writeback" cache mode,
along with ensuring the write was committed (fsync syscall).
Looks like we were already leaning in this …
> Stop qemu-img writing with cache=none

- tests/framework/pvc.go
Addresses a flake where the clone target DV is "Succeeded" and empty:
```bash
[WARN] error executing command ["/bin/sh" "-c" "md5sum /pvc/disk.img"], error: command terminated with exit code 1
INFO: stderr: [md5sum: /pvc/disk.img: No such file or directory]
```
What I believe happens here is that the filler pod is not committing writes and directly exiting after the `echo 1245 > disk.img`,
resulting in us cloning an empty pvc and doing a successfull job at it.
Did not see it fail at all with the `&& sync` addition.
Fixes #
**Special notes for …
> Commit write to disk in source-pvc filler pod

- cluster-sync/nfs/nfs-server.yaml
- pkg/controller/datavolume-controller.go
- tests/cloner_test.go
- tests/framework/nfs-utils.go
BugId: 1999571 - I think this bug was a regression from when we refactored for CSI cloning.
Fixes #
```release-note
BugId: 1999571 - fix clone into larger capacity nfs volume
```
> BugId: 1999571 - fix clone into larger capacity nfs volume

- doc/datavolumes.md
- pkg/importer/BUILD.bazel
- pkg/importer/vddk-datasource_amd64.go
- pkg/importer/vddk-datasource_test.go
This pull request allows the VDDK importer to accept snapshot change IDs in the "previous" fields of multi-stage checkpoint lists. This way, snapshots can be deleted as part of the process of a warm migration, instead of deleting multiple snapshots all at once after the migration is finished. This is the [recommended VMware workflow](https://kb.vmware.com/s/article/76082) and should help address [RHBZ#1942651](https://bugzilla.redhat.com/show_bug.cgi?id=1942651) in a nicer way.
Fixes [RHBZ#2000298](https://bugzilla.redhat.com/show_bug.cgi?id=2000298)
I opted to try to preserve the existing support for snapshot IDs instead of replacing it with change IDs only, in case there are …
> VDDK: accept snapshot change IDs in previous checkpoint fields

- cmd/cdi-controller/BUILD.bazel
- cmd/cdi-controller/controller.go
- pkg/common/common.go
- pkg/controller/clone-controller.go
- pkg/controller/clone-controller_test.go
- pkg/controller/datavolume-controller.go
- pkg/controller/datavolume-controller_test.go
- pkg/controller/util.go
- pkg/operator/resources/namespaced/controller.go
- tests/BUILD.bazel
- tests/cloner_test.go
See bug:  https://bugzilla.redhat.com/show_bug.cgi?id=1855182
When dumb cloning across namespaces, and a source in use (pod mounting source PVC) then it is possible for the token to time out (5 min).  To address that, the datavolume controller will add a "forever" token to the PVC.  This should be safe because the forever token includes the pvc UID.
Fixes #
```release-note
BufFix: BZ 1855182 - clone token timing out
```
> Add long term token to pvcs when host assisted cloning cross namespaces

- pkg/operator/resources/namespaced/BUILD.bazel
- pkg/operator/resources/namespaced/apiserver.go
- pkg/operator/resources/namespaced/controller.go
- pkg/operator/resources/namespaced/uploadproxy.go
- pkg/operator/resources/operator/BUILD.bazel
- pkg/operator/resources/operator/operator.go
Added cpu/mem requests for operator/controller/apiserver and uploadproxy.
Fixes #
```release-note
Enhancement: CDI control plane now has cpu/mem requests set.
```
> Set requests for CDI control plane

- pkg/controller/datavolume-controller.go
Explicitly set that storage class name
When the storage request is specified using the 'storage' API in
a DataVolume, CDI uses Storage Profiles to look up any missing
values that would be required to create the underlying PVC.
If the user omits the storage class parameter in their DV,
CDI assumes the cluster's default storage class will be used.
Since CDI calculates the storage class that should be used in
this case, it should explicitly set that storage class name
in the PVC it creates.
Fixes #
**Release …
> Explicitly set the storage class name

- WORKSPACE
- hack/build/config.sh
- hack/build/docker/builder/Dockerfile
consistent with kubevirt and will be required if we update k8s libraries
Fixes #
```release-note
NONE
```
> update go to 1.16.6

- manifests/templates/imageio.yaml.in
We see an error starting the deployment's server d/s:
```bash
[cnv-qe-jenkins@alex48-451-xzjsk-executor ocs-test]$ oc logs -f -n openshift-cnv imageio-deployment-f9bfff68-clbs2 imageiotest
Using configuration from /etc/pki/tls/openssl.cnf
...
File "/ovirt-imageio/daemon/ovirt_imageio/uhttp.py", line 80, in server_bind
self.socket.bind(self.server_address)
PermissionError: [Errno 13] Permission denied
curl: (7) Couldn't connect to server
```
Running as root seems to solve it, and doesn't harm test integrity since it's a test-helper.
Fixes # …
> Run imageio test deployment as root

- tests/cloner_test.go
- tests/utils/pod.go
- tests/utils/pvc.go
[test_id:4000] Create a data volume and then clone it while killing the
container and verify retry count was pretty flaky lately. The likely culprit was the small amount of data being cloned. This causes the pods to be removed before we have a chance to connect issue the kill command.
Fixes #
```release-note
NONE
```
> Retry clone kill which is flaky

- WORKSPACE
- hack/build/bazel-build-builder.sh
- hack/build/config.sh
Instead of checking the digest, use a tag that is derived from
a date/time and git hash. Check if hack/build/docker has changed
before building a new builder image on merge of a PR.
Fixes #
```release-note
NONE
```
> Update builder push to align with kubevirt.

- doc/cdi-config.md
Improve fsOverhead description on config docs. The doc was misleading, now it shows that filesystemOverhead is a composite and has more than one subelements.
Fixes #
```release-note
NONE
```
> Improve fsOverhead description on config docs

- hack/ci/language.sh
- hack/gen-swagger-doc/deploy.sh
Now that the default branch is main.
Actually waiting on @aglitke to do the change.
```release-note
NONE
```
> Revert "cdi-api-reference default branch is master, add an exception for it"

- tests/datavolume_test.go
- tests/webhook_test.go
- `Should deny/allow user when creating datavolume`
Delay between when permissions are applied and enforced is possible, lets loop over,
similarly to https://github.com/kubevirt/containerized-data-importer/pull/882.
- `Cloner pod should have specific datavolume annotations passed but not others`
Some envs like OpenShift check network validity (net1 isn't real), which will stop cdi-upload pod from running, and thus source-pod from getting created.
Since we already checked the annotation exists on it, we can remove it so the process continues and creates the source pod.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) …
> Tackle some flakes

- cluster-sync/ephemeral_provider.sh
- tests/cloner_test.go
- tests/csiclone_test.go
- tests/import_test.go
- tests/upload_test.go
- tests/utils/common.go
Update the default storage for hpp lanes to be the csi driver instead of the legacy driver.
Fixes #
```release-note
NONE
```
> Update default storage to use CSI hpp driver

- pkg/image/BUILD.bazel
- pkg/image/qemu.go
- pkg/image/qemu_test.go
- tests/import_test.go
When trying to preallocate big size such as 1Gi
the preallocation failed since the dd occupied too
much memory and OOMKiller killed the process.
To fix it the dd will write in 1Mi block size the
requested size (will write the extra reminder if the
size is not aligned to 1Mi)
There was a test which checked blank block preallocation
but the size was only 100Mi which didnt fail, changed to 1Gi.
Signed-off-by: Shelly Kagan <skagan@redhat.com>
Fixes # BZ#2017613
https://bugzilla.redhat.com/show_bug.cgi?id=2017613
```release-note
NONE
```
> Fix blank block preallocation import

- tests/datavolume_test.go
- tests/upload_test.go
- Upload tests:
We only care that the operation will succeed eventually, were fine with one call failing.
- Annotation test:
```bash
Operation cannot be fulfilled on pods "cdi-upload-test-dv": the object has been modified; please apply your changes to the latest version and try again
```
Loop over the .Update call here as well, as were fine with it succeeding at some point.
Fixes #
```release-note
NONE
```
> Attempt to handle flakes in upload/annotations tests

- pkg/operator/controller/cr-manager.go
- pkg/operator/resources/operator/operator.go
- pkg/operator/resources/utils/common.go
- tests/operator_test.go
The current priority class for the operator is `openshift-user-critical`. This priority class does not exist in Kubernetes.
Instead, use the `kubevirt-cluster-critical` priority class that is created by HCO.
Fixes #2010 
Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>
```release-note
use the `kubevirt-cluster-critical` priority class for CDI pods.
```
> Replace the priorityClass to kubevirt-cluster-critical

- WORKSPACE
- cmd/cdi-importer/BUILD.bazel
- pkg/importer/BUILD.bazel
- pkg/importer/transport.go
- tools/cdi-source-update-poller/BUILD.bazel
- tools/cdi-source-update-poller/main.go
Depending on a Go binary from the package manager is undesirable
as whenever Go notifies us of a vulnerability and we need to
rebuild, we depend on the package to be updated, which may take
a while (especially in the case of, say, centos stream).
With a library, updates are a matter of rebuilding CDI itself,
and that's it.
```release-note
NONE
```
> Remove skopeo binary dependency - use containers/image instead

- go.mod
- go.sum
- pkg/apiserver/apiserver.go
- pkg/apiserver/apiserver_test.go
- pkg/controller/config-controller.go
- pkg/controller/config-controller_test.go
- pkg/controller/storageprofile-controller.go
- pkg/controller/storageprofile-controller_test.go
- pkg/operator/controller/BUILD.bazel
- pkg/operator/controller/callbacks.go
- pkg/operator/controller/controller_test.go
- pkg/operator/controller/cruft.go
- vendor/kubevirt.io/controller-lifecycle-operator-sdk/pkg/sdk/reconciler/reconciler.go
- vendor/modules.txt
- Vendor https://github.com/kubevirt/controller-lifecycle-operator-sdk/pull/19 so our deployments get labelled
- Address some of our specific resources that are only getting labels on creation
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=2017478
```release-note
BugFix: Some of the cdi resources are missing labels after upgrade
```
> Change some relationship labels on update as well

- pkg/operator/resources/cluster/rbac.go
- tests/rbac_test.go
Adds RBAC rules for storageprofiles
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=1992961
```release-note
Fix  access control for storageprofiles
```
> Add storageprofiles to RBAC

- cmd/cdi-importer/importer.go
Currently importer connects too early, so it gets restarted and successfully connects only on the second try.
```
$ k logs importer-registry-image-datavolume importer
I1130 12:27:49.884684       1 importer.go:77] Starting importer
I1130 12:27:49.884791       1 importer.go:131] begin import process
I1130 12:27:49.884857       1 http-datasource.go:387] Attempting to HEAD "http://localhost:8100/disk.img" via http client
I1130 12:27:49.885995       1 http-datasource.go:322] Attempting to get object "http://localhost:8100/disk.img" via http client
E1130 12:27:49.886382       1 importer.go:276] Get "http://localhost:8100/disk.img": dial tcp [::1]:8100: connect: connection refused
HTTP request errored …
```
> Fix cdi-containerimage-server readiness sync in cdi-importer

- doc/os-image-poll-and-update.md
- pkg/apis/core/v1beta1/openapi_generated.go
- pkg/controller/dataimportcron-controller.go
- pkg/operator/resources/crds_generated.go
- staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
- staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
Enable DataImportCron garbageCollect by default, so we won't have tons of dusty pvcs left around. 
Fixes #
```release-note
NONE
```
> Enable DataImportCron garbageCollect by default

- cluster-sync/ephemeral_provider.sh
- tests/cloner_test.go
- tests/csiclone_test.go
- tests/import_test.go
- tests/upload_test.go
- tests/utils/common.go
With hpp operator at v0.11.0 it now requires cert-manager, and webhook
This PR modifies the hpp setup to include setting up those items.
Backport of #2046 
Fixes #
```release-note
NONE
```
> [release-v1.38] Backport fix hpp tests

- tests/datavolume_test.go
For OpenShift we effectively build with centos stream, which builds
qemu-img without VDI support.
Our test previously succeeded because it only checked that the DV
was successful, not that the content is valid.
Skip for now.
```release-note
NONE
```
> Skip VDI test on OpenShift

- tests/datavolume_test.go
Extend the functional test to check for explicit storage class (storage class name handling implemented here: https://github.com/kubevirt/containerized-data-importer/pull/1936).
Check that the CDI sets the storage class on the DV/PVC when it is
not specified in the spec.storage API but computed by CDI.
Fixes #
```release-note
NONE
```
> Extend test for explicit storage class

- pkg/importer/transport.go
Check the tar header metadata if a tar entry is a directory instead of
checking if it has a `/` suffix.
This solves the following issue:
While most applications write a `/` at the end of a directory entry in a
tar header, it is not necessarily there. If it is missing, the directory
will be treated as the target file and CDI tries and fails to import the
`disk` directory itself:
```
iI1203 12:02:26.740362       1 transport.go:149] File 'disk' found in the layer
I1203 12:02:26.740461       1 util.go:172] Writing data...
E1203 12:02:26.742269       1 registry-datasource.go:123] Error reading directory
E1203 12:02:26.742319       1 data-processor.go:229] readdirent: not a directory
image file does not exist in image directory
```
**Which issue(s) this …
> Improve directory detection on containerdisk imports

- pkg/controller/storageprofile-controller.go
- pkg/controller/storageprofile-controller_test.go
- tests/cloner_test.go
This PR allows storage classes to set the preferred clone method with an annotation on the storage class. This is helpful for known provisioners that want different behavior for certain configurations in the storage class. For instance rook-ceph with encryption enabled, will want to a host assisted clone instead of smart clone.
Signed-off-by: Prajith Kesava Prasad <pkesavap@redhat.com>
Fixes # 
```release-note
NONE
```
> Trigger Host Assisted Cloning for encrypted ocs sc.

- pkg/operator/controller/controller_test.go
- pkg/operator/controller/prometheus.go
We want to be able to list all kubevirt alerts so we added labels to
differentiate them.
Signed-off-by: assafad <aadmi@redhat.com>
```release-note
Added common labels into alert definitions
```
> Add common labels into alert definitions

- tests/upload_test.go
So the upload func being called in the eventually loop means we're going to be running
this:
https://github.com/kubevirt/containerized-data-importer/blob/main/tests/upload_test.go#L415-L428
a bunch of times, which leads to sometimes failing with
```bash
<*errors.errorString | 0xc000200140>: {
s: "io: read/write on closed pipe",
}
io: read/write on closed pipe
occurred
/root/go/src/kubevirt.io/containerized-data-importer/tests/upload_test.go:424
```
Slightly incrementing the interval in which we call the upload func seems to mitigate this flake. …
> Attempt to mitigate flake #1989, 'io: read/write on closed pipe'

- hack/build/docker/builder/Dockerfile
we failed to push an updated builder for #1982, doing a no-op change will trigger the post-submit job.
-->
```release-note
NONE
```
> Whitespace change to builder to trigger postsubmit job

- cluster-sync/ephemeral_provider.sh
- tests/cloner_test.go
- tests/csiclone_test.go
- tests/import_test.go
- tests/upload_test.go
- tests/utils/common.go
Reverts the usage of the hpp CSI driver for this branch. The lanes in this branch have kubernetes that is older than the minimum version required by hpp with CSI.
Fixes #
Note I hardcoded the version to 0.9.0 in ephemeral.sh since that is the last release without CSI.
```release-note
NONE
```
> [release-v1.38] Revert "Backport fix hpp tests (#2047)"

- tests/dataimportcron_test.go
Locally see 90 seconds is not enough for ensuring PVCs were cleaned up in `[test_id:7406]`,
bumping the timeout to avoid flake.
Fixes #
```release-note
NONE
```
> Bump timeout in DataImportCron test suite
